### ISSUE TITLE
I can't play the music in app

### ISSUE THREAD

**Issue by pradeethrocker** [Shabinder/SpotiFlyer#10]
I can't find the library screen in the app. Pls help

**Comment by Shabinder** [comment]
There is no Library Screen but there is a History Screen .which can be used to see Recent Searches by clicking on the clock button as shown: 
![image](https://user-images.githubusercontent.com/44765050/99789802-2b0fe100-2b49-11eb-9daf-d66f9b4d458d.png)

**Comment by pradeethrocker** [comment]
Thank you for your quick response 🙂. But u have posted a screenshot 'Library Screen'(LibraryScreen2.jpg) with a player interface. So that only I have asked. No problem 👍 once again thanks.

**Comment by Shabinder** [comment]
> Thank you for your quick response slightly_smiling_face. But u have posted a screenshot '4.Library Screen'(LibraryScreen2.jpg) with a player interface. So that only I have asked. No problem +1 once again thanks.
> ![Screenshot_2020-11-20-17-20-08-99](https://user-images.githubusercontent.com/69318228/99797169-bc388500-2b54-11eb-8227-646996c00d93.jpg)

ohhhk, that is a screenshot of PowerAmp Media Player with a song downloaded using this app.
Its is just to show that ID3 tags like AlbumArt and Songs Info is embedded into Mp3 itself.
