### ISSUE TITLE
[IMPORTANT] F-Droid repo isn't updated its still on 3.5.0

### ISSUE THREAD

**Issue by UnixPhonez** [Shabinder/SpotiFlyer#1001]
F droid repo needs to be updated I feel most of these issues are duplicates since its still on version 3.5.0

**Comment by Shabinder** [comment]
F-Droid shows the updates after 2/3 Days.
So cant do anything till then, people should see already opened issues before opening new.

**Comment by UnixPhonez** [comment]
> F-Droid shows the updates after 2/3 Days. So cant do anything till then, people should see already opened issues before opening new.

The best strategy to clean up issues is close the issue and link it to a main issue / also pinning it would be great

**Comment by UnixPhonez** [comment]
Update 3.6.0 has been released on F-Droid
