### ISSUE TITLE
[Feature-Request]: Ability to delete history / clear history

### ISSUE THREAD

**Issue by UnixPhonez** [Shabinder/SpotiFlyer#1003]
A button to delete downloaded history or clear history would be great.

**Comment by UnixPhonez** [comment]
#1004

**Comment by mik1011984** [comment]
This would be great.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
