### ISSUE TITLE
[BUG] : android version crashing when trying to download

### ISSUE THREAD

**Issue by ArcMcNabbs** [Shabinder/SpotiFlyer#1021]
**Describe the bug:**
Android app crashed when I try to download a playlist of my spotify library(740 titles)

**Media Links Used:** 
https://open.spotify.com/playlist/2NyJs5pXOEgzqYw5fBk7ho?si=yRrpMgWpSU6uF9q_CixoPQ&utm_source=copy-link

**Expected behavior**
I expected motivation to stop supporting spotify due to recent events. Trying to move to apple music, and take my music with me

**Device Info (please complete the following information):**
 - Device:   samsung s7 edge
 - OS:   android
 - Version:   8.0
 - Country: Canada

**Additional context:**
An error window pops up miliseconds before crashing, but its too fast for me to read or screenshot
Apologies if this is not the correct ticket format, I am extremely new to github and this is my first time testing a product from here. Thank you for your time! <3

**Comment by Shabinder** [comment]
screen record maybe ?

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
