### ISSUE TITLE
[BUG] : <Unable to Download Artist in JioSaavan and Spotify plus invalid link>

### ISSUE THREAD

**Issue by GlassThrone** [Shabinder/SpotiFlyer#1024]
**Device Info (please complete the following information):**
 - Device:   [Samsung Note 20 Ulyra]
 - OS:   [Android 12 and 11]
 - Version:   [e.g. 3.6.1]
 - Country: [India, Canada and US]

**Additional context:**
When copying and artist link in JioSaavan and Sopity to download all Artist albums and songs, get an invalid link error. But same works in Gaana.

Not able to download SoundCloud Songs either. Invalid link error.
![Screenshot_20220130-084400.jpg](https://user-images.githubusercontent.com/90779985/151702481-f46c5f9d-cb38-4cf3-aee7-8d5bca1a73a2.jpg)

**Comment by Shabinder** [comment]
Thanks for reporting the issue,
share the link you used, so I can copy and test it rather than seeing from the image

**Comment by GlassThrone** [comment]
Thank you. Here is/are the link/s.

JioSaavan: https://www.saavn.com/s/artist/emiway-bantai-albums/HmfIoHJ-3PU_

Spotify:
https://open.spotify.com/artist/4kLCY9rhyOrp9f0AtdNXEz?si=rLKMruN0Sqm33bJ42Fr0Uw&utm_source=copy-link

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
