### ISSUE TITLE
When "downloaded", file is corrupted.

### ISSUE THREAD

**Issue by konm08** [Shabinder/SpotiFlyer#103]
I have an issue that makes the app to just eat your phone's space and sit. I cannot download anything. After "downloaded", I am going to my file explorer and see that "the file may be corrupted". What is going on?

**Comment by Shabinder** [comment]
See #97 , use v2.1 for now , will release a new version with the fix

**Comment by konm08** [comment]
something similar happens now again and it is trying to load forever. However, some hours ago I downloaded successfully a song and heard it until the end.

**Comment by Shabinder** [comment]
Check out **v2.3.0,** downloading issue is fixed
