### ISSUE TITLE
[BUG] : <Issue_Title> they keep playing the wrong songs

### ISSUE THREAD

**Issue by Kawxx55** [Shabinder/SpotiFlyer#1054]
They keep playing the wrong songs can u fixed this

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
