### ISSUE TITLE
Does this app directly download from spotify if we give a spotify track link or download from youtube. 

### ISSUE THREAD

**Issue by shockergit** [Shabinder/SpotiFlyer#1055]
Just a question

**Comment by 89z** [comment]
https://github.com/Shabinder/SpotiFlyer/issues/1113

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
