### ISSUE TITLE
Video download 

### ISSUE THREAD

**Issue by shockergit** [Shabinder/SpotiFlyer#1057]
Add support for video downloads from Youtube, Facebook and Instagram.
Option to change download queue order.
Auto retry when failed.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
