### ISSUE TITLE
A bug/issue

### ISSUE THREAD

**Issue by H-Labs1** [Shabinder/SpotiFlyer#1058]
Yeah, so it only downloades the first 50 songs in an album. So yeah...

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
