### ISSUE TITLE
Spotify: name files from album download after track number

### ISSUE THREAD

**Issue by darealshinji** [Shabinder/SpotiFlyer#106]
I downgraded the app to v2.1 in order to download from Spotify. When I download an album the files are only named after the title. Can you make it so that they are named after track number and title?

**Comment by Shabinder** [comment]
I won't be able to fetch track numbers from all sources I have and plan to include, So as to keep Naming Consistent and valid when we check in the future if the file is already downloaded or not.

So I won't be implementing this.
I hope you can understand, Thanks.
