### ISSUE TITLE
[Feature-Request]: Possibility to change downloaded files name format

### ISSUE THREAD

**Issue by pida42** [Shabinder/SpotiFlyer#1063]
Would be awesome if users can change the name of the downloaded (result) files.
Actually the app is saving files with the name of the track (+ .mp3), which is enough for the defaults. But would be really good to implement some way to define the format of result files names, eg:

```
FILE_FORMAT ?= "[%001+1] [%artist] - [%track].mp3"
```

(for example)

where the result will be fe.:

```
001 Login Jelz - Poetry.mp3
002 Zaphod Beeblbrox - Humma Kavula stupid.mp3
...
```

Alternatively just make some option to prepend file names with "[%artist] - ". This will also eliminate duplicities in tracks names in case user will download tracks with the same names.

**Comment by Kristoffer123456** [comment]
I'm also looking for this. Would be a great feature.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
