### ISSUE TITLE
new sources that you can add

### ISSUE THREAD

**Issue by mohibo** [Shabinder/SpotiFlyer#107]
for example,Soulseek,netease.vk.chiasenhac,nhaccuatui

**Comment by Shabinder** [comment]
Will Look into this, I will look and find if I can get API, if not then maybe I can reverse engineer their site to see how they communicate and replicate that.

But as you can guess its a time-consuming task and will try If I can make time for this.

Stay Tuned.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
