### ISSUE TITLE
Sound quality Selection Needed

### ISSUE THREAD

**Issue by vcint** [Shabinder/SpotiFlyer#1076]
please add a feature to select audio quality while downloading .

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
