### ISSUE TITLE
[Feature-Request]: Please add Deezer how source for the music downloads

### ISSUE THREAD

**Issue by CavaleriOmar** [Shabinder/SpotiFlyer#1077]
Given the repeated download problems with Spotify, would it be possible to add Deezer to the resources from which I can download?

**Comment by GlassThrone** [comment]
> 
> Given the repeated download problems with Spotify, would it be possible to add Deezer to the resources from which I can download?

This world be great as Spotify sound are not always what seen to be when downloaded

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
