### ISSUE TITLE
[Feature-Request]: Use SpotiFlyer as lib 

### ISSUE THREAD

**Issue by vladislawfox** [Shabinder/SpotiFlyer#1078]
Are you planning to make a separate library just for downloading audio that will do everything by itself?

**Comment by Shabinder** [comment]
library ? can you explain more about your usecase ?

**Comment by cwiokpl** [comment]
I think what @vladislawfox meant was an ability to integrate your solution to other applications. This is something that I would like to get too. 
A potential use case would be to have a simple script that scans my playlists and downloads a song whenever a new one is added. In this situation I would be able to just add a line of code e.g. spotiflyer.SearchAndDownload(<Song Name>) and the rest would be done entirely by your library.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
