### ISSUE TITLE
[BUG] : Songs downloading empty

### ISSUE THREAD

**Issue by anjalichr** [Shabinder/SpotiFlyer#1083]
**The bug:**
Some songs download but empty and even after many re-downloading those songs and even re-installing SpotiFlyer itself the problem still occurs with some particular songs

**Media Links Used:** 
1- https://open.spotify.com/track/776AftMmFFAWUIEAb3lHhw?si=27dbe5adb3814734
2- https://open.spotify.com/track/2l7V3AuTxGuswKjGovaSEv?si=4aed71730f594a80

**Device Info:**
 - Device:   VivoBook 14
 - OS:   Win 10
 - Version:   21H2
 - Country: India

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
