### ISSUE TITLE
Songs aren't really in 320kbps

### ISSUE THREAD

**Issue by Kroody** [Shabinder/SpotiFlyer#1091]
I noticed even after changing audio quality in the settings, the songs are still downloaded in 128kbps

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
