### ISSUE TITLE
[BUG] : Sound Cloud, client request fail error

### ISSUE THREAD

**Issue by GlassThrone** [Shabinder/SpotiFlyer#1092]
**Describe the bug:**
Any type of link copied from sound Cloud to download a song fail with a some kind of client request error

**Media Links Used:** 
Listen to Patake - Sunanda Sharma by Punjabi By Nature on #SoundCloud
https://soundcloud.app.goo.gl/di1k6

**Expected behavior**
Should provide the song and be able to download

**Screenshots:**
![Screenshot_20220208-213348.jpg](https://user-images.githubusercontent.com/90779985/153111142-f59d9e1e-7653-4df5-b44a-946d2abe2ff9.jpg)

**Device Info (please complete the following information):**
 - Device:   Note 20 ultra
 - OS:   Android 12
 - Version:  3.6.1
 - Country: India, Canada and US

**Comment by tywentghxst** [comment]
Same problem

**Comment by dp0s** [comment]
#3

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
