### ISSUE TITLE
[Feature-Request]: <AppImage for Linux>

### ISSUE THREAD

**Issue by fossimprove** [Shabinder/SpotiFlyer#1095]
Its better to have for Linux and portable to all distro

**Comment by gghhkm** [comment]
If this is being done, then logically Flatpak should be supported too. Just saying. 😉

**Comment by CodeCubeNeo** [comment]
I agree. This should be also available as a flatpak

**Comment by FillingTheVoidOnYT** [comment]
we need an appimage

**Comment by therealonlygithub1** [comment]
> If this is being done, then logically Flatpak should be supported too. Just saying. wink

+1 flatpak with an flathub submission would make it autoupdate via distros software stores and appimage would be great for portability

**Comment by nobaraos12** [comment]
an appimage or flatpak would be great

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
