### ISSUE TITLE
Downloading Quality

### ISSUE THREAD

**Issue by iabhishekkr** [Shabinder/SpotiFlyer#11]
Is there any option to increase the quality of downloaded songs from spotify?

**Comment by Shabinder** [comment]
**No** , the quality is already **_Max (160kbps)_** as Youtube doesnt provide more than that.
Spotify here is only the source for song Info , the audio is fetched from Youtube after searching the best  Possible match.

**Comment by iabhishekkr** [comment]
Thanks for reply.
Some applications like videoder is providing 256kbps option as well for audio downloading from youtube. If possible please look into that. 
Thank you.
