### ISSUE TITLE
give suport for multiple song download at a time while downloading playlist [Feature-Request]: <multiple download>

### ISSUE THREAD

**Issue by HEGADE** [Shabinder/SpotiFlyer#1109]

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
