### ISSUE TITLE
[BUG] : Songs that are already downloaded show as not downloaded in app/w other issues

### ISSUE THREAD

**Issue by CyberaxAnnon** [Shabinder/SpotiFlyer#1112]
**Describe the bug:**
When downloading from the app, some songs get downloaded. Once downloaded, and the app is shut down, it then shows it has not been downloaded dispite it already doing so.

There are other times where the song downloads but then does not play what so ever and instead are corrupt and need to be deleted along with showing they need to be downloaded again.

**Media Links Used:** 
(Needing to download even when already downloaded)
https://open.spotify.com/track/6wO0vMRAJB0r1lEWBJZNOq?si=D9NNEz7sQd6yNShpvp3QVw&utm_source=copy-link

(Downloaded but does not play and still shows needing to be downloaded)

https://open.spotify.com/track/5vkkhwtKWnGkFu3tagE71D?si=5rdW0xYvTpyx4bikET5uHg&utm_source=copy-link

https://open.spotify.com/track/5cRPdqpWkaNmIbPi6wJDg2?si=jHNFQMMRTZ24BenCkTXTxQ&utm_source=copy-link

**Expected behavior**
Should have a Tick rather than show an download sign
Song should play in full from beginning to end.

**Device Info (please complete the following information):**
 - Device:  Xiaomi Note 9 Pro
 - OS:  /e/
 - Version:   0.21.202201251583734
 - Country: New Zealand 

**Additional context:**
Also Using ProtonVPN in same location.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
