### ISSUE TITLE
320kbps not downloadable

### ISSUE THREAD

**Issue by KJagsweet** [Shabinder/SpotiFlyer#1113]
Except Jiosaavn, 320kbps is not downloading for any other sites..Eg. In Spotify it only downloads 128kbps instead of selected 320kbps quality

**Comment by jdo248** [comment]
I'm also facing the same issue. I've tried downloading from Spotify, Wynk Music, YouTube Music, and SoundCloud.
All I get are 128kbps files.

**Comment by 89z** [comment]
SoundCloud doesnt offer 320, unless you have a paid account.

**Comment by KJagsweet** [comment]
At least It would be Good if We could download 320kbps from Spotify also.
Jiosaavn 320kbps is working perfect.

**Comment by 89z** [comment]
https://github.com/Shabinder/SpotiFlyer/issues/1055

**Comment by 89z** [comment]
This tool doesnt download from Spotify, it downloads songs from YouTube if they have the same name as Spotify song.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
