### ISSUE TITLE
I have a problem downloading a song.

### ISSUE THREAD

**Issue by TmanGamer** [Shabinder/SpotiFlyer#1116]
I don't know how to format it but I try to download mac Miller's floating from circles deluxe but ir downloads keep floatin' from best day ever.

**Comment by TmanGamer** [comment]
sorry about duplicate I just woke up and forgot I was on the wrong account.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
