### ISSUE TITLE
[BUG] : <Issue_Title>

### ISSUE THREAD

**Issue by V3mpire** [Shabinder/SpotiFlyer#1117]
**Describe the bug:**

**Media Links Used:** 

**Expected behavior**

**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:    Samsung a 31
 - OS:   [Android 10
 - Version:   [e.g. 3.2.1]
 - Country: russia

**Additional context:**

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
