### ISSUE TITLE
[BUG] : opening settings from settings crash

### ISSUE THREAD

**Issue by j-romchain** [Shabinder/SpotiFlyer#1128]
**Describe the bug:**
In the android app the settings icon remains after opening the settings menu, clicking on it causes the app to crash

**Media Links Used:** 
N/A

**Expected behavior**
Settings button would dissappear, or app would do (seemingly) nothing/not crash when settings is opened from settings.

**Screenshots:**
Would attach recording if I could.

**StackTrace:**
N/A

**Device Info (please complete the following information):**
 - Device:   SAMSUNG smg965u/Samsung galaxy s9
 - OS:   Android 10
 - Version:   3.6.1
 - Country: USA

**Additional context:**
Not much...

**Comment by j-romchain** [comment]
confirmed on uber jar version as well.
a popup appears saying "Configurations in the stack must be unique"

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
