### ISSUE TITLE
[Feature-Request]: <Feature_Title>

Hi there I was wondering if there could be a media interface like Spotify and make the app like freezer music as new freezer music is pretty much dead I think adding this feature would be a winner even if you stuck a payment for lifetime use 😀 

### ISSUE THREAD

**Issue by owencz1998** [Shabinder/SpotiFlyer#1129]
Is it possible to have a ui like Spotify or like the app freezer so your able to use it like an normal Spotify app as freezer is pretty much dead:)

**Comment by 3BooD-CS** [comment]
This is a great idea,but I couldn't download songs from Spotify, I tried
YouTube and it worked. Maybe try to add more popular streaming services.
Also in the search bar can you add a "clear" button because it's
uncomfortable to erase a long link.


‫في السبت، 19 فبراير 2022 في 1:37 م تمت كتابة ما يلي بواسطة ‪owencz1998‬‏ <‪
***@***.***‬‏>:‬

**Comment by owencz1998** [comment]
Could possibly make a yt music ui that does it all from youtube i would suggest deezer but  thats if the creator would pay for hifi account to get the arl code so we can all download in flac but isnt really required  and also the ability to download every album from the artist from a single link. With most apps people seem to stop working on them after time which is sad to see because people love it (freezer music).

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
