### ISSUE TITLE
[BUG] : Song is not Same as Gaana or Spotify (Source)

### ISSUE THREAD

**Issue by GlassThrone** [Shabinder/SpotiFlyer#1138]
**Describe the bug:**
Many times lately when downloading a song from Spotify or Gaana or even an album or playlist, some songs in the album or playlist are not what the song is. Even a single track is different when downloaded.

**Media Links Used:** 
https://gaana.com/song/dream-boy-28
https://open.spotify.com/track/0iRETuEwGQYDcswzitj2Mr?si=ehyQgV16Tv6f-P7L75MOKA&utm_source=copy-link

**Expected behavior**
Song should be what you hear on Spotify, Gaana. Jiosaavan is sometimes correct. Try downloading with the two links above and see what I mean. Listen to them I Spotify or Gaana and you will see. Below is the Jiosaavan link that works correctly in this this song. At times it is the opposite.

https://www.saavn.com/s/song/punjabi/Dream-Boy/Dream-Boy/Bx4eQxYFQF4

**Device Info (please complete the following information):**
 - Device:  Galaxy Note 20Ultra, Galaxy A52s 5G
 - OS:   Android 12
 - Version:  3.6.1
 - Country: So far All the Countries I have tried

**Additional context:**
Not Applicable

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
