### ISSUE TITLE
[BUG] : <Music title>

### ISSUE THREAD

**Issue by hasa12977** [Shabinder/SpotiFlyer#1139]
Hello. When I want download a music, it shows its name normal <<see screenshot>> but when download is completed, it changes its name to something in Chinese or Japanese. 

![Screenshot_20220221-213337.jpg](https://user-images.githubusercontent.com/98240073/155052630-4403fe21-6794-4c38-a89b-40d481864f8d.jpg)

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
