### ISSUE TITLE
[BUG] : <Issue_Title>

### ISSUE THREAD

**Issue by Ezioauditorre58** [Shabinder/SpotiFlyer#1142]
**Media Links Used:** 

**Expected behavior**

**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info:**
 - Device:   [Samsung note 10 lite]
 - OS:   [Android]
 - Version:   [e.g. 3.6.1]
 - Country: [south africa]

**Additional context:**

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
