### ISSUE TITLE
The song i downloaded is not in a high quality to 320kpbs i check the mb and it's still low quality 

### ISSUE THREAD

**Issue by Kawxx55** [Shabinder/SpotiFlyer#1147]

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
