### ISSUE TITLE
[BUG] : <can't_give_access_to_save_music_to_SD_card>

### ISSUE THREAD

**Issue by qqshixx** [Shabinder/SpotiFlyer#1157]
**Describe the bug:**

**Media Links Used:** 

**Expected behavior**

**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   [Xiaomi Redmi 8]
 - OS:   [Android Q (Android 10)]
 - Version:   [e.g. 3.6.1]
 - Country: [Ukraine]

**Additional context:**
 I can not give access to download tracks to the SD card. error (quote): No download access to: storage/sd/music/, return to the previous value. help please

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
