### ISSUE TITLE
[BUG] : can't download music from SoundCloud 

### ISSUE THREAD

**Issue by MayBeNotSimon** [Shabinder/SpotiFlyer#1158]
**Describe the bug:**
 Everytime I want to download a track from SoundCloud it shows a ERROR Messege and the download isn't starting

**Media Links Used:** 
 All SoundCloud tracks
https://soundcloud.app.goo.gl/vQXpA

**Expected behavior**
 It should start downloading like it does with YouTube 

**Screenshots:**

![Screenshot_20220301-215239](https://user-images.githubusercontent.com/96396609/156247142-cbea838a-a942-478c-b5fe-cba9ffc57980.png)

**Device Info (please complete the following information):**
 - Device:   Google Pixel 4a
 - OS:   Android 11
 - Version:   newest at the time I am writing this 
 - Country: Germany

Everything works normal except SoundCloud

**Comment by yavnaz** [comment]
Same Issue

**Comment by MetalNeo** [comment]
Same issue here: https://soundcloud.com/user-84234361/dont-stop-thefatrat-rmxx

**Comment by hero369369** [comment]
Same

**Comment by RaleEZ** [comment]
- For anyone who cannot download music from SoundCloud via Spotiflyer, you can use website https://soundcloudtomp3.app | You can download MP3 files in both 128KB or 320KB. Hope it helps and solves your problem! 😁

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
