### ISSUE TITLE
Request to access SD card

### ISSUE THREAD

**Issue by hotlikewassabi** [Shabinder/SpotiFlyer#116]
I do not see the app requesting to have access and only says it doesn't have access when i try to download to the SD card or choose it as path.

**Comment by Shabinder** [comment]
@hotlikewassabi thanks.for reporting this issue , will fix this in coming update.

**Comment by Shabinder** [comment]
I am sorry to inform but writing to External SDCard  wont be added.
It requires SAF(Storage Access Framework) ,and it's like 25-50 times slower than Java File API. (https://www.xda-developers.com/android-q-storage-access-framework-scoped-storage/)
Moreover it brings more issues/hacks/WorkArounds/Slowness than it brings Features.

**Comment by vis2x** [comment]
@Shabinder do you know a specific version  that this bug doesn't work in? I would like to try downgrading to it in the meantime

**Comment by Shabinder** [comment]
> @Shabinder do you know a specific version that this bug doesn't occur in? I would like to try downgrading to it in the meantime

Nope , It occurs in all Versions.
