### ISSUE TITLE
[BUG] : WebApp doesn't fetch the song, gets stuck on the loading page.

### ISSUE THREAD

**Issue by asrvd** [Shabinder/SpotiFlyer#1164]
**Describe the bug:**
The webapp doesn't fetch the song data after searching it.

**Media Links Used:** 
https://open.spotify.com/track/4C3vAnXJmFR2McECc1du5l?si=d0cf0eaf9699410e

**Expected behavior**
Able to download the song.

**Screenshots:**
![image](https://user-images.githubusercontent.com/68690233/156561073-9b8cfd87-c7f3-4eb3-9fe8-cb09010ebf3e.png)

**Device Info (please complete the following information):**
 - Device:   Desktop
 - OS:   Windows 10
 - Version:   3.6.1
 - Country: India

**Comment by yavnaz** [comment]
Same here, while using SoundCloud

**Comment by MysticMaestro** [comment]
same issue for me using spotify

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
