### ISSUE TITLE
[Feature-Request]: Download music from osu map links

### ISSUE THREAD

**Issue by counter185** [Shabinder/SpotiFlyer#1178]
**Is your feature request related to a problem? Please describe.**
No, other than the fact osu has a massive catalog of music that is not available and/or is region-locked on YouTube or Spotify. There's also quite a few lesser-known songs that would just be completely lost if they weren't made into osu maps.

**Describe the solution you'd like**
Add support for downloading music from osu map links. I will explain how this can be done in the **Additional context** section

**Describe alternatives you've considered**
I mean, I could always just download them from the website and manually unpack the mp3 files

**Additional context**
A GET requests need to be made to the following link: `https://osu.ppy.sh/beatmapsets/<id>/download`, where `<id>` is song-specific
Additionally, the following headers must be set in the request:
* `Referer`: it must be `https://osu.ppy.sh/beatmapsets/<id>`. This is also the link users would normally paste into the app.
* `Accept-Encoding`: `gzip, deflate, br`
* `Accept`: I'm not sure if everything here is required, but the following string works:
`text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8`
* `Cookie`: These cookies must be present:
  1. `XSRF-TOKEN`
  2. `osu_session`
Both of these are normally set in the browser after logging in on the website

If the request is invalid, an HTML document with a login prompt will be sent
Otherwise, the request will return a ZIP archive containing the main music file (it is often the `.mp3` format), custom sound effect files and backgrounds [if there are any], and `.osu` files
These are text files, from which metadata (separated by newlines) can be read
Most notably:
* `AudioFilename: <audio file>`: the name (with extension) of the main music file contained in the archive
* `Title: <>`: song title (ASCII characters only)
* `TitleUnicode: <>`: song title (UTF-8)
* `Artist: <>`: song artist (ASCII characters only)
* `ArtistUnicode: <>`: song artist (UTF-8)

While there are multiple `.osu` files (for context, they are all the included difficulty levels), the game's mapping guidelines state that `Title`, `Artist` and `AudioFilename` must stay the same across all difficulties, so it's safe to assume every present `.osu` file will have the same values for these fields

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
