### ISSUE TITLE
Re-download

### ISSUE THREAD

**Issue by DivyanshVerma12** [Shabinder/SpotiFlyer#1183]
There should be a re-download feature as when downloading complete albums or even sometimes only one song the downloaded song is not working.
As the download is corrupted and you cannot re-download the song until you have changed download location so please try to add that.
Also thank you for your amazing work as it provides good quality for free. 
So really thank you.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
