### ISSUE TITLE
some songs I download only are 1 second long, what do I do about it?

### ISSUE THREAD

**Issue by Vikng412** [Shabinder/SpotiFlyer#1186]
![image](https://user-images.githubusercontent.com/78209058/157710625-bdce9382-cc9e-4eac-b909-a9fd0055feaf.png)
![image](https://user-images.githubusercontent.com/78209058/157710674-7eade56c-8fd5-4d12-9f14-041ce4ef24f1.png)

An Update:I found out that this problem is only when you download songs on Windows/PC. Songs download full length on android.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
