### ISSUE TITLE
Desired Songs doesnt get downloaded, Youtube Matching Error.

### ISSUE THREAD

**Issue by Jkim1402** [Shabinder/SpotiFlyer#119]
about 23 crashes every 163 music i download, is there a patch?

**Comment by Shabinder** [comment]
Device Info?
Platform?
Version Using?

**Comment by Jkim1402** [comment]
I am running on my Samsung galaxy s20 and windows 10 computer
sorry I haven't specified correctly.
The app doesn't crash it works perfectly fine.
its that some music fail to download when downloading

**Comment by Shabinder** [comment]
> Like this


Like what? I think you forgot to attach a screenshot

**Comment by Shabinder** [comment]
Does the issue happen on both android and windows? and does the failed songs downloads when you retry?

**Comment by Jkim1402** [comment]
i have its under the like this message

**Comment by Jkim1402** [comment]
i cannot retry, there is no button for it

**Comment by Shabinder** [comment]
> i have its under the like this message


Nope Its Isnt there.
<img width="642" alt="image" src="https://user-images.githubusercontent.com/44765050/117718598-eb71aa00-b1f9-11eb-900a-5d3ec6852a7e.png">

**Comment by Jkim1402** [comment]
[image: Screenshot_20210510-204204_SpotiFlyer.jpg]
oh sorry let me do it again

**Comment by Jkim1402** [comment]
i tried it again however couple still fail. some manage out though

**Comment by Jkim1402** [comment]
So in the
https://open.spotify.com/playlist/37i9dQZF1DZ06evO2Uv076?si=nL_-7sLcQ_issYb7C0Plxg&utm_source=copy-link&dl_branch=1

Playlist
Scroll to the bottom and try download these 2

**Comment by Jkim1402** [comment]
[image: Screenshot_20210510-211522_SpotiFlyer.jpg]
can you see now

**Comment by Jkim1402** [comment]
yes

**Comment by Shabinder** [comment]
if there is a youtube song for same, I can improve youtube matching algo to correctly find the song.

Share the youtube music link if the song you are looking for is there.

PS: https://music.youtube.com/watch?v=S852F9VkS2c is this the desired song?

**Comment by Jkim1402** [comment]
Yes, that's it.
alright, thank you for helping.
i hope the youtube algorithm improvement goes well
Thank you.
I also want to code in the future like you (even though this is quite off
topic)

**Comment by Jkim1402** [comment]
Thank you for your support!

**Comment by Shabinder** [comment]
> i also donated 9 dollars thank you for your support


Thanks for your kind donation, It means a lot!

May I know on which platform/link you donated?

**Comment by Jkim1402** [comment]
i done it from opencollective.com ?
[image: Open collective]
<https://opencollective.com/>

**Comment by Jkim1402** [comment]
Ahaha your welcome

**Comment by Jkim1402** [comment]
Btw I can translate the app into korean but I'm doing my GCSEs right now so
when I finish that, I'll get onto it

**Comment by Jkim1402** [comment]
Hey, it's Juan again, congrats on you version 3.0 release

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
