### ISSUE TITLE
add support for apple music

### ISSUE THREAD

**Issue by linusrg1** [Shabinder/SpotiFlyer#1190]
itd be great if this had support for apple music as with the way apple music currently is you cannot always download all songs.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
