### ISSUE TITLE
Can't download to SD card (S20 ULTRA)

### ISSUE THREAD

**Issue by BezZero** [Shabinder/SpotiFlyer#1195]
I am trying to set the download location to SD card on Android but it doesn't show up, I only see internal storage.
![Screenshot_20220312-141008](https://user-images.githubusercontent.com/93748498/158031593-41fb221f-bf98-4cb9-8ebc-da6a8df6be30.jpg)

**Comment by CorruptedPlazma** [comment]
Same problem here on a Galaxy A12 running Android 12/OneUI Core 4.1

**Comment by Exx4** [comment]
Same problem here on a Nokia 6.1 running LineageOS 18.1

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
