### ISSUE TITLE
Songs Not Downloading in 320 KBPS Quality

### ISSUE THREAD

**Issue by Purpledroid88** [Shabinder/SpotiFlyer#1199]
All songs, regardless of how they sound within Spotify, are downloading in 128 kbps resolution. So when you listen to the songs offline on a music player app, there is a significant difference in the sound quality. Spotify picks up much more detail and so, tracks sound way better on Spotify than they sound coming from Spotiflyer, even when I switch the preferred audio quality setting to 320 kbps within the Spotiflyer app.

**Comment by CQCmaster** [comment]
Same issue with YouTube. Only 128kbps :(

**Comment by Purpledroid88** [comment]
So this is a known issue? Is there any way to fix this?

**Comment by QQBQBQL** [comment]
same issue here

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
