### ISSUE TITLE
Download location?

### ISSUE THREAD

**Issue by stathis8585** [Shabinder/SpotiFlyer#12]
It seems that i share the playlists and songs are downloaded. But i dont seem to have a library screen or be able to find the downloads. Xiaomi mi8 here. Thank you in advance

**Comment by muertead** [comment]
It will be visibal in couple days in Music folder

**Comment by stathis8585** [comment]
Thanks!

**Comment by Shabinder** [comment]
Not a Couple Days , Just refresh your music app in order to make it refresh its Library and you will get all the Downloads there.
