### ISSUE TITLE
[BUG] : <Download issue>

### ISSUE THREAD

**Issue by Mr-ZQS** [Shabinder/SpotiFlyer#1203]
**Describe the bug:**
cant download the song from either spotify playlist or by providing the yt url directly

**Media Links Used:** 
https://www.youtube.com/watch?v=HlzI69m1df0

**Expected behavior**
find the song or start download from the provided yt link

**Screenshots:**
https://i.imgur.com/h8nvpNp.png

**StackTrace:**
```
DownloadLinkFetchFailed(errorTrace=Find Link for Kol Elly Fi Alby 

Fetching From Saavn Failed:DownloadLinkFetchFailed(errorTrace=No SAAVN Match Found for Kol Elly Fi Alby)
	at com.shabinder.common.providers.saavn.requests.JioSaavnRequests$DefaultImpls.findBestSongDownloadURL(JioSaavnRequests.kt:44)
	at com.shabinder.common.providers.saavn.requests.JioSaavnRequests$findBestSongDownloadURL$1.invokeSuspend(JioSaavnRequests.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionG
```

**Device Info:**
 - OS:   [WinOS]
 - Version:   [10 21H2]
 - Country: [Egypt]

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
