### ISSUE TITLE
Can't download songs with similar titles 

### ISSUE THREAD

**Issue by Kendu26** [Shabinder/SpotiFlyer#1204]
I'm unable to download songs that have the same titles ... After I download a certain song with a particular title, I'm unable to download an entirely different song of the same title. It just shows the downloaded sign even though I haven't downloaded the new one yet

**Comment by d-gaia** [comment]
I also have the same issue here. Cannot download a song due to existence of other song with the same name. Even changing the existing song name and location won't do anything.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
