### ISSUE TITLE
Some music won't to be downloaded.

### ISSUE THREAD

**Issue by BaraaAlmodrek** [Shabinder/SpotiFlyer#121]
![Screenshot_2021-05-14-04-42-57-119_com shabinder spotiflyer](https://user-images.githubusercontent.com/12837462/118213798-e23d4300-b46e-11eb-9426-10f4971d2be4.jpg)

**Comment by Shabinder** [comment]
v3.2.0 have some fixes and you can see the cause if some song fails , and share that by creating a new issue if there is any

https://github.com/Shabinder/SpotiFlyer/releases/tag/3.2.0
