### ISSUE TITLE
[BUG] : Fragmented downloads are not registered when restarting a playlist

### ISSUE THREAD

**Issue by luphoria** [Shabinder/SpotiFlyer#1215]
**Describe the bug:**

If you download any song, but exit the app before the download is complete, a partial download remains and is then registered by spotiflyer as a successful download.
**Media Links Used:** 

NA
**Expected behavior**

The fragment is detected as a fragment, and the download either restarts or is discarded
**Screenshots:**

NA
**StackTrace:**
```
Paste Stacktrace here if available
```
NA
**Device Info (please complete the following information):**
 - Device:   oneplus 8
 - OS:   android
 - Version:   f-droid: latest 
 - Country: USA

**Additional context:**

NA

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
