### ISSUE TITLE
Soundcloud download issue

### ISSUE THREAD

**Issue by SaifUllah25** [Shabinder/SpotiFlyer#1216]
Can't download a single song from Soundcloud
Always an Error
(Also tried VPN, but doesn't work)

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
