### ISSUE TITLE
App wont install

### ISSUE THREAD

**Issue by MalusiMbatha** [Shabinder/SpotiFlyer#122]
app wont install on my samsung A30s it returns a message app not installed
![Screenshot_20210516-125451_Package installer](https://user-images.githubusercontent.com/75620071/118394612-01da9400-b646-11eb-8ce6-ef0487f225f7.jpg)

**Comment by Shabinder** [comment]
if you are updating, uninstall the previous version and try again.

**Comment by Shabinder** [comment]
also check play protect isn't blocking the app, in some devices you will be asked to allow installation in play protect dialog, allow that too.

**Comment by Shabinder** [comment]
Did you get the installation done?

**Comment by MalusiMbatha** [comment]
i uninstalled the old one and i was able to install the new version thank you.

**Comment by Shabinder** [comment]
Gr8 , closing this issue then
