### ISSUE TITLE
[BUG] : Filenames are just underscore(s)

### ISSUE THREAD

**Issue by CarterSnich** [Shabinder/SpotiFlyer#1222]
**Describe the bug:**

Filesnames of some songs are just underscore(s), causing some songs detected as already downloaded. Already checked the `/Spotiflyer` and `/Spotiflyer/Tracks` folders.

**Media Links Used:** 

First song:
https://open.spotify.com/track/1OA144pXkdPDAdp8nm14Pk?si=4YtXzRdSQcmUP1iTdraLpA&utm_source=copy-link

Second song:
https://open.spotify.com/track/2StLz1e2VTwCm8Jnkke7OF?si=9pqc5cSCTL-juQ0kkce8IA&utm_source=copy-link

**Expected behavior**

Filenames of the downloaded songs should be the title or something that make sense instead of just underscore(s).

**Screenshots:**

![Screenshot_2022-03-22-17-57-16-95_034e0326429f3b404601e9b17fbe8654](https://user-images.githubusercontent.com/52433531/159455010-7ffbc8a8-5048-4ff3-851d-673853061e48.jpg)

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   Realme 6i
 - OS:   Android 11
 - Version:   3.6.1
 - Country:  Philippines

**Additional context:**

**Comment by 5vr** [comment]
> This seems to happen with certain non-ascii characters, like the Russian alphabet. Entire albums are just a bunch of underscores.

What's the fix?

**Comment by CarterSnich** [comment]
> > This seems to happen with certain non-ascii characters, like the Russian alphabet. Entire albums are just a bunch of underscores.
> 
> What's the fix?

You can fix it by yourself or just wait for the maintainer to fix it. I have already forgotten this since I use `yt-dlp` on Termux now. It works so much better.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
