### ISSUE TITLE
[BUG] : no network connection

### ISSUE THREAD

**Issue by changemenemo** [Shabinder/SpotiFlyer#1237]
**Describe the bug:**
Sorry I m not going to respect the template before I might forget when I will really have the time to complete this bug report

GrapheneOS android12 
No network connection with or without vpn.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
