### ISSUE TITLE
media player

### ISSUE THREAD

**Issue by senolfndk** [Shabinder/SpotiFlyer#1238]
can you make a media player like this

![Screenshot_20220327-003516](https://user-images.githubusercontent.com/52818836/160258115-cb96016f-63c1-4be6-b12e-2a2fb1b07428.jpg)
![Screenshot_20220327-004233](https://user-images.githubusercontent.com/52818836/160258116-48e9738d-b52b-452e-a692-737665200811.jpg)

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
