### ISSUE TITLE
Error running on windows

### ISSUE THREAD

**Issue by KCMicheal** [Shabinder/SpotiFlyer#124]
Please the desktop version doesn't seem to work even after making it an admin

**Comment by Shabinder** [comment]
What issue are you encountering , please describe.
Is App Opening ?, can you search songs?

**Comment by KCMicheal** [comment]
No its doesn't proceed even after showing a white portrait window background then the process exits.

**Comment by Shabinder** [comment]
hey do you have installed java?
try running java --version in cmd and share output

**Comment by KCMicheal** [comment]
![Screenshot (168)](https://user-images.githubusercontent.com/63565225/118624687-4474ab80-b7c1-11eb-8fc9-1547b368c1c4.png)

**Comment by Shabinder** [comment]
So as far as I can understand you open the app and see a white blank screen, nothing more right?

**Comment by Shabinder** [comment]
Try installing java 15 and rerunning the app.
after installing java 15 , check again using java --version to see if newly installed java 15 is default.

**Comment by KCMicheal** [comment]
yes

**Comment by KCMicheal** [comment]
> Okay I just installed the java JDK and restarted my system yet it's still not any better
> ![{59616AA5-54FE-48B5-8600-1698AA85709B} png](https://user-images.githubusercontent.com/63565225/118653309-4b121b80-b7df-11eb-8994-6d040051a0ce.jpg)

Here☝

**Comment by Shabinder** [comment]
Now did you get the app working?

**Comment by Shabinder** [comment]
@KCMicheal , Hey , you might get the IDEA that I won't address this issue as I haven't responded back for quite some time,

DON'T Worry, In a day or two (**_probably this weekend)_** I will share a **jar** with you which you can run and then provide me the **stacktrace** which will appear in terminal.

**So I ask you to please wait till weekend** , I am occupied with some other tasks right now. 🙃 

I will be sharing you the **jar** and **instruction** on what to do to resolve the issue you facing. ✌️

**Comment by SayanK1** [comment]
App is not opening. "**Failed to launch JVM**" dialogue box appears. see the screenshot.
![Screenshot 2021-05-22 182050](https://user-images.githubusercontent.com/84628484/119228240-bcc7cd80-bb2f-11eb-9e81-2f3c2665d2b7.png)

**Comment by Shabinder** [comment]
I will drop a jar tomorrow which hopefully will work without issues on systems where .exe is giving issues

**Comment by Shabinder** [comment]
@SayanK1 @KCMicheal v3.1.0 is Released , please check it out if Windows MSI doesn't work try Windows Jar version , it should work
