### ISSUE TITLE
[BUG] : Songs skips forward exactly at 10 second mark in each downloaded song (from Spotify)

### ISSUE THREAD

**Issue by wwwouterrr** [Shabinder/SpotiFlyer#1246]
**Describe the bug:**
All tracks downloaded from Spotify skip tens of milliseconds at the 10 second mark. 
Noticed when analysing tracks using DJ software.

**Media Links Used:** 
Any song from Spotify

**Expected behavior**
Track is shortened by tens of milliseconds at the 10 second mark, making tracks unsuitable for beat mixing.
This happens on all tracks (I tried many).

**Screenshots:**
![spotiflyer](https://user-images.githubusercontent.com/55625783/160791357-c0a068c0-ebb2-4bbb-9826-2a4c200faab8.png)

Screenshot shows beat analysis by Rekordbox on two different songs downloaded using Spotiflyer. Both exhibit the same glitch at 10 seconds into the track.

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   PC & Phone
 - OS:   Windows 11, Android
 - Country:  Netherlands

**Additional context:**
Exact same issue occurs with Windows and Android version. On every single track. This is a major bug.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
