### ISSUE TITLE
No song is downloading 

### ISSUE THREAD

**Issue by felix7droid** [Shabinder/SpotiFlyer#125]
I've tried every method but no song is downloading.
![20210518_111357](https://user-images.githubusercontent.com/84341952/118600260-337c6800-b7ca-11eb-9992-7f2e2c1fb596.jpg)

**Comment by Shabinder** [comment]
Share device info please , have you granted storage permission ? And share playlist link too

**Comment by felix7droid** [comment]
It's a galaxy a10s running on android 10. One UI 2.1 
Yes,I've granted all permissions including storage and background running.link:
https://open.spotify.com/album/5dGWwsZ9iB2Xc3UKR0gif2?si=bmvafx-SRdO8Ryih8m6xNw&utm_source=copy-link

**Comment by MareGraphics** [comment]
The same thing happens to me, I'm on Redmi note 8 pro, MIUI 12, android 10

**Comment by AbdallahMehiz** [comment]
Same

**Comment by felix7droid** [comment]
Thanks, dude its working after the update...👍

**Comment by Shabinder** [comment]
> Thanks, dude its working after the update...+1

I am glad it started working for you.
But I literally never found the cause and did something specifically to fix said issue. Something automatically Happened behind the scenes, Anyway important thing is it works. :partying_face:
