### ISSUE TITLE
[BUG] : Silent track beginnings and instrumentals

### ISSUE THREAD

**Issue by iansquenet** [Shabinder/SpotiFlyer#1250]
**Describe the bug:**
Some songs are a few second silent at the beginning, others come as instrumentals.

**Media Links Used:** 
Spotify.

**Expected behavior**
Expected to get a track that starts right away and doesn't come as a instrumental.

**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:  Intel computer [e.g. iPhone6, Samsung J2, PocoF1]
 - OS:  WinOS 10 Pro [e.g. iOS, Android 10, WinOS, MacOS]
 - Version:  21H2 [e.g. 3.2.1]
 - Country: Estonia [eg: India, will help in detecting if service is accessible to u]

**Additional context:**

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
