### ISSUE TITLE
[Feature-Request]: The thumbnail of respective song correctly

### ISSUE THREAD

**Issue by heartlog** [Shabinder/SpotiFlyer#1251]
Just a request to correctly add the thumbnail of correct song

Every time I download songs each song get the thumbnail of first song so, please fix to set correct thumbnail

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
