### ISSUE TITLE
[BUG] : Everything is broken

### ISSUE THREAD

**Issue by chello783** [Shabinder/SpotiFlyer#1253]
Issues include
- Not downloading songs
- Downloading only the instrumental
- Downloading live versions
- downloading fucking nightcore versions
Can you please fix your fucking app already it's been unusable for months

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
