### ISSUE TITLE
No support for external storage (microSD)? ?

### ISSUE THREAD

**Issue by D3NN15x** [Shabinder/SpotiFlyer#1257]
The App doesnt let me choose my microSD card as a Download Location. I dont want to download whole playlists again and copy the new songs since my library contains over 1800 songs. 

Please let me know if this feature is missing or i didnt notice the Problem. I gave the App full storage permissions already and in the developer options i activated full storage access (needed it anyway for other purposes).

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
