### ISSUE TITLE
[BUG] : <Issue_Title>

### ISSUE THREAD

**Issue by Bhaumik2004** [Shabinder/SpotiFlyer#1266]
**Describe the bug:**
When downloading a playlist, some songs with the same name but different artists and evrything do not download or only one of them downloads.
There's another: some songs are just not downloading. a file is created with the song name but that file is always lesst than 100kb in size (screenshot attached)

**Media Links Used:** 
(https://open.spotify.com/playlist/6Eu8KlpD8GOjmqEIa0bvqi?si=67f8e33161ac4711)

**Expected behavior**
All the songs should download because they have they same name but are from different artists and the duration is also different.

**Screenshots:**
![image](https://user-images.githubusercontent.com/72428864/162190137-bcbe3cc4-92e7-41ea-b65a-380db78e03a0.png)

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:  Dell Inspiron 3521
 - OS:   Windows 10 Pro
 - Version:   3.6.1
 - Country: India

**Additional context:**

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
