### ISSUE TITLE
Čs SpotiFlyer 

### ISSUE THREAD

**Issue by Pafkara** [Shabinder/SpotiFlyer#1271]
https://github.com/Shabinder/SpotiFlyer/blob/translations/Strings_cs.properties/a9b1647433b0fae9b7135cee0a789499b81cf62f

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
