### ISSUE TITLE
Cz

### ISSUE THREAD

**Issue by Pafkara** [Shabinder/SpotiFlyer#1277]
Cz SpotiFlyer 

_Originally posted by @Pafkara in https://github.com/Shabinder/SpotiFlyer/pull/1072#pullrequestreview-934745553_

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
