### ISSUE TITLE
[BUG] : downloaded files missing disc number tag

### ISSUE THREAD

**Issue by azumukupoe** [Shabinder/SpotiFlyer#1283]
**Describe the bug:**

downloaded files are missing disc number tags
**Media Links Used:** 

https://open.spotify.com/album/0LV4hwe1982xjN0bVBhpFw?si=vamLzSiNRVe1KHgRB8gmNw
**Expected behavior**

files to be tagged with disc number
**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device: Samsung SC-03J
 - OS: Android 9
 - Version: v3.6.1
 - Country: Japan

**Additional context:**

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
