### ISSUE TITLE
[BUG] : Long songs not fully downloading

### ISSUE THREAD

**Issue by Rarufuwu** [Shabinder/SpotiFlyer#1292]
**Describe the bug:**
Some downloads that are 10+ mins long only download half the song. I was downloading the song "Alpha - C418" which was about 10:03 mins long, it only downloaded 5:02 mins of the song. I tried downloading from other links like youtube but still the same result.

**Media Links Used:** 
https://open.spotify.com/track/0RZfz4zLlFb1lNtoEr7yDR?si=cdb123b514bc408d
https://www.youtube.com/watch?v=uNCGM7FJ8wQ

**Expected behavior**
I expected the song to be fully downloaded.

**Screenshots:**
![image](https://user-images.githubusercontent.com/101916390/163101895-525a63a6-1046-4e26-9448-aeee9060abaa.png) 
![image](https://user-images.githubusercontent.com/101916390/163102472-b62e164e-1511-4232-b709-a050c5528794.png)
*I also don't know what FFmpeg is 😓*

**Device Info:**
 - Device:   [Dell Latitude E6430]
 - OS:   [WinOS]
 - Version:   [20H2]
 - Country: [eg: Philippines]

**Additional context:**
This is my first day of using this app and I really like it but sometimes songs just don't download correctly.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
