### ISSUE TITLE
Show download progress [Feature Request]

### ISSUE THREAD

**Issue by Daksh777** [Shabinder/SpotiFlyer#13]
It would be great if the download progress for individual songs being downloaded were shown in the notification (and possibly in the app?)

**Comment by mani445** [comment]
> It would be great if the download progress for individual songs being downloaded were shown in the notification (and possibly in the app?)

Wow

**Comment by Shabinder** [comment]
Yeah , working on same. 
Will be released in next update.
**_Stay Tuned_**

**Comment by Shabinder** [comment]
Added a **Download Progress Arc** in 1.7 Release.
![image](https://user-images.githubusercontent.com/44765050/100902608-0cb3c900-34eb-11eb-9b2e-6a28c0e2a80a.png)
