### ISSUE TITLE
[BUG] : Genre is set to `Genre:` instead of the actual genre

### ISSUE THREAD

**Issue by danbulant** [Shabinder/SpotiFlyer#1302]
**Describe the bug:**

The ID3 tag Genre is set to text `genre:` instead of actual genre

**Media Links Used:** 

All I tried from spotify.

**Expected behavior**

Correct genre set

**Screenshots:**

<img width="150" alt="image" src="https://user-images.githubusercontent.com/30036876/163818981-ad1065f5-67ce-4e08-ac18-6736c027e2b4.png">

**Device Info (please complete the following information):**
 - Device:   Lenovo Legion 5 pro
 - OS:   Windows 11
 - Version:   3.6.1
 - Country: Czech Republic

**Comment by samiullahqutbi** [comment]
I'm also facing this problem

**Comment by spyrou008** [comment]
Reproduced on Linux version of [SpotiFlyer](https://github.com/Shabinder/SpotiFlyer) with music files downloaded thanks to a Spotify link.
See image below:
![image](https://user-images.githubusercontent.com/76167958/173538084-0510c09c-669e-4428-828b-3d3401c15427.png)
Also: Comment is wrong. 
Note: linked to https://github.com/Shabinder/SpotiFlyer/issues/1430

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
