### ISSUE TITLE
[BUG] : <Application is too laggy. Each click is actually clicked after like 5 seconds>

### ISSUE THREAD

**Issue by iamsamiullah** [Shabinder/SpotiFlyer#1304]
**Describe the bug:**

**Media Links Used:** 

**Expected behavior:** It should be working smoothly

**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   PC
 - OS:   WINDOWS 10
 - Version:   21H2
 - Country: INDIA

**Additional context:**

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
