### ISSUE TITLE
[BUG] : Bitrate switch issue

### ISSUE THREAD

**Issue by asmol82** [Shabinder/SpotiFlyer#1306]
Hello!
I'm trying to download music from Spotify at 320 kbps through a windows 7 app, but the output file only gives me 128kbps bitrate. How can this be fixed? Here's a link to the proof file just in case. [https://od.lk/f/N18yMDk4NTk5NTFf](url)

Thanks.

**Comment by CaffineAddic** [comment]
I got the same issue all the music files are downloaded as 128 kbps where we want 320 kpbs

**Comment by asmol82** [comment]
I switched to the paid Noteburner. Youtube, as practice has shown, does not always provide the necessary content, and Noteburner downloads all the necessary albums for my mp3 player. Spotify rocks! \m/

So it goes!

**Comment by CaffineAddic** [comment]
Too poor to afford it

**Comment by asmol82** [comment]
Your problems, I have enough money for this so far and everything is just fine. ))
