### ISSUE TITLE
[BUG] : <The BUg Reporting Popup is not in a proper size which makes it hard to copy the bug code>

### ISSUE THREAD

**Issue by CodeOnYT** [Shabinder/SpotiFlyer#1310]
The BUg Reporting Popup is not in a proper size which makes it hard to copy the bug code

**Comment by CodeOnYT** [comment]
![image](https://user-images.githubusercontent.com/51966967/164574593-2d94a5d3-b57e-473f-9d4f-ef3348a08405.png)

**Comment by CodeOnYT** [comment]
![image](https://user-images.githubusercontent.com/51966967/164574754-164589e5-b17c-4189-a982-be5f90e32269.png)
It is something like this.
but is should be correct to set auto width and height based on device width and height of the display

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
