### ISSUE TITLE
Problems with downloading other kind of audio files

### ISSUE THREAD

**Issue by MisterBombastic3** [Shabinder/SpotiFlyer#1314]
Foremost, I want to thank you for this tool. It is very simplistic and efficient. Although I have recently encountered that some kind of audio that are not common songs (for instance radio plays) unfortunately don't work at all. I would be extremely grateful if this issue could be fixed for this ingenious program.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
