### ISSUE TITLE
[BUG] not downloading the correct version.

### ISSUE THREAD

**Issue by WrecKedByPotaTo** [Shabinder/SpotiFlyer#1330]
This is going to be very niche song but whenever I try to download "Take me Home, Country Road" link below it only has the instrumental version with no words. I know not many people will ever want this song but if there is anything you can do I would appreciate it.
https://open.spotify.com/track/1YYhDizHx7PnDhAhko6cDS?si=ZgnouAHjQB-loc8ICwYtRw&utm_source=copy-link

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
