### ISSUE TITLE
[Feature-Request]: portable version

### ISSUE THREAD

**Issue by thaynos** [Shabinder/SpotiFlyer#1331]
I would love to have a portable version or at the very least not have the app require admin access to install.

Make a portable zip version which does not require admin permission, dependencies can be made in the same path instead i guess?

**Comment by nobaraos12** [comment]
portable version would be amazing for laptops or computers that don't have admin access.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
