### ISSUE TITLE
[Feature-Request]: Volume Normalization

### ISSUE THREAD

**Issue by teodortomas** [Shabinder/SpotiFlyer#1333]
**Is your feature request related to a problem? Please describe.**

_**I hate, that every song i download has different volume, I need to normalize it with mp3gain, wich is only for pc, so i need to transfer mp3 files to my pc and back**_

**Describe the solution you'd like**

_**I would like some automatic normalization working even on phones (if possible)**_

**Describe alternatives you've considered**
-

**Additional context**
**_Here you can see, that mp3gain is showing these dB volume levels for my playlist..._**
![obrazek](https://user-images.githubusercontent.com/91433717/166506527-e39123b8-cee8-481d-b805-ef594570c202.png)

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
