### ISSUE TITLE
[Feature-Request]: <Lyrics Integration>

### ISSUE THREAD

**Issue by b2sinha** [Shabinder/SpotiFlyer#1337]
Along with metadata is there any way to save its (songs) lyrics .

Or this can be on your ''To Do''

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
