### ISSUE TITLE
[BUG] : 401 Unauthorized. text error

### ISSUE THREAD

**Issue by guranu** [Shabinder/SpotiFlyer#1338]
**Describe the bug:**whenever i try to download any songs it gives me this error
Media Links Used:
https://m.soundcloud.com/harmful-logic/sets/soulgemcollection-ep-https

Expected behavior: i was expecting the program to work as intended 

**Screenshots:**
![Screenshot_20220503-160430](https://user-images.githubusercontent.com/103632948/167267492-000f0f8d-1623-4c7a-9efd-bfaa47d12662.jpg)

**Device Info (please complete the following information):**
 - Device: Oneplus 7
 - OS: Android 10
 - Version: 3.6.1
 - Country: Russia

**Comment by guranu** [comment]
why did i even expected a response from this.

**Comment by guranu** [comment]
So much for support you FUCKING LAZY SACKS OF SHITS HOW MANY FUCKING PEPOLE ARE TALKING THE FACT THAT THEY FUCKING CAN'T DOWNLOAD SONG'S FROM YOU'RE FUCKING SERVICE AND YET YOU DO FUCKING NOTHING ABOUT IT.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
