### ISSUE TITLE
[BUG] : not downloading vocals 

### ISSUE THREAD

**Issue by decarabiia** [Shabinder/SpotiFlyer#1345]
**Describe the bug:**
despite the spotify link i used having a vocal track, the downloader only grabbed the backing instrumentals
i have managed to replicate this on both the android and windows desktop versions of the app

[update 16 may 2022] actually i wonder if spotiflyer's downloading an entirely different track than the link i input? i've apparently downloaded covers of a song instead, when i link the original (tho this is only with spotify links so far, has yet to happen with yt music)

**Media Links Used:** 
https://open.spotify.com/track/7y76ci3Ghg0wFgX0ldNbCx?si=29cea1c130ee436c
[this is the file i ended up with](https://cdn.discordapp.com/attachments/918528795705741435/972650714792857620/dcbdbe34a660c382.mp3)

**Device Info (please complete the following information):**
 - Device: samsung note 10
 - OS: android 12, win 10
 - Version: 3.6.1
 - Country: canada

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
