### ISSUE TITLE
[BUG] : <The app download the wrong song>

### ISSUE THREAD

**Issue by d-gaia** [Shabinder/SpotiFlyer#1354]
**Describe the bug:**

Downloaded song is the wrong song

**Media Links Used:** 
[](https://open.spotify.com/track/1pOUyghyAB1gKHTtz9tXt0?si=955c6562787b4d23&nd=1)

**Expected behavior**

The downloaded song is the correct song

**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   PC
 - OS:   WinOS
 - Version:   3.6.1
 - Country: [eg: India, will help in detecting if service is accessible to u]

**Additional context:**

The downloaded song is different from the what the media link provides

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
