### ISSUE TITLE
[BUG] : <Issue_Title> Support for Spotify SHOW is not implemented yet

### ISSUE THREAD

**Issue by Sibasish** [Shabinder/SpotiFlyer#1355]
**Describe the bug:**
I tried do download one of the youtube Podcasts but the download didnot even start as I faced the error whose screenshot is attached. Please let me knoe what needs to be done.

**Media Links Used:** 
<[!---  - Paste Song/Album/Playlist Link where you encountered this issue ---](https://open.spotify.com/show/6iOUWo1PR5AmpR5me97idh?si=c37b3f4db4f54cfb)
https://open.spotify.com/show/3gyenNhpv2JIvu5nTccaFr?si=d040a03b7a83450a>

**Device Info (please complete the following information):**
 - Device:   HP I
 - Processor : Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz   1.80 GHz
 - RAM : 8.00 GB
![Screenshot (43)](https://user-images.githubusercontent.com/8840620/168476752-47ff8a82-382a-4b0d-a6b7-9b4dc9e5f0f6.png)

 - OS:   Windows 10 Home Single Language
 - OS build : 19044.1706
 - Version:  21H2 
 - Country: India

**Comment by Sibasish** [comment]
Any response on this?

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
