### ISSUE TITLE
Publish on Play Store

### ISSUE THREAD

**Issue by theshininginception** [Shabinder/SpotiFlyer#1356]
Hello,

Wouldn't it be great if SpotiFlyer could be published on the Play Store to expand reach to users and provide an easier way to keep the app updated?

Thank you

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
