### ISSUE TITLE
Songs Not downloading!!!

### ISSUE THREAD

**Issue by chinu8005** [Shabinder/SpotiFlyer#1367]
I came across this issue while downloading a few songs. As I love your work so send this issue as a Text file. Thank You for #Spotiflyer
[Spotiflyer Issue.txt](https://github.com/Shabinder/SpotiFlyer/files/8723932/Spotiflyer.Issue.txt)

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
