### ISSUE TITLE
DownloadLinkFetchFailed(errorTrace=Find Link for Mabahrbsh 

### ISSUE THREAD

**Issue by ahmed-elgzar** [Shabinder/SpotiFlyer#1369]
Fetching From Saavn Failed:DownloadLinkFetchFailed(errorTrace=No SAAVN Match Found for Mabahrbsh)
	at com.shabinder.common.providers.saavn.requests.JioSaavnRequests$DefaultImpls.findBestSongDownloadURL(Ji

**Comment by tksalarzai** [comment]
Following.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
