### ISSUE TITLE
[Error] Cannot Launch SpotiFlyer

### ISSUE THREAD

**Issue by NaagShakti** [Shabinder/SpotiFlyer#137]
_**Distributor ID**: Kali
**Description**:    Kali GNU/Linux Rolling
**Release**:         2021.2
**Codename**:     kali-rolling
**uname -a**:       SMP Debian 5.10.28-1kali1 (2021-04-12) x86_64 GNU/Linux_

```
$ java -jar SpotiFlyer*.jar

Error: LinkageError occurred while loading main class MainKt
        java.lang.UnsupportedClassVersionError: MainKt has been compiled by a more recent version of the Java Runtime (class file version 58.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```

How can this issue be resolved?
Also I am unable to run after installing with .deb package with error 
```
Error: dl failure on line 534
Error: failed /opt/spotiflyer/lib/runtime/lib/server/libjvm.so, because /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /opt/spotiflyer/lib/runtime/lib/server/libjvm.so)
Failed to launch JVM
```

I know there is high probability that problem is with my packages. How may I solve this?

**Comment by Shabinder** [comment]
As Issue said , you need jre class version 58, i.e.,install java 14 and check it using java --version before executing .jar

![image](https://user-images.githubusercontent.com/44765050/119726183-76a39e80-be8e-11eb-885d-9c0fe1bf0b9d.png)

**Comment by NaagShakti** [comment]
Thanks! Worked like a charm. I was unable to understand the error at first. Thanks for this awesome mind boggling project!
