### ISSUE TITLE
[FEATURE REQUEST] Option for artist folder when downloading an album

### ISSUE THREAD

**Issue by Captn138** [Shabinder/SpotiFlyer#1371]
Title says all, i suggest an option that lets you download an album in the 'Albums' folder or download it in an artist-specific folder inside the 'Album' folder.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
