### ISSUE TITLE
[FEATURE REQUEST] Clear history button

### ISSUE THREAD

**Issue by Captn138** [Shabinder/SpotiFlyer#1372]
The history function is great but sometimes I would very much like to be able to clear it, as I don't always have a stable connection and need to go through my history to restart some downloads, it can be a bit confusing.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
