### ISSUE TITLE
[FEATURE REQUEST] Downloads tab in-app

### ISSUE THREAD

**Issue by Captn138** [Shabinder/SpotiFlyer#1373]
Like the notification indicator but would be great to pause, resume, stop, restart and clear downloads for a better control. Also, an option to limit the number of simultaneous downloads would be great.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
