### ISSUE TITLE
[Feature-Request]: <docker image for unraid>

### ISSUE THREAD

**Issue by funny0121** [Shabinder/SpotiFlyer#1374]
Hey great app, is there any way to you could create a docker image? I would love to use this in unraid with lidarr. Thanks

**Comment by Marcus-Schubert** [comment]
Indeed, having a docker image would be very beneficial.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
