### ISSUE TITLE
[BUG] : "Failed to launch JVM"

### ISSUE THREAD

**Issue by Sabbkavelli** [Shabinder/SpotiFlyer#1377]
**Describe the bug:**
When I try to open the app it says "Failed to launch JVM"

**Screenshots:**
![image](https://user-images.githubusercontent.com/76211745/169700477-8ff34b73-edbd-4a77-a043-175cfb6feba4.png)

**Device Info (please complete the following information):**
 - Device:   A laptop
 - OS:   WinOS
 - Version:   OS Build 19041.546, Windows 10
 - Country: US

**Additional context:**
I tried to download ffmpeg and put in in a folder while also saving it in system variables https://youtu.be/r1AtmY-RMyQ .
Then I went and put it in system 32 https://bytemeta.vip/repo/Shabinder/SpotiFlyer/issues/1111 .
And now I deleted it.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
