### ISSUE TITLE
[BUG] : <Issue_Title>No letters on the application on windows 10

### ISSUE THREAD

**Issue by thecharus** [Shabinder/SpotiFlyer#1380]
No letters on the application on windows 10
There are no letter, you cannot read anything

**Media Links Used:** 
No need, the app interace does not show any letters.

**Expected behavior**
See letters to know what is happening including errors

**Screenshots:**
![imagen](https://user-images.githubusercontent.com/47488030/169909728-15b121fb-839d-47cd-8ef7-ec46bc4a3034.png)

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   Computer
 - OS:   Windows 10 21H2 
 - Version:  3.6.1
 - Country: Guatemala

**Additional context:**

![imagen](https://user-images.githubusercontent.com/47488030/169910127-05420ff6-623f-4602-bf48-ed32e45e4e93.png)
![imagen](https://user-images.githubusercontent.com/47488030/169910165-4cf4116f-c11a-421e-a222-6b68dff07b7c.png)

I tried changing Windows Theme to check if issue was pertaining to the theme, and same situation. I included a couple of screenshots.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
