### ISSUE TITLE
[BUG] : Wrong bitrate download

### ISSUE THREAD

**Issue by AliAlmasi** [Shabinder/SpotiFlyer#1381]
I've set the **preferred bitrate** at **320**, but the **downloaded file** is **128**.
No matter where you're trying to download, the bitrate of the downloaded file is 128.
<hr>
OS: Windows 11

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
