### ISSUE TITLE
[Feature-Request]: Proxy Setting for Windows-MSI

### ISSUE THREAD

**Issue by pingko-WI** [Shabinder/SpotiFlyer#1383]
I can't use Windows-MSI in my office because my company blocked something like Spotify, Netflix etc. So I think **Proxy Setting for Windows-MSI version** is essential, to avoid firewall disturbing. If **https and socks5** proxy setting could be added in future, that would be very nice. Cheers!

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
