### ISSUE TITLE
[BUG] : Build fails with lint and compilation errors

### ISSUE THREAD

**Issue by manosbatsis** [Shabinder/SpotiFlyer#1386]
Task `build` fails on `ktlintKotlinScriptCheck` while  `assemble` fails with compilation errors:

```
> Task :web-app:compileKotlinJs FAILED
e: /home/manos/StudioProjects/SpotiFlyerFork/web-app/src/main/kotlin/App.kt: (65, 75): Classifier 'DefaultStoreFactory' does not have a companion object, and thus must be initialized here
e: /home/manos/StudioProjects/SpotiFlyerFork/web-app/src/main/kotlin/root/RootR.kt: (19, 32): Unresolved reference: RouterState
e: /home/manos/StudioProjects/SpotiFlyerFork/web-app/src/main/kotlin/root/RootR.kt: (59, 22): Unresolved reference: RouterState
```

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
