### ISSUE TITLE
Wrapper for other Foss players to use

### ISSUE THREAD

**Issue by mubashir-rehman** [Shabinder/SpotiFlyer#139]
Create an api or wrapper for other Foss players to use SpotiFlyer for song download.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
