### ISSUE TITLE
[BUG] : <Issue_Title> Always Downloading from the wrong link

### ISSUE THREAD

**Issue by Onmyosama** [Shabinder/SpotiFlyer#1393]
**Describe the bug:**

**Media Links Used:** 

**Expected behavior**

**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device: itel p36 pro
 - OS:  Android 9
 - Version:  2
 - Country: Nigeria

**Additional context:**
 on Spotify there's two options for listening to either the censored or explicit versions of a song when i want to download any track, i always copy the link of the explicit version but it keeps downloading the censored version..i downloaded an explicit album yesterday and it omitted one particular song and downloaded it censored... not only that but sometimes it downloades different songs entirely..i could try to download one song now and it would download the remix for me...can this be fixed?

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
