### ISSUE TITLE
[Feature-Request]: Displaying Download Result in History

### ISSUE THREAD

**Issue by thenithinbalaji** [Shabinder/SpotiFlyer#1395]
# Problem
When a playlist is downloaded, the notification shows the number of failed and successful downloads. But when I go to history, I have to click on the playlist and scroll through the list to see what's downloaded and what's not.  

# Solution 
Display the number of failed and successful downloads in the history tab along with the playlist name

# Alternate Solution 
Display the song list inside the downloaded playlist in the history tab in sorted order with failed downloads followed by successful downloads

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
