### ISSUE TITLE
[Feature-Request]: Clear History Button

### ISSUE THREAD

**Issue by thenithinbalaji** [Shabinder/SpotiFlyer#1396]
# Problem 
No option to clear the history. 

# Solution
A button to clear the entire history or a particular song history alone.

**Comment by honzahk** [comment]
Temporary solution - remove the database file `C:\Users\admin\SpotiFlyer\Database\Database.db` and restart the app

**Comment by thenithinbalaji** [comment]
@honzahk what about Android?

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
