### ISSUE TITLE
[Feature-Request]: Swipe to move across About and History Tabs in Android

### ISSUE THREAD

**Issue by thenithinbalaji** [Shabinder/SpotiFlyer#1398]
# Problem
Have to click on History Tab every time to move to History from About. 

# Solution
Swipe Right to move from About to History 
Swipe Left to move from History to About 

# Alternatives
Remove the About tab and make "About" a small button at the top bar.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
