### ISSUE TITLE
[Feature-Request]: Read Clipboard automatically when inside the app & ask whether to download 

### ISSUE THREAD

**Issue by thenithinbalaji** [Shabinder/SpotiFlyer#1399]
# Problem
Have to paste the link manually in the "Paste Link Here Bar"

# Solution 
Read Clipboard automatically when inside the app & ask whether to download the song

# Alternatives 
Fill the "Paste Link Here Bar" using clipboard data.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
