### ISSUE TITLE
Feature request: CLI support

### ISSUE THREAD

**Issue by dzek69** [Shabinder/SpotiFlyer#140]
I'd like to have this tool working from bash on my Linux server. Any plans for something like that?

**Comment by Shabinder** [comment]
Maybe in future,but no plans for now.

Leave this issue open , It sounds interesting and I will see what I can do. ✌️

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
