### ISSUE TITLE
[BUG] : Extreme internet usage while idle, barely opened

### ISSUE THREAD

**Issue by TheNubOfLegend** [Shabinder/SpotiFlyer#1401]
**Describe the bug:**
71 gigabytes of internet usage were recorded by my phone attributed to this app from the period May 1 - May 29.  This is while the app was either entirely or almost entirely untouched, and never used, as I had not yet gotten to the point where it would have been useful.

**Media Links Used:** 
N/A

**Expected behavior**
Idk... not using literally 15x as much internet as all of the other apps on my phone, combined.  In fact, using none at all as I never used the app for its intended purpose.

**Screenshots:**
I removed the app as soon as I was made aware of the problem, and did not take any screenshots.  Without a strong argument for the service using so much data, I am not going to download the app again for privacy concerns.

**StackTrace:**
N/A afaik

**Device Info (please complete the following information):**
 - Device:  Motorola One Action
 - OS:  Android 10
 - Version:  3.6.1
 - Country: USA

**Additional context:**
This amount of data is over 2x as large as the amount I have stored on my phone, alone.  The season or two of Better Call Saul I have watched this month have totalled 2.5 gigabytes of traffic, meaning that Spotiflyer was sending around 30 or 40 seasons of a show, streamed at 720/1080p somewhere.  My internet speed caps at about 20 MiB/s, which means that the equivalent amount of data was sent to 8 hours of constantly using all available bandwidth to me.  

This is either a huge leak of data, one that would be entirely unnecessary given that I never used the service and therefore never manually pinged or requested data from any server using the service, or there is something seriously malicious going on with this app.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
