### ISSUE TITLE
[enhancement] media player

### ISSUE THREAD

**Issue by dotziph** [Shabinder/SpotiFlyer#1405]
If you would instead of building a media player into the app you could build your app into [this](https://github.com/MuntashirAkon/Metro) media player. Personally I think it would be an out of this world good app if you could make this happen.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
