### ISSUE TITLE
[Feature-Request]: apparmor profile

### ISSUE THREAD

**Issue by drzraf** [Shabinder/SpotiFlyer#1409]
**Is your feature request related to a problem? Please describe.**
An apparmor profile ensures application filesystem accesses stay well defined thus well confined.

**Describe the solution you'd like**
Provide an `apparmor` profile as part of the Debian package
(`/etc/apparmor.d/opt.spotiflyer.bin.SpotiFlyer`)

**Additional context**
Attached a working profile (but could possibly be further restrictive):

```
#include <tunables/global>

/opt/spotiflyer/spotiflyerLauncher {
  /opt/ r,
  /opt/spotiflyer/** r,
  /opt/spotiflyer/lib/runtime/** rmr,
  /opt/spotiflyer/lib/app/*.* rmr,
  /opt/spotiflyer/bin/SpotiFlyer ix,
  owner @{HOME}/SpotiFlyer/ rwk,
  owner @{HOME}/SpotiFlyer/** rwlk,
}
```

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.

**Comment by drzraf** [comment]
https://gitlab.com/shabinder/soundbound/-/tree/main/Experimental-Sources/0.2 isn't opensource
(and Linux isn't supported). Not really an alternative for me.

**Comment by Shabinder** [comment]
Its first release only, linux will be supported down the lane.
