### ISSUE TITLE
[Feature-Request]: Windows 11 UI for the Windows app

### ISSUE THREAD

**Issue by Trsier** [Shabinder/SpotiFlyer#1412]
Can you please add Windows 11 UI to the Windows app if possible? The github page says that the app is being rewritten, so it would be nice if you let us know whether the design change will ever be considered. Thanks.

**Comment by Shabinder** [comment]
for desktop we will be using Jetpack compose, hence havent considered above yet.
But still the rewrite is in early phase, lets see what future brings.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
