### ISSUE TITLE
VPS Donation Notice

### ISSUE THREAD

**Issue by PTHyperdrive** [Shabinder/SpotiFlyer#1415]
I've already sent you an email, please take a look

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
