### ISSUE TITLE
[BUG] : got the wrong song

### ISSUE THREAD

**Issue by Afterlight0338** [Shabinder/SpotiFlyer#1417]
**Describe the bug:**
so it downloaded the song that has osu! hitsound

**Media Links Used:** 
https://open.spotify.com/track/2c1LEycbJDdpAfJKPkLFwO?si=40c_jR6WR8igDe0YuQQ2uw&utm_source=copy-link

**Expected behavior**
https://youtu.be/igfAVIF7QYw instead of whatever osu video it downloaded

**Device Info (please complete the following information):**
 - Device:   Poco M4 Pro 5G
 - OS:   Android 11 MIUI 12.5.7
 - Version:   3.6.1
 - Country: Malaysia

**Additional context:**
happens to song that is popular on osu!

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
