### ISSUE TITLE
Songs not downloading

### ISSUE THREAD

**Issue by ghost** [Shabinder/SpotiFlyer#142]
Redmi Note 8 Pro, MIUI 12.0.8.0 QGGMIXM, ANDROID 10
All permissions were granted
![Screenshot_2021-05-29-20-33-09-281_com shabinder spotiflyer](https://user-images.githubusercontent.com/59295266/120082849-24949000-c0bd-11eb-92af-19a82f2d7c5e.jpg)

**Comment by AbdallahMehiz** [comment]
I guess i am ignored, good app bro

**Comment by Shabinder** [comment]
> I guess i am ignored, good app bro

You Are not ignored, I just dont have the measures to help you out.... yet

I own a Poco F1, with MIUI (Android 10) , and app is working fine in my device.

I can only see whats the issue if I get my hands on a **device with above said issue**

**Comment by otakuchan198** [comment]
Hi,
Not actual active help(for the time being), but hopefully some insight.

I am having the same issue on two devices(LG V30 via FDroid, Manjaro via jar).

On the mobile I could not download anything(though I did not try very long).
On PC I could download the same songs I could not download on the mobile and then some.

I noticed the issue again when I tried downloading a playlist, when it downloaded some but not all songs with the x that is in the post above. Actually I wanted to get some information on that x as I don't know what it means.
That aside, I closed the app and started it again. It downloaded one additional song (I know from the timestamps) and stopped again.

If you need more information I can try and get it for you. I have a Windows at hand as well and could try it there too, for example.

**Comment by yavnaz** [comment]
Hi, good job on this app;  much appreciated! I'm having the same issue with songs not downloading on my international unlocked SG Note 20 Plus, running Android 11.

**Comment by Shabinder** [comment]
@yavnaz @otakuchan198 v3.2.0 may work , check it out , if it still doesnt share the crash report which is viewable in-App by creating a new issue.

https://github.com/Shabinder/SpotiFlyer/releases/tag/3.2.0
