### ISSUE TITLE
Genre not included in songs

### ISSUE THREAD

**Issue by No-Git-Tag** [Shabinder/SpotiFlyer#1430]
# Issue
songs/albums downloaded using Spotiflyer do not have genre mentioned, it is just "Genre:"

# remedy
 potentially search databases for genre of song and adding it to the metadata for said song/album

**Comment by spyrou008** [comment]
Reproduced on Linux version of [SpotiFlyer](https://github.com/Shabinder/SpotiFlyer) with music files downloaded thanks to a Spotify link.
See image below:
![image](https://user-images.githubusercontent.com/76167958/173538084-0510c09c-669e-4428-828b-3d3401c15427.png)
Also: Comment is wrong. 
Note: linked to https://github.com/Shabinder/SpotiFlyer/issues/1302

**Comment by sT0n3r** [comment]
Any luck on getting this fixed ?

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
