### ISSUE TITLE
[BUG] : The audio quality is 128kbps.. 

### ISSUE THREAD

**Issue by ktodorow** [Shabinder/SpotiFlyer#1432]
I installed SpotiFlyer on Linux.. When I download a song it's not 320kbps.. Any ideas why?

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
