### ISSUE TITLE
[BUG] : <Pressing the settings button in settings causes app to crash>

### ISSUE THREAD

**Issue by jbro129** [Shabinder/SpotiFlyer#1435]
**Describe the bug:**
Step 1: Open the app
Step 2: Click the settings button on the top right corner.
Step 3: Once inside the settings menu, click the settings button in the top right again.
Step 4: The app has crashed.

**Device Info (please complete the following information):**
 - Device: Galaxy S20 Ultra
 - OS: Android 11
 - Version: v3.6.1
 - Country: US

I understand the app is being rewritten as it currently says in the repos descriptions. I didn't know if this was already reported or not.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
