### ISSUE TITLE
[Feature-Request]: Site For Your App

### ISSUE THREAD

**Issue by Hashah2311** [Shabinder/SpotiFlyer#1436]
### Keep up the great work👍, Thank You

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
