### ISSUE TITLE
Higher than 128 kbps would be nice

### ISSUE THREAD

**Issue by Amy-Triptyline** [Shabinder/SpotiFlyer#144]
As tutle

**Comment by Shabinder** [comment]
Hey 320 Kbps support has been added , will be available in next release.
New Release will be available in 2/3 Days.
https://github.com/Shabinder/SpotiFlyer/commit/3913bfa4b154f62798fcfb42ab9fbd35b4478665

**Comment by Amy-Triptyline** [comment]
Hey great news! Thanks for speedy reply :) And I understand about the SD card now. Cheers. 👍
