### ISSUE TITLE
[BUG] : can't  download  song.....plz fix it.

### ISSUE THREAD

**Issue by nikhil13space31** [Shabinder/SpotiFlyer#1445]
**Describe the bug:**

**Media Links Used:** 
https://open.spotify.com/track/6vp2kWUZ99zyxpzkwtLtJu?si=YqOd1Rv8T1Ka-7od3EYU5g&utm_source=copy-link

**Expected behavior**

**Screenshots:**

![image](https://user-images.githubusercontent.com/107199110/172872812-6b06e763-0872-4d7c-8b87-1b592316203a.png)

**StackTrace:**
```
Paste Stacktrace here if available
https://open.spotify.com/track/6vp2kWUZ99zyxpzkwtLtJu?si=9nrl_aMbRXK6FgcpgAVUmg&utm_source=copy-link

**Device Info (please complete the following information):**
 - Device: Samsung M31
 - OS:  Android 12
 - Version:   [e.g. 3.2.1]
 - Country: [eg: India, will help in detecting if service is accessible to u]

**Additional context:**
<!--- Add any other context about the problem here. --->

**Comment by nikhil13space31** [comment]
> 
> 
> **Describe the bug:**
> 
> 
> **Media Links Used:** 
> https://open.spotify.com/track/6vp2kWUZ99zyxpzkwtLtJu?si=YqOd1Rv8T1Ka-7od3EYU5g&utm_source=copy-link
> 
> **Expected behavior**
> 
> 
> **Screenshots:**
> 
> ![image](https://user-images.githubusercontent.com/107199110/172872812-6b06e763-0872-4d7c-8b87-1b592316203a.png)
> 
> 
> **StackTrace:**
> ```
> Paste Stacktrace here if available
> https://open.spotify.com/track/6vp2kWUZ99zyxpzkwtLtJu?si=9nrl_aMbRXK6FgcpgAVUmg&utm_source=copy-link
> 
> **Device Info (please complete the following information):**
>  - Device: Samsung M31
>  - OS:  Android 12
>  - Version:   [e.g. 3.2.1]
>  - Country: [eg: India, will help in detecting if service is accessible to u]
> 
> **Additional context:**
> 
> 
 

Plz 
Fix it fast......

**Comment by guranu** [comment]
It's a waste of time to expect them to fix it.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
