### ISSUE TITLE
[Feature-Request]: Entry SpotiFlyer put in the correct menu subsection in GNU Linux

### ISSUE THREAD

**Issue by spyrou008** [Shabinder/SpotiFlyer#1448]
**Is your feature request related to a problem? Please describe.**
When SpotiFlyer is installed , in Linux, an entry is created in the menu. (the equivalent thing of the MS Windows : "Start menu"). The SpotiFlyer entry is created in the category "Other". 

**Describe the solution you'd like**
The SpotiFlyer entry should be created in the category "Multimedia". as all the other multimedia softwares, such as: mpv, vlc, sound converter, etc.

**Describe alternatives you've considered**
N/A. only alternative is to edit the menu manually. or with "MenuLibre"

**Additional context**
See screenshot: AS IS
![SpotiFlyer-AS-IS](https://user-images.githubusercontent.com/76167958/173106056-ac0f894c-3237-490f-906e-6ee448fedb7a.png)

See screenshot: TO BE
![SpotiFlyer-TO-BE](https://user-images.githubusercontent.com/76167958/173106079-f9238f37-eff0-44e9-9b8d-c9c26086194e.png)

**Comment by SilentPartner** [comment]
My request is not problem related but first inquiring as to if this app/software has the ability to retrieve the same data but encode said results as .ogg in place of the.mp3 format currently offered/standard? Next, l wanted to know if it's it possible to import YouTube subscriptions, import SoundCloud subscriptions, export your subscriptions as a backup and lastly export all Spotiflyer data as a backup?

Any or all of these suggestions would be optimal in my opinion and based on my needs/desires.

My only logical alternative would be to continue using this phenomenal application and manually convert the resulting.mp3's into.ogg files.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
