### ISSUE TITLE
Spotify quality won't download 320 kbps

### ISSUE THREAD

**Issue by knightmob** [Shabinder/SpotiFlyer#1449]
Hello, what a wonderful app you have, I'm excited for it's new reboot release! There's just one thing though, why is the quality still low? even though I set the music quality to 320 kbps but after I download any songs, quality is still stuck to 128 kbps. Idk if it's a bug or it's just my Android fucking up, but I hope you'll fix this issue! Btw one hell of an app, keep up the good work!

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
