### ISSUE TITLE
Wrong Song

### ISSUE THREAD

**Issue by Rhys-Davies2007** [Shabinder/SpotiFlyer#145]
I found this issue both quite funny and confusing.  I downloaded a playlist and everything was perfect except for one song.  Livin' for That by Lil Pitchy didn't have any vocals and it was just the instrumental version of the song.  Not sure what happened but that is the only issue I've expirenced.

**Comment by Rhys-Davies2007** [comment]
Noticed this with two other songs as well.  Just for You also by Lil Pitchy.  And also Headshot by Polo G, Lil TJ and Fivio Foreign.

**Comment by Shabinder** [comment]
Yeah this possible , please share playlist link where these two songs you downloaded

**Comment by Rhys-Davies2007** [comment]
Sure!  Here's the link: https://open.spotify.com/playlist/5444dslvM8SCSH7JkcEDWE?si=87ed906dd341443f

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
