### ISSUE TITLE
[Don't mute explicit words]: In some songs there are explicit words which you mute them so pls don't mute them

### ISSUE THREAD

**Issue by Snowwyy123** [Shabinder/SpotiFlyer#1453]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Tofixrs** [comment]
Is this ever gonna be addressed? Songs from spotify still download the unexplicit version

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
