### ISSUE TITLE
[BUG] : Russian letters changed in downloaded file , but in app all right

### ISSUE THREAD

**Issue by DonTMover** [Shabinder/SpotiFlyer#1459]
**Describe the bug:**
 Russian language in files filled "___" symbols

**Media Links Used:** 
 https://open.spotify.com/playlist/5EFnaDrUHA3dUc2UuVAh7D?si=69ghXGXdQXqfHtmsL7PmxQ&utm_source=copy-link

**Expected behavior**

**Screenshots:**
![Screenshot_20220615-161733_Files_by_Google.png](https://user-images.githubusercontent.com/46960051/173836850-5151c1db-b940-4eb3-82d9-4ff1b0467d45.png)![Screenshot_20220615-161845_SpotiFlyer.png](https://user-images.githubusercontent.com/46960051/173836867-ce8b537f-a77f-4682-89e3-8d26a8821b7e.png)

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   Poco x3 pro
 - OS:   Android 11
 - Version:   3.6.1
 - Country: Belarus

**Additional context:**

**Comment by ArqeNade** [comment]
The same problem exists in Turkish language.
