### ISSUE TITLE
download speed

### ISSUE THREAD

**Issue by senolfndk** [Shabinder/SpotiFlyer#146]
windows 10 not downloading songs 😕

https://user-images.githubusercontent.com/52818836/120112917-ad283480-c180-11eb-98a6-d603bc7ff81d.mp4

**Comment by Shabinder** [comment]
Web App is in Beta and will be slow because of an intermediate Proxy!.

if you are using Win10 try Desktop version instead,

Anyway you can always track WebApps Progress in Console.
To Access Console:
 - Press Q (To Enter Inspect Mode)
 - Then go into console.
Refer Below Images: 
![image](https://user-images.githubusercontent.com/44765050/120113330-93461c00-c197-11eb-9439-ac17bc16174d.png)

**Comment by senolfndk** [comment]
the link does not stick https://user-images.githubusercontent.com/52818836/120113780-b74c3200-c184-11eb-9b38-2ae799d36e25.mp4

**Comment by senolfndk** [comment]
the link does not stick 
![SharedScreenshot](https://user-images.githubusercontent.com/52818836/120113840-07c38f80-c185-11eb-9be3-9b6fc04fe077.jpg)

**Comment by Shabinder** [comment]
try using ctrl c & ctrl v

**Comment by senolfndk** [comment]
I press ctrl but it doesn't work

**Comment by Shabinder** [comment]
that's Strange , as it does work for me

Still I think its a blame to Jetpack Compose Desktop , as Its still very new and immature.
 - Use Android App (it's Stable)
 - then the only option is to just use web app and compromise with speed
 - Manually type link into desktop app

**Comment by senolfndk** [comment]
ok I solved the sticking problem

**Comment by Shabinder** [comment]
> ok I solved the sticking problem

How ?
Your Solution would help others who are facing similar solution.

**Comment by senolfndk** [comment]
I tried again as you said, pressed ctrl v and it stuck

**Comment by senolfndk** [comment]
download speed is too slow

**Comment by Shabinder** [comment]
> download speed is too slow

Even in Desktop App? 
What Speed Are you getting? 
For me Speed is as par with my connection.

If Downloads are successful then there isnt much I can do :upside_down_face: 

In Coming Release I am adding more sources which will add some more delay in favour of getting a Higher Quality Audio.

It's just something we have to compromise with.

**Comment by senolfndk** [comment]
yes it's slow in the desktop app too 
![SharedScreenshot](https://user-images.githubusercontent.com/52818836/120117468-0189df00-c196-11eb-99d4-d9420a374b9b.jpg)
