### ISSUE TITLE
[BUG] : does not work in windows 7: .msi nor .jar

### ISSUE THREAD

**Issue by PepeParada** [Shabinder/SpotiFlyer#1463]
Hello. I use google translate.

I have Windows 7 x64 home edition. I have the latest Java update installed. I tried the .jar file first, and it didn't work on my machine.
Then I tried with the .msi file and that didn't work either.
In the latter I could see the active process in the task manager, but I couldn't open the application at all.

I can still use the app from my Android just fine. So I thank the developer very much.
I just wanted to try on Windows, but there was no way.

**Comment by DonTMover** [comment]
use java -jar file.jar

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
