### ISSUE TITLE
[Feature-Request]: Retry failed downloads button

### ISSUE THREAD

**Issue by aha999** [Shabinder/SpotiFlyer#1467]
**Is your feature request related to a problem? Please describe.**
Currently if some of the downloads fail (Android app), there is no "retry failed downloads" button, to see if anything was wrong so it could be normally downloaded.

**Describe the solution you'd like**
Add a "retry failed downloads" button.

**Comment by Xanthey** [comment]
Currently downloading a 5,000-song Spotify playlist, i would love to see this feature as well. Currently i'm waiting for it to finish it's run so that i can go down the list and manually retry each.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
