### ISSUE TITLE
Music quality

### ISSUE THREAD

**Issue by john009q** [Shabinder/SpotiFlyer#147]
Hi how to choose music quality?

**Comment by Shabinder** [comment]
Sadly U cant from next Update:
Highest Available Quality(320KBPS) will be preferred.

**Comment by Shabinder** [comment]
Apk with 320KBPS is release check it out

**Comment by Shaashank009** [comment]
> Apk with 320KBPS is release check it out
Hello brother thank you so much for this work
I have a question privious version have best quality sound or this new 3.1.1 have, and the size of the songs are big. Long size songs = best quality?

**Comment by Shabinder** [comment]
@Shaashank009 3.1.0 new release provides better quality upto 320 kbps while prev release was limited to 128 kbps , and yes 320 kbps are larger in size than 128 kbps

**Comment by mizzunet** [comment]
This issue may be closed, I guess

**Comment by Shabinder** [comment]
> This issue may be closed, I guess

Leave it open as in future I intend to give a **music quality chooser** , like user can select which quality he wants ,as some might want to prefer 128KBPS bcuz of low **size**

**Comment by IM71** [comment]
@Shabinder Hi, success to download from spotify and youtube music, but only get 128KBPS using 3.1.0, any fix?
THX!

**Comment by Shabinder** [comment]
@IM71  320KBPS is not available for every song , only which are also available on Jiosaavn, so if you are getting 128KBPS that means that song wasn't available on Jio-Saavn and hence app downloaded from Youtube Music.

**Comment by alireza1385mamani** [comment]
Hello everyone how are you I hope you will be good I haven't request for you can you do something that we can choose the quality of this songs that we are downloading and please add the free lossless audio code support for the songs thank you

**Comment by rahool-rex** [comment]
Hello developer Great work. Direct option to download song from share option is what I wanted & it was right there. One more thing I don't have option to download song in particular bitrate like I downloaded a song from youtube (1080p available) & it was already auto downloaded @128kbps bt wt if I want @higher bitrate. Please add this option already using latest version. Thanks again for such work.

**Comment by Shabinder** [comment]
> Hello everyone how are you I hope you will be good I haven't request for you can you do something that we can choose the quality of this songs that we are downloading and please add the free lossless audio code support for the songs thank you

I am sorry to inform but we will be using mp3 only because of their vast support and even 3rd party libs for editing m4a metadat etc isnt that gr8 for all platforms , however this could change in future

**Comment by Shabinder** [comment]
You can select Preferred Music Quality in v3.2.0 

https://github.com/Shabinder/SpotiFlyer/releases/tag/3.2.0
