### ISSUE TITLE
I was trying to download some songs from the Guardians of the Galaxy The Original Video Game Playlist but they don't want to download.

### ISSUE THREAD

**Issue by Jawlee5888** [Shabinder/SpotiFlyer#1478]
**Media Links Used:** 
]([](url)https://open.spotify.com/playlist/1IaaDKR0912vGUrrRxtTV9)
**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:  Samsung Galaxy Tab A7 [e.g. iPhone6, Samsung J2, PocoF1]
 - OS: Android 11  [e.g. iOS, Android 10, WinOS, MacOS]
 - Version: 3.1 [e.g. 3.2.1]
 - Country: Michigan [eg: India, will help in detecting if service is accessible to u]

**Additional context:**

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
