### ISSUE TITLE
Song Directory

### ISSUE THREAD

**Issue by makujan** [Shabinder/SpotiFlyer#148]
Where can i find my downloaded songs i'm using android

**Comment by Shabinder** [comment]
Default Directory: storage/emulated/0//**Music/SpotiFlyer/**

**Comment by dvoyakiy** [comment]
When I try to change the default to SD card it says permission denied. Could you please help with that? I downloads songs to internal storage successfully but doesn't work with external storage.

**Comment by Shabinder** [comment]
This is desirable, As App Doesnt support writing on SD , and probably will neved do , unless google allows normal java file api access on SD instad of Storage access framework.

For more background on this issue refer to #116 #143
