### ISSUE TITLE
[BUG] : Bad taskbar integration under Ubuntu

### ISSUE THREAD

**Issue by AFCMS** [Shabinder/SpotiFlyer#1483]
**Describe the bug:**

In the taskbar, the icon is blurred and the infotext says "java-lang-Thread"

**Expected behavior**
The infotext should show "SpotiFlyer" like the window title.
The icon should have a higher resolution.

**Screenshots:**
![Capture d’écran du 2022-06-25 18-44-39](https://user-images.githubusercontent.com/61794590/175783063-a52f699c-b0c7-46dc-abb7-c4048da4c8aa.png)

**Device Info (please complete the following information):**
 - Device:   ASUS Laptop
 - OS:   Ubuntu
 - Version:   20.04
 - Country: France

**Additional context:**
I used the `.deb` file to install SpotiFlyer

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
