### ISSUE TITLE
[BUG] : Download Error

### ISSUE THREAD

**Issue by Fallen-Skull** [Shabinder/SpotiFlyer#1497]
Hello , This project of yours is really usefull...Very Rare to find..
but when i download most of it downloads but some songs altered version gets downloaded is there any way to fix it..
Cause its the only problem this program has..
PLS FIX THIS 
Also I use to download spotify Playlist

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
