### ISSUE TITLE
Not downloading

### ISSUE THREAD

**Issue by Y0lands** [Shabinder/SpotiFlyer#15]
I used the app a few days ago and it was working fine, but today nothing wants to download. Completed just stays at 0 for hours.

**Comment by Shabinder** [comment]
Okay in few cases the bug is that if last track is not found then whole Playlist/Album wont download , I have fixed this , will push an update soon.

**Comment by Shabinder** [comment]
Fixed in new Update, check it out! , if issue still persists , reopen the issue or open another regarding the issue.
