### ISSUE TITLE
After downloading any song the search bar should clear.

### ISSUE THREAD

**Issue by t4sn33m-s4h4t** [Shabinder/SpotiFlyer#1505]
After downloading any song by searching the search bar should clear. The Spotify links are too long so it takes time to clear the search bar. It should clear automatically.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
