### ISSUE TITLE
Jio Saavn Link not works after share from Android App

### ISSUE THREAD

**Issue by Aleandr-1987** [Shabinder/SpotiFlyer#151]
Hi, As it says I tried adding Albums, Playlist and even single tracks from Jio-Saavn but song don't appear on downloading list. It remains blank. Other sources like Spotify, Gaana and YouTube music is working fine.
![Screenshot_20210601-095120262](https://user-images.githubusercontent.com/66353026/120266223-1910b700-c2bf-11eb-9628-906900dc91c0.jpg)

**Comment by Shabinder** [comment]
I just found this issue , please copy links from **browser** jio-saavn , app links won't work for now will fix in next update

**Comment by Aleandr-1987** [comment]
Ok thanks for the information.

**Comment by Shabinder** [comment]
Fixed in https://github.com/Shabinder/SpotiFlyer/commit/37fe18ef1675728822286165e51f4b64f81f05d8 , will be available in 3.2.0
