### ISSUE TITLE
[BUG] : <FFmpeg not found at path>

### ISSUE THREAD

**Issue by Fla201** [Shabinder/SpotiFlyer#1511]

**Comment by Rishi-k-s** [comment]
Same issue : https://github.com/Shabinder/SpotiFlyer/issues/746

**Comment by bverkron** [comment]
Same

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
