### ISSUE TITLE
[BUG] : Not downloading over 128kbps

### ISSUE THREAD

**Issue by wolfram85** [Shabinder/SpotiFlyer#1512]
I do own a YT Music Premium account but I'm unable to download music at High Quality even if this is setted in the Spotifly and YT Music app or website . All songs are downloaded just at 128kbps.

System: Android 12 and Windows 11

Thank you

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
