### ISSUE TITLE
[BUG] : Partial download

### ISSUE THREAD

**Issue by BercziSandor** [Shabinder/SpotiFlyer#1518]
**Describe the bug:**
You can play the song on the web spotify in the full length. (13:20)
The app seems to download the song (see screenshot) in the full length  but after opening you can see that the file is corrupt: Spotiflyer downloads only the first 6:45 of the song.
I could reproduce this behavior on Android and Windows.

**Media Links Used:** 
https://open.spotify.com/embed/track/6CqrTdQiKhNoG6AnOkVXwc

**Expected behavior**
 - Error message OR
 - Download the song fully

**Screenshots:**
![image](https://user-images.githubusercontent.com/1443421/177713997-04fb2969-5fab-4f0c-b79b-a137122c5d72.png)

**StackTrace:**
NA

**Device Info (please complete the following information):**
 - Device:   PC
 - OS:   Win10
 - Version:   3.6.1
 - Country: Austria

**Additional context:**
The last bytes of the downloaded file are:
```
3f05 e16f c054 0344 cfc5 a222 621f f212
209a 1724 9ff8 9217 23c1 790b 7ffa 9a84
2428 31fe b5b4 283d 4c41 4d45 332e 3939
2e35 5555 5555 5555 5555 5555 5555 5555
5555 5555 5555 5555 5555 5555 5555 5555
5555 5555 5555 5555 5555 5555 5555 5555
5555 5555 5555 5555 5555 5555 5555 5555
5555 5555 5555 5555 5555 5555 5555 5555
5555 5555 5555 5555 5555 5555 5555 5555
5555 5555 5555 5555 5555 5555 5555 5555
5555 5555 5555 5555 5555 5555 5555 5555
5555 5555 5555 5555 5555 5555 5555 5555
5555 5555 5555 5555 5555 5555 5555 5555
5555 5555 5555 5555 5555 5555 5555 5555
5555 5555 5555 5555 5555 5555 5555 5555
5555 5555 5555 5555 5555 5555 5555 5555
5555 5555 5555 5555 5555 5555 5555 5555
5555 5555 5555 5555 5555 5555 5555 5555
5555 5555 5555 5555 5555 5555 5555 5441
474b e974 657a 6572 20c9 7600 0000 0000
0000 0000 0000 0000 0000 0000 0000 0041
6674 6572 2043 7279 696e 6700 0000 0000
0000 0000 0000 0000 0000 0000 0046 f66c
6420 c973 20c9 6700 0000 0000 0000 0000
0000 0000 0000 0000 0000 0032 3031 3347
656e 7265 733a 4765 6e72 6573 3a6e 756c
6c00 0000 0000 0000 0000 0000 00ff 
```

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
