### ISSUE TITLE
Feature: Downloads tab

### ISSUE THREAD

**Issue by mizzunet** [Shabinder/SpotiFlyer#152]
As for now, downloading showing only as in the notification, right?
I think it would be nicer if there's a tab for Download where shows downloads with progress percentage.

**Comment by Shabinder** [comment]
> As for now, downloading showing only as in the notification, right?
> I think it would be nicer if there's a tab for Download where shows downloads with progress percentage.

Download progress is itself shown at right side in Circular Progress bar , A seperate tab for same is needed?

**Comment by Shabinder** [comment]
Instead I intend to make the behaviour of that progress bar better as for now I have seen it usually waits for completion and then fills from zero to 100 instantly...right?

**Comment by mizzunet** [comment]
> > As for now, downloading showing only as in the notification, right?
> > I think it would be nicer if there's a tab for Download where shows downloads with progress percentage.
> 
> Download progress is itself shown at right side in Circular Progress bar , A seperate tab for the same is needed?

But when downloading multiple songs, isn't it a bit hard to go back and see the if it's actually downloading or stuck and all?

**Comment by mizzunet** [comment]
> Instead I intend to make the behaviour of that progress bar better as for now I have seen it usually waits for completion and then fills from zero to 100 instantly...right?

I didn't get that. 
Maybe progress in notification would be sufficient I think.

**Comment by Shabinder** [comment]
> > Instead I intend to make the behaviour of that progress bar better as for now I have seen it usually waits for completion and then fills from zero to 100 instantly...right?
> 
> I didn't get that.
> Maybe progress in the notification would be sufficient I think, rather than a new tab

I meant the circular progress bar which appears after user clicks in download IconButton

**Comment by mizzunet** [comment]
> > > Instead I intend to make the behaviour of that progress bar better as for now I have seen it usually waits for completion and then fills from zero to 100 instantly...right?
> > 
> > 
> > I didn't get that.
> > Maybe progress in the notification would be sufficient I think, rather than a new tab
> 
> I meant the circular progress bar which appears after user clicks in download IconButton

Ah I see. https://github.com/Shabinder/SpotiFlyer/issues/152#issuecomment-852050616

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
