### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by stemy2** [Shabinder/SpotiFlyer#153]
Hello,

I can't even perform a search without having the message "an error occured, check your link/connection". I checked, my connection works well outside this app.

**Comment by Shabinder** [comment]
You can't do a normal search query yet , instead paste a link from supported platforms.

**Comment by zedmike** [comment]
I get the same connection error when trying to add a podcast like https://open.spotify.com/show/4rOoJ6Egrf8K2IrywzwOMk

**Comment by Shabinder** [comment]
Podcasts and episodes are not supported yet
