### ISSUE TITLE
[BUG] : wrong song

### ISSUE THREAD

**Issue by ThinBucket82549** [Shabinder/SpotiFlyer#1537]
So. Im gonna take a guess that this just looks up the song on youtube if you put in a spotify link. Becuase i downloaded a song and it wasnt the song. It had the tags correct but the song was from another album by the artist. (Plus its 128 kbps)

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
