### ISSUE TITLE
JVM

### ISSUE THREAD

**Issue by Ritvikisalive-coding** [Shabinder/SpotiFlyer#1541]
Every time i try to open the app it keeps complaining about not being able to launch jvm and ive uninstalled and reinstalled the app several times and still cant find the problem i have also restarted my device but that didnt fix it either. it was working fine like two weeks ago

**Comment by InternalAardvark** [comment]
im having the same issue 
![image](https://user-images.githubusercontent.com/74672717/181853183-6c7be3de-63ec-4055-8332-1f1a6d261374.png)

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
