### ISSUE TITLE
Downloads edited version of most tracks

### ISSUE THREAD

**Issue by BooksMcTrappin** [Shabinder/SpotiFlyer#1542]
Anyway to have it look for versions that are not edited?

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
