### ISSUE TITLE
[MVIKotlin]: Main thread id is undefined, main thread assert is disabled

### ISSUE THREAD

**Issue by billymitchell** [Shabinder/SpotiFlyer#1545]
macOS Ventura beta 13
.jar not installing after JAVA installed 
tried to run "java -jar Myjar_file.jar" in terminal 

Debug: (Kermit) System Time:1657994476 , Token Expiry:1657997802
Debug: (Kermit) Spotify Provider Created with TokenData(access_token=BQAQ9i6La6HUOMGJ97H60Lp7VZtUMOUgSFpRFi8TMrYOXzQsaxe1Ns4Uiaqr4YrkyFDZ9XegWk67PiLqwy3y4NiEfiKNr0XJOntnEfqB7WtT7SQgJ_4, token_type=null, expiry=1657997802)
[MVIKotlin]: Main thread id is undefined, main thread assert is disabled

**Comment by ogulec** [comment]
same, any update?

**Comment by therealmichaelberna** [comment]
Hello guys, here's what I did that seems to have fixed it. Java changed up a bunch of things and now jars don't work with the old jre that we know and love. I had an older jre and a openjdk installed. 
After installing jdk-19 from Java's website (they just call it "Java" now instead of jdk/jre), I set the %JAVA_HOME% variable and then re-launched it. It is working now for me at least.

**Comment by ogulec** [comment]
> Hello guys, here's what I did that seems to have fixed it. Java changed up a bunch of things and now jars don't work with the old jre that we know and love. I had an older jre and a openjdk installed. After installing jdk-19 from Java's website (they just call it "Java" now instead of jdk/jre), I set the %JAVA_HOME% variable and then re-launched it. It is working now for me at least.

not succeed on my side, how did you set Java Home variable?

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
