### ISSUE TITLE
Long file names are clipped

### ISSUE THREAD

**Issue by Y2kz** [Shabinder/SpotiFlyer#155]
###  **BUG**
- When the file name is long the file-name is clipped
- There should be a moving (scrolling) file-name if file name is too long

### Screenshot
![zscrshot](https://user-images.githubusercontent.com/39020251/120515245-c1bc3500-c3eb-11eb-83d8-1bf0d7165533.jpg)

### DEVICE
Android version 10

**Comment by Shabinder** [comment]
Yeah , for now we stop overflow using ellipsis.

We can have a scrolling name , nice idea will see what can I do in next update.

**Comment by Y2kz** [comment]
Please do add a pause/stop option while downloding & ability to remove previous history
and you might want to look into landscape orientation in home as it is not possible to select and scroll the history in that orientation.
**BTW Nice App I was looking for this kind of app for long.**

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
