### ISSUE TITLE
[BUG] : <Issue_Title>

### ISSUE THREAD

**Issue by MetalLover98** [Shabinder/SpotiFlyer#1555]
I downloaded a couple songs and I noticed that even through the 320kpbs was on but it was 128kbps I'm on Motorola G stylus 5G

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
