### ISSUE TITLE
[BUG] : Sound bug

### ISSUE THREAD

**Issue by Symeki** [Shabinder/SpotiFlyer#1561]
**Describe the bug:**
I downloaded a song and sounds like shit the original version of it sounds other it is like the voice pitched  

**Media Links Used:** 
 I did it with this link: https://open.spotify.com/playlist/2UA3NXWhNP2eXjWGJ5D1jE?si=uRfdTUjrQBid6K0fH9h8ow&utm_source=copy-link  
But the song where it does the pitching is "allein sein"

**Expected behavior**
 I expected that the voice wouldn't be pitched 

**Screenshots:**
 It is a sound bug so i dont think it would be smart to do a screenshot 

**StackTrace:**
```
I dont have one
```

**Device Info (please complete the following information):**
 - Device:   [Ulefone Power Armor 14]
 - OS:   [Android 11]
 - Kernel Version:   [4.19.127]
 - Country: [Norway]

**Additional context:**

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
