### ISSUE TITLE
.dmg file problem

### ISSUE THREAD

**Issue by rehmm070304** [Shabinder/SpotiFlyer#1566]
Hi,

I downloaded the .dmg version of SpotiFlyer for mac but every time I try to open the application, I get a message pop-up saying that the disk image is damaged and the application cannot be opened. I've tried with multiple versions but the same problem occurs. Can somebody please help or advise me on what to do? 

Thanks,

R

**Comment by friendly-user-t** [comment]
Use .jar instead of .dmg, as explained in the Readme...
<img width="780" alt="Bildschirmfoto 2022-07-23 um 13 14 37" src="https://user-images.githubusercontent.com/47547091/180602788-046b54cf-98f2-4a05-a349-c6367a95251a.png">

**Comment by rehmm070304** [comment]
OK, thank you very much.

**Comment by debmaj2** [comment]
another option is to disable gatekeeper, add Spotiflyer to exception, and then renable gatekeeper

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
