### ISSUE TITLE
[BUG] : Difference in same song downloaded through Android and Windows

### ISSUE THREAD

**Issue by Akhilesh-T** [Shabinder/SpotiFlyer#1573]
**Describe the bug:**
A song downloaded using Android app is slightly larger than the one downloaded using Windows app

**Media Links Used:** 
https://open.spotify.com/track/2Hs659VSIWrtetYzclXVP6?si=97950fd4bc0743c7

**Expected behavior**
Both files should have been exactly same

**Screenshots:**
1. Android file
![Android](https://user-images.githubusercontent.com/80357467/180633721-2568309d-ffb8-4cd8-868d-afc07e6ed00a.png)

2. Windows file
![Windows](https://user-images.githubusercontent.com/80357467/180633743-436eb309-5809-4427-8c58-98e62ee6da96.png)

**Device Info (please complete the following information):**

 - Device:
1. Samsung M51 (Android 12)
2. Windows 10

 - Version:
 1. Samsung: 3.6.1
 2. Windows: SpotiFlyer-windows-x64-3.6.1.jar
 
- Country: India

**Additional context:**
Interestingly, both files seem to be similar on the Spectrum Analyser (Spek). I wonder what makes them different.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
