### ISSUE TITLE
[Feature-Request]: Modify music title and tags on the fly

### ISSUE THREAD

**Issue by arijit4** [Shabinder/SpotiFlyer#1579]
When I download any music from YouTube, it automatically tries to set artist name and title. But most often it's wrong. I've to rename the songs all the time afterwards. I even need a tag editor to change tags.

There should be a form which I would optionally fill up to set or change the details mentioned.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
