### ISSUE TITLE
Missing guidelines for translation contributors

### ISSUE THREAD

**Issue by codegenerator-cz** [Shabinder/SpotiFlyer#158]
Hello there,

sadly I can't seem to find any info how to submit translations, could you please add some guidelines to readme?

Thanks!

**Comment by Shabinder** [comment]
I will modify Resources in order to add Translations and more with ease, give me a day or two (busy this week), I will do that and will update here with the info you can proceed with.
Thank you for the initiative to contibute :+1:

**Comment by codegenerator-cz** [comment]
Anytime, I try to spend more time contributing to projects I use rather than only commercial work ;) Actually your quite surprised me, that's way quicker than I expected. I don't rush you at all,  given my laziness and busy work life I can't guarantee I will be as quick with my contribution 😟 however if I initiated some changes I am obliged to return the courtesy and delivery my part ASAP too :)

**Comment by Shabinder** [comment]
> Anytime, I try to spend more time contributing to projects I use rather than only commercial work ;) Actually your quite surprised me, that's way quicker than I expected. I don't rush you at all, given my laziness and busy work life I can't guarantee I will be as quick with my contribution worried however if I initiated some changes I am obliged to return the courtesy and delivery my part ASAP too :)

No worries, there are no obligations , take ur time and contribute whenever you can. :v:

**Comment by Shabinder** [comment]
Forgot to link it here :upside_down_face:  

here you go, https://github.com/Shabinder/SpotiFlyer/blob/main/CONTRIBUTING.md#contibuting-translations
