### ISSUE TITLE
download error

### ISSUE THREAD

**Issue by rehmm070304** [Shabinder/SpotiFlyer#1586]
Hi,

I try to download a song from soundcloud using SpotiFlyer but it comes out as an error. Can someone advise me on what to do. Thanks.

R

**Comment by guranu** [comment]
Did use the link from the website or ffom the app?

**Comment by rehmm070304** [comment]
From the website.

**Comment by Akhilesh-T** [comment]
What error exactly?

**Comment by rehmm070304** [comment]
it just says error and copies the link i pasted to download the song.

**Comment by guranu** [comment]
> From the website.

Don't use the link from the website apperantly it only works with the mobile apps link.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
