### ISSUE TITLE
[BUG] : <FORCES CLOSE>

### ISSUE THREAD

**Issue by Jarvis2301** [Shabinder/SpotiFlyer#1587]
Force Close if install to my device
My device : OPPO A57
App Version SpotiFlyer 3.6.1

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
