### ISSUE TITLE
[BUG] : <Unable to download song>

### ISSUE THREAD

**Issue by jman3000c** [Shabinder/SpotiFlyer#1599]
**Describe the bug:**

**Media Links Used:** 

**Expected behavior**

**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:  laptop lenovo thinkpad w540
 - OS:   [WinOS]
 - Version:   [e.g. 3.2.1]
 - Country: [South Africa]

**Additional context:**

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
