### ISSUE TITLE
[Feature request] Add the possibility to delete history 

### ISSUE THREAD

**Issue by Sitavi** [Shabinder/SpotiFlyer#160]
I think that it would be really great to have a button to delete one song or all the history

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
