### ISSUE TITLE
[BUG] : <Songs with the same title get ignored when downloading a playlist>

### ISSUE THREAD

**Issue by Dr-Sauce** [Shabinder/SpotiFlyer#1600]
**Describe the bug:**

When you download a playlist and there are songs with the same names, only one song gets downloaded.

**Media Links Used:** 

**Expected behavior**

**Screenshots:**

Only BTS's Run got downloaded and OneRepublic's Run got skipped.
<img width="432" alt="image" src="https://user-images.githubusercontent.com/82555878/182537760-adbdd208-e405-435a-8e61-f795e2b2b5d1.png">

Same issue here.
<img width="587" alt="image" src="https://user-images.githubusercontent.com/82555878/182537864-38fd08e7-a53d-4767-b615-53a8bbe2d9ee.png">
**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:  
 - OS:   Windows 11
 - Version:  
 - Country: US (VPN)

**Additional context:**

**Comment by NikolasPpd** [comment]
Same thing happened to me on android. I had two songs with the same title. When I pressed the download button next to one of them, both changed to the download animation, both seemed to have been downloaded but in the app's notification it said that one was downloaded successfully and the other one failed to download.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
