### ISSUE TITLE
[BUG] : Cyrillic letters 

### ISSUE THREAD

**Issue by breadduke** [Shabinder/SpotiFlyer#1601]
**Describe the bug:**
When trying to download a song with Cyrillic in the title, he replaces all the letters with spaces, and if the number of letters in two DIFFERENT songs is the same, then he simply does not download one of them

**Media Links Used:** 
[](https://open.spotify.com/track/75w8cY9muA3d24UoEXoPTA?si=YcE_letHR56pd9W9ExH7Ug&utm_source=copy-link)

**Expected behavior**
So that the Cyrillic letters are present in the name after downloading

**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   Redmi 8
 - OS:   Android 10
 - Version:   3.6.1
 - Country: Russia

**Additional context:**

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
