### ISSUE TITLE
[Feature-Request]: Add Deezer downloader

### ISSUE THREAD

**Issue by nadiration** [Shabinder/SpotiFlyer#1608]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution you'd like**
I would like for the addition of Deezer to the available platforms the reason i like downloading from Deezer is that you can choose the option to ad synchronized lyrics (.lrc file) to the mp3 file

Thank you for everything.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
