### ISSUE TITLE
[BUG] : <Failed songs falsely marked as downloaded songs>

### ISSUE THREAD

**Issue by ApocalypticWanderer** [Shabinder/SpotiFlyer#1622]
**Describe the bug:**

After downloading a large playlist there seems to be more songs missing than the "Failed" downloaded songs counted. After downloading the whole playlist it should have downloaded 672 songs. It failed at downloading 16, so the total should be 656. However, the total downloaded songs is only 646. I can only count 16 songs that have the cross downloaded icon indicating that it failed. This means there are 10 songs being marked as downloaded even though they're not. 

**Expected behavior**

It should have downloaded more songs. Or the "failed" counter should have been higher. 

**Screenshots:**

Songs in playlist
![WhatsApp Image 2022-08-08 at 4 57 49 PM (1)](https://user-images.githubusercontent.com/38218339/183449195-5a003735-b363-4538-87ac-a040eb563aac.jpeg)
Stated songs downloaded
![WhatsApp Image 2022-08-08 at 4 57 49 PM (2)](https://user-images.githubusercontent.com/38218339/183449204-2537ad2d-6ad6-43ff-ae6e-865e80ad84ef.jpeg)
Actual amount of songs downloaded
![WhatsApp Image 2022-08-08 at 4 57 49 PM](https://user-images.githubusercontent.com/38218339/183449176-6289bf8b-cb6f-4414-8919-f4f7ea79b75e.jpeg)

**Device Info (please complete the following information):**
 - Device:   [Samsung Galaxy A72]
 - OS:   [Android 12]
 - Version:   [3.6.1]
 - Country: [Netherlands]

**Additional context:**

Spotify playlist in question: https://open.spotify.com/playlist/2VKJZXsOZjiysmAPf4tQGy?si=baaf91d4b6164b8e

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
