### ISSUE TITLE
[BUG] : Some files that claim to be downloaded really aren't

### ISSUE THREAD

**Issue by SenseiLeRoof** [Shabinder/SpotiFlyer#1624]
**Describe the bug:**
In attempting to download an album, a small handful of songs will be improper mp3s with a file size of <100kb. Further attempts to redownload those songs from the same link will give the same result.

**Media Links Used:** 
https://open.spotify.com/album/4j2w31z0hl3fRsTzSwgc3R embedded in https://www.theymightbegiants.com/they-might-be-giants

**Expected behavior**
All files properly downloading

**Screenshots:**
![image](https://user-images.githubusercontent.com/29762285/183512952-bd098576-a6c5-4cba-a84e-ea785f0299e1.png)

**Device Info (please complete the following information):**
 - Device: PC
 - OS: Windows 10
 - Version: 3.6.1
 - Country: USA

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
