### ISSUE TITLE
[BUG] : Issue loading SoundCloud links

### ISSUE THREAD

**Issue by itsnnotdamiann** [Shabinder/SpotiFlyer#1626]
**Describe the bug:**
Error encountered when entering SoundCloud links in Spotiflyer app

**Media Links Used:** 
https://soundcloud.app.goo.gl/bYHvf
https://soundcloud.com/mickyweekes/over

**Screenshots:**
https://userimages.githubusercontent.com/110897852/183614423-087efb2e-b1de-4e9f-a42b-af3abc23fcf2.png

**StackTrace:**
```
N/A
```

**Device Info
 - Device:  Google Pixel 6
 - OS:   Android 12
 - Version:   3.6.1
 - Country: US

**Additional context:

**Comment by 89z** [comment]
URL is not valid

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
