### ISSUE TITLE
Possibility to re-try a failed song download

### ISSUE THREAD

**Issue by EdoSecco** [Shabinder/SpotiFlyer#163]
As for title, sometimes some songs are downloaded and other not; it would be very useful to, for example, press again single failed songs in order to try to download them again.

**Comment by Shabinder** [comment]
Will do in next update

**Comment by Shabinder** [comment]
Done in https://github.com/Shabinder/SpotiFlyer/commit/9881cc55aa0ce6e65590f9bb2fa54e2d56edc24e will be available in 3.2.0
