### ISSUE TITLE
[Feature-Request]: Loudness normalization

### ISSUE THREAD

**Issue by walti0** [Shabinder/SpotiFlyer#1630]
Is possible to add loudness normalization, because it's annoying when every song have different volume and I have to volume up and down in every song.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
