### ISSUE TITLE
[BUG] : Song Different

### ISSUE THREAD

**Issue by DatFatBo1** [Shabinder/SpotiFlyer#1631]
First time using this app and i dunno if this is how it works or its a bug but...

I mostly download from Spotify, and somehow the songs are different when i played it from spotify and when i downloaded the song...

An example of this is the song "Mr Loverman - Ricky Montegomery"

>>https://open.spotify.com/track/2IVsRhKrx8hlQBOWy4qebo?si=TWRw7s4WRfCJpYouCOHh0w&utm_source=copy-link

instead of it just a man singing, when i downloaded it, it was now like a duet. And it was not just this song there were many

So tell me if this is how it actually works or its a bug

Thank you

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
