### ISSUE TITLE
[Feature-Request]: <Feature_Title>

### ISSUE THREAD

**Issue by SilentPartner** [Shabinder/SpotiFlyer#1637]
My request is not problem related but first inquiring as to if this app/software has the ability to retrieve the same data but encode said results as .ogg in place of the.mp3 format currently offered/standard? Next, l wanted to know if it's it possible to import YouTube subscriptions, import SoundCloud subscriptions, export your subscriptions as a backup and lastly export all Spotiflyer data as a backup?

Any or all of these suggestions would be optimal in my opinion and based on my needs/desires.

My only logical alternative would be to continue using this phenomenal application and manually convert the resulting.mp3's into.ogg files.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
