### ISSUE TITLE
[Feature-Request]: Release of the CLI Version

### ISSUE THREAD

**Issue by miabl0** [Shabinder/SpotiFlyer#1639]
There is a folder called console app, but there is no release of a console version. Trying to build the project myself using the gradlew file does not output a working console-app.
Am I building the project wrong, or is the console-app just not accessible?

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
