### ISSUE TITLE
Map function not found

### ISSUE THREAD

**Issue by ii64** [Shabinder/SpotiFlyer#164]
Is this Bug? in logger there's exception but the UI keep trying
![image](https://user-images.githubusercontent.com/26342994/120818565-f01d4a00-c57c-11eb-84cb-8d5850615976.png)

Looks like the youtube api failed to find value in JS for video `secret` parameter
https://github.com/Shabinder/youtube-api-dl/blob/a199a78c9fb11e00bfd627b887e815ef47809423/src/commonMain/kotlin/io.github/shabinder/cipher/CachedCipherFactory.kt#L215

**Comment by Shabinder** [comment]
Share playlist /song you tried so i can reproduce it

**Comment by ii64** [comment]
I was thinking to attach the video link before and i remember what happened with youtube-dl
Here is the video id `NgQVLbD-lQ0`

**Comment by Shabinder** [comment]
Fixed in https://github.com/Shabinder/SpotiFlyer/commit/43ca70daf7e9b50494ed7eb3cb9d998900b68f6f  and https://github.com/Shabinder/youtube-api-dl/commit/934271683cb66b851726c26a2637812a7e1bf300 will be available in 3.2.0
