### ISSUE TITLE
Translate hebrow

### ISSUE THREAD

**Issue by nhman-python** [Shabinder/SpotiFlyer#1648]
title = SpotiFlyer
about = אודות
history = היסטוריה
donate = תרום
preferences = העדפות
search = חיפוש
supportedPlatforms = פלטפורמות נתמכות
supportDevelopment = תמיכה בפיתוח
openProjectRepo = פרוייקט פתוח Repo
starOrForkProject = כוכב / מזלג את הפרויקט על Github.
help = עזרה
translate = תרגם
helpTranslateDescription = עזור לנו לתרגם אפליקציה זו בשפה המקומית שלך.
supportDeveloper = תמיכה בפיתוח
donateDescription = אם אתה חושב שמגיע לי לקבל תשלום עבור העבודה שלי, אתה יכול לתמוך בי כאן.
share = Share
shareDescription = שתף את האפליקציה הזו עם החברים והמשפחה שלך.
whatWentWrong = משהו השתבש...
copyToClipboard = הועתק ללוח
copyCodeInGithubIssue = העתק והדבק את הקוד למטה בעת יצירת בעיית GitHub / דיווח על בעיה זו לקבלת עזרה טובה יותר.
status = מצב
analytics = ניתוח
analyticsDescription = הנתונים שלך אנונימיים ולעולם אינם משותפים עם שירותי צד שלישי.
noHistoryAvailable = אין היסטוריה זמינה
cleaningAndExiting = ניקוי ויציאה
total = סה"כ
completed = הושלם
failed = נכשל
exit = יציאה
downloading = יורד
processing = מעבד
queued = בתור
setDownloadDirectory = הגדר את ספריית ההורדות
downloadDirectorySetTo = ספריית הורדה מוגדרת ל: {0}
noWriteAccess = אין גישת כתיבה ב: {0} , חוזר לאחורה
shareMessage = היי, בדוק את תוכנת הורדת המוזיקה המצוינת הזו http://github.com/Shabinder/SpotiFlyer
grantAnalytics = אפשר ניתוח
noInternetConnection = אין חיבור אינטרנט!
checkInternetConnection = אנא בדוק את חיבור הרשת שלך.
grantPermissions = מתן הרשאות
requiredPermissions = הרשאות נדרשות:
storagePermission = הרשאות אחסון.
storagePermissionReason = כדי להוריד את השירים האהובים עליך למכשיר זה.
backgroundRunning = ריצת רקע.
backgroundRunningReason = להורדת כל השירים ברקע ללא הפרעות במערכת.
no = לא
yes = בכיף

acraNotificationTitle = אופס, ספוטיפלייר קרס
acraNotificationText = אנא שלחו דוח קריסה למפתחי אפליקציות, כך שייתכן שהאירוע המצער הזה לא יקרה שוב.
albumArt = Album art
tracks = מסלולים
coverImage = תמונת פתיחה
reSearch = חפש שוב
loading = טוען
downloadAll = הורד הכל
button = Button
errorOccurred = אירעה שגיאה, בדוק את הקישור / החיבור שלך
downloadDone = הורדה הושלמה
downloadError = שגיאה! לא מצליח להוריד את הרצועה הזו
downloadStart = התחל הורדה
supportUs = אנו זקוקים לתמיכתכם!
donation = תרומה
worldWideDonations = תרומות ברחבי העולם
indianDonations = תרומות הודיות בלבד
dismiss = לשחרר
remindLater = תזכיר לי אחר כך

mp3ConverterBusy = ממיר MP3 לא ניתן להשגה, כנראה עסוק!
unknownError = שגיאה לא ידוע
noMatchFound = לא נמצאה התאמה!
noLinkFound = לא נמצא קישור להורדה
linkNotValid = הקישור שהוזן אינו תקף!
featureUnImplemented = תכונה עדיין לא יושמה.

minute = דקה
second = שניה

spotiflyerLogo = SpotiFlyer סמל
backButton = כפתור חזרה
infoTab = לשונית מידע
historyTab = לשונית היסטוריה
linkTextBox = תיבת טקסט קישור
pasteLinkHere = הדבק פה לינק...
enterALink = תן לי קישור!
madeWith = עשוי מ
love = אוהב
inIndia = בהודו
open = פתח
byDeveloperName = מאת: שבינדר סינג תרגום אלי דיין

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
