### ISSUE TITLE
Add Track number as metadata

### ISSUE THREAD

**Issue by fine2006** [Shabinder/SpotiFlyer#165]
Kindly add track number as metadata, if its extractable.

**Comment by Shabinder** [comment]
Sure , 
will do this asap after my exams

**Comment by fine2006** [comment]
Thank you for listening to the suggestion 👍

**Comment by Shabinder** [comment]
Done in https://github.com/Shabinder/SpotiFlyer/commit/67a07dba498aaad3ea236fe37d77761f71e5facd
