### ISSUE TITLE
No Write Access to Memory Card

### ISSUE THREAD

**Issue by dhhruv** [Shabinder/SpotiFlyer#166]
First of all, nice work you've done. Now, the problem occurring is that whenever I select Memory Card to download, it says you don't have access rights. I'm using Redmi Note 9 Pro Max and I've tried everything I can from Settings to give access externally but doesn't work and it reverts back to phone storage. 
It'd be nice of you to take a look into this. Thanks.

**Comment by Shabinder** [comment]
Thanks for your feedback , I really appreciate it :smile:

Please Refer: #116 

External SdCard write access won't be supported, because of the reasons mentioned in above issue
