### ISSUE TITLE
[BUG] : Downl;oad all button downkloading songs 1 by 1

### ISSUE THREAD

**Issue by abobainc** [Shabinder/SpotiFlyer#1664]
In desktop version it download songs 1 by 1 if i click dopwqnlaod all button but if i click all songs manually it will download 4 at a time
And also downkload of 1 playlist 100 songs takes like 1+ hour because 1 song is ~80 seconds idk why so slow

**Comment by abobainc** [comment]
bruhhh it takes so mlong to download even 10 songs
i downloaded 8 in 20 jminutes

**Comment by JaxonYon** [comment]
How is this a bug?

**Comment by Jasperrr91** [comment]
> How is this a bug?

Songs are not downloading async but sync when clicking `download all`. When manually clicking you can actually download async so it's either a bug or a lack of a fairly basic feature. Haven't dived into the code to check yet but the contributor of this project seems to have gone away anyway.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
