### ISSUE TITLE
[BUG] : <Language>

### ISSUE THREAD

**Issue by So2K** [Shabinder/SpotiFlyer#1677]
Кириллица сдохла 
![image](https://user-images.githubusercontent.com/33857303/185894811-3cb8c628-2e9c-4d33-bd1e-1de381a91ae7.png)
![image](https://user-images.githubusercontent.com/33857303/185894889-6d1cff60-cffd-4d96-9ad9-238fd0e1d397.png)

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
