### ISSUE TITLE
[BUG]: Settings icon crashes android app

### ISSUE THREAD

**Issue by SpaghettDev** [Shabinder/SpotiFlyer#1679]
**Describe the bug:**
If you click the Settings button once, it'll, evidently, take you to the settings page. But if you click on it another time, the app crashes.

**Media Links Used:** 
None.

**Expected behavior**
Not crash.

**Screenshots:**
https://user-images.githubusercontent.com/37266659/185976116-a56c5023-3f3d-4916-97d7-ed62bda73086.mp4

**Device Info:**
 - Device: Samsung A32 (Model SM-A325M/DS)
 - OS: Android
 - Version: 3.6.1
 - Country: Canada

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
