### ISSUE TITLE
[BUG] : <Failed to lunch JVM on Windows Version>

### ISSUE THREAD

**Issue by ferburri** [Shabinder/SpotiFlyer#1694]
**Describe the bug:**
At the time that I open the program, an error pops up telling that "Failed to lunch JVM". I've tried to install again the program but it occurs again.

**Expected behavior**
Open the Launcher

**Screenshots:**
<img width="155" alt="image" src="https://user-images.githubusercontent.com/79408013/187045883-1af5fd5c-61b9-4eb2-a806-004bcc33a1b2.png">

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   LG Gram
 - OS:  WinOS
 - Version:  11
 - Country: Spain

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
