### ISSUE TITLE
fd2cd206a37bf1f0d010c7e91996a3cf7bbeecac

### ISSUE THREAD

**Issue by Pafkara** [Shabinder/SpotiFlyer#1696]
https://github.com/Shabinder/SpotiFlyer/commit/463c005ccc8032aed1954cc755a04670722e9617

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
