### ISSUE TITLE
[Feature-Request]: WebNowPlaying Support

### ISSUE THREAD

**Issue by TheBeeBoi** [Shabinder/SpotiFlyer#1699]
Can webnowplaying companion support be added?
Webnowplaying is basically a plugin for rainmeter (a windows desktop customization tool)
PS: It's based on javascript

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
