### ISSUE TITLE
Stays open and can't swipe away after download

### ISSUE THREAD

**Issue by Bwangster12** [Shabinder/SpotiFlyer#17]
It seems it stays open and the persistent notification can't be swiped away after finishes downloading.  I have to force close.

**Comment by Shabinder** [comment]
I will be adding a Close Action in the Notification Itself in Coming Update.
I have many things in Mind for the next update , so it may take some time , 
**_Stay Tuned!_**

**Comment by Shabinder** [comment]
v1.7 is out and it does have an Exit Button which may be used if Notification Doesn't Go after Downloading.
