### ISSUE TITLE
Album data not added to songs when downloading whole album from Spotify

### ISSUE THREAD

**Issue by kdkasad** [Shabinder/SpotiFlyer#170]
When I try to download individual songs from Spotify, the album name is saved in the metadata of the audio file that gets downloaded. However, when I open the album link in Spotiflyer and download the song from there, the album name doesn't get saved in the metadata.

For an example, here's an [individual song](https://open.spotify.com/track/62VWmsNoDmqT0Mj9oHHFVh?si=_ao6bU_jT4SyNRtw-oF2Xg&utm_source=copy-link&dl_branch=1) and here's the [album it belongs to](https://open.spotify.com/album/4vuijqNCK71JTiACBmdCTo?si=3V_2r_UgRkmTBPY-EMKVeA&utm_source=copy-link&dl_branch=1). The song downloads correctly using both links, but the album metadata is missing when using the second one.

This also occurs when pressing the `Download all` button for the album. However, it works as expected for playlists and individual songs. Only albums seem to be missing metadata.

**Comment by Shabinder** [comment]
Thanks for reporting this issue will fix asap after my Exams

**Comment by Shabinder** [comment]
Fixed in https://github.com/Shabinder/SpotiFlyer/commit/f323021bac16f58f51139d430e72c8a9e273a329
