### ISSUE TITLE
[BUG] : doesn't download. And sometimes download but don't work

### ISSUE THREAD

**Issue by Miniemil** [Shabinder/SpotiFlyer#1701]
**Describe the bug:**

**Media Links Used:** 

**Expected behavior**

**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device: OnePlus nord n10 5g
 - OS: android 11
 - Version: 
 - Country: Finland 

**Additional context:**

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
