### ISSUE TITLE
[BUG] : App crashes on using download all feature, also download always failed

### ISSUE THREAD

**Issue by bakaemon** [Shabinder/SpotiFlyer#1703]
### What is it? How to reproduce 
Using any playlist link and use "download all" button will cause a silent crash with no other notice.
Also, download each track doesn't work either, even with VPN enabled.
### Version
Latest release version 3.6.1
### Device/OS
Redmi 9 Android 9 MIUI
### Additional note
I only tested with 100+ songs playlists and yet did it with fewer songs playlists.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
