### ISSUE TITLE
[Feature-Request] : Add a setting for auto file renaming for downloaded files

### ISSUE THREAD

**Issue by rchllsosa** [Shabinder/SpotiFlyer#1705]
The user can choose a rename pattern:

(e.g Artist - Song Title / Song Title - Artist / Song Title - Artist - Album Name, etc) 

> see image below for reference

![image](https://user-images.githubusercontent.com/95327414/187343044-eb96b526-8103-4763-b858-9edeb6438e3e.png)

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
