### ISSUE TITLE
Some Youtube Music links dont work

### ISSUE THREAD

**Issue by rapejim** [Shabinder/SpotiFlyer#171]
I installed the windows version on my PC and dont work when I try to use this link:

https://music.youtube.com/watch?v=kgJHhww8Ejc&list=RDAMVMkgJHhww8Ejc

but if I use the same without "list" param, it work perfect:

https://music.youtube.com/watch?v=kgJHhww8Ejc

**Comment by Shabinder** [comment]
Thanks for reporting this issue will fix asap

**Comment by Shabinder** [comment]
Hey @rapejim ,
If SpotiFlyer receives a **`list`** param, it tries to fetch whole playlist. 
and we use a Youtube Parser as of now , and Generally most of the content is interviewable in YT Music and Youtube , but some are not as the above link is not :
![image](https://user-images.githubusercontent.com/44765050/125183340-7c352800-e233-11eb-8d5e-c0fd38d317b5.png)

So, its not an issue of Link format, instead it's a parsing bug, I will try to support youtube music too, but no ETA for now
