### ISSUE TITLE
[BUG] :  song with cyrillic names are saving incorrectly 

### ISSUE THREAD

**Issue by nokoran** [Shabinder/SpotiFlyer#1728]
when downloading songs with cyrillic names, file name is being replaced with underscores, which is a bit troublesome, cus i need to manually rename files in system to prevent files with the same names in a folder

**Comment by MagnetizedFreckles** [comment]
Yes, this is very inconvenient bug. 
For me, as a temporary solution, works TagLib plugin from KRename. I guess, there are also other scripts for reading track name from tags and then applying it to file name.
However I hope that this bug will be addressed.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
