### ISSUE TITLE
Create an RPM Package

### ISSUE THREAD

**Issue by Tomoghno** [Shabinder/SpotiFlyer#173]
It will be very helpful if make an RPM Package for This Software

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
