### ISSUE TITLE
[Feature-Request]: Open songs via app

### ISSUE THREAD

**Issue by Aulteran** [Shabinder/SpotiFlyer#1732]
I'm pretty frustrated when I have to head into my files and find the spot flier folder and then play the music.

Make a feature where I can see the songs I have downloaded(not download history) and when I click on it, it will ask me what app I want to use to play the media.

Here's a screenshot of it working in the files app![Screenshot_20220908-004724_Android System.jpg](https://user-images.githubusercontent.com/83958862/189036660-be26d772-d677-4ab7-a1fc-28a84e0cacb3.jpg)

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
