### ISSUE TITLE
[BUG] : Android app crashing when settings icon tapped twice

### ISSUE THREAD

**Issue by spongycode** [Shabinder/SpotiFlyer#1734]
**App crash:**
Android version of the app is crashing when settings icon on the top right corner is pressed on the setting screen itself.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
