### ISSUE TITLE
[BUG] : <App crash>

### ISSUE THREAD

**Issue by Ananas78** [Shabinder/SpotiFlyer#1746]
Describe the bug:
The app suddenly stop after I pressed Preference twice. 

**Screenshots:**

![Screenshot_20220914-012410025](https://user-images.githubusercontent.com/113459805/189968362-7c72e256-b4c7-42dd-a2bb-b8f691df165d.jpg)

**Device Info**
 - Device:   [PocoF1]
 - OS:   [Android 10]
 - Version:   [3.6.1]
 - Country: [Malaysia]

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
