### ISSUE TITLE
[Feature-Request]: multiple downloads simultaneously

### ISSUE THREAD

**Issue by Mehmuod** [Shabinder/SpotiFlyer#1750]
The ability to download several songs at the same time when you download a playlist; because one by one is kinda slow for big playlists.

Great app. Thanks.

**Comment by j-romchain** [comment]
it does it already... kinda... it seems to have a limit of around 12 songs, and it only starts one at a time, kinda like clicking a link on a webpage, you can only click one link at a time, but the downloads can continue while you click the next links...

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
