### ISSUE TITLE
[BUG] : Turkish character problem. [ü/Ü]

### ISSUE THREAD

**Issue by kyoyacchi** [Shabinder/SpotiFlyer#1751]
**Describe the bug:**

Paste a link then wait.

**Media Links Used:** 

I don't think that's matters, but....
https://www.youtube.com/watch?v=nUBWp89ATE8

**Expected behavior**

It should show "ü" normally
**Screenshots:**

![Screenshot_20220914-175218](https://user-images.githubusercontent.com/63583961/190189778-4e125325-b104-4ee1-b3b1-da3c0c9c472e.jpg)

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:  Tecno Spark 7T
 - OS:   Android 11
 - Version:   3.6.1
 - Country: Türkiye (Turkey)

**Additional context:**

Maybe change font?
Note: "Yükleniyor" means "Loading"

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
