### ISSUE TITLE
FFmpeg breaks

### ISSUE THREAD

**Issue by singhdilveer1** [Shabinder/SpotiFlyer#1754]
I suspect this program uses FFMpeg, it fails to convert some songs which results in only the music cover with an .mp3 extension to be there in the downloads directory. No idea how to get logs but this is definitely a common issue for me accross multiple OSes so I suspect the same has happened to others too.

I have experienced this issue on windows, ubuntu, mint.

**Comment by XurrencyFX** [comment]
> I suspect this program uses FFMpeg, it fails to convert some songs which results in only the music cover with an .mp3 extension to be there in the downloads directory. No idea how to get logs but this is definitely a common issue for me accross multiple OSes so I suspect the same has happened to others too.
> 
> I have experienced this issue on windows, ubuntu, mint.

Same here

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
