### ISSUE TITLE
[BUG] :App crashes when I open it.

### ISSUE THREAD

**Issue by Alterzyy** [Shabinder/SpotiFlyer#1757]
**Describe the bug:**
When I install and open the app as normal.  The app suddenly crashes and throws me again to tge home screen.

**Media Links Used:** 
While launching app

**Expected behavior**
App should start normally and do it's expected work

**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   [vivo 1606]
 - OS:   [Android]
 - Version:   [6.0.1]
 - Country: [India]

**Additional context:**

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
