### ISSUE TITLE
how compile?

### ISSUE THREAD

**Issue by j-romchain** [Shabinder/SpotiFlyer#1758]
I am kinda new, but I got as far as running gradlew.bat... am I doing something wrong, or where would the compiled files be?

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
