### ISSUE TITLE
[BUG] : error null cannot be cast to non-null type. kotlinx.serialization.json.JsonObject

### ISSUE THREAD

**Issue by adarshkannada** [Shabinder/SpotiFlyer#1766]
**Describe the bug:**
while downloading from the following link, the error comes.
null cannot be cast to non-null type. kotlinx.serialization.json.JsonObject

**Media Links Used:** 
(https://www.jiosaavn.com/song/mungaru-male/Qh4GWjJGXmE)

**Expected behavior**
song to be downloaded

**Screenshots:**
![Screenshot_20220918-095607](https://user-images.githubusercontent.com/13301113/190885854-ebfb010b-c6f0-4564-a51a-0aee99d503e5.jpg)

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:  samsung galaxy s20 fe 5g
 - OS:   android 12
 - Version:   oneUI 4.1 latest
 - Country: India

**Additional context:**

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
