### ISSUE TITLE
[BUG] : Search doesn't work

### ISSUE THREAD

**Issue by Lucky-Luca234** [Shabinder/SpotiFlyer#1778]
**Describe the bug:**

When i press the search button i just get an popup saying: Client request(https://api-v2.soundcloud.com/resolve?url= and a bunch of numbers and letters after that. 
**Media Links Used:** 

https://soundcloud.com/user-227360808/9-gpf-dragon-porn-fuck-part-69?si=bef1a5e5681b4a4191494c0a8c1ce9d8&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing
**Expected behavior**

It should search the url.
**Screenshots:**

![image](https://user-images.githubusercontent.com/29671902/191851961-e628fd56-e38e-4d16-9753-198665877c98.png)

**StackTrace:**
I could provide the StackTrace but i don't know how i can see it. Could anyone direct me to a source what explains how to do this?

**Device Info (please complete the following information):**
 - Device:   pc
 - OS:   windows 10 21h1
 - Version:   3.6.1
 - Country: The Netherlands

**Additional context:**

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
