### ISSUE TITLE
Add Anghami Music 

### ISSUE THREAD

**Issue by Kero309x** [Shabinder/SpotiFlyer#178]
I suggest to add ability for all users using anghami app to download songs from spotiflyer it will be a great thank you.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
