### ISSUE TITLE
A way to download podcasts

### ISSUE THREAD

**Issue by RetroBabe92** [Shabinder/SpotiFlyer#1781]
Would be awesome if we had a way to download podcasts off spotify

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
