### ISSUE TITLE
[BUG] : <Issue_Title>

### ISSUE THREAD

**Issue by lucascallea** [Shabinder/SpotiFlyer#1794]
Some Songs Fail and some songs download, I've waited 2 weeks and still songs don't want to download, is this gonna be fixed???

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
