### ISSUE TITLE
[Feature-Request]: Automatic downloading of songs in playlists

### ISSUE THREAD

**Issue by Jar-Of-Dirt** [Shabinder/SpotiFlyer#1795]
Just a cool feature i would love
A way for the appt to automatically download songs that you add in your playlist on yt music or Spotify so you don't have to manually so it every time u add a song to your playlist in yt music or Spotify

**Comment by Shabinder** [comment]
Thanks for the feature request, I have this in mind from a long time, but since I started worked on a rewrite, I will implement after that's complete.

Stay tuned.

**Comment by Jar-Of-Dirt** [comment]
Ohk, thank you for the app, it's so useful :)

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
