### ISSUE TITLE
[Feature-Request]: Save playlist

### ISSUE THREAD

**Issue by ChrizKu** [Shabinder/SpotiFlyer#1796]
Hi,

would be nice, when also the playlist would be saved as m3u or pls, so the order of the titles can be preserved.
linked to the local path (relatively).

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
