### ISSUE TITLE
Can't find downloaded songs (Windows 10)

### ISSUE THREAD

**Issue by Aleandr-1987** [Shabinder/SpotiFlyer#181]
Hi, I have been using your android version and it works great. So I decided to try the Windows version. I added a playlist and in the app is shows all downloaded but can't find the songs. I look in the folder i chose and also the default location which is documents.

**Comment by hedgyx** [comment]
Hi, the reason you can't find your songs is because the default directory sis NOT the documents folder, it's C:\Users\YourUsername\SpotiFlyer

I've ran into the same problem and searched up the song I downloaded

**Comment by Aleandr-1987** [comment]
> Hi, the reason you can't find your songs is because the default directory sis NOT the documents folder, it's C:\Users\YourUsername\SpotiFlyer
> 
> I've ran into the same problem and searched up the song I downloaded

Thanks for the information. Will definitely check there.

**Comment by Shabinder** [comment]
> C:\Users\YourUsername\SpotiFlyer

As Mentioned by @hedgyx, you will find songs in the above directory

**Comment by Aleandr-1987** [comment]
Ok. Thanks
