### ISSUE TITLE
Spotify Stopped because of rate limiting.

### ISSUE THREAD

**Issue by T-vK** [Shabinder/SpotiFlyer#1814]
**Describe the bug:**
Opening a playlist results in this error:
```
Client request(https://api.spotify.com/v1/playlists/{PLAYLIST_ID} invalid: 429 . Text: "Too many requests"
```

I got this after downloading roughly 20 songs earlier that day. In the past I was able to download hundreds of songs without any issues.

**Media Links Used:** 
Not specific to one link. This happens with every playlist link.

**Expected behavior**
Shows list of songs of a playlist

**Screenshots:**
![image](https://user-images.githubusercontent.com/11368523/193939481-7e554e79-7a16-4691-a4f4-3fe010beaef9.png)

**StackTrace:**
No errors in Logcat...

**Device Info (please complete the following information):**
 - Device:  OnePlus 7 Pro
 - OS:   Android 11
 - Version:   3.6.1 (latest from F-Droid)
 - Country: Germany

**Comment by Lykantac** [comment]
Yeah same here I was able to download a lot of my playlist then all of the sudden this morning it gave me that error. And I am running samsung galaxy note 10 5g

**Comment by Daviddiala** [comment]
![Screenshot_20221005-043906](https://user-images.githubusercontent.com/115058079/193977310-8754ebda-94d4-4112-bcf5-2cee7f4afc86.png)

This bug is quite frustrating

**Comment by Lykantac** [comment]
Yes it is.

**Comment by T-vK** [comment]
I just dug a bit through the source code wondering if all SpotiFlyer users share the same authentication token. Because even after changing my IP address, I am still getting rate-limited.

From what I can tell, a unique token is retrieved for each user. But every token is retrieved through the same client ID and client secret:

https://github.com/Shabinder/SpotiFlyer/blob/73bd43d23c303c101eb557bcd926d67ffe925f94/common/providers/src/commonMain/kotlin/com.shabinder.common.providers/spotify/requests/SpotifyAuth.kt#L48-L49

We might be able to bypass the rate-limiting by using our own client ID and client secret which can be created [here](https://developer.spotify.com/dashboard/applications).

This would however require rebuilding the app. Adding an option to SpotiFlyer to allow using our own id/secret would be neat.  
Other than that, there might be a way to overwrite the stored token, but that probably requires a rooted phone and manually retrieving a token from the `https://accounts.spotify.com/api/token` API.

**Comment by Lykantac** [comment]
![Uploading Screenshot_20221005_085931.jpg…]()

**Comment by Lykantac** [comment]
Apply for extended quota mode
If your app is meant to be used by many Spotify users at the same time then you should apply for extended quota mode. Apps in this mode have a rate limit that is much higher than apps in development mode, the default mode for new apps. You can apply for a quota extension by opening your app detail page in the Developer Dashboard and tapping on the Request Extension link.

Develop a backoff-retry strategy
When your app has been rate limited it will receive a 429 error response from Spotify. Your app can use this information as a cue to slow down the number of API requests that it makes to the Web API. The header of the 429 response will normally include a Retry-After header with a value in seconds. Consider waiting for the number of seconds specified in Retry-After before your app calls the Web API again.

Use batch APIs to your advantage
Spotify has some APIs — like the Get Multiple Albums endpoint — that allow you to fetch a batch of data in one API request. You can reduce your API requests by calling the batch APIs when you know that you will need data from a set of objects.

Use the snapshot_id
Playlist APIs expose a snapshot_id that corresponds to the version of the playlist that you are working with. Downloading a playlist can be expensive so some apps may want to store and refer to the snapshot_id to avoid refreshing an entire playlist that has not changed. You can learn more about snapshot_id in our Working with Playlists guide.

Study your app’s request patterns
When you load your app’s detail page in the Developer Dashboard you’ll find a graph that can tell you about your API request volume over time. Understanding anomalies in API requests — and the reasons for them — can help you find ways to avoid hitting the rate limit. For example, if you notice that your website receives a surge in traffic after you send out your weekly newsletter then you might decide that you want to stagger the delivery of those emails over the course of a day.

For more advanced insights into your app’s request patterns, consider tracking your app’s API calls to Spotify using your own logging tools.

Consider ‘lazy loading’ features
Users often don’t want to use every feature that is available to them on a web page, or in the view of a mobile app. You can avoid making API requests by making API calls conditional on user interactions, like tapping on a ‘learn more’ link, or scrolling to a defined region of a web page.

**Comment by Lykantac** [comment]
![Screenshot_20221005_085931](https://user-images.githubusercontent.com/43898953/194080495-011455cf-4d34-464a-b2a6-482fa3ca6ea1.jpg)

**Comment by T-vK** [comment]
I'm not sure, but my guess is that SpotiFlyer is registered as a development app and applying for extended quota has a high chance of getting declined since downloading songs from Spotify outside of their ecosystem is probably against the ToS.
It's also unclear to me if "extended quota" would even solve the issue, considering that it merely increases the limit. It might make for a temporary workaround though. 
I vote for making the clientId and clientSecret user-configurable.

**Comment by Shabinder** [comment]
will update the clientId and secret and make them configurable and do a release in coming day.

**Comment by hydrayash** [comment]
Please fix this issue cause i can't download a single song because of it

**Comment by ZazoVa** [comment]
> I just dug a bit through the source code wondering if all SpotiFlyer users share the same authentication token. Because even after changing my IP address, I am still getting rate-limited.
> 
> From what I can tell, a unique token is retrieved for each user. But every token is retrieved through the same client ID and client secret:
> 
> https://github.com/Shabinder/SpotiFlyer/blob/73bd43d23c303c101eb557bcd926d67ffe925f94/common/providers/src/commonMain/kotlin/com.shabinder.common.providers/spotify/requests/SpotifyAuth.kt#L48-L49
> 
> We might be able to bypass the rate-limiting by using our own client ID and client secret which can be created [here](https://developer.spotify.com/dashboard/applications).
> 
> This would however require rebuilding the app. Adding an option to SpotiFlyer to allow using our own id/secret would be neat. Other than that, there might be a way to overwrite the stored token, but that probably requires a rooted phone and manually retrieving a token from the `https://accounts.spotify.com/api/token` API.
> 
> **Edit:** I managed to manipulate the token which can be found in: `/data/data/com.sharebinder.spotiflyer/databases/Database.db` in the table `Token`. I used my own client ID + client secret to generate a new auth token and replaced the existing one with my newly generated one. I can now open playlists and download songs again. In one hour my token will have have expired though and I'll have to repeat the procedure, so this is not a proper fix. It's just to prove that the rate-limiting is down to spotify limiting requests on a client ID level.

Do u know where can i find that section in the Windows version?

**Comment by savagemz** [comment]
hopefully he'll fix it soon

**Comment by DivineSapt** [comment]
> will update the clientId and secret and make them configurable and do a release in coming day.

when will it be released cuz I am still getting that problem

**Comment by T-vK** [comment]
> Do u know where can i find that section in the Windows version?

I'd say it uses the same source file for all operating systems.

The Database.db file is probably in `%APPDATA%\Spotiflyer\Database\Database.db` or something like that on Windows. On Linux it is in `~/Spotiflyer/Database/Database.db`.

On Linux you can overwrite the access token by running this form the terminal:
(You need to insert your CLIENT_ID and CLIENT_SECRET of course. You can get it [here](https://developer.spotify.com/dashboard/applications).)

```
SPOTIFY_CLIENT_ID=*********************
SPOTIFY_CLIENT_SECRET=*******************

SPOTIFY_ENCODED_CREDENTIALS="$(echo -n "${SPOTIFY_CLIENT_ID}:${SPOTIFY_CLIENT_SECRET}" | base64 | tr -d "\n")"

res="$(curl -s -X "POST" -H "Authorization: Basic ${SPOTIFY_ENCODED_CREDENTIALS}" -d grant_type=client_credentials https://accounts.spotify.com/api/token)"

SPOTIFY_AUTH_TOKEN="$(echo "$res" | grep -oP '\"access_token\":\"\K[\w-:]+')"
SPOTIFY_AUTH_TOKEN_EXPIRES_IN="$(echo "$res" | grep -oP '\"expires_in\":\K\d+')"
UNIX_TIME_NOW="$(date +%s)"
SPOTIFY_AUTH_TOKEN_EXPIRY="$((UNIX_TIME_NOW+SPOTIFY_AUTH_TOKEN_EXPIRES_IN))"

echo "UPDATE token SET accessToken = '${SPOTIFY_AUTH_TOKEN}', expiry = ${SPOTIFY_AUTH_TOKEN_EXPIRY} WHERE tokenIndex = 0;" | sqlite3 ~/SpotiFlyer/Database/Database.db
```

**Comment by Saransh719** [comment]
I have changed 

> I just dug a bit through the source code wondering if all SpotiFlyer users share the same authentication token. Because even after changing my IP address, I am still getting rate-limited.
> 
> From what I can tell, a unique token is retrieved for each user. But every token is retrieved through the same client ID and client secret:
> 
> https://github.com/Shabinder/SpotiFlyer/blob/73bd43d23c303c101eb557bcd926d67ffe925f94/common/providers/src/commonMain/kotlin/com.shabinder.common.providers/spotify/requests/SpotifyAuth.kt#L48-L49
> 
> We might be able to bypass the rate-limiting by using our own client ID and client secret which can be created [here](https://developer.spotify.com/dashboard/applications).
> 
> This would however require rebuilding the app. Adding an option to SpotiFlyer to allow using our own id/secret would be neat. Other than that, there might be a way to overwrite the stored token, but that probably requires a rooted phone and manually retrieving a token from the `https://accounts.spotify.com/api/token` API.
> 
> **Edit:** I managed to manipulate the token which can be found in: `/data/data/com.sharebinder.spotiflyer/databases/Database.db` in the table `Token`. I used my own client ID + client secret to generate a new auth token and replaced the existing one with my newly generated one. I can now open playlists and download songs again. In one hour my token will have have expired though and I'll have to repeat the procedure, so this is not a proper fix. It's just to prove that the rate-limiting is down to spotify limiting requests on a client ID level.

I have managed to get the client id and edit the code. Can you please tell me how to build the project as there is no .sln file.

**Comment by T-vK** [comment]
> I have managed to get the client id and edit the code. Can you please tell me how to build the project as there is no .sln file.

No, I couldn't. I've never looked into how to build it. Maybe start by looking at the [gradlew.bat](https://github.com/Shabinder/SpotiFlyer/blob/main/gradlew.bat) file.

**Comment by ZazoVa** [comment]
> > Do u know where can i find that section in the Windows version?
> 
> I'd say it uses the same source file for all operating systems.
> 
> The Database.db file is probably in `%APPDATA%\Spotiflyer\Database\Database.db` or something like that on Windows. On Linux it is in `~/Spotiflyer/Database/Database.db`.
> 
> On Linux you can overwrite the access token by running this form the terminal: (You need to insert your CLIENT_ID and CLIENT_SECRET of course. You can get it [here](https://developer.spotify.com/dashboard/applications).)
> 
> ```
> SPOTIFY_CLIENT_ID=*********************
> SPOTIFY_CLIENT_SECRET=*******************
> 
> SPOTIFY_ENCODED_CREDENTIALS="$(echo -n "${SPOTIFY_CLIENT_ID}:${SPOTIFY_CLIENT_SECRET}" | base64 | tr -d "\n")"
> 
> res="$(curl -s -X "POST" -H "Authorization: Basic ${SPOTIFY_ENCODED_CREDENTIALS}" -d grant_type=client_credentials https://accounts.spotify.com/api/token)"
> 
> SPOTIFY_AUTH_TOKEN="$(echo "$res" | grep -oP '\"access_token\":\"\K[\w-:]+')"
> SPOTIFY_AUTH_TOKEN_EXPIRES_IN="$(echo "$res" | grep -oP '\"expires_in\":\K\d+')"
> UNIX_TIME_NOW="$(date +%s)"
> SPOTIFY_AUTH_TOKEN_EXPIRY="$((UNIX_TIME_NOW+SPOTIFY_AUTH_TOKEN_EXPIRES_IN))"
> 
> echo "UPDATE token SET accessToken = '${SPOTIFY_AUTH_TOKEN}', expiry = ${SPOTIFY_AUTH_TOKEN_EXPIRY} WHERE tokenIndex = 0;" | sqlite3 ~/SpotiFlyer/Database/Database.db
> ```

Ended up finding it on "CD:\Users\username\SpotiFlyer\Database\Database.db"

**Comment by Saransh719** [comment]
> > I have managed to get the client id and edit the code. Can you please tell me how to build the project as there is no .sln file.
> 
> No, I couldn't. I've never looked into how to build it. Maybe start by looking at the [gradlew.bat](https://github.com/Shabinder/SpotiFlyer/blob/main/gradlew.bat) file.

Well finally got it done using android studio. Thanks for the tip tho

**Comment by chacha121** [comment]
anything for noobs??

**Comment by ZazoVa** [comment]
> anything for noobs??
> 
> 

noob here. I'm still looking for a way to modify the file on Windows and they already gave a somewhat simple tutorial for Android. if you need more help just reply to my comment.

**Comment by chacha121** [comment]
> > anything for noobs??
> 
> noob here. I'm still looking for a way to modify the file on Windows and they already gave a somewhat simple tutorial for Android. if you need more help just reply to my comment.

it seems all the fixes will work for an hour only...
so for me, it's not worth doing this...(also I used soundloader)

**Comment by Shabinder** [comment]
> > > anything for noobs??
> > 
> > 
> > noob here. I'm still looking for a way to modify the file on Windows and they already gave a somewhat simple tutorial for Android. if you need more help just reply to my comment.
> 
> it seems all the fixes will work for an hour only... so for me, it's not worth doing this...(also I used soundloader)

If you build using ur own personal key, It will work fine as it did earlier. nothing like an hour or so limit.

**Comment by T-vK** [comment]
> it seems all the fixes will work for an hour only... so for me, it's not worth doing this...(also I used soundloader)

This is only true for my workarounds regarding the database manipulations. Manipulating the auth key in the database has to be redone once an hour. If you rebuild the project using your own client id and secret id in the source code, it will automatically refresh your auth token. But admittedly, none of these methods are noob-friendly. For now the only noob-friendly solution is to patiently wait for Shabinder's update. :)

**Comment by ZazoVa** [comment]
> > > > anything for noobs??
> > > 
> > > 
> > > noob here. I'm still looking for a way to modify the file on Windows and they already gave a somewhat simple tutorial for Android. if you need more help just reply to my comment.
> > 
> > it seems all the fixes will work for an hour only... so for me, it's not worth doing this...(also I used soundloader)
> 
> If you build using ur own personal key, It will work fine as it did earlier. nothing like an hour or so limit.

I know this is too noob to ask but what can I use to modify the database file?1

**Comment by T-vK** [comment]
> I know this is too noob to ask but what can I use to modify the database file?1

I used `sqlite3`, but it's a CLI application. You cold also use `sqliteman`, if you want a GUI.
For Android I used `aSQLiteManager` (and a root file explorer to copy the Database.db into my Downloads directory which was required to open it with `aSQLiteManager` and after modifying it, you have to copy it back to `/data/data/com.sharebinder.spotiflyer/databases` of course).

**Comment by Anakulasmos** [comment]
Hey, can someone write a summary on the android tutorial to solve the error? I cant seem to understand what to do

**Comment by chacha121** [comment]
> Hey, can someone write a summary on the android tutorial to solve the error? I cant seem to understand what to do

for a while use> https://www.soundloaders.com/spotify-downloader/

**Comment by Anakulasmos** [comment]
> > Hey, can someone write a summary on the android tutorial to solve the error? I cant seem to understand what to do
> 
> for a while use> https://www.soundloaders.com/spotify-downloader/ (quality-320kbps)

Thx a lot

**Comment by Anakulasmos** [comment]
> will update the clientId and secret and make them configurable and do a release in coming day.

Keep up the work, THANK YOU FOR THE APP!!!!!!

**Comment by Shabinder** [comment]
Here we go guys: [v3.6.2](https://github.com/Shabinder/SpotiFlyer/releases/tag/v3.6.2) is released 🚀 fixing this issue.
https://github.com/Shabinder/SpotiFlyer/releases/tag/v3.6.2

A **rewrite** of the whole app is also **_in progress_**, its still in **_early stages_** but **Stay Tuned** to see what it brings when it lands 👀 .

**Comment by FullThortlePenguin** [comment]
> will update the clientId and secret and make them configurable and do a release in coming day.

Is it out yet?

**Comment by FullThortlePenguin** [comment]
:(

**Comment by kcryptonian** [comment]
> > will update the clientId and secret and make them configurable and do a release in coming day.
> 
> Is it out yet?

Yes it is, you'll find it in settings.

**Comment by GripZViSx** [comment]
> I just dug a bit through the source code wondering if all SpotiFlyer users share the same authentication token. Because even after changing my IP address, I am still getting rate-limited.
> 
> From what I can tell, a unique token is retrieved for each user. But every token is retrieved through the same client ID and client secret:
> 
> https://github.com/Shabinder/SpotiFlyer/blob/73bd43d23c303c101eb557bcd926d67ffe925f94/common/providers/src/commonMain/kotlin/com.shabinder.common.providers/spotify/requests/SpotifyAuth.kt#L48-L49
> 
> We might be able to bypass the rate-limiting by using our own client ID and client secret which can be created [here](https://developer.spotify.com/dashboard/applications).
> 
> This would however require rebuilding the app. Adding an option to SpotiFlyer to allow using our own id/secret would be neat. Other than that, there might be a way to overwrite the stored token, but that probably requires a rooted phone and manually retrieving a token from the `https://accounts.spotify.com/api/token` API.
> 
> **Edit:** I managed to manipulate the token which can be found in: `/data/data/com.sharebinder.spotiflyer/databases/Database.db` in the table `Token`. I used my own client ID + client secret to generate a new auth token and replaced the existing one with my newly generated one. I can now open playlists and download songs again. In one hour my token will have have expired though and I'll have to repeat the procedure, so this is not a proper fix. It's just to prove that the rate-limiting is down to spotify limiting requests on a client ID level.

Hello If Anyone Want To Change The Following Things Then You Must Download Apktool_M on Android and then decompile the app. Then you have to search for the same token above here by copy paste. It will show you option for `SpotifyAuth.kl` file. Click and change it with your own id and token and then save it. Afte it complie the project(there is option for that). That's it. (Sorry for bad English)

**Comment by bluemadeliefje** [comment]
Is there a solution already? I'm sorry, also technical noob here. 
I read things about a new update/release? Can anything tell me where I can download that? If it helps to solve this problem, otherwise another solution is more then welcome.
