### ISSUE TITLE
[BUG] : <client request invalid>

### ISSUE THREAD

**Issue by Akiba21** [Shabinder/SpotiFlyer#1815]
![Screenshot_20221004-222841](https://user-images.githubusercontent.com/115057659/193976134-4fdd54fe-fa4b-42f6-83fe-faa4ed426978.png)

**Describe the bug:**
<!when trying to download some music from spotify automatically the error appears. since today, yesterday was normal>

**Media Links Used:** 

**Expected behavior**

**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   [Motorola m60]
 - OS:   [Android 11]
 - Version:   [3.6.1]
 - Country: [Colombia]

**Additional context:**

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
