### ISSUE TITLE
Spotify is not working 

### ISSUE THREAD

**Issue by yashsarnaik** [Shabinder/SpotiFlyer#1816]
![IMG-20221005-WA0040.jpg](https://user-images.githubusercontent.com/85468955/194005722-cc5e43b5-6f87-417d-9fa4-5b6659204668.jpg) 
All of sudden I'm getting error like this

**Comment by T-vK** [comment]
See #1814

**Comment by LawanIdriss** [comment]
I also encountered this problem, but after deleting app caches it works fine.
Client: Spotify
OS: Android 11

**Comment by Sachinrajmukti** [comment]
not working

**Comment by LawanIdriss** [comment]
@Sachinrajmukti, I notice now it stop working. Sorry for the inconvenience this may cause you, the developers are working on it. Thanks

**Comment by kashetolu** [comment]
I have tried everything but still not working. Please help. Its such a great app otherwise.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
