### ISSUE TITLE
[BUG] : <Can't download any music even with vpn>

### ISSUE THREAD

**Issue by AliMODsPL** [Shabinder/SpotiFlyer#1817]
**Device Info**
 - Device:   Realme 8 5G
 - OS:   ColorOS (Android)
 - Version:   11
 - Country: Poland no VPN, Belgia VPN
- Root: No rooted 
- OEM: Locked
- App version 3.6.1 (latest)

**Additional context:**
App worked maybe 3 times and now it not working is too much bugged dev pls fix it almost 1k issues... Also site can't load link...
Screenshot: https://ibb.co/fDHpcb3

**Comment by Shabinder** [comment]
#1814 duplicate
