### ISSUE TITLE
[BUG] Settings icon appears even after opening settings

### ISSUE THREAD

**Issue by abhi-deshpande** [Shabinder/SpotiFlyer#1818]
Settings icon in the right upper corner still appears after opening settings window. If clicked on it, app crashes.

![Screenshot_20221006-091212_SpotiFlyer~2](https://user-images.githubusercontent.com/56992370/194213201-7518b808-a311-46f7-9683-2cf2a3d73c3d.png)

The icon can be removed when settings instance is detected.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
