### ISSUE TITLE
[BUG] : <Spotiflyer shows invalid:429 error "Too many requests.>

### ISSUE THREAD

**Issue by rohit-singh-git** [Shabinder/SpotiFlyer#1819]
I wanted to download a playlist from the Spotify, but when i paste the link in spotiflyer then it shows "Client request(https://api.spotify.com/v1/playlists/playlist_name) invalid: 429 . Text: "Too many requests".

**Comment by T-vK** [comment]
See #1814

**Comment by SBNRICKRUIZ** [comment]
I have the same issue. What can i do to fix It?

**Comment by enzoathayde** [comment]
same issue too :/

**Comment by frost1010001** [comment]
I am fasing the same issue when trying to download a playlist

**Comment by gh-flutterdev** [comment]
I have the same error too!! Please help.

**Comment by Lvval** [comment]
Any luck on solving this error. ?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by happykiller7406** [comment]
I also encounter the same problems

**Comment by SBNRICKRUIZ** [comment]
I still have that issue
![Screenshot_20221006-210501](https://user-images.githubusercontent.com/115346967/194945864-93db356f-f4cf-42b6-8e04-ae3fca61fdf4.png)

**Comment by miltonjsvidal** [comment]
Same

**Comment by Gr3g0rk** [comment]
Same here

**Comment by sobhanbera** [comment]
See #1814!

**Comment by dwb190565** [comment]
I was having the same issue. Just updated to latest version and problem solved. Link here: 
https://github.com/Shabinder/SpotiFlyer/releases/tag/v3.6.2

**Comment by Lvval** [comment]
Super it's working

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by enzoathayde** [comment]
> I was having the same issue. Just updated to latest version and problem solved. Link here: https://github.com/Shabinder/SpotiFlyer/releases/tag/v3.6.2

amazing, tk a lot

**Comment by dwb190565** [comment]
> > I was having the same issue. Just updated to latest version and problem solved. Link here: https://github.com/Shabinder/SpotiFlyer/releases/tag/v3.6.2
> 
> amazing, tk a lot

Splendiferous!

**Comment by funkyblue** [comment]
It's back again

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
