### ISSUE TITLE
the app is broken

### ISSUE THREAD

**Issue by DaKingOfMonkes** [Shabinder/SpotiFlyer#1820]
Downloading any song from Spotify results in the same error:
Client request({spotify song link here})
invalid: 429. Text: "Too many requests"

Downloading songs on youtube works, it's only for Spotify.
![Screenshot_2022-10-07-09-14-05-93_034e0326429f3b404601e9b17fbe8654](https://user-images.githubusercontent.com/95692573/194446229-170dd9ef-96c8-41f8-88e8-b36d187049d6.jpg)

**Comment by Mateus13000** [comment]
It was like that to me, but today is working just fine!
![Screenshot_20221007-135625_SpotiFlyer](https://user-images.githubusercontent.com/38146322/194610913-ef9aafec-c340-4b5a-becd-27f6622bda71.png)

**Comment by DaKingOfMonkes** [comment]
> It was like that to me, but today is working just fine! ![Screenshot_20221007-135625_SpotiFlyer](https://user-images.githubusercontent.com/38146322/194610913-ef9aafec-c340-4b5a-becd-27f6622bda71.png)

Unfortunately mine is still not working :(

**Comment by T-vK** [comment]
See #1814

**Comment by yavnaz** [comment]
Same here; not working....PERIOD!

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
