### ISSUE TITLE
[BUG] : Songs cannot be downloaded from JioSaavn, causing errors.

### ISSUE THREAD

**Issue by vinayhr01** [Shabinder/SpotiFlyer#1826]
I am not able to download any song from JioSaavn in latest version of the application which is v3.6.1.

Previously the application used to download all JioSaavn songs seamlessly.  Maybe JioSaavn app updation is the reason.
Kindly fix it.

I tried searching in the application to download the song by copying the link provided with share option within the JioSaavn application, which created the URL as https://www.saavn.com when pasted in spotiflyer application, later on I tried copying the link from the same share option but within the JioSaavn web application which created the URL as https://www.jiosaavn.com in spotiflyer application, causing the below shown failure as in screenshot after clicking on search button in spotiflyer android application. 

Here are the screenshots of trying to search and download a song from android application.
![photo_2022-10-08_19-49-44](https://user-images.githubusercontent.com/70259608/194712471-27b28da2-3c2f-42f4-b279-6a490218cac2.jpg)
![photo_2022-10-08_19-49-39](https://user-images.githubusercontent.com/70259608/194712474-d93fe0bd-1b1b-4891-80d3-7d35d75c8c90.jpg)

Device Information:

 - Device:   Poco X3 Pro
 - OS:   MIUI, Android 12
 - Version:   3.6.1
 - Country: India

**Comment by Sanjay451** [comment]
Facing the same issue. Unable to download any song from JioSaavn. Thought this might be an issue with the specific song that I was trying to download. But was randomly checking songs to download from JioSaavn getting same error for every song.

**Comment by vinayhr01** [comment]
Hoping to get that fixed quickly from the devlopers.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
