### ISSUE TITLE
[Feature-Request]: Flatpak support & flathub submission 

### ISSUE THREAD

**Issue by FillingTheVoidOnYT** [Shabinder/SpotiFlyer#1827]
**Is your feature request related to a problem? Please describe.**
Can't install on my linux system

**Describe the solution you'd like**
An flatpak to be created 

**Describe alternatives you've considered**
there isn't any 

**Additional context**
submission to flathub would bring access to many users

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
