### ISSUE TITLE
[Feature-Request]: Apple Silicon support for macbooks with m1 & m2 chips

### ISSUE THREAD

**Issue by FillingTheVoidOnYT** [Shabinder/SpotiFlyer#1828]
**Is your feature request related to a problem? Please describe.**
apple silicon support 

**Describe the solution you'd like**
being able to use the appp
**Describe alternatives you've considered**
there aren't any alternatives
**Additional context**
app doesn't run on mac m2

**Comment by nobaraos12** [comment]
heavily needed

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
