### ISSUE TITLE
[BUG] : client request 

### ISSUE THREAD

**Issue by JKT482k23** [Shabinder/SpotiFlyer#1831]
![Screenshot_2022-10-10-10-45-07-251_com shabinder spotiflyer](https://user-images.githubusercontent.com/110312450/194796692-e36975f1-1ae4-4da7-a8d7-8b907bf8a6cd.jpg)

**Describe the bug:**

**Media Links Used:** 

**Expected behavior**

**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   [e.g. iPhone6, Samsung J2, PocoF1]
 - OS:   [e.g. iOS, Android 10, WinOS, MacOS]
 - Version:   [e.g. 3.2.1]
 - Country: [eg: India, will help in detecting if service is accessible to u]

**Additional context:**

**Comment by Niteify** [comment]
Having the same issue on android and windows.
![image](https://user-images.githubusercontent.com/40525844/194926403-559e80ee-6931-44d7-af31-6661fd185344.png)

**Comment by Zamzingus** [comment]
I'm having the same issue also on my Samsung Galaxy S21

**Comment by zketox** [comment]
Same problem on Redmi 7A

**Comment by JKT482k23** [comment]
Can the developer fix this problem

**Comment by Shabinder** [comment]
#1814 
Fixed in 3.6.2
