### ISSUE TITLE
[BUG] : <Apps Not Working. Why?>

### ISSUE THREAD

**Issue by Saifulislam70990** [Shabinder/SpotiFlyer#1832]
![Screenshot_20221010-204118](https://user-images.githubusercontent.com/98544123/194930235-76296b46-e827-4546-811b-6b8aaa537a2a.jpg)

> 

**Describe the bug:**

**Media Links Used:** 

**Expected behavior**

**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   [e.g. iPhone6, Samsung J2, PocoF1]
 - OS:   [e.g. iOS, Android 10, WinOS, MacOS]
 - Version:   [e.g. 3.2.1]
 - Country: [eg: India, will help in detecting if service is accessible to u]

**Additional context:**

**Comment by johnnyeightpence** [comment]
Same here

**Comment by Dhrubaof2002** [comment]
Same here

**Comment by locamotus** [comment]
Same here
