### ISSUE TITLE
[BUG] : Hebrew letters being written as underscores

### ISSUE THREAD

**Issue by josh672** [Shabinder/SpotiFlyer#1841]
Hebrew letters show up in the preview playlist, but after downloading, they are written to the file name as underscore characters.

This makes it impossible to download a playlist because a filename with 5 characters will overwrite another filename with 5 characters because the names are the same after being saved as underscores.

Please fix this, I love the app, there is so much great music coming from israel right now. I would love to be able to download the music and arrange my playlists into file folders.

Keep up the great work I hope this issue gets fixed.

Device: Samsung galaxy a13 5g
Os: android 12
Sf version: 3.6.2
Region: us (nord vpn- access to various countries)

![Screenshot_20221012-195928_Cx File Explorer](https://user-images.githubusercontent.com/115678942/195497548-9c4176bb-9264-4c37-adc6-a9d5b5cc812e.jpg)

![Screenshot_20221012-211120](https://user-images.githubusercontent.com/115678942/195497699-e445baef-3b16-4b52-b761-3c66de1aae76.jpg)

**Comment by Erictheplague** [comment]
Rename songs metadata to song title

**Comment by josh672** [comment]
So download one song at a time, rename it, and then download the next one
and repeat?

**Comment by Erictheplague** [comment]
Yes

**Comment by josh672** [comment]
Okay, fine. Thank you for responding to my emails

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
