### ISSUE TITLE
[BUG] :  Song with same name get overwritten. 

### ISSUE THREAD

**Issue by OmkarVedpathak** [Shabinder/SpotiFlyer#1845]
**Describe the bug:**
Song with same name get overwritten 
Eg: "Baazigar" have two versions of "Chhupana Bhi Nahin Aata" with different artist. Song no 4 and 6

**Media Links Used:** 
https://open.spotify.com/album/5idbEvMrr6c2XiAZNBtkKm?si=dx6yNTfMTxWRMfjNwMhnOw&utm_source=copy-link

**Expected behavior**
Both song should be downloaded with alteration in file name. Eg Chhupana_Bhi_Nahin_Aata.mp3 and Chhupana_Bhi_Nahin_Aata_1.mp3

**Screenshots:**
NA

**StackTrace:**
```
NA
```

**Device Info (please complete the following information):**
 - Device:   Realme x2
 - OS:   Custom Rom - android 12
 - Version:   3.6.2
 - Country: India

**Additional context:**

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
