### ISSUE TITLE
[BUG] : incorrect Metadata

### ISSUE THREAD

**Issue by Harmxn02** [Shabinder/SpotiFlyer#1846]
**Describe the bug:**
Song metadata is not the song's metadate, but rather the metadata of the YouTube video you used to download the song. 
Some songs are uploaded by for example NoCopyrightSounds, but they aren't the artist of the song; but when you download it, it shows NoCopyrightSounds as the artist.

It also has a lengthy name, instead of what is shown on Spotify.

I am used to downloading songs like this though, and I'm using another app to fix the metadata (it's called AutomaTag), but your app used to do it correctly, and it's annoying to manually fix each song.

**Media Links Used:** 
any use of the app

**Expected behavior**
Download a song, and have the correct metadata (artist, song name)

**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   Samsung S22
 - OS:   Android 12
 - Version:  OneUI 4.1
 - Country: Belgium

**Additional context:**
I think it may be because you had to circumvent the Spotify rate limiting. But hey, *I am very thankful the app is back and running. you are amazing dude :)*

**Comment by Erictheplague** [comment]
Use ES explorer to correct metadata of songs you wish to change

**Comment by Harmxn02** [comment]
I redownloaded the playlist I had troubles with, and the metadate is correct now
