### ISSUE TITLE
[BUG] : App Crash android 6.0.1

### ISSUE THREAD

**Issue by karmadev0** [Shabinder/SpotiFlyer#1850]
**Describe the bug:**

I have used the service for a long time in its old version, since for some reason the new ones do not open or it crashes, basically it is the error: "this application has stopped", but for some reason the notification bar of the apps

**Media Links Used:** 

https://open.spotify.com/playlist/37i9dQZF1DXblapgdEq7WZ?si=-D5VmHAHRjeZQNjEzbzsDg&utm_source=copy-link

**Expected behavior**

at least open and work normally

**Screenshots:**

not available for being the typical android poster

**Device Info (please complete the following information):**
 - Device [Samsung J2 Prime]
 - OS:   [Android OS]
 - Version:   [6.0.1]
 - Country: [Venezuela]

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
