### ISSUE TITLE
[BUG] : <Issue_Title>can't download


java.lang.Exception: Client request(https://rr1---sn-2uuxa3vh-jb3e7.googlevideo.com/videoplayback?expire=1665738406&ei=RtJIY_aFLbWC4-EP8OGy0AQ&ip=180.244.25.124&id=o-AKJAeQGISDpNF2GKHCGH5kZuzHuXYJAwqtUux5XF7XSi&itag=140&source=youtube&requiressl=yes&mh=Cc&mm=31%2C29&mn=sn-2uuxa3vh-jb3e7%2Csn-npoe7nsk&ms=au%2Crdu&mv=m&mvi=1&pl=21&gcr=id&initcwndbps=663750&vprv=1&mime=audio%2Fmp4&gir=yes&clen=2454253&dur=151.533&lmt=1665517292377918&mt=1665716464&fvip=4&keepalive=yes&fexp=24001373%2C24007246&c=MWEB&txp=2318224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgUvenqCqAtnSVW2W9OmRQubxR-dmyRXVsDAMZPYtYHqUCIQDwUqGJpcw9Cg9G8iK6-4Uwv2p3eW-SSjJPNDqm_jzwYQ%3D%3D&sig=AOq0QJ8wRgIhAN1lvzUUlgkFyJjguGJz4zBU4wIRdqXm1czYNSmNb6a0AiEAsNwkXo1FeTUPBNjOPWot_F4R2lFt0xjW-PsNEJ3Rzzo%3D&title=EDGING) invalid: 403 Forbidden. Text: ""


### ISSUE THREAD

**Issue by dyeybey** [Shabinder/SpotiFlyer#1851]
**Describe the bug:**

**Media Links Used:** 

**Expected behavior**

**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   [e.g. iPhone6, Samsung J2, PocoF1]
 - OS:   [e.g. iOS, Android 10, WinOS, MacOS]
 - Version:   [e.g. 3.2.1]
 - Country: [eg: India, will help in detecting if service is accessible to u]

**Additional context:**

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
