### ISSUE TITLE
[BUG] : App keeps downloading at 320kbps even after changing quality

### ISSUE THREAD

**Issue by abhi-deshpande** [Shabinder/SpotiFlyer#1855]
**Description:**
Spotiflyer has capability of downloading audio in different qualities. But even after changing the quality settings, it keeps downloading at 320kbps.

**Media Links Used:** 
Find [here](https://gaana.com/album/bolava-vitthal-english-2008).

**Expected behavior**
Downloaded audio quality must be according to the set settings.

**Device Info:**
 - Device: Motorola moto E5 plus
 - OS: Lineage OS 18.1
 - Version: 3.6.2
 - Country: India

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
