### ISSUE TITLE
Issue with some album arts not loading clearly "blurry"

### ISSUE THREAD

**Issue by Kendu26** [Shabinder/SpotiFlyer#1856]
Hello shabinder, first off, thanks for the update to the app. I'm having an issue with the app only downloading blurry cover arts for some songs or albums whenever I download a song. It's never happened before the update.

_Originally posted by @Kendu26 in https://github.com/Shabinder/SpotiFlyer/discussions/1854_

**Comment by DarkKiller8456** [comment]
Yes it's happening since the new update all the album covers are coming blurred

**Comment by StoneK47** [comment]
It's been happening to me for a whole week now and I tried deleting and reinstalling but nothing worked the album covers are still low resolution

**Comment by Kendu26** [comment]
Pls, does anyone have a solution to the issue?

**Comment by Kendu26** [comment]
When you want to share the song or album link to spotiflyer, make sure u share it from the album page options not the song option icon. This is what I'm saying 
![Screenshot_20221102-102354](https://user-images.githubusercontent.com/101534556/199452977-f75aa539-00b8-451a-9020-13f0b9dd3582.png)
Hope it helps.

**Comment by Shabinder** [comment]
Fixed in latest update v3.2.3
