### ISSUE TITLE
[BUG] : POOR QUALITY ALBUM ARTS FOR ALL SONGS AND ALBUMS

### ISSUE THREAD

**Issue by kyouma21** [Shabinder/SpotiFlyer#1859]
**Describe the bug:**
Album art is of Poor Quality for all songs and albums

**Media Links Used:** 
https://open.spotify.com/track/7cAFrpq9c6nJJcnF04ah39?si=B_sXKEZTS7K_glOac4gOhw

**Expected behavior**

**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   Oneplus 7 Pro
 - OS:   Android 11
 - Version:  Latest
![Screenshot_20221015-235455](https://user-images.githubusercontent.com/115888653/195996092-305c399c-202d-4be7-b49b-ed136f6866b1.jpg)

 - Country: Philippines
**Additional context:**

**Comment by d4f5409d** [comment]
#1868

**Comment by Shabinder** [comment]
Fixed in v3.6.3.
