### ISSUE TITLE
[BUG] : <Cover Photo Blur. Why?>

### ISSUE THREAD

**Issue by Saifulislam70990** [Shabinder/SpotiFlyer#1860]
![Screenshot_20221015-193653](https://user-images.githubusercontent.com/98544123/195997893-0e360323-4c6e-4a27-8d8b-32cd63aee44f.jpg)

**Describe the bug:**

**Media Links Used:** 

**Expected behavior**

**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   [e.g. iPhone6, Samsung J2, PocoF1]
 - OS:   [e.g. iOS, Android 10, WinOS, MacOS]
 - Version:   [e.g. 3.2.1]
 - Country: [eg: India, will help in detecting if service is accessible to u]

**Additional context:**

**Comment by Shabinder** [comment]
Fixed in v3.6.3.
