### ISSUE TITLE
Music with same titles has been marked downloaded by the app but physically has never downloaded it. 

### ISSUE THREAD

**Issue by Endstarky** [Shabinder/SpotiFlyer#1861]
**Describe the bug:**

**Media Links Used:** 

**Expected behavior**

**Screenshots:**
![Screenshot_2022-10-15-21-45-29-80_034e0326429f3b404601e9b17fbe8654](https://user-images.githubusercontent.com/67501470/196001761-57dce44a-fe7d-4e07-ba9a-1dd1376846b9.jpg)
![Screenshot_2022-10-15-23-23-35-30_3e6d449c199baba3f618e7d8603fa484](https://user-images.githubusercontent.com/67501470/196001765-ccf6384f-1e79-47fb-b5ff-bc36eb4ae17d.jpg)

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   realme 2 pro
 - OS:    Android 10
 - Version:   3.2.6
 - Country: India

**Additional context:**
Please fix it! 
Thank you.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
