### ISSUE TITLE
[BUG] : Album Art Blur ?

### ISSUE THREAD

**Issue by jainalmustaqin** [Shabinder/SpotiFlyer#1863]
**Describe the bug:**
When I download the song the album art is blurry

**Media Links Used:** 
<a href="https://open.spotify.com/track/1taiyNwQ9IZfQnZ9ymzpeZ">Click Here !</a>

**Expected behavior**
Please, Fix the bug.

**Screenshots:**
![Screenshot_20221016-095348](https://user-images.githubusercontent.com/31983123/196015862-60b9059c-a971-4bf3-b064-5189e92487aa.png)

**Device Info (please complete the following information):**
 - Device:   REALME C21Y
 - OS:   Android 11
 - Version:   3.6.2
 - Country: Indonesia

**Comment by d4f5409d** [comment]
Du0licate of #1868

**Comment by Shabinder** [comment]
Fixed in v3.6.3.
