### ISSUE TITLE
[BUG] : <Issue_Title> The Song Thumbnail Is Blurred

### ISSUE THREAD

**Issue by shravank75** [Shabinder/SpotiFlyer#1865]
**Describe the bug:**

**Media Links Used:** 

**Expected behavior**

**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   [e.g. iPhone6, Samsung J2, PocoF1]
 - OS:   [e.g. iOS, Android 10, WinOS, MacOS]
 - Version:   [e.g. 3.2.1]
 - Country: [eg: India, will help in detecting if service is accessible to u]

**Additional context:**

**Comment by shravank75** [comment]
The song thumbnail gets blurred in this new update and even some of the songs when downloaded are different plz resolve this issues

**Comment by d4f5409d** [comment]
Duplicate #1868

**Comment by Shabinder** [comment]
Fixed in v3.6.3.
