### ISSUE TITLE
Wrong songs from Spotify. Songs are 128kbps

### ISSUE THREAD

**Issue by Shpigorx** [Shabinder/SpotiFlyer#1866]
I download [this playlist ](https://open.spotify.com/playlist/5Rg9GrllUa0RvZN54jMEs5) and got 

1. [this song by Yuki](https://open.spotify.com/track/0m2EKbjO92P8SZbBQkydI2?si=9cc96b02eaec4a6f) not as on Spotify. I get acoustic version of this song.
1. this [song by Peggies](https://open.spotify.com/track/3DpnZMnlXIVWVB8RWFjuAI?si=19b2fbd2838b4de6) has 1:36 long (TV version) instead of full.
2. [song by Minami](https://open.spotify.com/track/1gUAX2ImxDsB3YDcyxMXlB?si=232d870cda284718) is absent in folder but is in downloaded list.

Also all songs 128kbps.

I Use PC ver (Win 10x64) of the app, last ver at this time.

**Comment by GuyInDogSuit** [comment]
I'm getting 128 kbps on everything, too, on the latest Windows client.
It also can't find a few songs I've downloaded (though they do show up fine in the search).

**Comment by Shpigorx** [comment]
> I'm getting 128 kbps on everything, too, on the latest Windows client. It also can't find a few songs I've downloaded (though they do show up fine in the search).

I will tell you a secret, app does not download from spotify. I think it searches on yt music and get there or somewhere . I tested a few similar apps. There is only one app that gets music directly from spotify and takes time to download each song sequentially

**Comment by Aceroph** [comment]
> 

what app downloads directly?

**Comment by Shpigorx** [comment]
Sidify. But:

- It is not free. Cracked ver exists tho.
- You need Spotify PC. 
Sidify connects to it and grabs audio directly. The speed is ~5x. So 5min songs takes ~1min to grab
- You acc may be blocked. My get block after 6+ month. 
That acc was created especially for downloads. Also my main acc is not blocked with premium sub from time to time. I grabbed songs with 2 accs.
- You can download real 320 kbps with free spot acc. Tested with spectro analys

**Comment by bverkron** [comment]
Unfortunately I think @Shpigorx is correct.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
