### ISSUE TITLE
very low resolution album cover in 3.6.2 update

### ISSUE THREAD

**Issue by abdogood399** [Shabinder/SpotiFlyer#1868]
please fix this issue cause it looks really bad and it used to be better in previous versions however i tried downgrading but it wouldn't let me download any songs

**Comment by nikhiljanu2004** [comment]
> ![IMG-20221017-WA0017.jpg](https://user-images.githubusercontent.com/56756992/196139034-613f601c-eb22-40b0-985f-b6d907bcad41.jpg)
> 
> 
> It's also low in v3.6.1

Not in 3.6.1, this new version (3.6.2) is only having such a problem, I tried downgrading it, but it won't let me downgrade.

**Comment by nikhiljanu2004** [comment]
> ![IMG-20221017-WA0017.jpg](https://user-images.githubusercontent.com/56756992/196139034-613f601c-eb22-40b0-985f-b6d907bcad41.jpg)
> 
> 
> It's also low in v3.6.1

![Screenshot_20221017-145619_Samsung Music.jpg](https://user-images.githubusercontent.com/115984811/196141770-bddc42e1-b25c-4504-9161-db17c6c480ef.jpg)!
[Screenshot_20221017-145602_Samsung Music.jpg](https://user-images.githubusercontent.com/115984811/196141823-78d14fa3-faa7-4291-903f-edbd6b63bec5.jpg)

A comparison for reference.

**Comment by Vandabell** [comment]
Same issue I got here

**Comment by Sanjay451** [comment]
Facing the same issue with latest update (3.6.2). Haven't tried downgrading.

@Shabinder could you please check.

**Comment by d4f5409d** [comment]
Same here.

**Comment by GeorgeSakketos** [comment]
Same problem here.
