### ISSUE TITLE
[Feature-Request]: Add lower bitrate types for spoken stuff

### ISSUE THREAD

**Issue by Mokura** [Shabinder/SpotiFlyer#1875]
**Is your feature request related to a problem? Please describe.**
Not really a problem, but I travel a lot.  I download the audio for videocasts and game playthroughs on YouTube to listen to.  Mostly-spoken stuff I don't mind downloading at a lower bitrate in order to save space.

**Describe the solution you'd like**
64kbps option, maybe even 48kbps.

**Describe alternatives you've considered**
NewPipe lets me download lower quality audio, but not in batch (yet).

**Additional context**
![Screenshot_20221018-132141_NewPipe](https://user-images.githubusercontent.com/5167919/196501348-ed72040f-48d1-40fb-9b0d-3db3b910c999.png)

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.

**Comment by Mokura** [comment]
Will Soundbound also be an open source project?
