### ISSUE TITLE
[BUG] : <Issue_Title>The latest version (3.6.2) is not downloading the thumbnail of the song in high resolution which it did before this update  .   Please fix this

### ISSUE THREAD

**Issue by animesh32846821873u3o** [Shabinder/SpotiFlyer#1878]
**Describe the bug:**

**Media Links Used:** 

**Expected behavior**

**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   [e.g. iPhone6, Samsung J2, PocoF1]
 - OS:   [e.g. iOS, Android 10, WinOS, MacOS]
 - Version:   [e.g. 3.2.1]
 - Country: [eg: India, will help in detecting if service is accessible to u]

**Additional context:**

**Comment by d4f5409d** [comment]
#1868
