### ISSUE TITLE
Intel Macos: No ffmpeg found at path

### ISSUE THREAD

**Issue by N00dlesandwitch** [Shabinder/SpotiFlyer#1879]
When I open it says "No FFMPEG found at path" but I've used FFMPEG for audacity, and some type of Youtube ripper in the past. And I can run ffmpeg directly in terminal. Installed it with HomeBrew but also tried installing from the FFMPEG site then putting it in my usr/local/bin folder- any ideas? (Also I'm new to reporting on Github so hopefully I've done this all correct, thank you!)

**Comment by n0kovo** [comment]
Same problem here

**Comment by dasauto1** [comment]
this issue still exists as I have ffmpeg in PATH, not sure what is wrong.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
