### ISSUE TITLE
[BUG] : Some songs become corrupted

### ISSUE THREAD

**Issue by Trash-panda250** [Shabinder/SpotiFlyer#1880]
**Describe the bug:**
Whenever I'm downloading a song from an album it has a chance to become corrupted after being downloaded. First it happened when i was downloading an iron maiden album and half the songs on the album became corrupted, next i tired a System of a down album and certain songs would do the same thing, Today i tried with a Queen album and the second song i tried to download was corrupted. I've tried restarting, Deleting a redownloading the song, and spot flyer itself but the issue seems to keep happening.

**Media Links Used:** 
https://open.spotify.com/album/1GbtB4zTqAsyfZEsm1RZfx?si=FBqIxr7RR529RQe80tHaSA - Queen, A Night At The Opera
https://open.spotify.com/album/309KOMEivisMmBuzk09635?si=15eca1dcad5f4083 - Iron Maiden, Powerslave
https://open.spotify.com/album/6lA1sGw7eCv27bcpd5E0wT?si=6ea6d22ee7e24b24 - System Of A Down, Steal this Album

**Expected behavior**
I just want someone to help me figure this out, im not really sure what else to say.

**Screenshots:**

![spotiflyer 1](https://user-images.githubusercontent.com/116218410/196797067-7b707f9a-f5df-4551-8fc3-6d0c9109fdf6.PNG)
![spotiflyer 2](https://user-images.githubusercontent.com/116218410/196797117-62fa0060-0609-4af8-8415-29e6f82f16c8.PNG)

**Device Info**
 - Device:   Deasktop PC
 - OS:   Windows 10
 - Version:   3.6.2
 - Country: England

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
