### ISSUE TITLE
[BUG] : <SpotiFlyer doesn't work anymore like past on Spotify>

### ISSUE THREAD

**Issue by islamsanjida215** [Shabinder/SpotiFlyer#1886]
On the latest update of spotiflyer, it doesn't behave like normal. I was a big fan of SpotiFlyer. On past, there was barely 1-2 songs downloading which I faced at the previous update. Now if I go for download songs, 9 out of 10 are not downloading. 

A humble request to you guys to fix the problem

 - Device: Huawei Nova Lite 3+
 - OS:   Android 9
 - Version:  
 - Country: Bangladesh

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
