### ISSUE TITLE
[BUG] : <ALBUM ART LOW RESOLUTION>

### ISSUE THREAD

**Issue by StaticGamerYT-India** [Shabinder/SpotiFlyer#1891]
The album art is of a really low resolution, please fix this thing
i guess it has been done intentionally to reduce file size but cmon its 2022 people have much storage for all this 
please fix this :)

**Screenshots:**
![image](https://user-images.githubusercontent.com/77852984/197328726-5fed06b0-b4ad-495e-9d1a-03605d2a7e2a.png)

Version - 3.6.2
OS-  Windows 11 22H2

**Comment by Erictheplague** [comment]
Learn Kotlin and contribute to Spotiflyer

**Comment by Danqtpa2t** [comment]
Same

**Comment by Shabinder** [comment]
Fixed in v3.6.3.
