### ISSUE TITLE
Crashes upon pasting link and pressing search [Windows 10 (Version 21H2/OS Build 19044.2130)]

### ISSUE THREAD

**Issue by mindlessssss** [Shabinder/SpotiFlyer#1895]
I open the Windows app, it launches, I paste my Spotify playlist link, press search, it crashes. No logs to be found.

**Comment by Erictheplague** [comment]
Uninstall current apk and install it again

**Comment by mindlessssss** [comment]
> Uninstall current apk and install it again

On windows?

**Comment by Erictheplague** [comment]
Yes

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
