### ISSUE TITLE
[BUG] : <Issue_Title>

### ISSUE THREAD

**Issue by dragoneatr** [Shabinder/SpotiFlyer#1896]
**Describe the bug:**

i download and run the proper app for my system but when i open the app after finishing the wizard it only opens up as a white screen and doesnt do anything.
**Media Links Used:** 

**Expected behavior**

![Screenshot 2022-10-23 040949](https://user-images.githubusercontent.com/116492269/197388733-cdc72555-359b-4070-bc5f-6624cefb4a7b.png)
nothing except blank white
**Screenshots:**

attached
**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   toshiba satellite
 - OS:  WinOS
 - Version:   [e.g. 3.6.2]
 - Country: united states

**Additional context:**

**Comment by Erictheplague** [comment]
Uninstall and Reinstall it

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
