### ISSUE TITLE
No internet connectivity!

### ISSUE THREAD

**Issue by Contay6** [Shabinder/SpotiFlyer#19]
Hey my phone's Wifi doesn't work so I use Gnirehtet to get access and the app doesn't recognize that it's connected, cheers
this is the github link to 'Gnirehtet https://github.com/Genymobile/gnirehtet'

**Comment by Shabinder** [comment]
Thanks for the issue, will fix in next release.
Till then , Stay Tuned.

**Comment by Shabinder** [comment]
Closed By Mistake.😅

**Comment by Contay6** [comment]
Cheers mate, appreciate it

**Comment by Shabinder** [comment]
This issue should be fixed in v2.2.0 ,if not please report back and feel free to reopen this issue.

**Comment by anzan000** [comment]
No internet Connection on WIFI. Verse 3.6.3
![Uploading Screenshot_20230624-080750.jpg…]()
