### ISSUE TITLE
glitch problem

### ISSUE THREAD

**Issue by beshoyy** [Shabinder/SpotiFlyer#190]
in the first time i used this app my phone get glitched and stop of working for a minute so i thought this app contain malware or something like this and removed it but after this i realized that this app really awesome with some bugs, KEEP GOING and please fix it, thanks. 

phone : redmi note 10
rom : miui 12.0.10

**Comment by Shabinder** [comment]
Can you describe the said glitch in detail?
I haven't encountered anything of such kind on my device.

**Comment by beshoyy** [comment]
when i installed this app for the first time i refused at the first to give it the permissions it's needed and after refused my phone freezed for 1 min or less

**Comment by Shabinder** [comment]
> when i installed this app for the first time i refused at the first to give it the permissions it's needed and after refused my phone freezed for 1 min or less

Ohhh, will investigate the issue.
I have added a recursive loop to ask permission again and again is not granted as those are Necessary for app to work, that might be the cause of slowdown :upside_down_face:

**Comment by beshoyy** [comment]
Lol I thought my phone was damaged..
In general, thank you so much for your interest in solving my problem and for this application again, and I hope that you will add the feature of downloading from Anghami in the future, I will close the issue now.
