### ISSUE TITLE
Clear and/or paste buttons, or multiple inputs

### ISSUE THREAD

**Issue by breadcat** [Shabinder/SpotiFlyer#191]
My usual workflow using this involves pasting single playlists at a time, downloading them then pasting in the next link and repeating the process.

Currently I have to manually delete the previous playlist link, could you add a X icon at the end of the bar to clear?
It would also be nice if there was a paste button to negate the need for clear then manually pasting by long pressing the box.

Another nice feature would be to replace the single playlist link field with a multiple line box, one per playlist searched.

Thanks again for creating the software!

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
