### ISSUE TITLE
[BUG] : jar file doesn't open

### ISSUE THREAD

**Issue by ghost** [Shabinder/SpotiFlyer#1911]
and don't tell me to reinstall Java, I proved with JDownloader and it does open

**Comment by Menorah** [comment]
Install [Java SE 19](https://www.oracle.com/java/technologies/javase/jdk19-archive-downloads.html). For me, that solved the problem on Windows 11.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
