### ISSUE TITLE
[BUG] : <Bad quality song cover>

### ISSUE THREAD

**Issue by TheKarvos** [Shabinder/SpotiFlyer#1913]
![Screenshot_20221024-183625](https://user-images.githubusercontent.com/116115985/197590377-5a6941d1-9a85-4b7a-b557-b6ef7f7efadd.jpg)

**Describe the bug:**

**Media Links Used:** 

**Expected behavior**

**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   [e.g. iPhone6, Samsung J2, PocoF1]
 - OS:   [e.g. iOS, Android 10, WinOS, MacOS]
 - Version:   [e.g. 3.2.1]
 - Country: [eg: India, will help in detecting if service is accessible to u]

**Additional context:**

**Comment by Shabinder** [comment]
fixed in v3.2.3
