### ISSUE TITLE
Add FLAC Support

### ISSUE THREAD

**Issue by timea-techgirl** [Shabinder/SpotiFlyer#192]
Hello, can you please add support to download FLAC audio?
Currently, downloaded songs are in 320 kbps.
Thanks!

**Comment by Shabinder** [comment]
Are you aware of any sources with a rich media library and allow Flac Downloading ?

**Comment by phantom2152** [comment]
You can get it from deezer

**Comment by phantom2152** [comment]
Use can use deezer api

**Comment by vehosah** [comment]
or soulseek.or chiasenhac

**Comment by ericsomto** [comment]
![1667530494409917.png](https://user-images.githubusercontent.com/81354428/227473083-a00696b1-1e7b-441d-94c1-336ee20eec84.png)

**Comment by s0mt0chukwu** [comment]
There should flac support for Spotiflyer.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
