### ISSUE TITLE
[BUG] : why is counlty.shabinder.in connection being made once a minute?

### ISSUE THREAD

**Issue by ghtesting2020** [Shabinder/SpotiFlyer#1922]
**Describe the bug:**
I assumed it was due to analytics but even with analytics off counlty.shabinder.in is being pinged once every minute.

**Expected behavior**
Do not ping counlty.shabinder.in. What's the purpose? The app works fine without it. I have it blocked in my firewall and there is no difference.

**Device Info (please complete the following information):**
 - Device: Pixel 6
 - OS:  Android
 - Version: 3.6.2 from fdroid
 - Country: USA

**Additional context:**
It would be nice if this connection was removed. it makes me uneasy as to why the app is trying this address every minute with seemingly no purpose.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
