### ISSUE TITLE
what is the solution 

### ISSUE THREAD

**Issue by CESARKHALID** [Shabinder/SpotiFlyer#193]
![solution](https://user-images.githubusercontent.com/73532128/123855880-4f6e4000-d918-11eb-90ad-e6bd0cf53932.png)

what i should do for i can resolve **

**Comment by Shabinder** [comment]
https://github.com/Shabinder/SpotiFlyer/commit/252e0c101d46a164642fbb275b58ead1395291c9

Clone at above Commit to build it

**Comment by Shabinder** [comment]
Try Again after updating project now MAIN Brack should be working
