### ISSUE TITLE
[BUG] :   Non-English named songs problem

### ISSUE THREAD

**Issue by User090306** [Shabinder/SpotiFlyer#1934]
Hi, I found out that while downloading some songs which have Chinese/Japanese names,they will be named like _____.mp3. And while downloading  multiple songs like XXXXX ,YYYYY and ZZZZZ, they will both be named as _____.mp3 and YYYYY will cover XXXXX, ZZZZZ will cover XXXXX so I only get the ZZZZZ which named as _____.mp3
Like this:
<img width="595" alt="image" src="https://user-images.githubusercontent.com/83623940/198873007-49ee554a-8f4c-484c-96cc-2292a87113ab.png">

If you cant understand what I'm talking about, try to download https://open.spotify.com/album/27I7fCoQRSdL9PT1nFWEPC?si=203zdP1sQ5GhpsOhzckStQ and you will know whats wrong.

OS:Win11Home(Simplified Chinese)

Thak you.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
