### ISSUE TITLE
Says it's already been downloaded when it hasn't because I've never put that song Into the app

### ISSUE THREAD

**Issue by LGD-Valtar** [Shabinder/SpotiFlyer#1939]
I've been using this app for ages and I've found an issue. For some songs from Spotify I put into Spotiflyer it says I've downloaded it, I clearly haven't because I have checked my phone's files. Normally I just went and used YouTube to download the same song but it's getting sort of irritating. Could you please add a fix?
Ty for the app btw its great Ive just been getting into j-pop and I can't type in Japanese so finding in yt was hard for me.

**Comment by Fiesty-Cushion** [comment]
It does that when there is already a song in the directory with the exact name as the song you are trying to download. A quick way around is to rename the file you have in your library and clear cache and data for spotiflyer and try again. It worked for me.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
