### ISSUE TITLE
A few bugs I noticed

### ISSUE THREAD

**Issue by FireMS** [Shabinder/SpotiFlyer#1941]
Hello!

I've been using Spotiflyer for quite a while now. (few months) And here's a few bugs I've encountered.

1. Download speeds are VERY slow. They used to be fairly speedy, but I believe as the project has gotten bigger, download rates have lowered. I've tried various different solutions, also put in my own user-set credentials.

2. Majority of times, downloads will fail, especially when downloading from playlists/albums. This goes for both mobile, and Windows 10. 

3. On some occasions, more likely for longer files, they will stop halfway through. The audio file is corrupted halfway. It will be playing like normal, and will suddenly loop or change to the next song. This is not just my music player, because I've tried it on three different streaming platforms on different devices. 

4. (Not really a bug, more of a design flaw.) When downloading to separate folders, not within the spotiflyer directory, the app will say "No FFmpeg found at path." And will block certain buttons on both the mobile and desktop. This happens with every single one of my songs over 10 minutes.

I run this app from both my phone (Samsung Galaxy S9) and my computer. (Windows 10). And I really appreciate the work and effort that went into making this project possible. I hope to see this project thrive in the future.

**Comment by FireMS** [comment]
I did forget to add, I download all of my music from Spotify, and I'm not entirely sure if this is only happening with Spotify or all platforms.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
