### ISSUE TITLE
[BUG] : This track gets downloaded but when opened it plays different song  https://open.spotify.com/track/0U3nXvCx7v6t7CXqEdAWOr?si=jznjWzeFR2qyY7PcSzDt3w&utm_source=copy-link

### ISSUE THREAD

**Issue by shravank75** [Shabinder/SpotiFlyer#1959]
**Describe the bug:**

**Media Links Used:** 

**Expected behavior**

**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   [e.g. iPhone6, Samsung J2, PocoF1]
 - OS:   [e.g. iOS, Android 10, WinOS, MacOS]
 - Version:   [e.g. 3.2.1]
 - Country: [eg: India, will help in detecting if service is accessible to u]

**Additional context:**

**Comment by shravank75** [comment]
https://open.spotify.com/track/0U3nXvCx7v6t7CXqEdAWOr?si=jznjWzeFR2qyY7PcSzDt3w&utm_source=copy-link

**Comment by dhakkann** [comment]
Same issue with this one
https://open.spotify.com/track/4iFPsNzNV7V9KJgcOX7TEO?si=MjFQLvalQyaI5oUH2qFUBQ&utm_source=copy-link

It instead downloads a short lofi version of it with duration 1:50, and size 4.43 MB( 4641534 B)

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
