### ISSUE TITLE
[BUG] : Soundcloud doesn't download

### ISSUE THREAD

**Issue by Minecodes** [Shabinder/SpotiFlyer#1975]
**Describe the bug:**
When I download from Soundcloud, it fails already at the search with the HTTP error 401 Unauthorized. The search is not opened and no fails are displayed under the downloads.

**Media Links Used:** 
- https://on.soundcloud.com/wfUcJ
- https://on.soundcloud.com/CRcyx
- https://on.soundcloud.com/zyxGA

**Expected behavior:**
The search should open and I can click download. Then it should download the song.

**Screenshots:**
![IMG_20221103_091156.jpg](https://user-images.githubusercontent.com/65566012/199673173-1b896a87-6b18-47f5-838f-6d94285d7ef1.jpg)

**Device Info (please complete the following information):**
 - Device:  (Xiaomi) Poco X3 Pro
 - OS:   Android 12 / MIUI Global 13.0.3 (Stable)
 - Version:
  - Android: 12 SKQ1.211006.001
  - MIUI: 13.0.3.0 (SJUEUXM)
  - App: 3.6.3
 - Country: Germany

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
