### ISSUE TITLE
[BUG] : app deletes all my .lrc files in the main download directory

### ISSUE THREAD

**Issue by dhakkann** [Shabinder/SpotiFlyer#1981]
**Describe the bug:**
I use a third-party application to save lyrics(.lrc files) for offline listening; downloading any new track/album/playlist through Spotiflyer app, deletes my .lrc files, even for previously downloaded tracks/albums/playlists. The .lrc files are deleted after clicking on the Exit button in the notification. The .lrc files are renamed the way Spotiflyer renames its mp3 files, just with .lrc extension.

**Expected behavior**
The app should only interfere with .mp3 files, and leave user created files in Spotiflyer download directory as they are.

**Device Info (please complete the following information):**
 - Device:   Xiaomi POCO X4 Pro 5G (India)
 - OS:   Android 11
 - MIUI : 13.0.6 (Global)
 - Version:   RKQ1.211001.001
 - Country: India

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
