### ISSUE TITLE
[BUG] : <Issue_Title>

### ISSUE THREAD

**Issue by PAKALLata** [Shabinder/SpotiFlyer#1989]
![Screenshot_20221106-001914_Samsung Music](https://user-images.githubusercontent.com/117548247/200146457-450694db-9c46-40f8-8a92-5c78e6966bc5.jpg)
![Screenshot_20221106-001902_My Files](https://user-images.githubusercontent.com/117548247/200146471-84136950-0a96-4486-b235-a6a9653d3186.jpg)
When i download music from youtube,it save music to an album with the same image

**Describe the bug:**

**Media Links Used:** 

**Expected behavior**

**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   [e.g. iPhone6, Samsung J2, PocoF1]
 - OS:   [e.g. iOS, Android 10, WinOS, MacOS]
 - Version:   [e.g. 3.2.1]
 - Country: [eg: India, will help in detecting if service is accessible to u]

**Additional context:**

**Comment by Erictheplague** [comment]
Have you sent @Shabinder a token for appreciation to keep maintaining Spotiflyer?

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
