### ISSUE TITLE
[Feature-Request]: you are ruining the audio quality by converting downloads into mp3 format

### ISSUE THREAD

**Issue by mo-han** [Shabinder/SpotiFlyer#1995]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
download the tracks as is, if it's aac, save it as original aac, of it's opus, save it as original opus.
just please don't convert it to mp3!

**Describe alternatives you've considered**

**Additional context**

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
