### ISSUE TITLE
[BUG] : Error downloading from Spotify

### ISSUE THREAD

**Issue by theLadEli** [Shabinder/SpotiFlyer#1997]
### Describe the bug:
I tried downloading some music from a playlist from Spotify. I set the download folder, and made sure Spotify Credentials were filled in.
I first pasted in a playlist link and tried downloading all. When that failed, I tried one or two files individually, but kept on getting this error:
```
com.github.kokorin.jaffree.JaffreeException: Failed to start process.
	at com.github.kokorin.jaffree.process.ProcessHandler.execute(ProcessHandler.java:148)
	at com.github.kokorin.jaffree.ffmpeg.FFmpeg.execute(FFmpeg.java:400)
	at com.shabinder.common.core_components.media_converter.DesktopMediaConverter$convertAudioFile$2.invokeSuspend(DesktopMediaConverter.kt:34)
	at com.shabinder.common.core_
```

I also got a small notification on the bottom right corner of the program saying:
```
No FFmpeg found at path.
```

### Media Links Used:
Playlist - https://open.spotify.com/playlist/1tNAVWQpaIf25lS06brAcX?si=b01399a7def34588
I also tried some individual songs from that playlist.

### Expected behavior:
To download and save the music.

### Screenshots:
![image](https://user-images.githubusercontent.com/109231330/200271504-2ecbf4f7-a21d-4b1c-b3a0-c4deb41f58b7.png)
![image](https://user-images.githubusercontent.com/109231330/200270190-d5ee53b9-1a8c-4360-bc1b-aad7b9638c9f.png)

### Device Info:
 - Device:   Laptop (Asus Vivobook 15)
 - OS:   Windows 11
 - Version:   22H2 (OS Build 22621.674)
 - Country: London, United Kingdom

### Additional context:
I had a stable internet connection and was not using a VPN.

**Comment by mihin19** [comment]
For the **No FFmpeg found at path**  error did you put the ffmpeg.exe into the folder c:\program files\spotiflyer

**Comment by theLadEli** [comment]
No. Where do I find the file?

**Comment by dominic-salvador** [comment]
Solution can be found here: https://github.com/Shabinder/SpotiFlyer/issues/1729#issuecomment-1256069480
Just add to PATH the FFmpeg bin.

**Comment by theLadEli** [comment]
Awesome! Thanks so much, it works now.

If anyone else has an issue installing FFmpeg, I'd definitely recommend taking a look at this - https://www.youtube.com/watch?v=IECI72XEox0

**Comment by dominic-salvador** [comment]
I also wanted to add that on the Windows executable version, if you can't seem to save your songs like in the default Music Library. You can just change the download location to the root of your storage like C:\ OR make an exception in your antivirus.
I'm using the default windows 11 antivirus and it should look like this:

<img width="603" alt="image" src="https://user-images.githubusercontent.com/94506586/200543524-313a8073-f60d-46b3-97d7-bb2612f22571.png">
By making an exception, you can set the directory to the default library Music folder in windows. Hope it helps.

-ds

**Comment by theLadEli** [comment]
Awesome will save this for any future errors. Thanks so much!
