### ISSUE TITLE
[BUG] : <Issue_Title>

### ISSUE THREAD

**Issue by pedaodoscodigo** [Shabinder/SpotiFlyer#1999]
![png](https://user-images.githubusercontent.com/117699151/200457820-fdc2f7ab-26a7-45f7-a6fc-f966fe6a6d91.png)

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
