### ISSUE TITLE
Doesn't download or just crashes

### ISSUE THREAD

**Issue by Bwangster12** [Shabinder/SpotiFlyer#2]
Songs show as processing and show a spinning icon, but either don't finish or icon changes right to another download icon.  I've tried downloading albums and seem to only ever get 1 song.

Tried clearing data and cache, now app just keeps crashing.

**Comment by Shabinder** [comment]
Album section Crash bug has been brought to notice and will push an update soon fixing it.

**Comment by Bwangster12** [comment]
Individual songs don't download either.  I just tried selecting 1 songs and
the same thing happened, where it just shows processing and never downloads.

**Comment by Shabinder** [comment]
Hey, **New Update has been released** , Check it Out.
I am closing this issue for now , if you face any issue feel free to comment or open a new issue.👍
