### ISSUE TITLE
Crash issue

### ISSUE THREAD

**Issue by Troy0076** [Shabinder/SpotiFlyer#200]
The app is crashing whenever I open the app or when I try to download any song.

**Comment by Shabinder** [comment]
> The app is crashing whenever I open the app or when I try to download any song.

Please Provide few more details ...
On which Platform are you using it..?
Device Details, Os info etc ?

I have my server down for a few days hence I am no able to gather any crashlytics, however I will rolling out a new Update in a few days with far better Error Handling and more fixes... so you can wait for that or share crash logs from current app

**Comment by Troy0076** [comment]
It's crashing when downloading songs. Like I'm trying to download an entire playlist and after a few moments like downloading some songs it send a notification saying it crashed.I'm running it on android platformDevice: Samsung galaxy J7 prime.Android version: 8.1.0Sent from my Galaxy
-------- Original message --------From: Shabinder Singh ***@***.***> Date: 01/07/2021  7:14 pm  (GMT+06:00) To: Shabinder/SpotiFlyer ***@***.***> Cc: Troy0076 ***@***.***>, Author ***@***.***> Subject: Re: [Shabinder/SpotiFlyer] Crash issue (#200) 

The app is crashing whenever I open the app or when I try to download any song.

Please Provide few more details ...
On which Platform are you using it..?
Device Details, Os info etc ?
I have my server down for a few days hence I am no able to gather any crashlytics, however I will rolling out a new Update in a few days with far better Error Handling and more fixes... so you can wait for that or share crash logs from current app

**Comment by Shabinder** [comment]
Try Out v3.2.0 it should fix some bugs and if there is any share the crash report which is viewable in app

https://github.com/Shabinder/SpotiFlyer/releases/tag/3.2.0

If issue persists kindly create a new issue for that
