### ISSUE TITLE
[BUG] : Song limit problem

### ISSUE THREAD

**Issue by WeirdMetalhead** [Shabinder/SpotiFlyer#2000]
So, I'm having no problems with spotiflyer so far. On the contrary, it's the best app for downloading music in top quality and it's free, so that's a plus. But recently, I discovered that particular songs I've downloaded that are more than 7 minutes long, cannot be played whole when I'm listening to them. E.g, black metal songs that are usually more than 8 minutes long, will play till the 7th minute and then will be cut off and skip to the next song. I have no idea if that's how it's supposed to act since it's long but I'd appreciate it if I found a solution for that. Thank you!

Device Info
 - Device:   RealMi7i
 - OS:   Android
 - Version:   3.6.3

**Comment by EtherSecAgent** [comment]
Seems like this software doesn't like downloading items that a larger than 5 mins, just errors out

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
