### ISSUE TITLE
The audio quality is set for 320kbps, but the audio is only on 128 kbps

### ISSUE THREAD

**Issue by emanghilit** [Shabinder/SpotiFlyer#2004]
![image](https://user-images.githubusercontent.com/109598414/200574104-4639046f-72f5-48ae-b015-30ce9d80e8b8.png)

![image](https://user-images.githubusercontent.com/109598414/200574356-eb07b9ec-aa78-46c3-ae98-d4f5e89c5381.png)

**Comment by SpaceNATO** [comment]
The same is happening to me, I've installed ffmpeg following this guide. [https://phoenixnap.com/kb/ffmpeg-windows](url)

**Comment by maravento** [comment]
> The same is happening to me, I've installed ffmpeg following this guide. [https://phoenixnap.com/kb/ffmpeg-windows](url)

the problem persists after doing the procedure and the music downloads at 128kbps

**Comment by vehosah** [comment]
> The same is happening to me, I've installed ffmpeg following this guide. [https://phoenixnap.com/kb/ffmpeg-windows](url)

This link leads to nowhere

**Comment by bverkron** [comment]
Same problem for me.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
