### ISSUE TITLE
[BUG] : Wrong song

### ISSUE THREAD

**Issue by swordapi** [Shabinder/SpotiFlyer#2005]
The template is unnecessary. So when I download a song or a playlist from Spotify its sometimes downloads like not the original version and this is really annoying. Like it downloads covers of the song or a other version of the song.
Please fix fast.

**Comment by iamflorencejay** [comment]
Same that's happened to me ever since I've use it

**Comment by d4f5409d** [comment]
I guess this is because the Spotify is only there to identify the song and it pulls the songs you download from YT and YT Music. Thiss happened to me with Nuclear Music Player too. Better than nothing 🤷‍♂️

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
