### ISSUE TITLE
[BUG] : Album tracks with same title not downloading

### ISSUE THREAD

**Issue by s3ned** [Shabinder/SpotiFlyer#2006]
**Describe the bug:**
All tracks that has been downloaded in a different album are not downloaded again. Even though they are different versions with different track durations an album title

**Media Links Used:** 
[](https://open.spotify.com/album/2UJcKiJxNryhL050F5Z1Fk)

**Expected behavior**
All songs in an album to be downloaded and not referred to from a database based solely on track title

**Screenshots:**

![missing tracks](https://user-images.githubusercontent.com/5307767/200921039-d5eb252c-38aa-4ed7-a661-1d775fc8a828.png)

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   [laptop]
 - OS:   [windows]
 - Version:   [10]
 - Country: [netherlands]

**Additional context:**

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
