### ISSUE TITLE
[BUG] : <Issue_Title>

### ISSUE THREAD

**Issue by Plumpinator** [Shabinder/SpotiFlyer#2010]
**Describe the bug:**
 Song won't download 

**Media Links Used:** 

https://open.spotify.com/track/2CgOd0Lj5MuvOqzqdaAXtS?si=YrFiHZwiRJSjF3PSum2HLQ&utm_source=copy-link
**Expected behavior**

The song should download instead of failing
**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   [e.g. iPhone6, Samsung J2, PocoF1]
 - OS:   [e.g. iOS, Android 10, WinOS, MacOS]
 - Version:   [e.g. 3.2.1]
 - Country: [eg: India, will help in detecting if service is accessible to u]

**Additional context:**

**Comment by Plumpinator** [comment]
Device is a 2018 samsung j3

**Comment by Plumpinator** [comment]
Only this song didn't work

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
