### ISSUE TITLE
[Feature-Request]: <option to download music on sd card>

### ISSUE THREAD

**Issue by PraveenKumarpkm** [Shabinder/SpotiFlyer#2012]
**Is your feature request related to a problem? Please describe.**
Yes, I want to save all songs in the memory card but your app doesn't let me. It only gives me phone storage option.

**Describe the solution you'd like**
Please add a option for saving in sd card

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
