### ISSUE TITLE
Issue with spotify tracks and youtube thumbnails

### ISSUE THREAD

**Issue by swarnimpandit694** [Shabinder/SpotiFlyer#2014]
Bug: 
Dosent download the track which is expected to be downloaded....instead downloads something different
 
Actual track : 
![Screenshot_20221113-080654_Spotify](https://user-images.githubusercontent.com/97526858/201502942-e435ec3f-8fbf-4df3-8cfc-0c50a86996c8.jpg)

And the downloaded track 
![Screenshot_20221113-080745_Oto Music](https://user-images.githubusercontent.com/97526858/201502953-add3b580-07ef-4ae2-afd1-d64472a16c12.jpg)

There the actual track is a song...but when i download it...it is just some musical or instrumental 

Device 
Samsung galaxy F23-5G
With android 12 
Country india 

The track download from youtube music also shows different thumbnails
Original:
![Screenshot_20221113-081210_YouTube Music](https://user-images.githubusercontent.com/97526858/201503045-7d282046-38e8-47dc-9cbf-fc040b7a1f47.jpg)
Downloaded:
![Screenshot_20221113-081149_Oto Music](https://user-images.githubusercontent.com/97526858/201503057-ea520512-4c79-4ee3-a9ee-fde529848522.jpg)

Thnaks for reading i hope you will fix it soon....and thank you for your work ...I helps me a lot

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
