### ISSUE TITLE
[Feature-Request]: Podcasts

### ISSUE THREAD

**Issue by asdfmonster261** [Shabinder/SpotiFlyer#2015]
Some podcasts, like JRE, don't have widevine on them. You can download them like this:

Basic overview is download init.webm for both audio and video, and then all the segments, then concatenate them with ffmpeg.

You can find them in the network tab in the web player, the segments the same way. Examples of the init.webm 
`https://video-akpcw-cdn-spotify-com.akamaized.net/segments/v1/origins/***/sources/***/encodings/***/profiles/23/inits/webm?token=<token info>`

`https://video-akpcw-cdn-spotify-com.akamaized.net/segments/v1/origins/***/sources/***/encodings/***/profiles/19/inits/webm?token=<token info>`

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
