### ISSUE TITLE
Flexibilty of memory 

### ISSUE THREAD

**Issue by Divyanshigarg** [Shabinder/SpotiFlyer#2020]
Give the flexibility for user to select between 128 kbps and 360kbps music. It will help save memory. 
Considering it doesn't allow the user to select the music quality beforedownloading.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
