### ISSUE TITLE
[BUG] : Spotiflyer cannot write on SD Card even though it has access to it.

### ISSUE THREAD

**Issue by kwan-vini** [Shabinder/SpotiFlyer#2022]
I'm using Spotiflyer 3.6.3 on Android 7.1.2. Brazilian.

When i try to change the path directory to my SD Card, it can't, even though it has access to it.

It displays a toast message saying:

NO WRITE ACCESS in: (directory path) , Reverting back to previous.

While the devs are rewriting the code, i guess i'll just put this here so they are aware of this bug.

**Comment by Shabinder** [comment]
refer #116

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
