### ISSUE TITLE
Spotiflyer downloads the wrong song; blurry album art

### ISSUE THREAD

**Issue by lolSteeeeve** [Shabinder/SpotiFlyer#203]
``
Often doesnt download the song that i expected to get (eg: I wanted the original one, downloaded the remix version. )
``

**__Suggestions:__**

``
The cover album is blurry. I know it happened on older versions of Spotiflyer but Is there any way or any possibility for the program to get the hq images?
``

**Comment by Shabinder** [comment]
We get best optimal cover art maybe in future there will be more hq sources but not as of now
