### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by vishal1896** [Shabinder/SpotiFlyer#2031]
**Describe the bug:** download failing and providing error

**Media Links Used:** 

https://open.spotify.com/playlist/2lN5ZUTEiqhqItTYeeVEL8?si=605dd77e397d488b

**Expected behavior**

**Screenshots:**

![image](https://user-images.githubusercontent.com/67838032/202610847-0b143adc-9f45-4c99-b34e-c17de6a211d7.png)

**StackTrace:**
```
com.github.kokorin.jaffree.JaffreeException: Failed to start process.
	at com.github.kokorin.jaffree.process.ProcessHandler.execute(ProcessHandler.java:148)
	at com.github.kokorin.jaffree.ffmpeg.FFmpeg.execute(FFmpeg.java:400)
	at com.shabinder.common.core_co
```

**Device Info (please complete the following information):**
 - Device:   MSI GF63
 - OS:   WinOS
 - Version:  11
 - Country: India

**Additional context:**

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
