### ISSUE TITLE
[BUG] : <Issue_Title> issue downloading some songs, Spotify 

### ISSUE THREAD

**Issue by grgryforsythe** [Shabinder/SpotiFlyer#2032]
**Describe the bug:**

**Media Links Used:** 

**Expected behavior**

**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   [e.g. iPhone6, Samsung J2, PocoF1]
 - OS:   [e.g. iOS, Android 10, WinOS, MacOS]
 - Version:   [e.g. 3.2.1]
 - Country: [eg: India, will help in detecting if service is accessible to u]

**Additional context:**

**Comment by grgryforsythe** [comment]
![Screenshot_20221117-224105](https://user-images.githubusercontent.com/61732182/202612318-93c58822-9fe4-4617-86cb-2848689a5da7.png)
Moto edge 2021, android 12, USA
Some songs it won't let you download and some will download, Spotify

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
