### ISSUE TITLE
[Feature-Request]: <More donating options>

### ISSUE THREAD

**Issue by d4f5409d** [Shabinder/SpotiFlyer#2048]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I would like to get more places where I can donate to support Spotiflyer's development (Liberapay, Kofi, Monero, etc.)

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by Shabinder** [comment]
Kofi is there, OpenCollective is there.
will look into others.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.

**Comment by d4f5409d** [comment]
Sad to hear that, but thanks for letting me know!
