### ISSUE TITLE
Spotify account suspended 

### ISSUE THREAD

**Issue by MihaiNecreala** [Shabinder/SpotiFlyer#2050]
Hi there,

I got suspended fron Spotify, after using this app.  There's any issues related to multiple accounts on the same device, because i see that the application itself it's using some credentials... I have made a reset of Spotify credentials, yesterday, and today i got this surprise.

Anyone got this issue?

Thanks.

**Comment by Shabinder** [comment]
Strange, were you using your own creds in spotiflyer.

**Comment by MihaiNecreala** [comment]
> Strange, were you using your own creds in spotiflyer.

Not sure, but after resetting spotiflyer creds, and passing several hours, i got an email from Spotify, noticed me that my account was suspended, because of suspicious activity.

This needs to be investigated. Thanks.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
