### ISSUE TITLE
[BUG] : MacOS [MVIKotlin]: Main thread id is undefined, main thread assert is disabled

### ISSUE THREAD

**Issue by lkvapil** [Shabinder/SpotiFlyer#2068]
java -version

java version "19.0.1" 2022-10-18
Java(TM) SE Runtime Environment (build 19.0.1+10-21)
Java HotSpot(TM) 64-Bit Server VM (build 19.0.1+10-21, mixed mode, sharing)

Debug: (Kermit) System Time:1669540408 , Token Expiry:1669499110
Debug: (Kermit) Requesting New Token
[MVIKotlin]: Main thread id is undefined, main thread assert is disabled
Debug: (Kermit) Spotify Provider Created with TokenData(access_token=BQDPYJKj4rbZvR9ULl936L8vuZrKVxM2R5TKNJUjp2W3Xd8uTTNzEDcTivWfBn5DV_wmjXiTJ-scqNrTh7T4dH9XRbOdnWp3gTCXIc44quSqA1fRTA8, token_type=Bearer, expiry=3600)

 - Device:   MacBook Pro M1, 2020
 - OS:   MacOS Monterey
 - Version:   12.2.1
 - Country: Europe

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
