### ISSUE TITLE
Can't download any song

### ISSUE THREAD

**Issue by Varibily** [Shabinder/SpotiFlyer#207]
With last apk updated cant download from youtube or spotify.

**Comment by Varibily** [comment]
Total : 2 Completed:0 Failed:2

**Comment by hb-scope** [comment]
Same. 313 songs, 310 failed. 3 others were probably already downloaded.

**Comment by Varibily** [comment]
Any solution?

**Comment by FabiusFr** [comment]
Same issues guys 😩
Congrats for ur work

**Comment by kh9deir** [comment]
@Shabinder

**Comment by adilson-pereira** [comment]
Same here

**Comment by Shabinder** [comment]
Hi Guys, I am out of station for a few days, will fix it as soon as Possible

**Comment by FabiusFr** [comment]
Thanks 👍

Le mer. 7 juil. 2021 à 07:51, Shabinder Singh ***@***.***> a
écrit :

**Comment by Shabinder** [comment]
@FabiusFr @hb-scope @adilson-pereira @kh9deir @Varibily Fixed in v3.2.0 https://github.com/Shabinder/SpotiFlyer/releases/tag/3.2.0
