### ISSUE TITLE
[BUG] : downloaded a different song to the one requested

### ISSUE THREAD

**Issue by ghostingaround** [Shabinder/SpotiFlyer#2071]
**Describe the bug:**
Downloaded a song i don't know instead of the songs requested, it did that for two different songs, i tried to download them again but i got the same result each times

**Media Links Used:** 
https://open.spotify.com/track/1DIjA9FCbvjusX71PyBWac?si=g5CwE8-lRxu_dPD5AQotlg&utm_source=copy-link
https://open.spotify.com/track/1VG2DlO7uEMSmzTcYRb8og?si=32OeRfIuS6aLPFrOuzLXnw&utm_source=copy-link

**Device Info:**
 - Device:   sony xperia 10 mark 3
 - OS:   android 11
 - Version:   3.6.3
 - Country: France

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
