### ISSUE TITLE
keeps closing on laptop

### ISSUE THREAD

**Issue by vegtarot** [Shabinder/SpotiFlyer#2076]
I am using the windows version of spotiflyer and it keeps closing I have tried using spotify and YouTube music but it just closes could anyone help me

**Comment by JaaiDead** [comment]
how to reproduce?

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
