### ISSUE TITLE
[Feature-Request]: A popup where it says you already downloaded the music and it gives you the option to not include it downloading again.

### ISSUE THREAD

**Issue by Gusion77** [Shabinder/SpotiFlyer#2083]
I don't know if this exist yet but it should since there's no point in downloading the same music again if you already have it.

And if it does exist, I tried downloading the same music just to confirm but there's no warning or a message saying I already have it. Downloading the same music is only wasting time like for example when downloading a playlist it would really help. Thank you and I hope you implement this.

**Comment by Shabinder** [comment]
Its implemented if you download from same playlist or so.
when searching the track individually, it wont show as downloaded.

will be tackling this in re-write I am working on.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
