### ISSUE TITLE
Unknown issue

### ISSUE THREAD

**Issue by Alex-Shelega** [Shabinder/SpotiFlyer#2089]
I wanted to download some album from Spotify and I couldn't then I find out I can't do it nohow...

Here's the code the app suggested to copy:
" DownloadLinkFetchFailed(errorTrace=Find Link for  - Distant Worlds III -> VideoID:ZF7-JqMM21A

Yt1sMp3 Failed for ZF7-JqMM21A:io.ktor.client.features.ServerResponseException: Server error(https://yt1s.com/api/ajaxSearch/index: 503 Service Temporarily Unavailable. Text: "<!DOCTYPE html>
<html lang="en-US">
<head>
    <title>Just a moment...</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="robots" content="noindex,nofollow">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="/cdn-cgi/styles/challenges.css" rel="stylesheet">
    <meta http-equiv="refresh" content="35">

</head>
<body class="no-js">
    <div class="main-wrapper" role="main">
    <div class="main-content">
        <h1 class="zone-name-title h1">
            <img class="heading-favicon" src="/favicon.ico"
                 onerror="this.onerror=null;this.parentNode.removeChild(this)">
            yt1s.com
        </h1>
        <h2 class="h2" id="challenge-running">
            Checking if the site connection is secure
        </h2>
        <noscript>
            <div id="challenge-error-title">
                <div class="h2">
                    <span class="icon-wrapper">
                        <div class="heading-icon warning-icon"></div>
                    </span>
                    <span id="challenge-error-text">
                        Enable JavaScript and cookies to continue
                    </span>
                </div>
            </div>
        </noscript>
        <div id="trk_jschal_js" style="display:none;background-image:url('/cdn-cgi/images/trace/jsch/nojs/transparent.gif?ray=772557cee9857599')"></div>
        <div id="challenge-body-text" class="core-msg spacer">
            yt1s.com needs to review the security of your connection before proceeding.
        </div>
        <form id="challenge-form" action="/api/ajaxSearch/index?__cf_chl_f_tk=W8M5YsvdAoYZIJ4SEuC9DvX.1L2ZdKqTunJEjK38C8s-1669829762-0-gaNycGzNB70" method="POST" enctype="application/x-www-form-urlencoded">
            <input type="hidden" name="md" value="EN023QqI5LEaVinurOMLQC9847D.9.kZdcgR41nkNJA-1669829762-0-AdNlqLYlYRV-pwwtVb5B1kfdcLsjY8GUhVnWJjdOrMB97z4Izw_Ua4j8TlhmtTjA-4LaXRIng8ITMsPqeeJiry6m63cSSTtwwsxusbAvMDb9Ano1xTqkMX9b4Vhy4Az-7TlyvDTV7EUa9_dbThF4ptVuN9edeRTfUv6N_FJB0ALleKuCtyH68Z996hv7waTbjrc3B3o6i0g8ixZWNrP5ERvF0f5JkLQAx7qQv8I0n0l3y4tPo6j7zG1oyNFi5WdawifEh36l-OriMv4gqPdKBp4SY5GxfECUbxKuEqdidMl8HiKVG16eqKczf90APjDqs6TLsubKSzVqKGfbLgqB02mLRrNzH2kkjabSMas6WWl9tTvNQxJQbaE63awRiebKRWNKnY4d2pANGyp-4QsJ6riGB45uxsvruLA71PanBEh6uB6nsz50_Tr2ClENMY2RRFfGIRQAI9mBwp2UsAKVMzjbpW-EZ1YnfRdiPyLa5rIDpmZWHCZ16iXdB4Oy6a0OUJZKmfZIbBu1FLC5xBb6j8YLDXuY--VVTg0GOXy2qWgsbr7QvAUp9Mu3AJUXD4VHPLYGcfSRq2MyUM6qrcRIODw2jALnX6l9ejSik9mCv5hrMA1WwsDIdJ6lHXLN2Nwrbw">
            <input type="hidden" name="r" value="o8xjjLogGipExztCjFo6c.bNsoQoTXyuPjUZtD7D_U4-1669829762-0-AWwg9D0Vnovxot40EHpKjLtqF4uEaPr4XgR5Ci5zlUb3uSoDicQpLqjSVW9+WYX44GXsw50ySziki74+P7SFBVWeXq8b+wZTon4vjKSiiF0jTjmM+lI2IOAI2XwD7hpt2XsZorsO84vxZQzO0k2YlHssfXBqHBcxnpMVOwy9kD/2A+OFAWTaXLuIZLd/dmoLqofbMyPXWDsYfIrDG1vEQLjfnidCP1BrhSMMRGs4ya4gbcEzvPF5SGcDRtotpiUJUu3IoZwTv46Y1jNSjgjk2owyRNloF1qL+cgCEOsg4+raBXvnpKXawM5SqUqidxPAi4dZcoOo7Z1eJMNw/Kam6vmQOuGQJd+7/ApsJtGf3zLRq0fuxVw62tfsjPZbyvxohmVlOxQ48bwU/DSdwFxaAp53I81tuoj50c+P2glcRRuJfSfHQhgJvry1J5r9hltGDlRLFPhIrw+mY+UOPECKc0cos5eV8gzXUk9OdEhDmpKNgNFYZc/+Jpkhl/cSRJznz0lfNZAFFi+EibTF8ZAPdRym/2ZA5flOWu5ZeKgnT9wYENtar8FcDi8wxTgCgMhmsp74hmWwdE0CU/i6RtxSVAYsMmhK8WcfCgDjTLAp+iPfwHJcDYSy19Z2IYgph2fKm2NFEIGKzaqwNXMSQzxk9ck1MR+wNwe5FDafovq6GGr9fHdIcwZFPyjoLiHMJtU/y9moVdZT0PB86gprcIqOO7tIDo34JpOlH1XnQM7OZbhgUBPpOpJIZ68ciWlRs4hNaYG8Cfj/bReFQGymLJZ3eeK0kO2xNRlehiaLnchjaEOuaW8deD7YhB/23ufiAjdBJtIhiwscJQ8SPT5gMv9VtiUSPSIx+9p3RrY7C0e8STDVzK/rFzN6uoqMBPT/X41QMC6fpHM4yEKQaFbHB5b3wYJn2w5Rs5mwdo7Cpda/giOjjBSsTMjWBoNMleequwYxtRTEFTeHoKSdAkipYOpZtjXSRz8n+fMwFtdxPx8mSZT6roYdZT0PHNuO6W16fwW/dkJu1AWe1O8khKc0d2/TAujjAzPfUa14rsFiOqLctVFfKOHylHsQc2q6V0gNZdvNE+x5fmEnhT/8El/lCVll3tDhPEjfS+1yTFv7eIbWHg+9Dte+OiW9WeBzzkiujyJNjbO7nTTq7VvrR23QeQ5Qae8JBm7RpVtI76Qa8xr3GuSDkdDob1mNgS0FkVO04WgWj/FxbYH3QE04JASw8rSQzu5fhCJuaJeKsDq7QQQefnuwc5mzhw6tAekvnkTjtzBriMftylF+8h5Tm+pAMpzpsJ4TOCNep8UgK7jiOgZHvssu6xHz91SYRMjjWGEdlIRXJJIiVj5FfxeSLDcw38GLcQmJaLQYV1QQCuW3PVfZa/W30mWWvJbiZi/A6P1dsbfQIgPutFzKj0U1rvh+z8bw88DfHNtQFX8N4m/zpeY+pVx++AszHOUNVGn3jdKXraDttt0TtXTtHcm70qfCC+x40BUP5Y1OAN/xVz6RlHSVtM9ELmyVLKVRbudJd73+YXkGAvzEp03j13HAnQdsCSrD1r9gHK7jGWDWClwoD5XJnoeo2AsR7nVjVe12Q2FO1f/GTHtZdCYT2cYUARcZjlGjjJUOJLuQZPcSkiZpgD2dHWPENjrZEWxoFB27KV79YNW/ITM5lvdcn6qH2bD+885w4dIDr+Bj5HWIfOYba3n8fhu042nskarFd4XilNNRvmMvdoCdVQhh17V7PYG0mhXX1+Oicinj+JZO+pgHRZulCUfg5uFGi839nEmhwz1nbZGgxY3G3Pk8CaoDbbckkWPZpOR4fq+tf2SUTCsupXcBzL/s+83N+Y21p5FXCHUqxk5lQ7lINwxtNAog2Y0+6aq9yoZBDDH4r66f768OVbz2ZlkcQzEGvod+ek36dl0kAB9N7g==">
        </form>
    </div>
</div>
<script>
    (function(){
        window._cf_chl_opt={
            cvId: '2',
            cType: 'non-interactive',
            cNounce: '61951',
            cRay: '772557cee9857599',
            cHash: '2f23ebd57be07b5',
            cUPMDTk: "\/api\/ajaxSearch\/index?__cf_chl_tk=W8M5YsvdAoYZIJ4SEuC9DvX.1L2ZdKqTunJEjK38C8s-1669829762-0-gaNycGzNB70",
            cFPWv: 'b',
            cTTimeMs: '1000',
            cTplV: 4,
            cTplB: 'cf',
            cRq: {
                ru: 'aHR0cHM6Ly95dDFzLmNvbS9hcGkvYWpheFNlYXJjaC9pbmRleA==',
                ra: 'S3RvciBjbGllbnQ=',
                rm: 'UE9TVA==',
                d: '1u9BMu/ouSe/7/O7olfOzs3oUnrJr7EWD+bl3wnuBtnjO6jjwpLRje+wPH+Xhf+h5supTNVJrxKZIs+FAr1A4t96AdHgHoymNHs+bD4IVup9ZiPOrr/C9I5it7dUwQo0QGMG1o0dq9KqSVww49opjHiTwji+GL2DUAWBOFZd4ofZHVmw6F7rgaSlu/XXFK8yJ8hVkdTiD0NNuEbPvM0BWIitlkCYtKOwjkOZZJiZJigF2wOQy8MeqVTwYmVyENy6RWOFm4NxElH0/2bh09K59ydiHZDCcteY0K6G1te7swRi005zSLAI0GPEBRuQy4fi4t7OvvprWLIQAYHzzFfJmT0fzsLs3Axuy0IwgTcNwNYJjg24w05bAI9QbWVqu9f6TkmDZ16LkNb/o6//q/NohcqnStC6yDJABBTeEKVL+mjo5PFcCD6axP/mAr/Y7dJ/6yDYfJd3Hs3QcPKjWFEuoNht1Jcm7egbZhRue7dfNKpyKyw3zxfcn47lNFBP84wLCDUnUDK+Kd7JftrbsV3Rm2wS2WjfNLursnSi/xjDW48rSJPUAPpP9YhByrYCdIBa7obVo9yfFpblQr3F+UP5Qw==',
                t: 'MTY2OTgyOTc2Mi40MTIwMDA=',
                m: 'khkuewWYpICgtfImiwukm6td6Q6BoLpWRwPRhe70gzU=',
                i1: 'ojybar897Ljcf+IpaBpesQ==',
                i2: 'gpfiGgc/m7azeZlj2oDqOg==',
                zh: 'slbOGnEscRNxFiOnTsX0AKh1TuDl2qbz+DoFMtxCWD8=',
                uh: 'oz7OrxkrnxacOh3btzIq4iwAY0NK/hCkZ0LN2B2nTlI=',
                hh: 'LBSS74KkcrNPPaDUVSmWQv8ZxJLhGAngcURUX8gX1AQ=',
            }
        };
        var trkjs = document.createElement('img');
        trkjs.setAttribute('src', '/cdn-cgi/images/trace/jsch/js/transparent.gif?ray=772557cee9857599');
        trkjs.setAttribute('style', 'display: none');
        document.body.appendChild(trkjs);
        var cpo = document.createElement('script');
        cpo.src = '/cdn-cgi/challenge-platform/h/b/orchestrate/jsch/v1?ray=772557cee9857599';
        window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;
        window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, -window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;
        if (window.history && window.history.replaceState) {
            var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;
            history.replaceState(null, null, "\/api\/ajaxSearch\/index?__cf_chl_rt_tk=W8M5YsvdAoYZIJ4SEuC9DvX.1L2ZdKqTunJEjK38C8s-1669829762-0-gaNycGzNB70" + window._cf_chl_opt.cOgUHash);
            cpo.onload = function() {
                history.replaceState(null, null, ogU);
            };
        }
        document.getElementsByTagName('head')[0].appendChild(cpo);
    }());
</script>

    <div class="footer" role="contentinfo">
        <div class="footer-inner">
            <div class="clearfix diagnostic-wrapper">
                <div class="ray-id">Ray ID: <code>772557cee9857599</code></div>
            </div>
            <div class="text-center">Performance &amp; security by <a rel="noopener noreferrer" href="https://www.cloudflare.com?utm_source=challenge&utm_campaign=j" target="_blank">Cloudflare</a></div>
        </div>
    </div>
</body>
</html>
"
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:15)
	at q7.a.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)

Trying Local Extraction

Fetching From Saavn Failed:DownloadLinkFetchFailed(errorTrace=No SAAVN Match Found for  - Distant Worlds III)
	at com.shabinder.common.providers.saavn.requests.JioSaavnRequests$DefaultImpls.findBestSongDownloadURL(JioSaavnRequests.kt:19)
	at com.shabinder.common.providers.saavn.requests.JioSaavnRequests$findBestSongDownloadURL$1.invokeSuspend(Unknown Source:10)
	at q7.a.resumeWith(ContinuationImpl.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)

Fetching From YT-Music Failed:io.ktor.client.features.ServerResponseException: Server error(https://yt1s.com/api/ajaxSearch/index: 503 Service Temporarily Unavailable. Text: "<!DOCTYPE html>
<html lang="en-US">
<head>
    <title>Just a moment...</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="robots" content="noindex,nofollow">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="/cdn-cgi/styles/challenges.css" rel="stylesheet">
    <meta http-equiv="refresh" content="35">

</head>
<body class="no-js">
    <div class="main-wrapper" role="main">
    <div class="main-content">
        <h1 class="zone-name-title h1">
            <img class="heading-favicon" src="/favicon.ico"
                 onerror="this.onerror=null;this.parentNode.removeChild(this)">
            yt1s.com
        </h1>
        <h2 class="h2" id="challenge-running">
            Checking if the site connection is secure
        </h2>
        <noscript>
            <div id="challenge-error-title">
                <div class="h2">
                    <span class="icon-wrapper">
                        <div class="heading-icon warning-icon"></div>
                    </span>
                    <span id="challenge-error-text">
                        Enable JavaScript and cookies to continue
                    </span>
                </div>
            </div>
        </noscript>
        <div id="trk_jschal_js" style="display:none;background-image:url('/cdn-cgi/images/trace/jsch/nojs/transparent.gif?ray=772557f8ac5b7797')"></div>
        <div id="challenge-body-text" class="core-msg spacer">
            yt1s.com needs to review the security of your connection before proceeding.
        </div>
        <form id="challenge-form" action="/api/ajaxSearch/index?__cf_chl_f_tk=bmuK849pd5jw4CuPy5Y.BxCXOM7E5YIvegTLDVYbwSc-1669829769-0-gaNycGzNB9E" method="POST" enctype="application/x-www-form-urlencoded">
            <input type="hidden" name="md" value="wcVWWWL.VJuKC6MraV__g1NNu01fSkMdcvI1xXQjV.M-1669829769-0-Af9OkUXGAgKOt8mz5_OM9LKJkoaUHRYzAbFCXSYnZYDpy8JOPRPXOzzp5rcN4kauZWIOcZLC5JAqMGyIEbXI8TwAxPPWxmgl6pbyP6eGUnWbL60sVL1tIs31qrhwPgr07oLE7ikYAgKbep7hWL7sKLMgTGjcFJHKZSBhFuK_wzgKCj7brB4Fkb_nelpn41OyJP4akUP9XZrnrvq14Wlc5cXdNgMrV1Q9NgiuqMo1sfma6nIxgMJ1weAO11CW8xzl4WW_Foz_XZo3-Mi7sUh3WYqz-EcO-ZDtcVFWVXnZJPvqkrq4OncUW2ktn660au8Ydd_zvNG86Fx12YhX0zsBAjo4UesUfq5KWzcfAGkLe3Z-lwzZlQpouwbMi8YzkXUAWMjZ3ejZEMmLvxNhlgMa2M8O6W6DQ9BkcA1NSTIEeA4pWIsDtZjUX7h3a6zZZT7YdnXzMIkNSBrV12paNA_fWn4mWhjDsAr-JLjaShzeuVu2eKhUA0Lw9hYhaBVtDjt99eW_vDgWguTqFU6u1ZNkxiSIxLBqpjCZrYbwzJkqyqGUF6pEgZnbaP2gWQPKO6RLxQgQYovYkK9Ev_Oy8S8PQW3P2HcfPtbin_hTu4VID2CMcPiXgp77ITxa9h4AXc1lSA">
            <input type="hidden" name="r" value="YN5wapeLNUk_FxVAIyPUMRawuPO3gQdCgoF08_MU3aI-1669829769-0-ATIaaz526kU8FykFA4qVIoyGT6Yw9BUEed1zBPHbpsqGR//LWCQiaM+yqwQ/9ExC1vIQK9KVu1EttAq2klAO29KHP1EuWnIcv8eNCC1RPpFdfaZ+qpAVCq91nsHeBvGuFhiCR7Ku4Sw3O+TBNDE3dx/IoUWQrn1VNOdt98IDfdGqIbviVk1ux3bDXMSImB5YTUXYfDlW979omEpHy0xZdte6LT7Y5MX3EsULI4ohVewc3R55OvZgLSv4l5yyJYb+QP0dVBFTKjd8MzU6M/EPxiIIDB2gr1g+m5ShubsE0iuPr1MdiFW05s8UuESzOIni00T9lkcQSoH6sAj4n62tIHfLzdOnKaWaq1Rc5J7y2w79OZ/fzWogzvZGLiY8FmpLDnStVMk3fs1aj3rGP2LSbGRhL/j66SM+C1EQZNI91oXLAZ+q0qVgYP4S8IlL61IxBZXGEUeIiiS6VPKUzgUKmKSlt+52j7ZISB/q+trNHrJv4tJetOMGUT9iML4j3slts+5jdxp/pAwE8ddiU24kKsatE154Sj3zgBIsCqQFUOLEBJLNAyHSB/BytF1WaLrRshEuxkI2/OPZcsdMpyZ/NlCAa9eEvoZstbQfearb3XKziq0oDJpxGk2AmDJA2ia+c0KFSFcpPEjoc+opPGB8Hiki/sSScq98RjNpzxJhLsvkbf3QHG4yKYgPbkZXekSDWrkicelSUYHdnxQkkIUL7eEU2gc1U8KaSMpAlyh3wpBtfE+PtIxZNSKbiM9MMNm79AzqqnRQnI7e5Nx8nFUzRStsPbuDm7GNqM+DO3nzz7z6pDn394eLzwPyD87S5JpSGWjs2WJZxeUS1TnfJIXMej7BBL5uUvTYVgjYNyWuvBnZAsE+UNvVOLNT0nozRSWIcFzH/ioZq/zhHSyy/w0hTG7uNceZscDdOY0YpNoL73uQmgPZFVZVvIbiHeh244NgeLKdOEBSOg3g+EOO6iq6AZrAQNa3o4qYA1ANpdhYdodicLg2xsuA4Z/rAsKpaUCYMcJDKj6xhpMDBGROo0wlOgBAA//QW0oWgBvsdkA0RVIJqbdn4ZXTtaa+BMVcNE87ZD31Qh6T/NlYfS4/AHwoaCQhk+tQIfUv+ikqEiTrF4dln3TU/db1H1RfcVJNLL+7cpXRe5pgEvCh7pLegBAitNZbY1x246Zlj95PcDOj89JKBgmDpSiTpAABKTf7xEe5/ynzo+nmVTgq8PDIOSi5XuFNCv6SwA8bw3sS5hjSqx+3bPjvjDKfEwYU9m5tIsn4adSjGX+SetA5FC2lAK5CME1zTx/ThSQD0fHDHw+JPe6LUwIqyfE+bZI9e4KoPAdfYAq+FxZjTl7fYyh6uTUiZJEQ7CovOkhfnmrhAt4dN9up4XYghEjRdJo/QQv4efOLZ8kBMqxVLif6wx1yO31JhtJ20MvLUdM8XmpULcGfIJyiZmLubZA0oCx0RtNyVmZFGjVUBRIuKl+789LdDggR19BrAFWJFdh/lHKo6fHZCNpVlasJzINyGlnGYnYrwYaBP7McfQyvtI72M+fr7WJJHXODyze+QE/nahsLGlZDX6HqaUg9z9td0JqNX8s8SQ4tNAfrVxKv6nlZseQPCL/FaT+DbblgBG/uqGNIXaB9ROxpAu2YbGE3dMxlH7f9p5fyP3qK70N8dxHIpVIuF75RkLfONaTFJc01ZAvqphmiogrDlF7+r53NX1x99KvxPvjyXv2FJqDtc60VmXst2IAgYuVxpZ/ZssBTgW8krfUg+4VoHjM4oSNTwaqsaHUguStjnUmZbhCjmeXcslO4mAMLL7G0hE2EswM6wfAc5hXMMZ1ZVXTcEHD33qOxGrWhy7ZgPEfTpP+o4Rd8zdK4I30k2Me5Xr2mpvQo6bn/FcV62vOKc7+2I2T/C7OWaxwbV0St4pW/G+0mZ6vvmrGU5mJTVS8=">
        </form>
    </div>
</div>
<script>
    (function(){
        window._cf_chl_opt={
            cvId: '2',
            cType: 'non-interactive',
            cNounce: '85679',
            cRay: '772557f8ac5b7797',
            cHash: '8e690ec3e923545',
            cUPMDTk: "\/api\/ajaxSearch\/index?__cf_chl_tk=bmuK849pd5jw4CuPy5Y.BxCXOM7E5YIvegTLDVYbwSc-1669829769-0-gaNycGzNB9E",
            cFPWv: 'b',
            cTTimeMs: '1000',
            cTplV: 4,
            cTplB: 'cf',
            cRq: {
                ru: 'aHR0cHM6Ly95dDFzLmNvbS9hcGkvYWpheFNlYXJjaC9pbmRleA==',
                ra: 'S3RvciBjbGllbnQ=',
                rm: 'UE9TVA==',
                d: 'tQU5RM1lYDekivP0VCdUv2NtMvSfEz8iMuX1bIvV66nMGCDDnJfl4lcEGDummcA5PvN+we6IXGa6mGkqG0DC4vEwxztgyvuI+m7+0Jy+74z7mPKPlmRQ1qFtQPqgDhNQu5npJU5B7YPu786p6TlmsW9hP0P6JG41OBaYCSNGjFr1pz4WRi2RNMj45AmnjGxIwr0jg77GVsrR9f/CVVG69EI3cReN+Ss4sGyrWybiKMyK4lkzjoD9/N1NdIkWv9ZeQDKnvu0d15xtUFrBzyuCBcc7+cvI05dFUnqBcvpPCmBH9SRZI6CBMT8TpENEz9r1gipLIrR2HxXMso0qqSe0BC3DEVhXa2RUVzn7qtIwjx6ekB3FJdkCIpaYktnvTGxwUS1vg/Q30KoXky0ZnH/pT4QFFIiOm3vOPLVu+U0SkyI7HUT7Zc/MXn66XgF0Yt7xin89QT7HJwIj8oErmtcujz1V7M2bY1YaMKqs9fAwDg9M2PC4nz9T1DpHLEWL2RY70dT08ZEmrjEvroleXV7gw7S0WwtXr83zzwgTkHL1CvEAXu25l4LGTqPZKnk0xrDdJllWVyw7qAZEj90oEGBE+w==',
                t: 'MTY2OTgyOTc2OS4wNjcwMDA=',
                m: 'SfRvvapEqFpFhNRA1Tcdv0/zPqmNqFHLMKCtDkmYhFE=',
                i1: '0LoFCkCVPPBeNXWl77OXPg==',
                i2: 'MkN6QOS7enmXV3VocemzfQ==',
                zh: 'slbOGnEscRNxFiOnTsX0AKh1TuDl2qbz+DoFMtxCWD8=',
                uh: 'oz7OrxkrnxacOh3btzIq4iwAY0NK/hCkZ0LN2B2nTlI=',
                hh: 'LBSS74KkcrNPPaDUVSmWQv8ZxJLhGAngcURUX8gX1AQ=',
            }
        };
        var trkjs = document.createElement('img');
        trkjs.setAttribute('src', '/cdn-cgi/images/trace/jsch/js/transparent.gif?ray=772557f8ac5b7797');
        trkjs.setAttribute('style', 'display: none');
        document.body.appendChild(trkjs);
        var cpo = document.createElement('script');
        cpo.src = '/cdn-cgi/challenge-platform/h/b/orchestrate/jsch/v1?ray=772557f8ac5b7797';
        window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;
        window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, -window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;
        if (window.history && window.history.replaceState) {
            var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;
            history.replaceState(null, null, "\/api\/ajaxSearch\/index?__cf_chl_rt_tk=bmuK849pd5jw4CuPy5Y.BxCXOM7E5YIvegTLDVYbwSc-1669829769-0-gaNycGzNB9E" + window._cf_chl_opt.cOgUHash);
            cpo.onload = function() {
                history.replaceState(null, null, ogU);
            };
        }
        document.getElementsByTagName('head')[0].appendChild(cpo);
    }());
</script>

    <div class="footer" role="contentinfo">
        <div class="footer-inner">
            <div class="clearfix diagnostic-wrapper">
                <div class="ray-id">Ray ID: <code>772557f8ac5b7797</code></div>
            </div>
            <div class="text-center">Performance &amp; security by <a rel="noopener noreferrer" href="https://www.cloudflare.com?utm_source=challenge&utm_campaign=j" target="_blank">Cloudflare</a></div>
        </div>
    </div>
</body>
</html>
"
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:15)
	at q7.a.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)

)
	at com.shabinder.common.providers.FetchPlatformQueryResult.findBestDownloadLink(FetchPlatformQueryResult.kt:59)
	at com.shabinder.common.providers.FetchPlatformQueryResult$findBestDownloadLink$1.invokeSuspend(Unknown Source:12)
	at q7.a.resumeWith(ContinuationImpl.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:12)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:2)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:12)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:2)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:12)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:2)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)
"
Device: Galaxy j7 (2016)
OS: Custom ROM

I've downloaded some songs before so it's definitely not because of OS

I'd be happy if this problem could be solved. Thanks. 
![Screenshot_20221130-213641](https://user-images.githubusercontent.com/118936322/204869639-1e1b41fa-1356-4de1-b6cc-57a3a6e80610.jpg)

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
