### ISSUE TITLE
Downloaded songs wont appear in library

### ISSUE THREAD

**Issue by Santsku** [Shabinder/SpotiFlyer#2090]
I bought a new phone, downloaded spotify premium from XManager and downloaded all my songs from spotiflyer, but my songs wont appear in my library before it used to be in a folder named "local files"

 

I thought the songs would apprar as a local files playlist in my library after downloading them

**Device Info (please complete the following information):**
 - Device:   Oneplus CE 2 lite ]
 - OS:   [e.g.  Android 11
 - Version: newest 
 - Country: Finland

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
