### ISSUE TITLE
Songs are not being downloaded in 320kbps

### ISSUE THREAD

**Issue by mypetcoelacanth** [Shabinder/SpotiFlyer#2092]
Lets say for ex. Icona Pop - All Night

The 320Kbps file of this song is around 7.13 MB.

The size of downloaded song is 3.13 MB

Also the song playing sounds liquidy in some places (must be due to missing part of songs, like bass sounds wiggly, sometimes vocal dont sound the way they are meant to sound)

Also a headsup, this thing only happens to some songs only, for ex. Macky Gee - Aftershock

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
