### ISSUE TITLE
[Feature-Request]: Faster Download

### ISSUE THREAD

**Issue by JasonDeving** [Shabinder/SpotiFlyer#2094]
Make the app download songs faster. I don't know why it's so slow. I'm using my own api for the spotifyer.

**Comment by is-code-afish** [comment]
This is likely not an issue with the app, but rather your network, or the storage speed on your device.

**Comment by Shabinder** [comment]
There is a possibility to increase download speed, will push changes in coming weeks and re-release.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
