### ISSUE TITLE
[Feature-Request]: Download directly to external storage.

### ISSUE THREAD

**Issue by is-code-afish** [Shabinder/SpotiFlyer#2098]
Currently, to my knowledge spotiflyer only writes to internal storage, and while this is likely due to android itself, I'm wondering if it would be possible to add an ability to choose on external storage as the download location.

**Comment by Shabinder** [comment]
I have explored the possibility and even implemented the same, but chose to revert it.
You can read more about it here: https://github.com/Shabinder/SpotiFlyer/issues/116
