### ISSUE TITLE
FAKE BITRATE!!!!

### ISSUE THREAD

**Issue by rajaghulamghous** [Shabinder/SpotiFlyer#2099]
I downloaded songs from spotiflyer thinking that they were in 320 KBPS and when I checked it in the windows properties segment it showed me that the songs were in 128KBPS and after that just too make sure I downloaded a 3rd party application called SPEK from github to see if that windows properties were telling the truth or not and unfortunately it was the audio quality of the songs that I downloaded from the spotiflyer app was in 128 KBPS and not the 320 KBPS as it was showing me in the settings menu. The proof of Fraud is attached down below and same goes to all the other songs i downloaded form tis fraudulent app.
![Screenshot_20221201-222140](https://user-images.githubusercontent.com/96863657/205118857-e85b33b8-7604-4871-ab57-5af855e65b42.jpg)
![Screenshot_20221201-222146](https://user-images.githubusercontent.com/96863657/205118874-68a44761-48b7-4e2d-a9be-de4c64c170ac.jpg)

![Screenshot (8)](https://user-images.githubusercontent.com/96863657/205118080-afbaccab-2ea4-4b06-9781-56a7606058d5.png)
![Screenshot (7)](https://user-images.githubusercontent.com/96863657/205118067-8c8313eb-9810-45df-a257-ea0b11c463ac.png)

**Comment by is-code-afish** [comment]
Don't over react, you obviously couldn't tell the difference originally, and learn to read. It says "preferred", It nowhere guarantees the bitrate you chose, as it largely depends on the 3rd party directories it downloads from, namely, spotify. So blame spotify, or an unkown bug.
