### ISSUE TITLE
Wrong Song

### ISSUE THREAD

**Issue by SeanPizzaSpark** [Shabinder/SpotiFlyer#21]
Sent the link from Spotify and the the song infos are correct except the song itself. I think that an option for us to search the song itself on YouTube and just copy the song info from Spotify will be the best solution. Also I think because the song is blocked in India.. the song it found was different

**Comment by Shabinder** [comment]
share the song's spotify link please.
So , I can Troubleshoot the problem.

**Comment by SeanPizzaSpark** [comment]
https://open.spotify.com/track/1AKGJQIHP3dIPuhOjdxD6a?si=_N0cyJWuRRiyWo8yQQ_Q8g&utm_source=copy-link

**Comment by Shabinder** [comment]
> Sent the link from Spotify and the the song infos are correct except the song itself. I think that an option for us to search the song itself on YouTube and just copy the song info from Spotify will be the best solution. Also **I think because the song is blocked in India**.. the song it found was different

Yeah the block might be the reason as I didnt got it search Request that is why another song(possible bestMatch) got Downloaded.

You can download the song from youtube just share its link to the app.

>song itself on YouTube and just copy the song info from Spotify 
Why not song info from youtube?
