### ISSUE TITLE
Icon is not visible in Android 7

### ISSUE THREAD

**Issue by GET100PERCENT** [Shabinder/SpotiFlyer#2102]
On Android 7, the application icon is not available on the launcher.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
