### ISSUE TITLE
[BUG] : Music but not lyrics

### ISSUE THREAD

**Issue by FrenchAnonymous** [Shabinder/SpotiFlyer#2103]
Hello,
I am trying to download the music "Ensemble" from Orelsan.
I had 2/3 problems with other titles, but after a redownload it works.
Unfortunately, this song has a problem and I can't fix it.
The music downloads, but when you listen to it, there is background music, but not the song sung by the artist.

MUSIC : https://open.spotify.com/track/5vrpa0aE2QveJ3uYY0fgmY?si=f901c953141c40ad

**Comment by LaVoieLactee** [comment]
I just managed to have lyrics, but part of it is missing

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
