### ISSUE TITLE
[Feature-Request]: Automatic background Playlist updating

### ISSUE THREAD

**Issue by lfloesser** [Shabinder/SpotiFlyer#2109]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
If Songs get added or removed to a Playlist you have saved in SpotiFlyer, it should automatically add/remove these songs from your device so you have life updated playlists and don't need to update it manually 

**Describe alternatives you've considered**
-

**Additional context**
Maybe make a setting so songs Only get added when Playlist get changed, not removed, so you still have all songs, even if on the Spotify Playlist they are removed.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
