### ISSUE TITLE
[Feature-Request]: Downloading Spotify podcasts

### ISSUE THREAD

**Issue by Afterlifepro** [Shabinder/SpotiFlyer#2121]
I recently attempted to download a podcats (in a playlist) however I could not download it.

It would make sense to be able to download Spotify podcasts like a YouTube video - audio only and with the cover.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
