### ISSUE TITLE
Doesn't download full song

### ISSUE THREAD

**Issue by zippybenjiman** [Shabinder/SpotiFlyer#2126]
When i try to download a 13:07 song (maybe i was boring - wilbur soot) it only downloads 6:34 min i even tried a youtube version, but that failed too

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
