### ISSUE TITLE
[Feature-Request]: Check Updates

### ISSUE THREAD

**Issue by Lukyzzz** [Shabinder/SpotiFlyer#2129]
OTA option, like "Check for updates" option in app

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
