### ISSUE TITLE
Not starting on Kubuntu

### ISSUE THREAD

**Issue by sylvainar** [Shabinder/SpotiFlyer#213]
Hello!

I'm having some issues, I downloaded the packaged (.deb) file and it doesn't work, I have this error at startup:
```
 /opt/spotiflyer/bin  ./SpotiFlyer 
Error: dl failure on line 534
Error: failed /opt/spotiflyer/lib/runtime/lib/server/libjvm.so, because /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /opt/spotiflyer/lib/runtime/lib/server/libjvm.so)
Failed to launch JVM
```
I'm using Kubuntu 20.04.

Thanks!

**Comment by Shabinder** [comment]
No Idea, try sudo apt-get update && sudo apt-get upgrade 

then try installing jdk 15 and the run 3.3.0 deb/jar
