### ISSUE TITLE
Please add an option to choose from the Explicit and the clean version of the song

### ISSUE THREAD

**Issue by samuel20086** [Shabinder/SpotiFlyer#2137]
Can you please add an option so we could choose what version of the song we want to download because when some words get bleeped out it drives me crazy but overall it is an amazing app

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
