### ISSUE TITLE
[BUG] : Quality

### ISSUE THREAD

**Issue by willowelmartin** [Shabinder/SpotiFlyer#2139]
Hello!! I've used the app to download over 40 songs from spotify so far, and despite my preferred quality being 320KBPS, I always get 128KBPS music.

**Comment by trgcyln** [comment]
same in here.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
