### ISSUE TITLE
Streaming data not found error 

### ISSUE THREAD

**Issue by kochas23** [Shabinder/SpotiFlyer#2164]
Android 12, poco x3 pro,Greece 
Every time I copy and paste a link from any platform it says streaming data not found instead of searching for the link to eventually download it. This is an issue that hasn't happened to me before, I noticed it today for the first time in 6 months. This has happened to more than 20 links across youtube soundcloud and spotify. Please fix it!

**Comment by Bobo123142** [comment]
i have the same problem and im from bulgaria so this problem might be only in eastern europe

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
