### ISSUE TITLE
[Feature-Request]: <Feature_Title>

### ISSUE THREAD

**Issue by saqibparvaiz** [Shabinder/SpotiFlyer#2168]
Please provide linux version as appimage. Deb version is for only debian based and jar version breaks so many times.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
