### ISSUE TITLE
streaming data not found

### ISSUE THREAD

**Issue by Bobo123142** [Shabinder/SpotiFlyer#2169]
ive been using spotiflyer for about a month or so and it stopped working
i try to download a mp3 from youtube and it just says "streaming data not found"

i dont know if this is because of my phone but if it is its a samsung A13 galaxy
please fix i even reinstalled the program

**Comment by Cerbero1984** [comment]
Hi , paste the link and delete the words "=share " work for me. 
Example:https://youtube.com/watch?v=_Rks2oCRS88&feature=shares
Regards.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
