### ISSUE TITLE
[BUG] : fake song

### ISSUE THREAD

**Issue by 69peopleonline** [Shabinder/SpotiFlyer#2171]
I tried to download a song if necessary the song was sketchers i listened to it thought of downloading it and then it was not normal  the beginning was normal and then it turned to indian rap please fix this and other songs like unforgettable with the black sand and red moon picture, fix this please, thanks

**Comment by SaltyBill** [comment]
Same as me!:(

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
