### ISSUE TITLE
[BUG] : wrong song download

### ISSUE THREAD

**Issue by jyotirmoydotdev** [Shabinder/SpotiFlyer#2179]
**Describe the bug:**
downloaded the wrong song

**Media Links Used:** 
https://open.spotify.com/track/2dHHgzDwk4BJdRwy9uXhTO?si=9ee96e16aefa4b37

**Expected behavior**
should download the song attached to the link

**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   Samsung A6+
 - OS:  Android
 - Version:   3.6.3
 - Country: India
 
**Additional context:**

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
