### ISSUE TITLE
Slower download Speed than usual

### ISSUE THREAD

**Issue by Goddyspors** [Shabinder/SpotiFlyer#2195]
The download speed is much slower than usual, 70 s for every song.
The connection is really fast and i have my own credentials of spotify inserted.
Anything that i can do?

Thank You.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
