### ISSUE TITLE
Downloads different songs than what it shoud

### ISSUE THREAD

**Issue by m-aron** [Shabinder/SpotiFlyer#2197]
I downloaded an album and a playlist from Spotify so far. Some song are just fine but one had parts of a completely different song merged onto the end of the song, (a 45 second snippet of it), that would play at the end of the song.

In an other case, a song from the playlist played a different song off its album, contrary to what the title said and what I wanted to download.

It's also wierd that some songs from the same album are downloaded explicit, while others are clean, although i linked the explicit version of the same album

 - Device:  Samsung A50
 - OS:  Android 11
 - Version:   3.6.3
 - Country: Romania

Additional context: the album was SOS by SZA, and a country song was merged into the track "Gone girl". Instead of "To Zion", which the title said, the audio playing was a different song from Lauryn Hill.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
