### ISSUE TITLE
[BUG] : PLEASE add support to more (rather unknown) songs somehow

### ISSUE THREAD

**Issue by lfloesser** [Shabinder/SpotiFlyer#2198]
**Describe the bug:**
Bro, I have a playlisz with 119 songs, and 106 of them can't be downloaded! Some are not even unpopular man. I rlly love the stuff u do, but is there any way to add support to more songs? Any online librarys?) 

**Media Links Used:** 
Example: 
https://open.spotify.com/playlist/3E4AVRFhH9LIQ4LunWzPDu?si=9GksjT2eQ5qlZ2T1Q4HyRQ&utm_source=copy-link
**Expected behavior**
It should download at least like 80% or 90% of the songs, then it's OK but only 13????

**Screenshots:**
![Screenshot_20221226_000650](https://user-images.githubusercontent.com/67869984/209484170-9909f3b6-b9a7-44a8-9e3c-464aa4715a03.jpg)

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   Samsung
 - OS:   Newest Android version 
 - Version:   newest
 - Country: Germany

**Additional context:**
Just wanted to thank u for the great tool!

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
