### ISSUE TITLE
Songs won't download on 1.7

### ISSUE THREAD

**Issue by Bwangster12** [Shabinder/SpotiFlyer#22]
Sharing a song on 1.7, nothing seems to download.  Just see song spinning. 
![Screenshot_20201202-133137](https://user-images.githubusercontent.com/26938129/100915720-c0449b00-34a2-11eb-81b8-ef83ffba61dd.png)

**Comment by Shabinder** [comment]
Can you check if total number has increased in Notification?

**Comment by faroukmok** [comment]
same for me, and no increase in notif.

**Comment by Bwangster12** [comment]
Clearing cache/data seems to have fixed it on one of my two phones, but not the other.  I also notice more random crashing on 1,7.  Not a lot, but more often than before.

**Comment by Shabinder** [comment]
Yeah , As I updated local database table schema but forgot to bump the version , that is why app crashes after upgrading from 1.7 , Please clean install the app in all devices , and app should work just fine, and I will further investigate the crashes if they still persist.
