### ISSUE TITLE
The app crashes on Android 11 

### ISSUE THREAD

**Issue by ookii-tsuki** [Shabinder/SpotiFlyer#221]
After I updated to 3.2.0 i tried to download an album but I still got errors and non of them were downloaded so I cleared the app data and tried again and now the app crashes whenever I click on the search bar
![IMG_20210711_092932](https://user-images.githubusercontent.com/42550249/125188214-e85f5e00-e22a-11eb-9c23-e014e84fb5c9.jpg)

**Comment by Shabinder** [comment]
> After I updated to 3.2.0 i tried to download an album but I still got errors and non of them were downloaded so I cleared the app data and tried again and now the app crashes whenever I click on the search bar


Strange , did you send the crash report ?

**Comment by ookii-tsuki** [comment]
Nothing happens when I click on the notification

**Comment by Shabinder** [comment]
> Nothing happens when I click on the notification

I recieved the crash report and will soon release a hot fix apk

**Comment by Shabinder** [comment]
For reference : this is the bug : https://issuetracker.google.com/issues/190893486

**Comment by FabiusFr** [comment]
Same for me when i try to paste links thanks

**Comment by Shabinder** [comment]
@FabiusFr @ookii-tsuki can you confirm if following works 

https://github.com/Shabinder/SpotiFlyer/releases/download/3.2.1/SpotiFlyer_v3.2.1_Signed.apk

**Comment by FabiusFr** [comment]
@Shabinder Yees u're the best thanks man 👍💪
