### ISSUE TITLE
[BUG] : <Issue_Title>

### ISSUE THREAD

**Issue by aZeBy** [Shabinder/SpotiFlyer#2220]
**Describe the bug:**Songs on the playlist keep failing to download.

**Media Links Used:** https://open.spotify.com/playlist/4oeCUSrRzlezYrGmJUfjpo?si=U5JQtcDGQJSU43Llcm42SQ&utm_source=copy-link

**Expected behavior**I expected all songs on the playlist to download but a number keep failing

**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   [Redmi note 10s]
 - OS:   [android 12]
 - Version:   [e.g. 3.2.1]
 - Country: [eg: India, will help in detecting if service is accessible to u]

**Additional context:**

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
