### ISSUE TITLE
[BUG] : No FFMPEG at path (macOS 11.7.1)

### ISSUE THREAD

**Issue by loading7088** [Shabinder/SpotiFlyer#2223]
Half my playlist wont download with the error No FFMPEG found at path. I've already installed FFMPEG to the folder with my music and ran the terminal thing to install it. It says Process completed.

https://open.spotify.com/playlist/5MmYON5Mom9nqfBBZ6jF8G

 - Device: MacBook Air 2013 11"
 - OS:   macOS Big Sur 
 -  Version:   11.7.1
 - Country: Canada

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
