### ISSUE TITLE
[Feature-Request]: <filename>

### ISSUE THREAD

**Issue by CMEPCBHG** [Shabinder/SpotiFlyer#2229]
Can't name the file normally when the it contains Chinese.All letters become __.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
