### ISSUE TITLE
[Feature Request] Add to Chocolatey 

### ISSUE THREAD

**Issue by NevGi-cpu** [Shabinder/SpotiFlyer#223]
Just add this software to chocolatey as it seems that new releases happens every other weeks and since i put my choco apps on auto update every week it will help me and other users so not to download the .exe everytime a new release happens which is efficient.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
