### ISSUE TITLE
errorOccurred 

### ISSUE THREAD

**Issue by LASITHAtheLEGEND** [Shabinder/SpotiFlyer#2241]
![Screenshot (90)](https://user-images.githubusercontent.com/122290615/211340677-2ad3a1ee-2aee-4dfe-927f-66878d69df68.png)

WHAT DOES THIS MEAN?

**Comment by ericsomto** [comment]
Buggy software

**Comment by LASITHAtheLEGEND** [comment]
> Buggy client

You know how to fix this?

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
