### ISSUE TITLE
[BUG] : Unable to download old playlist from Spotify

### ISSUE THREAD

**Issue by Abhash46** [Shabinder/SpotiFlyer#2259]
**Describe the bug:**
I am unable to download my old playlists that i had already made in Spotify. While if i create new playlists, they get downloaded without any issue. These old playlists were getting downloaded earlier, but since few days i get his error "invalid 404"

**Media Links Used:** 
[](https://open.spotify.com/playlist/1QiS49B74rl41hYrDLCy3C?si=e4627082996f4888&pt=8b790fc920f707c65b1dd09cfaaa4244)
https://open.spotify.com/playlist/5C3OcN7nMPwikw1HWN0FyM?si=45086191feba4883&pt=ba6645b036d6dfd9a85901eb0fa087f0

**Expected behavior**

**Screenshots:**
![Screenshot_20230114_100544](https://user-images.githubusercontent.com/80103401/212639649-60d4d33a-cb53-41e6-b18f-ca31a316fc04.jpg)

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   Samsung S21 & Windows 10 PC
 - OS:   Android 13 & Win 10
 - Version:   3.6.3
 - Country: India

**Additional context:**

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
