### ISSUE TITLE
Unbale to download tracks

### ISSUE THREAD

**Issue by samkan60** [Shabinder/SpotiFlyer#2267]
DownloadLinkFetchFailed(errorTrace=Find Link for Dzimba Dzemabwe 

Fetching From Saavn Failed:DownloadLinkFetchFailed(errorTrace=No SAAVN Match Found for Dzimba Dzemabwe)
	at com.shabinder.common.providers.saavn.requests.JioSaavnRequests

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
