### ISSUE TITLE
Server hosting related

### ISSUE THREAD

**Issue by Mainak009** [Shabinder/SpotiFlyer#2279]
I can help you with a working server(free)....ping me below
Telegram: @hacker007
Discord: Hacker007#1550

**Comment by ericsomto** [comment]
Soq ya diq

**Comment by Mainak009** [comment]
> Soq ya diq

Means?

**Comment by ericsomto** [comment]
अवांछित सन्देश रोकें

**Comment by Mainak009** [comment]
> अवांछित सन्देश रोकें

Pagal hai Keya?.... author me hi help manga isiliye diya.....check readme file

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
