### ISSUE TITLE
[BUG] : No Internet Connection 

### ISSUE THREAD

**Issue by Seandreas08** [Shabinder/SpotiFlyer#2280]
I have a

Model: Huawei p30 lite
Emui version: 12
Android version: 9

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
