### ISSUE TITLE
常用

### ISSUE THREAD

**Issue by MrG330** [Shabinder/SpotiFlyer#2281]

**Comment by ericsomto** [comment]
Are you okay?

**Comment by Tulip-0333** [comment]
"Commonly used" yeah alright

**Comment by MrG330** [comment]
> Are you okay?

I am fine

**Comment by Tulip-0333** [comment]
> > Are you okay?
> 
> I am fine

I heavily doubt this

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
