### ISSUE TITLE
Option : Embed lyrics when downloading. 

### ISSUE THREAD

**Issue by Beech0408** [Shabinder/SpotiFlyer#2285]
It would be very nice if the feature of adding lyrics to the music file being downloaded could be implemented.

Thank you in advance.

**Comment by ericsomto** [comment]
No

**Comment by 04jeremiah** [comment]
Yeah this Feature is much needed ..

**Comment by ericsomto** [comment]
Give reasons why it should

**Comment by 04jeremiah** [comment]
It can fully replace Spotify and provide a jump pack/immersive music experience if a mp3 file has a lrc file with it. Also many music player like "Poweramp" fully supported a lrc file. Wish developer consider it ..

**Comment by 04jeremiah** [comment]
![Screenshot_20230124-182055.jpg](https://user-images.githubusercontent.com/22298741/214266974-cdb41149-5935-4f8b-ae6b-d3b85a336f56.jpg)

**Comment by Beech0408** [comment]
Some music players too like  Musicolet would be able to show the song lyrics that would have been embedded by Spotiflyer when playing.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
