### ISSUE TITLE
[BUG] : does not download the original music downloads other music

### ISSUE THREAD

**Issue by Afredd07** [Shabinder/SpotiFlyer#2293]
**Describe the bug:**
 does not download the original music downloads other music. 

**Media Links Used:** 
 https://open.spotify.com/track/2Gw1Wkdoqvj00oYXHtNvq8?si=V5H9gdEtTWmnbpSFQGVpGA&utm_source=copy-link 

**Expected behavior**
 that the original music will be downloaded not another. 

**Screenshots:**
 If applicable, add screenshots / screenrecording to help explain your problem. 

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   [e.g. moto g9 play ]
 - OS:   [e.g. Android 11 ]
 - Version:   [e.g. 3.6.3]
 - Country: [eg: Perú ]

**Additional context:**
please, solution, it's already happening to me three times.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
