### ISSUE TITLE
[Feature-Request]: Descargar Flac hi-res

### ISSUE THREAD

**Issue by AngelJRomero21** [Shabinder/SpotiFlyer#2295]
Seria interesante que la aplicación descarguese musica Hi-Res, de plataformas como deezer o qobuz.

Estas se descargan en formato FLAC y tienen mejor calidad.

He intentado descargar musica de spotify y lo máximo que descarga es 128kbps.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
