### ISSUE TITLE
[BUG] : does not download the original music

### ISSUE THREAD

**Issue by Afredd07** [Shabinder/SpotiFlyer#2296]
**Describe the bug:**
it does not download the original version of the music and also the download in low sound.

**Media Links Used:**
https://open.spotify.com/track/2BHj31ufdEqVK5CkYDp9mA?si=JawfLOr1TlW7aWJRWkPLSQ&utm_source=copy-link

**Expected behavior**
which will download the original music.

**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   [e.g. moto g9 play ]
 - OS:   [e.g. iOS, Android 11 ]
 - Version:   [e.g. 3.6.3 ]
 - Country: [eg: Perú ]

**Additional context:**
it happens to me four times

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
