### ISSUE TITLE
App suddenly closes and doesn't download any song

### ISSUE THREAD

**Issue by rperez1997** [Shabinder/SpotiFlyer#23]
![Screenshot_20201203-072501_One UI Home](https://user-images.githubusercontent.com/75428708/101018413-76f35a80-3539-11eb-8d95-3731ac9ffe2d.jpg)
![Screenshot_20201203-072528_One UI Home](https://user-images.githubusercontent.com/75428708/101018434-7f4b9580-3539-11eb-9ffc-607cb2f2aff1.jpg)

**Comment by rperez1997** [comment]
https://open.spotify.com/playlist/37i9dQZF1DZ06evO2bBD4A?si=x0rbBLdCQumoiUhD8zW-Ug

Samsung Galaxy A10s

**Comment by jpayne120983** [comment]
Everything works except downloading it just spends tried with and without a vpn 
Using a note 10+

**Comment by Shabinder** [comment]
![image](https://user-images.githubusercontent.com/44765050/101052155-4c8eb500-35ac-11eb-9c14-52e4bee06e2d.png)
**_Tried, and working for me._**
_https://open.spotify.com/playlist/37i9dQZF1DZ06evO2bBD4A?si=x0rbBLdCQumoiUhD8zW-Ug_
**However I am further investigating the issue**, _is prev v1.6 working?_

**Comment by rperez1997** [comment]
Yes, 1.6 worked perfectly

**Comment by jpayne120983** [comment]
> ![image](https://user-images.githubusercontent.com/44765050/101052155-4c8eb500-35ac-11eb-9c14-52e4bee06e2d.png)
> **_@rperez1997 I Tried, and its working for me.,maybe try Clearing Data of App once?_**
> _https://open.spotify.com/playlist/37i9dQZF1DZ06evO2bBD4A?si=x0rbBLdCQumoiUhD8zW-Ug_
> **However I am further investigating the issue**, _is prev v1.6 working?_ 

I'll second that 1.6 awesome 👌

**Comment by Shabinder** [comment]
Thanks for the report , I am investigating what's going wrong ,

And everyone please try 1.7 after clearing data or uninstalling v1.6 and see of it works , hopefully it should...
And please reply here if it doesnt. _(even after uninstalling and reinstalling again.)_

**Comment by rperez1997** [comment]
I deleted data of the app, uninstalled and installed 1.8. It doesn't crash anymore but still doesn't download anything

![Screenshot_20201204-063502_SpotiFlyer](https://user-images.githubusercontent.com/75428708/101159192-04e34a00-35fb-11eb-9408-7e41f19a8e86.jpg)  

I tried a single song and the whole playlist

**Comment by jpayne120983** [comment]
I tried updating from 1.6  and fresh install to 1.8 no luck

**Comment by Shabinder** [comment]
I have been reported the same issue by few others who are also using **_Samsung Devices_** just as you @jpayne120983 @rperez1997,
At the moment I don't have/own any samsung device to test the app on.
I will work on the issue as soon as I get my hand on a Samsung device.

**Comment by jpayne120983** [comment]
> I have been reported the same issue by few others who are also using **_Samsung Devices_** just as you @jpayne120983 @rperez1997,
> At the moment I don't have/own any samsung device to test the app on.
> I will work on the issue as soon as I get my hand on a Samsung device.
> 
> _**PS:**_ Any one who knows some Kotlin can get **Source** and **_help in investigating_** the issue too.
> Anyway I will work on it myself as soon as possible

Well definitely no rush as 1.6 works perfectly for me your doing awesome job

**Comment by vinch49** [comment]
Hi, many thanks for development. 
release 1.6 runs on my phone.
But release 1.8 doesn't work. the download isn't running, it's freeze...

Pocophone F1 - MIUI 11.0.8

**Comment by jpayne120983** [comment]
Is there aaay to stop the new version popup since I'm stuck on 1.6 for now

**Comment by Shabinder** [comment]
Fixed in v2.0 release.
