### ISSUE TITLE
Ability to pause when downloading. 

### ISSUE THREAD

**Issue by Beech0408** [Shabinder/SpotiFlyer#2301]
It would be of massive help,especially when having crappy internet connection.

Thank you in advance.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
