### ISSUE TITLE
[BUG] : i dk but u was downloading a song via playlist link and this happened only to this song

### ISSUE THREAD

**Issue by Aditya149085** [Shabinder/SpotiFlyer#2303]
**Describe the bug:**
I pasted a Spotify link that i made then tried downloading the song all at once it stopped many time like app exited and when i tried to download one by one a song was not able to be downloaded and showed this above error.

**Media Links Used:** 
https://open.spotify.com/playlist/02Z7AOl20VWTqPv2d4WUzg?si=BJJgyUy4QjCLYsm6jh-FEw&utm_source=copy-link

**Expected behavior**
Able to download playlist all at once without stopping and able to download all songs 

**Screenshots:**
![Screenshot_2023-01-29-08-55-12-481_com shabinder spotiflyer](https://user-images.githubusercontent.com/52645320/215303019-dcc740e6-2f52-4ad0-bda1-d3dbbfd74afa.jpg)

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device: redmi note 10 pro
 - OS:   Android 
 - Version:   idk about this if your app then the stable latest version 
 - Country:india

**Additional context:**

![Screenshot_2023-01-29-08-55-09-813_com shabinder spotiflyer](https://user-images.githubusercontent.com/52645320/215303025-601e69c4-c52b-47d1-bfdb-2ed364ec3a0e.jpg)

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
