### ISSUE TITLE
[BUG] : does not download the original music

### ISSUE THREAD

**Issue by Afredd07** [Shabinder/SpotiFlyer#2304]
**Describe the bug:**
does not download the original music download other music.

**Media Links Used:** 
https://open.spotify.com/track/1lI3pfm02Fw6zajcGyxJsg?si=dNWLDvAPQGWfRguvQdF4Kw&utm_source=copy-link

**Expected behavior**
that the original music will be downloaded not another.

**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   [e.g. moto g9 play ]
 - OS:   [e.g. iOS, Android 11]
 - Version:   [e.g. 3.6.3]
 - Country: [eg: Perú ]

**Additional context:**
please, solution, it happens to me a lot of times

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
