### ISSUE TITLE
[BUG] :please, solution, it happens to me a lot of times

### ISSUE THREAD

**Issue by Afredd07** [Shabinder/SpotiFlyer#2305]
**Describe the bug:**
does not download the original music download other music.
**Media Links Used:** 
https://open.spotify.com/track/6Cz7JBvWziPGMMhGniqgVh?si=J05ZAdPIRmGmf1b_z-oExA&utm_source=copy-link&context=spotify%3Aplaylist%3A37i9dQZF1EIV9HLlng58pg

**Expected behavior**
which will download the original music.

**Screenshots:**

**StackTrace:**
``
```

**Device Info (please complete the following information):**
 - Device:   [e.g. moto g9 play ]
 - OS:   [e.g. iOS, Android 11]
 - Version:   [e.g. 3.6.3]
 - Country: [eg: Perú ]

**Additional context:**
that the original music will be downloaded and not another.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
