### ISSUE TITLE
[BUG] : I can't download a song that it duration was more than 10 minutes

### ISSUE THREAD

**Issue by JDRL555** [Shabinder/SpotiFlyer#2312]
**Bug description:**
First at all, my apologies if my bug description is not too clearly. I'm not an english speaker native, i'm from Venezuela and i try my best to express what i found into that increible app.

I have downloaded one of my favorites Tool albums, called "Fear inoculum". Those songs have a duration more or equals to 10 minutes, but when i download one of them, the song don't have the same duration or it corrupt at the 7th or 9th minute. Please let me know if there's a solution about it, because i really enjoyed the app to download my favorite tracks (and i'm really thanksfull to all of the app developers, you did a really good job with it!). Thanks and i really wait for some answer, or at least, a solution.

**Media Links Used:** 
This is the album link: https://open.spotify.com/album/7acEciVtnuTzmwKptkjth5?si=WEmG5dJ3SYi20ooYKUak1w

**Expected behavior**
Well, i expect the full songs to listen without any issue.

**Device Info (please complete the following information):**
 - Device:   Samsung A03
 - OS:   Android
 - Version:   12
 - Country: Venezuela

**Comment by lazybearsoft** [comment]
Same issue here.

**Comment by ericsomto** [comment]
> **Bug description:**
> First at all, my apologies if my bug description is not too clearly. I'm not an english speaker native, i'm from Venezuela and i try my best to express what i found into that increible app.
> 
> I have downloaded one of my favorites Tool albums, called "Fear inoculum". Those songs have a duration more or equals to 10 minutes, but when i download one of them, the song don't have the same duration or it corrupt at the 7th or 9th minute. Please let me know if there's a solution about it, because i really enjoyed the app to download my favorite tracks (and i'm really thanksfull to all of the app developers, you did a really good job with it!). Thanks and i really wait for some answer, or at least, a solution.
> 
> **Media Links Used:** 
> This is the album link: https://open.spotify.com/album/7acEciVtnuTzmwKptkjth5?si=WEmG5dJ3SYi20ooYKUak1w
> 
> **Expected behavior**
> Well, i expect the full songs to listen without any issue.
> 
> 
> **Device Info (please complete the following information):**
>  - Device:   Samsung A03
>  - OS:   Android
>  - Version:   12
>  - Country: Venezuela

Use another service

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
