### ISSUE TITLE
cant download some songs

### ISSUE THREAD

**Issue by IheartLing** [Shabinder/SpotiFlyer#2313]
For some reason, when i download a song this shows up:
		- DownloadLinkFetchFailed(trackName=For Those About to Race, jioSaavnError=java.util.NoSuchElementException: Collection is empty., ytMusicError=MP3ConversionFailed(extraInfo=Client request invalid: 404 Not Found. Text: "Not Found", message=MP3 Converter unreachable, probably BUSY !
			- Please Dont Open issue! , Online Converter Was Busy! , try again after some time and download will be successfull . 
-->

**Device Info**
 - Device:   [e.g. Samsung Note 8A]
 - OS:   [e.g. Android 9]
 - Version:   [e.g. 3.6.3]
 - Country: [eg: Malaysia]

**Comment by k9999official** [comment]
Same

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
