### ISSUE TITLE
[BUG] : Can't download from soundcloud

### ISSUE THREAD

**Issue by Amieldev** [Shabinder/SpotiFlyer#2315]
Soundcloud downloads are not working, instead it shows this error:

![Screenshot_20230201-181109](https://user-images.githubusercontent.com/80168657/216081990-8f7bb394-a515-4c8e-bd07-cdc9602cfc94.jpg)

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
