### ISSUE TITLE
[FEATURE REQUEST] Download Subtitles as.lrc or .txt

### ISSUE THREAD

**Issue by R0GUE-A5H** [Shabinder/SpotiFlyer#233]
If possible, then please give the option to download Subtitles of downloaded song also.
That'd be very cool feature. 
Sometimes, we can't find lyrics of some songs on internet. Even if we do managed to find lyrics, then it's timing would differ.
Looking forward for this feature in next update.

**Comment by Shabinder** [comment]
> If possible, then please give the option to download Subtitles of downloaded song also.
> That'd be very cool feature.
> Sometimes, we can't find lyrics of some songs on internet. Even if we do managed to find lyrics, then it's timing would differ.
> Looking forward for this feature in next update.

If I do implement this feature then I am more inclined toward embedding lyrics in mp3 itself  rather than providing seperate .txt or .irc , is there some benefit of seperate txt ?

**Comment by AshwinTheGammer** [comment]
>>is there some benefit of seperate txt ?

No, I said that cuz I've had downloaded Songs but not their Lyrics file. So that'd have been handy if I could only download lyrics file.
Well, it isn't the problem. I'll re-download the songs. 🙂

Giving options like: 
Download song ?
Download Song with Lyrics?

Would be cool.
However, you knows better how to handle this thing.
My phone supports .lrc.

If someone else's phn doesn't support .lrc as lyric file, then they can just change the extension of file of .txt file to whatever their phone supports and it'd certainly work, thereafter.
Thanks, one more question tho,
Does Spotiflyer download the song as bitrate of 320KBPS? Or 192?

**Comment by Shabinder** [comment]
>  Does Spotiflyer download the song as bitrate of 320KBPS? Or 192?

Depends , Some Songs Can be Fetched from JIO-SAAVN (which can be 320 KBPS) , if not then we move toward YT-Music (128 or 192 KBPS)

**Comment by pabloscloud** [comment]
Any updates on this? I would appreciate it a lot!

**Comment by Shabinder** [comment]
> Any updates on this? I would appreciate it a lot!

I am working on the reworking the whole project, and good news is we are close to initial release,
will definately add this later it into the app.

and one more thing: new project has a some new exciting things coming in, which will keep on getting polished in incremental releases.

but to summarise, we all have something to look out for, so stay tuned!

**Comment by pabloscloud** [comment]
Sounds great. Now I am hyped for sth I didn't know I would need or know that it exists a week ago 😂

**Comment by s0mt0chukwu** [comment]
> > > Any updates on this? I would appreciate it a lot!
> > 
> > I am working on the reworking the whole project, and good news is we are close to initial release,
> > will definately add this later it into the app.
> > 
> > and one more thing: new project has a some new exciting things coming in, which will keep on getting polished in incremental releases.
> > 
> > but to summarise, we all have something to look out for, so stay tuned!
> 
> **Will we be getting episodes/podcasts download support with this version. Just being optimistic** 🤞

WTF No!!!!!!!

**Comment by MakD** [comment]
> > > > Any updates on this? I would appreciate it a lot!
> > > 
> > > 
> > > I am working on the reworking the whole project, and good news is we are close to initial release,
> > > will definately add this later it into the app.
> > > and one more thing: new project has a some new exciting things coming in, which will keep on getting polished in incremental releases.
> > > but to summarise, we all have something to look out for, so stay tuned!
> > 
> > 
> > **Will we be getting episodes/podcasts download support with this version. Just being optimistic** 🤞
> 
> WTF No!!!!!!!

It was mentioned in his todo😅

**Comment by Shabinder** [comment]
> Will we be getting episodes/podcasts download support with this version. Just being optimistic 🤞


 - Not in first release, but as said is in todo, will definitely do this in later iterations.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
