### ISSUE TITLE
[Feature-Request]: Add Apple Music Support

### ISSUE THREAD

**Issue by MixoMax** [Shabinder/SpotiFlyer#2335]
Apple Music API integration just like the others.

**Comment by ericsomto** [comment]
No

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
