### ISSUE TITLE
Cannot download personal playlists in JioSaavn

### ISSUE THREAD

**Issue by CaptainKnox** [Shabinder/SpotiFlyer#234]
I have my playlists on JioSaavn which I cannot download. Playlists made by JioSaavn can be downloaded without any issues. When I try to paste the link and download, this pops up.
![Screenshot_2021-07-13-13-15-46-30_034e0326429f3b404601e9b17fbe8654](https://user-images.githubusercontent.com/29699930/125412854-ed640f00-e3dc-11eb-8778-1fc69d817d0b.jpg)

**Comment by Shabinder** [comment]
Stale no response

**Comment by CaptainKnox** [comment]
So sorry for forgetting about this. 

> > I have my playlists on JioSaavn which I cannot download. Playlists made by JioSaavn can be downloaded without any issues. When I try to paste the link and download, this pops up.
> 
> Can you share the link you are using ?
> 
> I believe JioSaavn uses 'featured' keyword in link after saavn.com/s/<>/....
> 
> Just a hunch can you replace playlist with featured and see if your link works ?

This works! Thanks! Closing this issue now.
