### ISSUE TITLE
[BUG] : Failed to launch JVM

### ISSUE THREAD

**Issue by fionnn** [Shabinder/SpotiFlyer#2340]
**Describe the bug:**
I was able to use the application like normal until about a week ago, and now I'm getting failed to launch JVM errors. I've reinstalled my java and also installed java 16 which is, from what I've heard, the optimal version for this.

**Media Links Used:** 
N/A

**Expected behavior**
I expected the application to launch as normal.

**Screenshots:**
https://i.imgur.com/23Zx82X.png

**StackTrace:**
```
N/A
```

**Device Info (please complete the following information):**
 - Device:  PC
 - OS:   Windows
 - Version:   11
 - Country: Ireland

**Additional context:**

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
