### ISSUE TITLE
Ability to select multiple songs to download. 

### ISSUE THREAD

**Issue by Beech0408** [Shabinder/SpotiFlyer#2342]
This would be very useful when downloading albums or playlists. It can allow users to choose the tracks that they want to download, instead of clicking on a song, one by one. This feature is not the same as that of the "Download all" button, because the "Download all" button downloads all the tracks; it does not allow you to choose the ones you want specifically them downloading them (the ones you have selected) at once. 
I hope you understand what I am trying to say.

Thank you in anticipation.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
