### ISSUE TITLE
[BUG] : Filename replaces spaces, special characters, and non-English charaters to underscores.

### ISSUE THREAD

**Issue by 5vr** [Shabinder/SpotiFlyer#2345]
**Describe the bug:**
- Spaces, Japanese characters, and symbols, all get converted to underscores in the downloaded file names including folder name.

**Media Links Used:** 
- https://open.spotify.com/playlist/37i9dQZF1DWYLp3LpUUY2V

**Expected behavior**
- Should name files like shown in the app

**Screenshots:**
![image](https://user-images.githubusercontent.com/80219278/218257819-46227da9-b13f-4088-bedc-58fc11afd822.png)

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   Laptop, idk the model
 - OS:   Windows 11
 - Version:   3.6.3.0
 - Country: India

**Additional context:**

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
