### ISSUE TITLE
Songs over 10 minutes will not download

### ISSUE THREAD

**Issue by muzikmark** [Shabinder/SpotiFlyer#2359]
Hi there. I'm using Spotiflyer on a Google Pixel 6.
I listen to a fair amount of live music and jam bands.
I noticed any song over 10 minutes will not download.
Can this be adjusted to "no time limit"?

Thanks!!

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
