### ISSUE TITLE
[NO WRITE ACCESS] : <Won't let me use my SD Card for downloads>

### ISSUE THREAD

**Issue by tdb14** [Shabinder/SpotiFlyer#2370]
The app won't let me change my download directory to my SD Card. The error I get is 'NO WRITE ACCESS ON /storage/3461-3061 reverting back to previous'

I expected to be able fo change my download directory freely from Internal Storage to my SD Card since the app is granted all the permissions it needs.

Screenshots:
![Screenshot_20230220-212220](https://user-images.githubusercontent.com/125916430/220184978-0bfc01af-6d88-488e-b3f3-e8b60115283f.jpg)
![Screenshot_20230220-212208](https://user-images.githubusercontent.com/125916430/220184981-59240d9c-dabc-4cba-88b2-363cf832ad53.jpg)
![Screenshot_20230220-212204](https://user-images.githubusercontent.com/125916430/220184984-32f6cae6-55ca-4d29-b3c4-b94dfbd2f8ee.jpg)

Device Info
 - Device:   Samung Galaxy J5 Pro (2017)
 - OS:   Android 9
 - Version:   UI Version 1.1
 - Country: South Africa

**Comment by ericsomto** [comment]
Just copy the songs from Spotiflyer internal storage to an external storage folder

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
