### ISSUE TITLE
[Feature-Request]: Download whole artist's library

### ISSUE THREAD

**Issue by ThinkpadT530user** [Shabinder/SpotiFlyer#2375]
I usually download everything from an artist and having to manually download every album gets quite frustrating.

If it's possible I would like you to add a feature to paste a link from an artist's page and have the option to download all the albums and songs at once.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
