### ISSUE TITLE
ERROR AFTER INSTALL SpotiFlyer ON WINDOWS 10

### ISSUE THREAD

**Issue by rexya2017** [Shabinder/SpotiFlyer#238]
Hello, i got the problem after installing this program. if I open SpotiFlyer I got message like this:
"Failed to launch JVM"
How can i fix the problem?
I'm useing Windows 10 20H2 (64-bit) build 19042.906.
![Error](https://user-images.githubusercontent.com/35487397/125529875-2b9436e4-3e1f-40c0-add9-d98d86b5e080.png)

**Comment by Shabinder** [comment]
Check if you have java installed :
`
java -version`

**Comment by KaungSithuLinn** [comment]
I already installed the java and it showing like this
{C:\Users\user>java -version
java version "1.8.0_311"
Java(TM) SE Runtime Environment (build 1.8.0_311-b11)
Java HotSpot(TM) Client VM (build 25.311-b11, mixed mode, sharing)}
But still showing the "Failed to launch JVM" even after uninstalled and reinstall the whole .msi file.
I realized it happened after I changed the Spotifly's default download location to my music folder.

**Comment by Shabinder** [comment]
u r using java 8, update to java 15/16

**Comment by KaungSithuLinn** [comment]
> u r using java 8, update to java 15/16

Oh right Yay!!! it work. Thanks bro 👌

**Comment by aaroniza0** [comment]
Hello, I'm running into the same issue, I can't find an installation link for java 16 without having to create a java account, I have java 17 installed but it doesn't look like it works with java 17, any help with this would be very much appreciated. It worked initially but I tried changing the downloads folder and I ended up messing up the program and now it doesn't work and is just reporting the same error after deleting the app and reinstalling it.
