### ISSUE TITLE
Spotiflyer not working - Android

### ISSUE THREAD

**Issue by bartosrichard** [Shabinder/SpotiFlyer#2417]
### Discussed in https://github.com/Shabinder/SpotiFlyer/discussions/2412

<div type='discussions-op-text'>

<sup>Originally posted by **bartosrichard** March  1, 2023</sup>
Hey everyone,
so I've used Spotiflyer in the past, everything was working well, I had no problems whatsoever, every download worked, except for rare exceptions. Last week I wanted to download some album from Spotify, so I did the usual paste link and download all, but to my surprise, all of the downloads failed, I tried another album, all failed again, after multiple tries with different albums, either all of them failed or one, max two songs downloaded. Really frustrating honestly, does anyone have any idea to fix this?
I am using the latest android version (3.6.3), trying to download from Spotify, I will provide any information if needed.
Sorry for any mistakes that could've occured in my text, I was in a rush sort of.</div>

**Comment by FQQD** [comment]
i seem to have the same problem, downloads from yt music dont work either

**Comment by bartosrichard** [comment]
> i seem to have the same problem, downloads from yt music dont work either

yeah, i just checked, for me it does not work either

**Comment by KewlAid83** [comment]
Just says invalid link every song I try downloading at all

**Comment by bartosrichard** [comment]
well, i tried using a vpn and when i connect to the us, it works, so solved ig, it works (kinda)

**Comment by AhsanAltaf702** [comment]
Same problem. It always didn't use to a work with Yt music, except of use vpn, but then song quality would be downgraded. From past few weeks, it's not even working with Spotify.

**Comment by br0hit** [comment]
Yup stopped working
