### ISSUE TITLE
[BUG] : Clipping sounds 

### ISSUE THREAD

**Issue by Joefres** [Shabinder/SpotiFlyer#2449]
When a song is downloaded and played from Spotify. There seems to be a clip sound on the track at about 10 seconds into to the song.

**Comment by ericsomto** [comment]
Reinstall app

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
