### ISSUE TITLE
VIRUS

### ISSUE THREAD

**Issue by So2K** [Shabinder/SpotiFlyer#2450]
This application is a virus, why is it so unstable, is such a simple task made as crooked as possible

**Comment by ericsomto** [comment]
Why are you being retarded rn ?
Just pay for Spotify premium instead of using the app

**Comment by Arnavxoxo** [comment]
> This application is a virus, why is it so unstable, is such a simple task made as crooked as possible

Worked fine for me

**Comment by Arnavxoxo** [comment]
Downloaded a playlist of 150 songs

**Comment by So2K** [comment]
> [ericsomto](/ericsomto)

That's the thing, I decided to try this app, but I wish I hadn't, because it's a virus from the Hindus, it's easier to pay the Spotify dough

**Comment by FurhadTheNerd** [comment]
Hindus virus? 😭
so what if it's made by a guy overseas? at least they're more talented than all of us

**Comment by ericsomto** [comment]
> > [ericsomto](/ericsomto)
> 
> That's the thing, I decided to try this app, but I wish I hadn't, because it's a virus from the Hindus, it's easier to pay the Spotify dough

Contribute to the windows version and improve it

**Comment by So2K** [comment]
> > > [ericsomto](/ericsomto)
> > 
> > That's the thing, I decided to try this app, but I wish I hadn't, because it's a virus from the Hindus, it's easier to pay the Spotify dough
> 
> Contribute to the windows version and improve it 


Dude, I hope you're kidding? What kind of contribution can there be? In the best case, it is necessary to completely demolish this repository and do everything from scratch. It's complete nonsense to make a program on java, so that there would be compatibility on all platforms, and the most carbon monoxide, why is there a web, why is the program on java, but at the same time the ui is web, how can you think of this

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
