### ISSUE TITLE
[BUG] : <Download failed>

### ISSUE THREAD

**Issue by Skilifer** [Shabinder/SpotiFlyer#2472]
I tried to download the song but it said something went wrong 

https://music.youtube.com/watch?v=YTCS7IWUJu8&feature=share

I expected that the song will download, the link to which I inserted into your application

 - Device:   Xiaomi Redmi Note 10 Pro
 - OS: MIUI Global 13.0.16 (Android 12)
 - Version:   3.6.3
 - Country: Ukraine 

Everything worked without errors before. Also I tried to download other songs but it failed.

**Comment by ericsomto** [comment]
Try using a VPN

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
