### ISSUE TITLE
Problem with lengthy audio

### ISSUE THREAD

**Issue by Makerkiddo** [Shabinder/SpotiFlyer#2486]
When downloading a 30 minute audio, it just skips the entire song exactly at the 7:50 mark. Is this an issue with Samsung Music, or is it some sort of limiting thing that someone would have to pay to download full songs?

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
