### ISSUE TITLE
Fix the issue of songs not being the song i waited to download 

### ISSUE THREAD

**Issue by Uytuuu** [Shabinder/SpotiFlyer#2504]
When you download a song it ends up being a completely different song. For example.  I downloaded side A (Old )
By Danny brown and it ended up being Grown Up by the same artist

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
