### ISSUE TITLE
[BUG] : hy friends need help please

### ISSUE THREAD

**Issue by Argee74** [Shabinder/SpotiFlyer#2506]
In the last time so much tracks on spotiflyer gaves me error.
Have all the same problem ore only me self?
Before 2-3 mounths earlier i dont have this problem. 
 What must i do if i get an error
![Screenshot_20230317_005740](https://user-images.githubusercontent.com/127552587/225778769-f372f808-e36c-47db-b133-e2c308f652d0.jpg)

	READ THIS!
	If some Song Download Failed with StackTrace having any of the following reason:
		- DownloadLinkFetchFailed(trackName=For Those About to Race, jioSaavnError=java.util.NoSuchElementException: Collection is empty., ytMusicError=MP3ConversionFailed(extraInfo=Client request invalid: 404 Not Found. Text: "Not Found", message=MP3 Converter unreachable, probably BUSY !
			- Please Dont Open issue! , Online Converter Was Busy! , try again after some time and download will be successfull . 
-->

**Describe the bug:**

**Media Links Used:** 

**Expected behavior**

**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   [e.g. iPhone6, Samsung J2, PocoF1]
 - OS:   [e.g. iOS, Android 10, WinOS, MacOS]
 - Version:   [e.g. 3.2.1]
 - Country: [eg: India, will help in detecting if service is accessible to u]

**Additional context:**

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
