### ISSUE TITLE
[BUG] : The sound/audio of the song I downloaded doesn't match

### ISSUE THREAD

**Issue by jainalmustaqin** [Shabinder/SpotiFlyer#2507]
**Describe the bug:**
When I download a song from Spotify via Spotiflyer, but when the sound or audio is played, the song doesn't match what I hear on Spotify 
**

**Media Links Used:** 
https://open.spotify.com/track/3yb0g36d1nOcnlgOPR6cnn

**The results of the songs I downloaded via Spotiflyer **
https://drive.google.com/file/d/18qOXc6LZEypTH6qGvB18_6lHMaEGwHWL/view

```

**Device Info (please complete the following information):**
 - Device:   Realme C33
 - OS:   Android 12
 - Version:   3.6.3
 - Country: Indonesian

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
