### ISSUE TITLE
[BUG] : <spotify stopped cause they changed the link type>

### ISSUE THREAD

**Issue by rormo34** [Shabinder/SpotiFlyer#2521]
Now you cant download from Spotify cause they changed the link from something like this " https://open.spotify.com/track/2lnzGkdtDj5mtlcOW2yRtG " to this "https://spotify.link/Fi0wU8OAiyb" and the app can't understand it .

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
