### ISSUE TITLE
Suggestion for new features 

### ISSUE THREAD

**Issue by Chand5y** [Shabinder/SpotiFlyer#2528]
Please Collab with xManager's Spotify and bring an option to download songs within the xManager's Spotify.

Or 

Can develop a good UI for playing music from Spotify and yt music within Spotiflyer

**Comment by owencz1998** [comment]
Use spotube

**Comment by owencz1998** [comment]
Use spotube 

https://github.com/KRTirtho/spotube

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
