### ISSUE TITLE
[BUG] : Main screen is white when lunch the app in windows

### ISSUE THREAD

**Issue by VahidDopler** [Shabinder/SpotiFlyer#2539]
![image](https://user-images.githubusercontent.com/77194408/226743398-381f8e45-a06e-4e9e-92d8-5a84e1407835.png)

**Comment by ericsomto** [comment]
It's from your device 
Reinstall the app

**Comment by VahidDopler** [comment]
i have did it but did not work

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
