### ISSUE TITLE
[BUG] : Spotiflyer won't open "Failed to launch JVM"

### ISSUE THREAD

**Issue by Cerberus-75** [Shabinder/SpotiFlyer#2549]
**Describe the bug:**

When trying to open the app, the error message "Failed to launch JVM" appears and then nothing happens.

**Media Links Used:** 
N/A

**Expected behaviour**
The app should open with no errors

**Screenshots:**
![image](https://user-images.githubusercontent.com/39175672/227185173-18959b53-06ba-4e04-896a-b26cbf8524da.png)

**StackTrace:**
N/A

**Device Info (please complete the following information):**
 - Device:   Desktop Computer
 - OS:   Windows 10
 - Version:   3.6.3
 - Country: Australia

**Additional context:**
I have attempted re installing the program, which hasn't worked and I am using openJDK 17 for java.
```
openjdk version "17.0.6" 2023-01-17 LTS
OpenJDK Runtime Environment Corretto-17.0.6.10.1 (build 17.0.6+10-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.6.10.1 (build 17.0.6+10-LTS, mixed mode, sharing)
```

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
