### ISSUE TITLE
Prevent duplicate Songs

### ISSUE THREAD

**Issue by BLACK4585** [Shabinder/SpotiFlyer#2556]
**Is your feature request related to a problem? Please describe.**
When I download my personalized playlists from Spotify from time to time, it obviously downloads some songs multiple times within different folders. This results in playing a song twice or more when playing in eg. in alphabetical order.

**Describe the solution you'd like**
It would be nice to enable a feature, that prevents downloading a song twice or more. A nice feature would be to be able to disable and enable the feature because sometimes you may need a playlist fully. For that it would be great to be able to change this setting when downloading a playlist, so for every playlist for its own. When I enter a playlist, SpotiFlyer should recognise the same songs even in the other playlist-folders it downloaded. Should not be hard since they are all in the same folder. On the other hand is it bad to scan every time you download a new playlist through all folder. So a better approach would be to store all downloaded songs in a file, better in a local DB for more performance.

**Describe alternatives you've considered**
Manually deleting duplicate songs :(

**Additional context**
~ Silence ~

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
