### ISSUE TITLE
[BUG] : spotify link change simple fix

### ISSUE THREAD

**Issue by TheStezusChrist** [Shabinder/SpotiFlyer#2573]
Spotiflyer is unable to process Spotify links due to Spotify changing their link format.

Link change 
Old/working link: https://open.spotify.com/playlist/37i9dQZF1EIZ1M2OKH95ZA?si=G4uinjD2Rni3r88KkRXz6Q&utm_source=copy-link

New/non-working link format :
https://spotify.link/7BXMTaUpkyb

Expected behavior
Pull and download the music/playlists from the link 

Screenshots:![Screenshot_20230327_133615.jpg](https://user-images.githubusercontent.com/128417893/228036365-d5d55509-060a-4456-83be-e17e3b40fe59.jpg)

![Screenshot_20230327_132746.jpg](https://user-images.githubusercontent.com/128417893/228036457-3d6c8a29-67e4-4f36-93cb-af0f277478ca.jpg)

Device Info/information
 - Device: Samsung A51
 - OS:  Android 13 
 - Version: REV1.0
 - Country: United States

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
