### ISSUE TITLE
[BUG] : DL Error

### ISSUE THREAD

**Issue by derangedstone** [Shabinder/SpotiFlyer#2583]
**Describe the bug:**
download error

**Media Links Used:** 
https://open.spotify.com/playlist/0qL6VBO1FL5C86LzNSedAz?si=c75d5ca9128b4e86

**Expected behavior**
expected the song to download

**Screenshots:**
![2023-03-29 17_31_25-Window](https://user-images.githubusercontent.com/72117478/228697831-a7028d85-13b0-47cb-8875-c12066e1b92a.png)

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info:**
 - Device:   Dell Inspiron 3880
 - OS:   Windows 10 Pro
 - Version:   3.6.3
 - Country: US

**Additional context:**

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
