### ISSUE TITLE
!!!!Note to all leaving bug reports!!!!

### ISSUE THREAD

**Issue by TheStezusChrist** [Shabinder/SpotiFlyer#2585]
Remember he is rewriting the coad for the app so be patient and wait on bug reports if you see alot of the same report being made for a little bit till he releases the next version

**Comment by LaVoieLactee** [comment]
How do you know he rewrote it? The latest version dates from October 2022 ^^'

**Comment by TheStezusChrist** [comment]
> How do you know he rewrote it? The latest version dates from October 2022 ^^'

Look at the spotiflyer github description that was put there like 3 weeks ago

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
