### ISSUE TITLE
[BUG] : Unable to download wnload songs 

### ISSUE THREAD

**Issue by VinayDhariwal07** [Shabinder/SpotiFlyer#2588]
It shows an error message everytime I try to put a playlist link, it used to work perfectly fine a couple months ago and this has been an issue after an update 
I have attached a screenshot of the message please look into it 
![Screenshot_20230401_191238](https://user-images.githubusercontent.com/124115536/229293027-0171904a-8e59-49ca-90c7-49c5de350c00.jpg)

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
