### ISSUE TITLE
[Feature-Request]: web version 

### ISSUE THREAD

**Issue by AadiVIP** [Shabinder/SpotiFlyer#2589]
I would like to have web version hosted on my website.

**Comment by s0mt0chukwu** [comment]
No

**Comment by AadiVIP** [comment]
Why

**Comment by s0mt0chukwu** [comment]
Not necessary

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
