### ISSUE TITLE
[BUG] : `xdg-desktop-menu: no writable system menu directory found` `post-installation script subprocess returned error exit status 3`

### ISSUE THREAD

**Issue by ghost** [Shabinder/SpotiFlyer#2600]
**Describe the bug:**

I can't install Spotiflyer with `sudo dpkg -i <spotiflyer>`. I get an error message from xdg-desktop-menu and from the .deb file's post-installation script.

**Media Links Used:** 

None

**Expected behavior**

I expected dpkg to install it to my system normally like I did before on a different debian based distro.

**Screenshots:**

![spotiflyer-bug](https://user-images.githubusercontent.com/117995066/229654044-eda7c14f-50d4-425c-bc4e-6bc3a6db6b47.png)

**StackTrace:**
Not installed

**Device Info (please complete the following information):**
 - Device: Laptop
 - OS:   Devuan GNU/Linux, using openrc.
 - Version:   3.63
 - Country: U.S.

**Additional context:**

I'm using dwm as my window manager.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
