### ISSUE TITLE
[Feature-Request]: <Adapt Spotiflyer Icon to Android 13 Icon Monet Theme Material You> 

### ISSUE THREAD

**Issue by ismaelbachicha** [Shabinder/SpotiFlyer#2608]
![Screenshot_2023-04-07-10-25-50-046_com miui home-edit](https://user-images.githubusercontent.com/130060028/230528298-b47d7a95-d593-4adc-9670-1e53699c1378.jpg)

Dear Spotiflyer Dev,

Can you adapt your icon to new Android 13 icon monet theme, material you? Because your icons are so boring, not totally dynamic when I change wallpapers to my phone based on Android 13 OS. Please adapt some changes. Thank you. 🙂

Sincerely yours,
Spotiflyer User
#2607

**Comment by snxw9** [comment]
What's the name of the theme

**Comment by ismaelbachicha** [comment]
https://9to5google.com/2022/12/09/android-13-themed-icons/

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
