### ISSUE TITLE
[BUG] : can't download anything

### ISSUE THREAD

**Issue by bluemadeliefje** [Shabinder/SpotiFlyer#2612]
**Describe the bug:**
I can't download anything with spotifyer at this moment. Tried to install and uninstall true the installer on my PC. The faultcode is:

Client request: (link to track/playlist). Invalid: 429 Too Many.

I first tried to download on my old laptop as well as on my new laptop. Both give the same error.

**Media Links Used:** 
I have this with every playlist and track, for example: 
https://open.spotify.com/playlist/5oazrHeJ9TBBrwVqJSZ3uB?si=cf67fc90a9874d59 
https://open.spotify.com/track/1jaVdF0FSPTWi8E4MWiLPR?si=00364c6a10784881

**Expected behavior**
I expected to happen that Spotifyer searched the playlist and tracks, so I can download it ^^

**Device Info (please complete the following information):**
 - Device:  Lenovo Ideapad 5 and my older HP laptop 
 - OS:   Windows 11 Home, but same problem on my older Windows 10 laptop.
 - Version:   Windows 11 Home 22HZ, version of Windows of my other laptop unknown.
 - Country: Netherlands

I hope you can help me, thank you!

**Comment by 8eS3rz4sDu8oUx4q39hhv8o2k2e72dkb** [comment]
The app is broken. Just move it to the bin.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
