### ISSUE TITLE
[BUG] : Wrong song version

### ISSUE THREAD

**Issue by SteelyxYT** [Shabinder/SpotiFlyer#2616]
When I download the songs discord and still alive, I get the wrong versions.

**Describe the bug:**
 In the song still alive, there is supposed to be a robotic voice singing the song from the portal game but I get at normal human voice and discord starts in an unexpected way as the song I have has a more catchy start.

**Media Links Used:** 
 https://open.spotify.com/playlist/4rqqE6Iz5MYgNFsbmSDCGu?si=g94UwuJeR9a2ZXDZdSFhJA
 

**Expected behavior**
I expected to have the same song as the one in my playlist

**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information): [samsung a71]
 - OS:   [android 13]
 - Version:   [3.6.3]
 - Country: [norway]

**Additional context:**

**Comment by backisnickel** [comment]
Same issue here... The version of the song downloaded is completely different then the one in the link copied...can you help pls.....

Link copied - https://open.spotify.com/track/3O3txttHVdh3sNEDt2yANj?si=O6Ww8RhITk-H8K0KcmcXWw&dd=1

Song downloaded -https://open.spotify.com/track/5nVNFm9Dzowgkr5X3N46Gv?si=Uy2Js06-RBGcgsE-PelIUQ&dd=1

**Comment by SteelyxYT** [comment]
Yeah I found what song version it was. It was a cover of the same song made by caleb hymes.
https://open.spotify.com/track/4eSUtLppXk5YgUz3rL8Rpt?si=76e273998aa347b2
Still don't like the cover though

**Comment by backisnickel** [comment]
I know the song I want to download, however when I share the entire playlist and start downloading the songs it does not pick up the correct version of the song.



⁣Get BlueMail for Android ​

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
