### ISSUE TITLE
Add rpm and appimage desktop targets

### ISSUE THREAD

**Issue by rahul-gill** [Shabinder/SpotiFlyer#2618]
So we can use them in another linux distributions without doing `java -jar`

**Comment by henrikbeck95** [comment]
Why not just adding an alias on your `.bashrc` or `.zshrc` file?

- `.bashrc` file
```bash
alias spotifly='java -jar ${HOME}/SpotiFlyer/SpotiFlyer-linux-x64-3.6.3.jar'
```

- Reload the terminal settings
    $ `. ~/.bashrc`

- Execute
    > $ `spotifly`

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
