### ISSUE TITLE
[Feature-Request]: include song uri, song id, shareurl into song metadata 

### ISSUE THREAD

**Issue by aguetkriegerisch** [Shabinder/SpotiFlyer#2622]
I have been using this application for almost a year now and it is one of the best I have used so far. However, I would like to organize all my music by genre, and this information is either inconsistent or not present in the metadata of the downloaded file. It would be a good idea to:

1- Address this issue by ensuring that all songs have their genre included in the metadata.

OR

2- Include the songId and/or URL from where the file was downloaded in the metadata, so that the Spotify API, for example, can be used later to obtain the genres associated with that particular song.

example of what im looking for: 
![image](https://user-images.githubusercontent.com/39163176/230944764-06bebb70-d570-41b6-83b9-2e1fd3219963.png)

That tool (music-genre-finder) from chosic.com uses the Spotify API to find the associated genres of a song, but I had to resort to it because those metadata do not exist in the files downloaded through Spotiflyer. It would be great to update the algorithm to query and save that data, or simply add the song's ID/URL/URI to those metadata to later develop a tool that searches and includes the genres within the files.

see:
`https://www.chosic.com/music-genre-finder/`

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
