### ISSUE TITLE
[BUG] : <Issue_Title>

### ISSUE THREAD

**Issue by Xcarry7** [Shabinder/SpotiFlyer#2626]
**Describe the bug:**
 music doesn't Download 

**Media Links Used:** 
 .x. (Album name)

**Expected behavior**
 i want that my music get Download 

**Screenshots:**
Screenshot_20230411-201616](https://user-images.githubusercontent.com/128780369/231253591-75a84e62-7cb0-4c27-a77d-6a37f4899e1c.jpg)

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   [e.g. iPhone6, Samsung J2, PocoF1]
 - OS:   [e.g. iOS, Android 10, WinOS, MacOS]
 - Version:   [e.g. 3.2.1]
 - Country: [eg: India, will help in detecting if service is accessible to u]

**Additional context:**

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
