### ISSUE TITLE
spotiflyer but doesn't download from spotify

### ISSUE THREAD

**Issue by vehosah** [Shabinder/SpotiFlyer#264]
why you called your app spotiflyer,you should have called it youtubeflyer,or saavnflyer

**Comment by null7devllun** [comment]
@vehosah Please describe your problem citing the error exactly as it is shown to you and any other relevant information related.

**Comment by vehosah** [comment]
> 
> 
> @vehosah Please describe your problem citing the error exactly as it is shown to you and any other relevant information related.
my problem exactly is that i tried to download something but the whole album failed and when i managed to download something it sounded like its a video from youtube

**Comment by Shabinder** [comment]
Yup for now songs sources are jio saavn(Preferred) and youtube(Used if not found on other sources)... more sources will be added in future... Stay Tuned
