### ISSUE TITLE
[BUG] : MAC - FFmpeg Path Not Found Arggh!

### ISSUE THREAD

**Issue by VinneyUK** [Shabinder/SpotiFlyer#2661]
**Describe the bug:**
Unable to satisfy the FFmpeg path issues on MAC, despite FFmpeg being installed correctly 

See seenshot - FFmpeg path resolves fine using command: FFmpeg in terminal...

Going bonkers here ....

**Media Links Used:** 
Any

**Screenshots:**

<img width="1363" alt="Screenshot 2023-04-15 at 11 55 17" src="https://user-images.githubusercontent.com/66467679/232209836-51449004-8a09-4d20-bab7-a55316d505c5.png">

**Device Info (please complete the following information):**
 - Device:   MacBook Pro - Intel
 - OS:   MacOS 13.3.1 (22E261)

**Comment by deringeorge4** [comment]
Im having the same issue

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
