### ISSUE TITLE
[Feature-Request]: Material You Support (Android 12+)

### ISSUE THREAD

**Issue by Hidetoshi6721** [Shabinder/SpotiFlyer#2681]
**Is your feature request related to a problem? Please describe.**
The UI looks good in itself, but I would prefer the MD3 design to fit better with Google's Android 12 and higher.

**Describe the solution you'd like**
Implement a working Android 12 Material You theme.

**Describe alternatives you've considered**
None

**Comment by Shabinder** [comment]
A variation using material3 components is being implemented in the re-write,
But for first alpha releases, I am not planning on to include dynamic theming, will consider later if high demand.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
