### ISSUE TITLE
[BUG] : <Issue_Title> song downloading not even starting 

### ISSUE THREAD

**Issue by Sheeeeesshhh** [Shabinder/SpotiFlyer#2684]
![Screenshot_2023-04-17-07-47-17-445](https://user-images.githubusercontent.com/130947112/232362436-8ff92088-64b0-46a4-b4ae-fd303256905d.jpeg)

**Describe the bug:**

**Media Links Used:** 

**Expected behavior**

**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   [e.g. iPhone6, Samsung J2, PocoF1]
 - OS:   [e.g. iOS, Android 10, WinOS, MacOS]
 - Version:   [e.g. 3.2.1]
 - Country: [eg: India, will help in detecting if service is accessible to u]

**Additional context:**

**Comment by TheStezusChrist** [comment]
Try this link 
https://music.youtube.com/watch?v=iNigcLXoSJw&feature=share

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
