### ISSUE TITLE
No Internet Connection Even If Connected to WiFi 

### ISSUE THREAD

**Issue by Dimpleilligirl** [Shabinder/SpotiFlyer#2688]
![Screenshot_20230417_150654](https://user-images.githubusercontent.com/130964898/232410157-be735365-cc8c-4b81-9d40-eb8e1206dc73.jpg)
<!---

**Device Info (please complete the following information):**
 - Device:   Vivo Y20s G
 - OS:   Android 13
 - Version: N/A 
 - Country: Philippines 

**Additional context:**
  Problem started last Saturday, I wanted to download the songs from Playlist with the artist named Kali Uchis, but when I tried it always said that: 'No Internet Connection' even though I am connected to WiFi. I've tried to uninstalled it and deleted the APK on my files and download it again, but it's still the same.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
