### ISSUE TITLE
[BUG] : <Issue_Title> songs are not downloading with Spotify links

### ISSUE THREAD

**Issue by Instagramuser09** [Shabinder/SpotiFlyer#2699]
![Screenshot_2023-04-18-01-12-47-51_034e0326429f3b404601e9b17fbe8654](https://user-images.githubusercontent.com/131041511/232593708-eb0a36ab-97ff-499b-9b67-d401f9c18ad2.jpg)

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
