### ISSUE TITLE
[BUG] : Some songs won't download

### ISSUE THREAD

**Issue by ghost** [Shabinder/SpotiFlyer#2708]
Hi, I have a problem. I was downloading albums from spotify and this happen

---
DownloadLinkFetchFailed(errorTrace=Find Link for UEHARA -FUTOSHI- 

Fetching From Saavn Failed:DownloadLinkFetchFailed(errorTrace=No SAAVN Match Found for UEHARA -FUTOSHI-)
---
DownloadLinkFetchFailed(errorTrace=Find Link for REREREREREREREREMAMAMAMAMAMAMAMA 

Fetching From Saavn Failed:DownloadLinkFetchFailed(errorTrace=No SAAVN Match Found for REREREREREREREREMAMAMAMAMAMAMAMA)
---
DownloadLinkFetchFailed(errorTrace=Find Link for Koino Kinako Watashini Kudasai 

Fetching From Saavn Failed:DownloadLinkFetchFailed(errorTrace=No SAAVN Match Found for Koino Kinako Watashini Kudasai)

**Comment by s0mt0chukwu** [comment]
Uninstall

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
