### ISSUE TITLE
[BUG] : Most of the songs are not downloading 

### ISSUE THREAD

**Issue by RamSekhri** [Shabinder/SpotiFlyer#2717]
Most of the songs are not downloading I can barely download songs from Spotify 
Play list link:  https://open.spotify.com/playlist/37i9dQZF1DWWwF1YkSKLlU?si=SvY8sTX7S_u3cVVj68e5bg&utm_source=copy-link&dd=1

![Screenshot_2023-04-19-07-43-28-22_034e0326429f3b404601e9b17fbe8654](https://user-images.githubusercontent.com/131222733/232948842-18717ab1-a748-4700-b433-ea6398e74f24.jpg)

The ticked songs where downloaded prior to the issue 

**Device Info (please complete the following information):**
 - Device:   Realme 9 se
 - OS:   Android 13
 - Version:   Latest 
 - Country: India

**Additional context:**

**Comment by kushal00011** [comment]
yes same bug here

**Comment by yavnaz** [comment]
Same here for me too

**Comment by Hareshkumar-Y** [comment]
same here

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
