### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by r4ndomico** [Shabinder/SpotiFlyer#274]
All downloading is failing from either Android, x86 or web versions. None versions, better saying.

**Comment by Shabinder** [comment]
? Can you share more info about the issue you facing on order for me to help you better

**Comment by r4ndomico** [comment]
The application doesn't work for me on any device or network I have. It worked the first times, then, stopped. I live in Brazil and this is, by far, the best solution I've ever seen. Wish I could continue using it.

https://user-images.githubusercontent.com/64955578/127104292-2da57153-4155-4abd-9d9b-902bfa52a755.mp4

**Comment by Shabinder** [comment]
@r4ndomico From the video I can see you are using Older Version which has stopped working.

Please Upgrade to Latest.

**Comment by freestyleyt** [comment]
Cómo se puede actualizar soy nuevo en esto?

**Comment by Shabinder** [comment]
https://github.com/Shabinder/SpotiFlyer/releases

**Comment by Shabinder** [comment]
You can also get it from Readme 
: https://github.com/Shabinder/SpotiFlyer#-install click on download button here

**Comment by r4ndomico** [comment]
@Shabinder you're the best!

**Comment by CypherCrypts** [comment]
> You can also get it from Readme : https://github.com/Shabinder/SpotiFlyer#-install click on download button here

Hey @Shabinder 
Can u pls help me, my spotiflyer isn't working when I want to download yt vids. I installed the apk around 4days ago and m already disappointed. Pls help me
