### ISSUE TITLE
possible  Episodes/Podcasts fix(answer on readme.md_

### ISSUE THREAD

**Issue by erik9012** [Shabinder/SpotiFlyer#277]
In the readme is noted: (If You know Any Source for Episodes/Podcasts create an Issue sharing It.) so i want to note that a possible source could be the (cracked) sidify to download podcast. Im using (cracked) sidify version 2.2.4 and its working fine. What you could do so is hosting the most popular podcasts/episodes from spotify on your own server or some free websites to add as download source

screenshots of sidify:

![image](https://user-images.githubusercontent.com/57501353/126550632-2857c5e3-c152-48e5-aef2-aaab47b308ac.png)
![image](https://user-images.githubusercontent.com/57501353/126550858-abc3968d-1ff4-4ce5-8a61-24f0d70c1811.png)
![image](https://user-images.githubusercontent.com/57501353/126550942-5571d02e-60c9-4e88-93d9-8fd700114acb.png)

all of this is just a suggestion. Thanks for this great app

**Comment by erik9012** [comment]
sources for paid sidify are https://www.sidify.de/apple-music-windows/drm-music-converter.html and 1337x.to for cracked some torrent websites

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
