### ISSUE TITLE
[BUG] : Clipping sound / song skips 

### ISSUE THREAD

**Issue by Joefres** [Shabinder/SpotiFlyer#2782]
Hi there, just wondering if anyone else is experiencing this issue. There seems to be a clipping sound at 10 seconds into to the song or the song skips at 10 seconds. I've tired reinstalling the app but still having the same issue. 

 - Device:  Samsung s9 plus 
 - OS:   Android 10
 - Version: 3.6.3
 - Country: Canada

**Comment by Joefres** [comment]
Anyone experiencing this issue. Any feedback would be greatly appreciated.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
