### ISSUE TITLE
[Feature-Request]: Discord server

### ISSUE THREAD

**Issue by Hello11230029** [Shabinder/SpotiFlyer#2783]
**Is your feature request related to a problem? Please describe.**
I have some problems with it and i cant make it work

**Describe the solution you'd like**
If you make a discord I could ask very easily in an support channel 
**Describe alternatives you've considered**
Just make one
**Additional context**
Nope nothing  here

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
