### ISSUE TITLE
No Song downloaded 

### ISSUE THREAD

**Issue by faroukmok** [Shabinder/SpotiFlyer#28]
Hi, 
i'm using the new release 1.8 and the problem still available. 
Device : Oppo Reno 2 
Android Version : V 10.0
![Screenshot_2020-12-05-17-16-01-02_034e0326429f3b404601e9b17fbe8654](https://user-images.githubusercontent.com/22342496/101249613-98ad3700-371d-11eb-96c9-783773418ac9.jpg)

Regards,

**Comment by faroukmok** [comment]
![Screenshot_2020-12-05-17-17-11-94](https://user-images.githubusercontent.com/22342496/101249998-bb3f5000-371d-11eb-9a75-7edfec209cf7.jpg)

The same in notification no changes.

**Comment by Shabinder** [comment]
The Cross Sign Means That No Song Could be fetched for the song you are searching.


**_Causes:_**
- Song Not Available Not YT Music.
- YT Music Not available in your Country.
