### ISSUE TITLE
Not Working 28 April 2023: I Can Not Download Even A Single Song

### ISSUE THREAD

**Issue by rohitsharmaji** [Shabinder/SpotiFlyer#2811]
This app was good, but for some previous days, the app is not working. I can not download any song, maybe there is some big error behind this. 

I request the dev. to fix this ASAP so that we can start using this app once again. If the app is dead, kindly let us know, so we can uninstall it and use any other app.

Thank You.

**Comment by yavnaz** [comment]
Same here. Can't download songs, albums or playlists on Spotify, SoundCloud nor YouTube Music!!!!

**Comment by Shabinder** [comment]
Rewrite is being finalized, will be avlbl for beta testing in a few weeks.
mentioned in github repo's description as well.

So stay tuned.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
