### ISSUE TITLE
[FIX 29-April-2023] not adding a bug or an issue, it's a fix. 

### ISSUE THREAD

**Issue by shanamzzz** [Shabinder/SpotiFlyer#2827]
Hello guys, The VPN trick is working for me. In my case I used INF VPN and set it's location to the Denver city, USA and it's now working. You should try your favorite VPN and see if that trick works for you guys too. Happy Spotifying :)

**Comment by rohitsharmaji** [comment]
You're wrong, this trick is not working.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
