### ISSUE TITLE
[Feature-Request]: organizing multiple disc albums differently

### ISSUE THREAD

**Issue by Mariadevis** [Shabinder/SpotiFlyer#2834]
Hi, when using this solution for a coupla days now, I noticed that multiple disc albums downloaded from spotify had a weird indexation for songs. I guess it's normal in the way it's supposed to be. So, I think what's happening is that the songs from the first disc are indexed from 1 to the number of songs there are, but so are songs from the second discs. The indexes don't follow each other.

Would it be possible to add some kind of value, maybe to the exif data, to recognize which disc is which? Or to add an option to modify indexes automatically to match up ?

Thanks for all the great work anyway, have a good day!

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
