### ISSUE TITLE
[BUG] : Can't download a song.

### ISSUE THREAD

**Issue by Mudasir2299** [Shabinder/SpotiFlyer#2887]
I tried to download a song multiple times without using a VPN and also with using multiple different VPNs. But, i still can't download this song. 
It's on Spotify.
Song Name: Unforgettable
Artists: Ben Cocks, Sid Narbom
Album: On the Block Beats

My Device: Xiaomi Poco F3
Android Version: 13
Spotiflyer Version: 3.6.3

I'm attaching the screenshots and video recordings for you. Please, fix this issue.
It's been 3 months, I've been trying to download this song. But, I can't due to some unknown error.

Hey, I'm trying to attach screenshots and Video recording but it's not happening. I don't know why. Can you give me an email. I'll email you those screenshots and screen recording.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
