### ISSUE TITLE
[BUG] : <Spotify_Songs_Downloading_Failure>

### ISSUE THREAD

**Issue by ajkumar9046** [Shabinder/SpotiFlyer#2895]
**Describe the bug:**

**Media Links Used:** 

**Expected behavior**

**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   Realme Narzo 50
 - OS:   Android 12
 - Version:   V3.0
 - Country:  India

**Additional context:**

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
