### ISSUE TITLE
Force Close

### ISSUE THREAD

**Issue by MANSTER** [Shabinder/SpotiFlyer#29]
I downloaded the latest version of spotiflyer and when i put a link (Any Spotify Track/Playlist Link) for a song the app automatically get closed

I'm using Android 6.0

_Sent from my F1 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Shabinder** [comment]
This Issue Has Been Fixed , A new Version having this and Many Other Bug Fixes are gonna be released Soon.

**Comment by MANSTER** [comment]
Thank you.
And please post it as soon as possible

**Comment by Shabinder** [comment]
New Release **v1.9** Hopefully Fixes the Issue you are facing.
If you still face it please reopen issue.
