### ISSUE TITLE
[Feature Request] Open supported links (Android)

### ISSUE THREAD

**Issue by Flashbrick** [Shabinder/SpotiFlyer#291]
Would be neat if one could click on a link and it opens in SpotiFlyer (on Android).

**Comment by Shabinder** [comment]
click on link where ? 
As of now links can be shared to spotiflyer in order to open them

**Comment by Flashbrick** [comment]
As mentioned in my other issue the sharing does not worked for me (but now it does).

When someone shares me a Spotify Link and I click it, it opens directly in Spotify and plays the song/album. What I want is that instead after clicking the link I go straight to SpotiFlyer and cab download it. (I guess it is called app links or supported web adresses.)

**Comment by ysatyam298** [comment]
> As mentioned in my other issue the sharing does not worked for me (but now it does).
> 
> When someone shares me a Spotify Link and I click it, it opens directly in Spotify and plays the song/album. What I want is that instead after clicking the link I go straight to SpotiFlyer and cab download it. (I guess it is called app links or supported web adresses.)

Yeah this would be great

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
