### ISSUE TITLE
[Feature Request] support tracking links

### ISSUE THREAD

**Issue by Flashbrick** [Shabinder/SpotiFlyer#292]
Sharing links directly from Spotify to SpotiFlyer won't work as the tracking parts are not ignored.

**Comment by Shabinder** [comment]
can you share a link which didnt worked for you

**Comment by Flashbrick** [comment]
> can you share a link which didnt worked for you

Okay I tried to reproduce it now and it worked. Then maybe it was a temporary bug.
And one link it did not worked previously: https://open.spotify.com/album/7tD7zMcFV4rhuCU72PID0Y?si=HiNZbgeVSCyRPhx_NLNCsg&utm_source=copy-link&dl_branch=1

**Comment by Shabinder** [comment]
> Okay I tried to reproduce it now and **it worked**. Then maybe it was a temporary bug.

Closing then.
