### ISSUE TITLE
[Feature Request] add "paste" button

### ISSUE THREAD

**Issue by Flashbrick** [Shabinder/SpotiFlyer#293]
Should be next to the link input field, would be much faster to download several songs/albums/playlists.
(I'm on android, don't know about the other platforms.)

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
