### ISSUE TITLE
[Feature Request] add artist support

### ISSUE THREAD

**Issue by Flashbrick** [Shabinder/SpotiFlyer#294]
Using Spotify I can't download all from one artists and it takes much more time.

**Comment by Shabinder** [comment]
Try in v3.3.0 and it should work:
https://github.com/Shabinder/SpotiFlyer/releases/tag/v3.3.0
https://github.com/Shabinder/SpotiFlyer/tree/main#-install

**Comment by pbanj** [comment]
Would be nice to have this for yt music too.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
