### ISSUE TITLE
[BUG] : <Issue_Downloadling>

### ISSUE THREAD

**Issue by Chittu0** [Shabinder/SpotiFlyer#2940]
![Screenshot_2023-05-12-07-08-38-91_034e0326429f3b404601e9b17fbe8654](https://github.com/Shabinder/SpotiFlyer/assets/133293446/ddf60bef-7b6e-4a50-8ec7-42606c4c09cd)
![Screenshot_2023-05-12-07-08-41-04_034e0326429f3b404601e9b17fbe8654](https://github.com/Shabinder/SpotiFlyer/assets/133293446/9bbe2834-cee6-4c92-a304-028a820e1c79)

**Describe the bug:**

**Media Links Used:** 

**Expected behavior**

**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   [e.g. iPhone6, Samsung J2, PocoF1]
 - OS:   [e.g. iOS, Android 10, WinOS, MacOS]
 - Version:   [e.g. 3.2.1]
 - Country: [eg: India, will help in detecting if service is accessible to u]

**Additional context:**

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
