### ISSUE TITLE
Jiojaavan not work

### ISSUE THREAD

**Issue by mathi300** [Shabinder/SpotiFlyer#295]
Spotiflyer app,
Jiojaavan  copy paste ok, but downloaded not work
Share this link
https://www.saavn.com/p/album/hindi/beta-1991/fRiRC4Z3TWs_

**Comment by Shabinder** [comment]
I just tested it in 3.2.2 version and its working fine 
![Screenshot_20210724-212821_SpotiFlyer](https://user-images.githubusercontent.com/44765050/126874135-2e73148e-0d49-4d00-86d7-9891c7fbce80.png)

**Comment by mathi300** [comment]
3.2.2  version please link

**Comment by mathi300** [comment]
Please link 3.2.2 version

**Comment by rampradhan64** [comment]
### @**PLEASE UPLOAD SpotiFlye3.2.2 version**

**Comment by Shabinder** [comment]
> ### @**PLEASE UPLOAD SpotiFlye3.2.2 version**
> 
> Desktop Vesrion

3.2.2 only contains Android Fix, so 3.2.1 Desktop is latest

**Comment by mathi300** [comment]
Please  send  link : Spotiflyer 3.2.2

**Comment by Shabinder** [comment]
I misspelled , its 3.2.1 : https://github.com/Shabinder/SpotiFlyer/releases/download/3.2.1/SpotiFlyer_v3.2.1_Signed.apk

**Comment by mathi300** [comment]
> I just tested it in 3.2.2 version and its working fine
> ![Screenshot_20210724-212821_SpotiFlyer](https://user-images.githubusercontent.com/44765050/126874135-2e73148e-0d49-4d00-86d7-9891c7fbce80.png)

Jiojaavan not work 3.2.1
![Screenshot_2021_0727_134106](https://user-images.githubusercontent.com/87803584/127120009-3401d147-34ad-488d-8f77-775490d8fe9a.jpg)
