### ISSUE TITLE
SPOTIFLYER BEEN KILLED OFF? : NO

### ISSUE THREAD

**Issue by yavnaz** [Shabinder/SpotiFlyer#2958]
I received an email stating that it was dead. Is this true? If so, please let us all know.

**Comment by Shabinder** [comment]
No its not dead, I am actively finalizing the rewrite, so please stay tuned for
a few weeks.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
