### ISSUE TITLE
Songs from gaana are  being downloaded in 192kbps only

### ISSUE THREAD

**Issue by ysatyam298** [Shabinder/SpotiFlyer#298]
I just updated to the latest version 3.2.1 and tried downloading a song from gaana.com and it downloaded in 192 kbps but a few days ago i was able to download the same song in 320kbps on version 3.2.0 but now even that version is not working and is showing download failed
Happening on both android 10 and 11

**Comment by praphul4u** [comment]
Not only gaana. Even spotify also downloading at 192 only. But YouTube music works perfect at 320

**Comment by Shabinder** [comment]
Share Link where you are encountering this issue

**Comment by praphul4u** [comment]
https://open.spotify.com/track/1R6A1G9lbmXnTlKEmpeLUt?si=sT5TV6LUTVy2l5uLPRdlMw&utm_source=copy-link&context=spotify%3Auser%3Aspotify%3Aplaylist%3A37i9dQZF1DXd8cOUiye1o2&dl_branch=1


downloads without any issue. When I check bitrate in poweramp it's just 192kbps. Same with all songs from Spotify and gaana

**Comment by ysatyam298** [comment]
> Share Link where you are encountering this issue

![Screenshot_20210727-101135](https://user-images.githubusercontent.com/87985869/127096679-0bdf2950-47f9-48da-85e2-66ec0592df0c.png)
https://gaana.com/song/tere-bina-zindagi-se-1
I was able to download this song in 320kbps 1 month ago but now its being downloaded in 192kbps only

**Comment by ysatyam298** [comment]
> https://open.spotify.com/track/1R6A1G9lbmXnTlKEmpeLUt?si=sT5TV6LUTVy2l5uLPRdlMw&utm_source=copy-link&context=spotify%3Auser%3Aspotify%3Aplaylist%3A37i9dQZF1DXd8cOUiye1o2&dl_branch=1
> 
> downloads without any issue. When I check bitrate in poweramp it's just 192kbps. Same with all songs from Spotify and gaana

Same with me

**Comment by Shabinder** [comment]
Try in v3.3.0 and it should work:
https://github.com/Shabinder/SpotiFlyer/releases/tag/v3.3.0
https://github.com/Shabinder/SpotiFlyer/tree/main#-install
