### ISSUE TITLE
[Can't search for the playlist] : <Searching for spotify playlist>

### ISSUE THREAD

**Issue by mangoman1403** [Shabinder/SpotiFlyer#2998]
**Describe the bug:**
Cant search for any spotify playlist

**Media Links Used:** 
<https://open.spotify.com/playlist/2WPjvzSSmy6zD3irOanvo4?si=61f67d89a44d47e0>

**Expected behavior**
I expected to search for my playlist and download the songs so that i could listen to them while travelling

**Screenshots:**
https://i.imgur.com/pwSryqr.png

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   [Dell Laptop-Latitude E7440]
 - OS:   [Windows 10]
 - Version:   [3.6.3]
 - Country: [India]

**Additional context:**
I was having the FFmpeg path not found bug before this, downloaded ffmpeg and sorted that out. Tried to download my playlist but it wont let me even search for it. ELPPPP!!!!!!

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with 
our new 
plugins.

**Comment by mangoman1403** [comment]
I'm using the windows version of spotiflyer, soundbound is only available
for androids currently.... Any other fix?
