### ISSUE TITLE
Failed Download

### ISSUE THREAD

**Issue by fjonadex** [Shabinder/SpotiFlyer#3009]
DownloadLinkFetchFailed(errorTrace=Find Link for Abandoned clouds 

Fetching From Saavn Failed:DownloadLinkFetchFailed(errorTrace=No SAAVN Match Found for Abandoned clouds)
	at com.shabinder.common.providers.saavn.requests.JioSaavnRequests$DefaultImpls.findBestSongDownloadURL(JioSaavnRequests.kt:44)
	at com.shabinder.common.pro

**Comment by thealidev** [comment]
I have this issue to

**Comment by thealidev** [comment]
Use vpn

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new plugins.

**Comment by anivoooodh** [comment]
where can i get the plugins

**Comment by Shabinder** [comment]
follow video installation (Install all providers)
https://soundbound.shabinder.in/install
