### ISSUE TITLE
Spotiflyer is discontinued, please install Soundbound with our new plugins.

### ISSUE THREAD

**Issue by s0mt0chukwu** [Shabinder/SpotiFlyer#3010]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.

_Originally posted by @Shabinder in https://github.com/Shabinder/SpotiFlyer/issues/2239#issuecomment-1555445302_

**Comment by marcofeltmann** [comment]
As mentioned in https://github.com/Shabinder/soundbound-extensions-lib/issues/1 I'm **unable** to switch to Soundbound as I won't infect my LineageOS with Google Stuff.

Please provide an alternate source, i.e. F-Droid.

**Comment by Shabinder** [comment]
#3013

**Comment by loca-file** [comment]
Hey, how I can install Soundbound on PC? Still getting errors despite installing FFmpeg, I know that Spotiflyer is discontinued, i'm just looking for a way to download some tracks that aren't available in my country.

**Comment by EvilYtGuy** [comment]
Which plug-ins do I need to install?

**Comment by Silvergish** [comment]
Well this sucks. I just learned about SpotiFlyer and it's discontinued. I was hoping to install it on MacOS. I don't use Android so I'm unable to install Soundbound.

**Comment by Shabinder** [comment]
Soundbound will eventually be avlbl on multiple platforms.

**Comment by fschaupp** [comment]
@Shabinder Is there an option to mark the app as dicontinued/moved on FDroid? I (as a typical user) wouldn't have checked on Github. 
Maybe there is a way to let the usebase know via in-app banner or FDroid store, it was moved to an other project.

**Comment by TadyHUN** [comment]
Downloaded a supposed to be PC version of Soundbound from "https://soundbound.dev/pc/" but it came down as this:
"Soundbound _ Music and Songs._0.0.29_soundbound.dev.apk"

**Comment by Shabinder** [comment]
> Downloaded a supposed to be PC version of Soundbound from "https://soundbound.dev/pc/" but it came down as this: "Soundbound _ Music and Songs._0.0.29_soundbound.dev.apk"

That is **NOT** the official site.

**Comment by AkitaAttribute** [comment]
Soundbound official website is sketchy looking.  Maybe put some effort into making your website not look like malware distribution.  Make the website for Spotiflyer redirect to the new app.  

You're still getting new bug reports because you decided to leave an open graveyard of apps that appear to be functional. 

This github repo is misleading also, as you didn't make a deprecated message in the readme.  So you have to sift through the Issues tab in order to find that it's actually dead. 

Instead you just decided to leave it un-depricated with an advertisement for soundbound at the top of the Readme.  Look at how the community on Github handles this, and you'll find that this is entirely inappropriate.

**Comment by Shabinder** [comment]
@AkitaAttribute 
 > Make the website for Spotiflyer redirect to the new app.

 I am not the owner of that website or operated by me, its some 3rd party website
 
</br>
</br>


> Soundbound official website is sketchy looking. Maybe put some effort into making your website not look like malware distribution

What do you mean, elaborate pls, I believe you are referring to ads there r8?, thats there to support me, as both the apps are **totally free & without ads**, when we do setup a tier/patron system and get reasonable support, the ads will be removed on the site as well, a user might go to the site for a very short duration, so I guess ads doesn't hurt that much.
 

</br>
</br>

> This github repo is misleading also, as you didn't make a deprecated message in the readme. So you have to sift through the Issues tab in order to find that it's actually dead.

Its mentioned in the top para of ReadME.md, see below image.
<img width="871" alt="image" src="https://github.com/user-attachments/assets/e585828d-8094-4a5f-9bff-b87ffecab3a5">

**Comment by 42willow** [comment]
For those looking for an alternative open source version to this discontinued project I'd personally recommend checking out [spotdl](https://github.com/spotDL/spotify-downloader), it uses the spotify API to fetch songs and find equivalents on youtube, then downloads them using [yt-dlp](https://github.com/yt-dlp/yt-dlp) as the backend (still actively maintained)

Although spotify's free plan offers a slightly higher bitrate of 160kbps as opposed to the 128kbps of youtube music (AFAIK) the difference shouldn't really be noticeable

Disclaimer: remember to be mindful of copyright and terms of service when downloading
