### ISSUE TITLE
[BUG] SD card no permission

### ISSUE THREAD

**Issue by GuentherGmbHHD** [Shabinder/SpotiFlyer#303]
**Describe the bug**
I can't download Songs instantly to SD card (No permission although permission is enable/ no request for external storage permission)

Make sure the app download instantly to SD card (option exist but doesn't work)

**Screenshots**
If applicable, add screenshots / screenrecording to help explain your problem.

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   [LG K41s]
 - OS:   [Android (10)]
 - Version:   [e.g. 3.2.1]

**Comment by GuentherGmbHHD** [comment]
![Screenshot_20210728-164904](https://user-images.githubusercontent.com/62447563/127346705-58fd4247-20a2-4f62-a974-0f338b285c07.png)

**Comment by alireza1385mamani** [comment]
Me too I have I have the same issues as others have

**Comment by Shabinder** [comment]
Its already been discussed and marked as wont-fix , for reasons behind that decision refer : #116
