### ISSUE TITLE
Some JioSaavn links don't work.

### ISSUE THREAD

**Issue by Nurmengardian** [Shabinder/SpotiFlyer#304]
I am a new user of the app and was simply trying out links from different sources, but found that **no JioSaavn URLs were working at all.** Maybe I'm using the wrong format but please check:
This is a sample link: https://www.jiosaavn.com/song/sach-keh-raha-hai/NlERBTVXeVY

The error is thrown as a toast message saying **Not a valid link**

Kudos on the great app, btw! Awesome work!

**Comment by mathi300** [comment]
> I am a new user of the app and was simply trying out links from different sources, but found that **no JioSaavn URLs were working at all.** Maybe I'm using the wrong format but please check:
> This is a sample link: https://www.jiosaavn.com/song/sach-keh-raha-hai/NlERBTVXeVY
> 
> The error is thrown as a toast message saying **Not a valid link**
> 
> Kudos on the great app, btw! Awesome work!

Kudos app please link

**Comment by Shabinder** [comment]
> Kudos app please link

What ?

**Comment by mathi300** [comment]
Jiojaavan not work

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
