### ISSUE TITLE
[BUG] : <only a few songs get downloaded>

### ISSUE THREAD

**Issue by xdFazy** [Shabinder/SpotiFlyer#3040]
**Describe the bug:**
Only a handful of songs from playlist are downloaded successfully 

**Media Links Used:** 
https://open.spotify.com/playlist/26jzYFTCacnjSKswd0Ithe?si=731740a30ce345f6 

**Expected behavior**
That all songs are being downloaded, not just a few 

**Screenshots:**

![image](https://github.com/Shabinder/SpotiFlyer/assets/85610968/6d92c303-31c8-4c70-a094-a801fb626675

**Device Info (please complete the following information):**
 - Device:  PC
 - OS:   WinOS
 - Version:   10
 - Country: Austria

**Additional context:**
My previous error that I had was "no FFMpeg found so I installed FFmpeg on my pc successfully. This is a new error

**Comment by Shabinder** [comment]
#3013
