### ISSUE TITLE
[BUG] : <Issue_Title>

### ISSUE THREAD

**Issue by MultiDaTopG** [Shabinder/SpotiFlyer#3061]
**Describe the bug:**
I press downliad and it will instantly fail to download showing the X mark.

**Media Links Used:** 
https://open.spotify.com/track/4Y4ekj3NtkUogYrIa8KGrT?si=84rvv-wITpKGKOBOjbDBrw&context=spotify%3Aplaylist%3A37i9dQZF1DX2aCk0vzzaZQ

**Expected behavior**
song was expected to download 

**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:  Samsung A73
 - OS: Android 13
 - Country: Qatar

**Comment by Shabinder** [comment]
#3013
