### ISSUE TITLE
[BUG] : MAC does not work

### ISSUE THREAD

**Issue by z0lo13** [Shabinder/SpotiFlyer#3070]
**Describe the bug:**

Nothing happens when Jar run. The Java process starts, but no window or anything

**Media Links Used:** 

**Expected behavior**

**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   MBP 16 2019
 - OS:  MacOS
 - Version:   13.2.1
 - Country: Canada

**Additional context:**

**Comment by Shabinder** [comment]
#3013 
wait for desktop release.
