### ISSUE TITLE
[BUG] : Android - Can't change download path

### ISSUE THREAD

**Issue by mkikets99** [Shabinder/SpotiFlyer#308]
**Describe the bug**
Download path problem: 
Cant select `/storage/emulated/0/Music`
Auto selects `/storage/emulated/0/Music/SpotiFlyer`

**Media Links Used:** 
  _Download works fine_

**Expected behavior**
App grants downloading in `/storage/emulated/0/Music`

**Screenshots**
Ukrainian, but ok...
![Screenshot_20210729-112320.jpg](https://user-images.githubusercontent.com/22869811/127458147-852ba1be-d57f-4ad4-8b52-0e9a8177ed61.jpg)

**StackTrace:**
```
None needed, i guess
```

**Device Info (please complete the following information):**
 - Device:   Samsung Galaxy Note 10 Plus
 - OS:   Android 11
 - Version:  3.2.1

**Additional context**
None

**Comment by Shabinder** [comment]
This is expected behaviour , whenever you choose any directory , It will create a sub Directory SpotiFlyer and then will place media in there in folders like Tracks, Albums, Playlists etc

**Comment by mkikets99** [comment]
Well on any player there is no piont to change that...

Except of Musicolet
Music in this app splits query into folders...
And most of music on my phone is saved in my `/storage/emulated/0/Music` folder...

**Comment by Shabinder** [comment]
I see what you are saying but implementing this change isn't that fruitful hence I wont be considering it as of now , maybe in future as I have plans to build a Music Player into this app as well then maybe we can consider this change but not as of now
