### ISSUE TITLE
[BUG] : Debian Buster can't open Spotiflyer 2.3.0

### ISSUE THREAD

**Issue by dblake76** [Shabinder/SpotiFlyer#309]
**Describe the bug**
SpotiFlyer on Debian Buster can't be started

**Expected behavior**
Should load and show a screen or anything else

**Device Info (please complete the following information):**
 - Device:   Desktop PC
 - OS:   Debian Buster 10.10.
 - Version:   3.2.0 DEB Version

**Additional context**
If trying to start via menuepoint nothing happens, if I try to start via terminal I can see the following error message:
`./SpotiFlyer: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ./SpotiFlyer)`

When I try to install missing components I receive the following:
`sudo apt install libstdc++6
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libstdc++6 is already the newest version (8.3.0-6).
`

Anyone can help?

DBLAKE76

**Comment by Shabinder** [comment]
Can you try with v3.3.0 both deb and jar ?

**Comment by dblake76** [comment]
Tried it with the newest version - works like a charm!

Thanks very much!
