### ISSUE TITLE
Download fails 

### ISSUE THREAD

**Issue by iambatman23** [Shabinder/SpotiFlyer#31]
I'm using android marshmallow. When I try to download any Spotify song, it fails.

**Comment by Shabinder** [comment]
What do you mean by fail? 
A cross sign appears instead of loading?

**Comment by Demosteneus** [comment]
Hi, same issue here.
The last version cannot download any songs.

For some it just says it fails, X appears.
For some the spinning icon keeps spinning forever and nothing downloads.

**Comment by iambatman23** [comment]
Yeah a cross sign appears instead of loading when I try to download Spotify songs. And when I try to download YouTube songs, the app crashes.

**Comment by Shabinder** [comment]
> Yeah a cross sign appears instead of loading when I try to download Spotify songs. And when I try to download YouTube songs, the app crashes.

Youtube section is in **Beta,** so the crashes are because of another library we depend on.

And in Spotify the cross sign shows :
 - Youtube Music is not available in your region. (_UseVPN_)
 - Song could not be found (but this happens rarely on only on some songs) (_Less likely_)

**Comment by Shabinder** [comment]
> Hi, same issue here.
> The last version cannot download any songs.
> 
> For some it just says it fails, X appears.

And in Spotify the cross sign shows 
 - Youtube Music is not available in your region. (UseVPN)   
 - Song could not be found (but this happens rarely on only on some songs) _(Less likely)_





> For some the spinning icon keeps spinning forever and nothing downloads.


This issue has been reported by many others but unfortunately I am not able to reproduce it on my end , I cant fix it until I cant find the cause.

**Comment by iambatman23** [comment]
If I use VPN then the app shows no internet connectivity. And I tried every song of my playlist in my Spotify, all of it failed. But spotiflyer 1.6 version used to download all songs successfully.

**Comment by Shabinder** [comment]
> If I use VPN then the app shows no internet connectivity. And I tried every song of my playlist in my Spotify, all of it failed. But spotiflyer 1.5 version used to download all songs successfully.

Yeah , v1.5 depended on web scarping from youtube so it worked , but the app has moved from Web Scraping to YT Music Api _(Bcuz of Performance causes)_ which unfortunately doesnt work where YT Music is not available.

And the No-Internet on Vpn seems like a bug, can I know which VPN do you use , so I can test .

**Comment by iambatman23** [comment]
I use superVPN

**Comment by Shabinder** [comment]
![image](https://user-images.githubusercontent.com/44765050/101748188-3e7fed80-3af2-11eb-88bf-069b773aef43.png)
I just tried with supervpn and got no error.

**Comment by iambatman23** [comment]
![Screenshot_2020-12-10_162748](https://user-images.githubusercontent.com/75691645/101760256-d71f6900-3b04-11eb-8247-f99287f32b12.jpg)
Yes only with VPN I get internet error

**Comment by jpayne120983** [comment]
Hotspot shield vpn works for me

**Comment by iambatman23** [comment]
![Screenshot_2020-12-10_184352](https://user-images.githubusercontent.com/75691645/101774037-c1676f00-3b17-11eb-93db-2ca0edfb5ca8.jpg)
Still doesn't work for me😢

**Comment by Shabinder** [comment]
Does the issue still persist in v2.0 release?

**Comment by yuukiw** [comment]
Sadly I have this issue, can I provode any logs?

**Comment by Shabinder** [comment]
Due to recent CodeBase Change , V2.2.0 supports Android API 24 and above.
Check Out if this issue still persists in Android API 24 and above in v2.2.0 release.
And No internet issue should also be fixed , hopefully, please check and report back.
