### ISSUE TITLE
[Feature-Request]: <Downloading_Podcasts>

### ISSUE THREAD

**Issue by CoolCrust** [Shabinder/SpotiFlyer#321]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when I am not able to download Spotify original and other Spotify podcasts

**Describe the solution you'd like**

**Describe alternatives you've considered**
No alternatives considered u are the only hope ease include the feature

**Additional context**

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
