### ISSUE TITLE
[BUG] : *Website says "Spotify" instead of "Spotiflyer"*

### ISSUE THREAD

**Issue by HorridModz** [Shabinder/SpotiFlyer#3253]
**Describe the bug:**

The website says "Spotify for PC" instead of "Spotiflyer for PC":

**Expected behavior**

The website should say "Spotiflyer for PC".

**Screenshots:**

![spotifyforpc2](https://github.com/Shabinder/SpotiFlyer/assets/105762560/0d155661-651e-4cc6-97bf-e1434a6ffbb0)
![spotifyforpc](https://github.com/Shabinder/SpotiFlyer/assets/105762560/389e55bd-b9e5-4736-84f6-9dcdf70057cd)

**Device Info (please complete the following information):**

 - Device:   [Computer]
 - OS:   [Windows 10]
 - Version:   [10.0.19045]
 - Country: [United States]

**Comment by Shabinder** [comment]
which website ?

**Comment by HorridModz** [comment]
Nevermind, I realized the website looks to be an unofficial scam. It's https://spotiflyer.app/, and it looks very suspicous.

**Comment by Shabinder** [comment]
Yes, I don't own and control that.
