### ISSUE TITLE
[BUG] : <Issue_Title>unable to download songs

### ISSUE THREAD

**Issue by Amandoc2021** [Shabinder/SpotiFlyer#342]
**Describe the bug**

**Media Links Used:** 
  - Paste Song/Album/Playlist Link where you encountered this issue

**Expected behavior**

**Screenshots**
If applicable, add screenshots / screenrecording to help explain your problem.

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   [e.g. iPhone6, Samsung J2, PocoF1]
 - OS:   [e.g. iOS, Android, WinOS, MacOS]
 - Version:   [e.g. 3.2.1]

**Additional context**

**Comment by Shabinder** [comment]
Please Fill the template with data about issue you are facing

**Comment by b3nsh4** [comment]
> 
> 
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **Media Links Used:** 
>   - Paste Song/Album/Playlist Link where you encountered this issue
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> If applicable, add screenshots / screenrecording to help explain your problem.
> 
> **StackTrace:**
> ```
> Paste Stacktrace here if available
> ```
> 
> **Device Info (please complete the following information):**
>  - Device:   [e.g. iPhone6, Samsung J2, PocoF1]
>  - OS:   [e.g. iOS, Android, WinOS, MacOS]
>  - Version:   [e.g. 3.2.1]
> 
> **Additional context**
> Add any other context about the problem here.
> 

This isn't a way to submit a bug report. Please read the pinned structure and report accordingly.

**Comment by Shabinder** [comment]
Try in v3.3.0 and it should work:
https://github.com/Shabinder/SpotiFlyer/releases/tag/v3.3.0
https://github.com/Shabinder/SpotiFlyer/tree/main#-install
