### ISSUE TITLE
[BUG] : No songs downloading (all errors)

### ISSUE THREAD

**Issue by Jkim1402** [Shabinder/SpotiFlyer#349]
**Describe the bug**

**Media Links Used:** 
  - Paste Song/Album/Playlist Link where you encountered this issue

**Expected behavior**

**Screenshots**
If applicable, add screenshots / screenrecording to help explain your problem.

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   [e.g. iPhone6, Samsung J2, PocoF1]
 - OS:   [e.g. iOS, Android, WinOS, MacOS]
 - Version:   [e.g. 3.2.1]

**Additional context**
Hello, I'm writing about the issue about the download link fetch failed, I tried every day and the same error keeps coming up. 
Using a Samsung galaxy s20
![Screenshot_20210802-214339](https://user-images.githubusercontent.com/82020854/127921702-e74e1230-e05d-4fb1-a29e-fb6f331383b6.jpg)
![Screenshot_20210802-214343](https://user-images.githubusercontent.com/82020854/127921707-0489a4eb-87fb-4d95-8ea6-5faf9afc1d6f.jpg)

**Comment by Shabinder** [comment]
Try in v3.3.0 and it should work:
https://github.com/Shabinder/SpotiFlyer/releases/tag/v3.3.0
https://github.com/Shabinder/SpotiFlyer/tree/main#-install
