### ISSUE TITLE
Doesnt download 

### ISSUE THREAD

**Issue by arslanmali786** [Shabinder/SpotiFlyer#35]
It keeps saying my songs downloads are failing for spotify and then the app crashes

**Comment by sanuwrotethis** [comment]
Downgraded from 1.9 to 1.8 and both times there is nothing coming. No songs or Directory created.

**Comment by Shabinder** [comment]
Please share your device details, and try using 1.5/1.6 as it works for some users facing issue on latest.
I will fix the issue once I get free as , as of now my university exams are coming.

**Comment by sanuwrotethis** [comment]
Using a OP 6t. Version 10.3.7

**Comment by sanuwrotethis** [comment]
Now only images downloads on v1.6, no mp3

**Comment by Shabinder** [comment]
Fixed in v2.0 release.
