### ISSUE TITLE
Please limit duplicate Issues

### ISSUE THREAD

**Issue by b3nsh4** [Shabinder/SpotiFlyer#362]
Please note - This is NOT a feature request/suggestion.

If @Shabinder can control duplicate issues like what we are seeing right now, it will be easy for everyone to find the fix when you reply to any single thread.
Regards!

**Comment by Rodrigolbdo** [comment]
Hola cual sería la contraseña para descargar  musica  de Spotify

**Comment by Shabinder** [comment]
> Hola cual sería la contraseña para descargar musica de Spotify

English Please, there is no kind of password needed and please open another issue to ask if facing any issue

**Comment by Prekunhid** [comment]
Cannot able to download many songs and also mb quality in 320kbps is very low when I compare the song with many many songs fail and more over song mb reduced

**Comment by Prekunhid** [comment]
https://spotify.link/MeEimJMc1yb

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
