### ISSUE TITLE
[ATTENTION HERE] : Use Apk Provided here, until I can fix all issues

### ISSUE THREAD

**Issue by Shabinder** [Shabinder/SpotiFlyer#374]
We use an External 3rd Party **m4a -> mp3 converter** which seems to have changed their API behavior and hence APP is DOWN and not working for the moment.

I request everybody to give me a few days, I will make some time and fix it as soon as possible.(Probably **_this Weekend_**, i.e., by Aug 9)

Please refrain from creating more issues until I fix the app and release a new version.
I appreciate your understanding.

**Comment by Xavier90280** [comment]
Thank You 🙌

**Comment by Elrebono** [comment]
Your awesome. I appreciate your work and thank you for your creation. Will contribute when I get paid. 👍👍

**Comment by felix7droid** [comment]
Keep it up

**Comment by adnanfml** [comment]
Looking forward to it. Thank you for such a great app.

**Comment by HimawariFujiko** [comment]
Thank you! Keep up the good work 👍

**Comment by ujjwal-fsl** [comment]
Bro how long will you tak to solve the issue??

**Comment by Shabinder** [comment]
> Bro how long will you tak to solve the issue??

I am working on this , this is gonna take somewhat longer than expected

**Comment by ujjwal-fsl** [comment]
Ohh,try to solve this fast because your app has alot demand.
I have an Instagram page on which I posted TOP 5 apps not on Play Store and
I'm flooded with DMs of Spotiflyer link, I'm telling everyone that will
send them as soon as it gets fixed.

**Comment by ujjawal30** [comment]
> Ohh,try to solve this fast because your app has alot demand. I have an Instagram page on which I posted TOP 5 apps not on Play Store and I'm flooded with DMs of Spotiflyer link, I'm telling everyone that will send them as soon as it gets fixed.

@ujjwal-fsl bro, I have also come here to checkout this app after seeing a random post on instagram explore section, but it is not working currently.

**Comment by ujjwal-fsl** [comment]
@ujjawal30 Bro you can DM me on @taknikigeek on Instagram, I can help you out for 3-4 days with some alternatives!!

**Comment by adnanfml** [comment]
how much longer? @Shabinder

**Comment by brainyron** [comment]
@Shabinder have you considered adding the option to use ffmpeg if it can be located either in the working directory or on PATH? That way users will have an option to be untethered from the cloud service should it break again.

**Comment by Xavier90280** [comment]
@Shabinder what is ffmpeg?

**Comment by brainyron** [comment]
@Xavier90280 it's a nearly universal media conversion tool.  https://en.wikipedia.org/wiki/FFmpeg

**Comment by Shabinder** [comment]
> @Shabinder have you considered adding the option to use ffmpeg if it can be located either in the working directory or on PATH? That way users will have an option to be untethered from the cloud service should it break again.

Initially we used ffmpeg for same, but it increased App Size significantly and for Desktop Users it will be a root cause for many issues like not being in path, etc.

Thats why I went down on a lane for using 3rd party service and as of now I am building a backend which we will act as a fallback for Media Conversion when primary one fails (Its taking some time and hence might be available in this or next update, will see)

**Comment by brainyron** [comment]
> > @Shabinder have you considered adding the option to use ffmpeg if it can be located either in the working directory or on PATH? That way users will have an option to be untethered from the cloud service should it break again.
> 
> Initially we used ffmpeg for same, but it increased App Size significantly and for Desktop Users it will be a root cause for many issues like not being in path, etc.
> 
> Thats why I went down on a lane for using 3rd party service and as of now I am building a backend which we will act as a fallback for Media Conversion when primary one fails (Its taking some time and hence might be available in this or next update, will see)

What if instead of having it be the default, you only enable it if the user supplies the path to the ffmpeg binary in the settings?  I've seen a lot of apps that handle media that work that way.  This would mean that it doesn't work for mobile apps but I think it would work well for the desktop app.

**Comment by Shabinder** [comment]
> > > @Shabinder have you considered adding the option to use ffmpeg if it can be located either in the working directory or on PATH? That way users will have an option to be untethered from the cloud service should it break again.
> > 
> > 
> > Initially we used ffmpeg for same, but it increased App Size significantly and for Desktop Users it will be a root cause for many issues like not being in path, etc.
> > Thats why I went down on a lane for using 3rd party service and as of now I am building a backend which we will act as a fallback for Media Conversion when primary one fails (Its taking some time and hence might be available in this or next update, will see)
> 
> What if instead of having it be the default, you only enable it if the user supplies the path to the ffmpeg binary in the settings? I've seen a lot of apps that handle media that work that way. This would mean that it doesn't work for mobile apps but I think it would work well for the desktop app.

Yeah that can work good for desktops, Really will be a nice feature to have, can you generate a feature request for this, in future will surely implement this :+1:

**Comment by yotiko** [comment]
@Shabinder  whats the ETA for the update?.
So i could patiently wait for the update 
But keep in mind that you are doing a great job 😁

**Comment by backisnickel** [comment]
> We use an External 3rd Party **m4a -> mp3 converter** which seems to have changed their API behavior and hence APP is DOWN and not working for the moment.
> 
> I request everybody to give me a few days, I will make some time and fix it as soon as possible.(Probably **_this Weekend_**, i.e., by Aug 9)
> 
> Please refrain from creating more issues until I fix the app and release a new version.
> I appreciate your understanding.

Any luck on the fix....

**Comment by Shabinder** [comment]
> Any luck on the fix....


I investigated the issue and apparently the 3rd Party Service has **Stopped their services** for m4a to mp3 conversion, Now I am evaluating other options like, **self-hosting one** or building and **integrating FFMpeg into the app itself** and their pros and cons, If I go with integrating FFMpeg route,
the app release may take some extra time but it will be more stable as It won't rely on 3rd party service.

**Comment by ZukeDST** [comment]
> > Any luck on the fix....
> 
> I investigated the issue and apparently the 3rd Party Service has **Stopped their services** for m4a to mp3 conversion, Now I am evaluating other options like, **self-hosting one** or building and **integrating FFMpeg into the app itself** and their pros and cons, If I go with integrating FFMpeg route,
> the app release may take some extra time but it will be more stable as It won't rely on 3rd party service.

Can you made a temporary ersion where we can download in m4a, and do the conversion job ourselves?

**Comment by al3x-huang** [comment]
> > > Any luck on the fix....
> > 
> > 
> > I investigated the issue and apparently the 3rd Party Service has **Stopped their services** for m4a to mp3 conversion, Now I am evaluating other options like, **self-hosting one** or building and **integrating FFMpeg into the app itself** and their pros and cons, If I go with integrating FFMpeg route,
> > the app release may take some extra time but it will be more stable as It won't rely on 3rd party service.
> 
> Can you made a temporary ersion where we can download in m4a, and do the conversion job ourselves?

This seems like a reasonable workaround if the conversion process will take some time to implement!

**Comment by Shabinder** [comment]
> > Can you made a temporary ersion where we can download in m4a, and do the conversion job ourselves?
> 
> @Shabinder This seems like a reasonable workaround if the conversion process will take some time to implement!

Lemme see if I can wrap up and test the fix soon, if not will share an apk with conversion disabled(no id3 tags / metadata will be there)

**Comment by Jamesk21504** [comment]
> > > Can you made a temporary ersion where we can download in m4a, and do the conversion job ourselves?
> > 
> > 
> > @Shabinder This seems like a reasonable workaround if the conversion process will take some time to implement!
> 
> Lemme see if I can wrap up and test the fix soon, if not will share an apk with conversion disabled(no id3 tags / metadata will be there)

I think we've been waiting long enough and if you can get the app full and functional then a lil more wait is worth it instead of a temp fix

**Comment by ZukeDST** [comment]
> Lemme see if I can wrap up and test the fix soon, if not will share an apk with conversion disabled(no id3 tags / metadata will be there)

@Shabinder have you an idea of the time that will be needed for the release?

**Comment by Shabinder** [comment]
> > Lemme see if I can wrap up and test the fix soon, if not will share an apk with conversion disabled(no id3 tags / metadata will be there)
> 
> @Shabinder have you an idea of the time that will be needed for the release?

Its been two days I have been messing with streamlining FFmpeg for Android so that when shipped in-app it wont bloat and as I have less experience with JNI, I am learning and doing and hence taking time.

If I simply pick someone else prebuilt ffmpeg, App starts working but it goes over 45MB in size. 
So that's the progress update guys

Lets do one thing, I will drop this huge apk here just for the meantime till I figure things out, Sounds Good?

**Comment by adnanfml** [comment]
> > > Lemme see if I can wrap up and test the fix soon, if not will share an apk with conversion disabled(no id3 tags / metadata will be there)
> > 
> > 
> > @Shabinder have you an idea of the time that will be needed for the release?
> 
> Its been two days I have been messing with streamlining FFmpeg for Android so that when shipped in-app it wont bloat and as I have less experience with JNI, I am learning and doing and hence taking time.
> 
> If I simply pick someone else prebuilt ffmpeg, App starts working but it goes over 45MB in size.
> So that's the progress update guys
> 
> Lets do one thing, I will drop that huge apk here just for the meantime till I figure things out, Sounds Good?

Yes please do that. The size doesn't matter that much.

**Comment by Jamesk21504** [comment]
> > > Lemme see if I can wrap up and test the fix soon, if not will share an apk with conversion disabled(no id3 tags / metadata will be there)
> > 
> > 
> > @Shabinder have you an idea of the time that will be needed for the release?
> 
> Its been two days I have been messing with streamlining FFmpeg for Android so that when shipped in-app it wont bloat and as I have less experience with JNI, I am learning and doing and hence taking time.
> 
> If I simply pick someone else prebuilt ffmpeg, App starts working but it goes over 45MB in size.
> So that's the progress update guys
> 
> Lets do one thing, I will drop that huge apk here just for the meantime till I figure things out, Sounds Good?

Can we expect it like today or something?
Sorry for seeming impatient but I've got a whole list  of songs ready by now😅

**Comment by Jokerverse** [comment]
> > > Lemme see if I can wrap up and test the fix soon, if not will share an apk with conversion disabled(no id3 tags / metadata will be there)
> > 
> > 
> > @Shabinder have you an idea of the time that will be needed for the release?
> 
> Its been two days I have been messing with streamlining FFmpeg for Android so that when shipped in-app it wont bloat and as I have less experience with JNI, I am learning and doing and hence taking time.
> 
> If I simply pick someone else prebuilt ffmpeg, App starts working but it goes over 45MB in size.
> So that's the progress update guys
> 
> Lets do one thing, I will drop that huge apk here just for the meantime till I figure things out, Sounds Good?

Sounds great man!

**Comment by ZukeDST** [comment]
> > > Lemme see if I can wrap up and test the fix soon, if not will share an apk with conversion disabled(no id3 tags / metadata will be there)
> > 
> > 
> > @Shabinder have you an idea of the time that will be needed for the release?
> 
> Its been two days I have been messing with streamlining FFmpeg for Android so that when shipped in-app it wont bloat and as I have less experience with JNI, I am learning and doing and hence taking time.
> 
> If I simply pick someone else prebuilt ffmpeg, App starts working but it goes over 45MB in size.
> So that's the progress update guys
> 
> Lets do one thing, I will drop that huge apk here just for the meantime till I figure things out, Sounds Good?

@Shabinder  is it released yet?

**Comment by vehosah** [comment]
https://open.spotify.com/album/2XEkvbWWBneHaMoZ6cx4uo i tried to download which obviously exist on jiosaavn but cant download unfortunately

**Comment by vehosah** [comment]
i used the apk here,but it didn't work

**Comment by Shabinder** [comment]
> 
> 
> i used the apk here,but it didn't work

Yup Its also obsolete now!, almost everything wont work.
BUT.............
I have fixed all bugs including ffmpeg in app, jio-saavn fetching and yt-music too.
So **everybody can expect a release very soon**, just fixing some minor issues here and there now.

**Comment by Shabinder** [comment]
Hey Guys 👋 ,
v3.3.0 is out : https://github.com/Shabinder/SpotiFlyer#-install

Thanks for everyone's patience and support.

**Comment by djsurajguna** [comment]
It is work perfectly but ssometime song is just 30s bit not always when it download from spotify .if you can fix that also this is GOLDEN..But anyway thank for this fix up...It feels so comfortable using this ,special when there is a Genius outthere like you guys  to fix problem...thank you again for fixing this up so fast and accurately
