### ISSUE TITLE
song, circles, would be downloaded without vocals 

### ISSUE THREAD

**Issue by Slowxzy** [Shabinder/SpotiFlyer#383]
**Describe the bug**

when you download the song [circles](https://open.spotify.com/track/6KjegbJPzNRetrgFJiHVMp?si=hjPeHH1CR_yLVLzOHWIB0w&utm_source=copy-link&dl_branch=1) the vocals won't be downloaded instead it will be the background ground music 

**Media Links Used:** 
  - Paste Song/Album/Playlist Link where you encountered this issue

https://open.spotify.com/track/6KjegbJPzNRetrgFJiHVMp?si=hjPeHH1CR_yLVLzOHWIB0w&utm_source=copy-link&dl_branch=1

**Expected behavior**
to download the whole song 

**Screenshots**
If applicable, add screenshots / screenrecording to help explain your problem.

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   Samsung Galaxy A70 
 - OS:   Android 11
 - Version:   3.2.1

**Additional context**

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
