### ISSUE TITLE
YouTube Music links not working (v2)

### ISSUE THREAD

**Issue by yossigrosskopf** [Shabinder/SpotiFlyer#40]
Pasting any links from YouTube music, playlists or individual songs just don't do anything, won't even show the the song information.
Spotify seems to work fine.

(Thanks for your great work)

**Comment by Shabinder** [comment]
Will Add in next update.

**Comment by skylinrcr01** [comment]
Same issue with YTM for me. There are no returned results when I enter a playlist. Thanks for working on this tool btw!

**Comment by skylinrcr01** [comment]
For what it's worth, it actually seems to work fine on my older android phone TA-1052 running pie. My Nokia 6.1 running android Q doesn't work at all though.

**Comment by Shabinder** [comment]
@skylinrcr01 @yossigrosskopf Youtube Music Support has been added in 2.1 release.
check it out and if you face any issues , report them here.

**Comment by yossigrosskopf** [comment]
> @skylinrcr01 @yossigrosskopf Youtube Music Support has been added in 2.1 release.
> check it out and if you face any issues, report them here.

Just tested.
I cannot test playlists at the moment as YTM is giving a server 400 error when trying to share a playlist however I tested it on a single track and full album and it works great.

Thank you for your work

PS: noticed you fixed the notification issues as well, amazing 
Any chance of adding an option to chose the default save location in an upcoming build?

**Comment by Shabinder** [comment]
> PS: noticed you fixed the notification issues as well, amazing
> Any chance of adding an option to chose the default save location in an upcoming build?

I haven't yet fixed the notification issue but will do it in upcoming builds.
Custom location for saving Media. I might do this , but honestly its not on priority list.
Anyway ,**Stay Tuned.**
Never know when i get time and implement these.

**Comment by skylinrcr01** [comment]
Works great for me. Thanks so much for fixing it so quickly.

As for the 400 error, it was doing that for me as well on playlists that were imported from play music. Playlists created in YTM that are public have worked fine for me.

**Comment by yossigrosskopf** [comment]
> 
> I haven't yet fixed the notification issue but will do it in upcoming builds.

Yeah noticed the notification came back after a few minutes and had to force close the app, looking forward to future updates

**Comment by yossigrosskopf** [comment]
> Works great for me. Thanks so much for fixing it so quickly.
> 
> As for the 400 error, it was doing that for me as well on playlists that were imported from play music. Playlists created in YTM that are public have worked fine for me.

Exactly, I actually did a re-run on the play music importer and that fixed it, must have been some bug on imports that were done when they first introduced it.
