### ISSUE TITLE
[Feature-Request]:  Allow ffmpeg to be used for local transcoding on desktop app

### ISSUE THREAD

**Issue by brainyron** [Shabinder/SpotiFlyer#413]
To reduce the dependency on external cloud services, it would be helpful to expose the ability for desktop users to utilize ffmpeg.  This could be exposed via the application settings as a text box where the user would specify the path to the ffmpeg binary.  That way, it is an "advanced users" function and by default the application behavior is the same as it is today -- use the cloud service for transcoding.

See discussion in https://github.com/Shabinder/SpotiFlyer/issues/374 for reference.

**Comment by Shabinder** [comment]
Implemented in v3.3.0, 
Now prebuilt FFmpeg is included in Android app and Desktop App expects FFmpeg in your path
