### ISSUE TITLE
[Feature-Request]: Youtube 'shorts' download

### ISSUE THREAD

**Issue by aha999** [Shabinder/SpotiFlyer#420]
**Is your feature request related to a problem? Please describe.**
Spotiflyer currently can't download [shorts](https://support.google.com/youtube/answer/10059070), or short videos from youtube. One example of a short: https://youtube.com/shorts/9j_yClddjqY

**Describe the solution you'd like**
Enable downloading of youtube shorts.

**Comment by junaidd09** [comment]
I'd like this feature too.

**Comment by Shabinder** [comment]
will look into it.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.

**Comment by aha999** [comment]
@Shabinder is Soundbound open source?
