### ISSUE TITLE
[BUG] : Longer Tracks(8+ minutes) Are Getting Cut Off

### ISSUE THREAD

**Issue by codekarllo** [Shabinder/SpotiFlyer#438]
**Describe the bug**
Songs containing more than 8 minutes are getting cut at this time.  The song seems that was downloaded correctly. On the player shows the right amount of time, but at 8 minutes mark it skips to the next song. This behavior occurred with all songs listed below.

**Media Links Used:** 
 https://www.youtube.com/watch?v=tJKwzmJSpN8
https://www.youtube.com/watch?v=id28fCyYgIU
https://www.youtube.com/watch?v=KC0pfCv4A0Y

**Expected behavior**
Must be converted all the content of the video.

**Screenshots**

**StackTrace:**
```

```

**Device Info (please complete the following information):**
 - Device:  Samsung Galaxy S9+
 - OS:   Android OS
 - Version:   10 

**Additional context**

**Comment by Darius499** [comment]
Hello, 
I fixed problem with some songs by deinstalling Spotiflyer and then reinstalling again but via F-Droid app store.
Songs that are around 13-14 min are fixed and play entirely, but i downloaded a song that is 24 min long and it cuts of so i don't know which length of song will work and which won't.

**Comment by skyvory** [comment]
More link sample:
https://www.youtube.com/watch?v=n4hkSU4Qka0
https://www.youtube.com/watch?v=pQGkthJDa1I
Cut to 9 minutes (plus/minus a few seconds).

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
