### ISSUE TITLE
Does not download the whole song

### ISSUE THREAD

**Issue by kosmmo** [Shabinder/SpotiFlyer#44]
Hi just some feedback for the new release, it downloads the songs but some songs it won't download the whole song

**Comment by Shabinder** [comment]
App downloads the song from youtube which might be somewhat different from spotify.
If you are sure the song on youtube is complete and app isnt downloading it , share the song link from youtube and spotify aswell.

**Comment by mani445** [comment]
> An option selecting song manual instead of cwhatsapp status of only 30 seconds downloading instead of song.

> An option selecting song manual instead of code

whatsapp status of only 30 seconds downloading instead of song
