### ISSUE TITLE
App notification appears even when not opening app

### ISSUE THREAD

**Issue by Bwangster12** [Shabinder/SpotiFlyer#48]
On latest version 2.0.1, I'm finding that even when not having opened the app, the app notification appears with nothing being downloaded.  If I exit it, it'll appear again after 30ish or so minutes.

**Comment by yossigrosskopf** [comment]
Noticed that as well, the app requires background permission (assuming so it can continue downloading if there is a queue) I went ahead and enabled battery optimization so it only runs when I open the app.

I suggest the developer allows the user to make that decision and to exit (hide the notification) if there is no download queue.

**Comment by Bwangster12** [comment]
Won't battery optimization kill the download in the background?

**Comment by yossigrosskopf** [comment]
Yes it would but I don't use the app for background downloads (yet) still waiting for YouTube music support.
Once that is added I will probably download a full playlist and the notification should keep it alive.

**Comment by Shabinder** [comment]
I have been notified about this issue about notification popping back up. Will fix it. just somewhat busy in this month bcuz of exams.
Stay Tuned , in one of the future release this issue will be fixed.

**Comment by Shabinder** [comment]
@yossigrosskopf 
Youtube Music support is complete, just waiting for fixing a few more things before I push a new release.

**Comment by Shabinder** [comment]
Check If this issue Still Persists in v2.2.0, hopefully it should be fixed.
If not please Report back.

**Comment by Shabinder** [comment]
@yossigrosskopf @Bwangster12 Check in v2.2.5 this seems to be fixed for me , After Pressing on Exit , it will clean and Notification dismisses after a few seconds for good!

Please Check and report

**Comment by Shabinder** [comment]
Stale Issue, closing because of no response.
