### ISSUE TITLE
Documentation - explain somewhere that songs are not actually "downloaded from Spotify"

### ISSUE THREAD

**Issue by brunetton** [Shabinder/SpotiFlyer#501]
Hi,

It took me some time to understand that songs are not actually downloaded from Spotify, but a name matching from other sources (youtube music mainly) is done and if there's a match, the song is downloaded from here.

I think it should be explained somewhere and linked from the README. @Shabinder do you agree with it ?

Source: https://github.com/Shabinder/SpotiFlyer/discussions/134#discussioncomment-778411

**Comment by shubhasai** [comment]
Hey Can I update the following documentation in the Readme.md

**Comment by Shabinder** [comment]
Thanks @shubhasai 👍
