### ISSUE TITLE
The crash after downloading a song 

### ISSUE THREAD

**Issue by kareemkobaby** [Shabinder/SpotiFlyer#51]
The app always crash after downloading one song and i cant even download a whole playlist

**Comment by kareemkobaby** [comment]
I did use the v2.1 and 2.0.1 and even 1.4 they all the same so i dont know if its from my phone or wat. The all songs after processing it

**Comment by kareemkobaby** [comment]
Plus most of the songs arent full im downloading from spotify btw

**Comment by Shabinder** [comment]
is your android earlier than Oreo ? I have been notified but crashes on earlier android Version like Lollipop,Marshmallow and Nougat.
Will Fix them soon.

if not, please share your device details.

**Comment by asyeraph** [comment]
im running on android nougat, please kindly fix it thanks

**Comment by asyeraph** [comment]
im running on android nougat, please kindly fix it thanks

**Comment by Shabinder** [comment]
Due to recent CodeBase Change , **V2.2.0** supports Android API **24 and above.**
Check Out if this issue still persists in Android API **24 and above** in **v2.2.0** release.
