### ISSUE TITLE
[Feature-Request]: <Override Prefered Audio Quality if not available>

### ISSUE THREAD

**Issue by Y2kz** [Shabinder/SpotiFlyer#518]
**Problem**
When I am downloading old music from Youtube noticed that if Prefered Audio Quality is set to say 320Kbps ,If the quality is not available the audio converter fails and returns an error.  If I set it to some lower quality like 128Kbps it woks fine.

**Solution**
I know that some of the users are able to troubleshoot the issue by looking the error log.
It would be nice if you can add a feature to downgrage (override) the set Prefered Audio Quality to lower quality automatically
or just a popup warning to inform the user to change it to lower quality.

Waiting for the Newer Version BTW.

**Comment by Shabinder** [comment]
Hey Thanks for reporting this issue, I will look into this asap, and the **new version** is coming **super soon**, stay tuned.

**Comment by Shabinder** [comment]
Try in v3.3.0 and this should be fixed : 
https://github.com/Shabinder/SpotiFlyer/releases/tag/v3.3.0
https://github.com/Shabinder/SpotiFlyer/tree/main#-install
