### ISSUE TITLE
[BUG] : Files less than 100kbps

### ISSUE THREAD

**Issue by Jamesk21504** [Shabinder/SpotiFlyer#528]
So of all the songs i tried..
"Daydream" by "Johnny Orlando" doesn't show an error in app but only downloads a file of about 100kb which is obviously unplayable... All other songs I've tried work perfectly ... I reported this before this apk released and you said it was a youtube match issue... But all other similar issues are gone... So I don't know what's happening with this one

Link used
https://open.spotify.com/track/7cGbXyQknlw334XA0NdH80?si=Ar6SHEXNSTqzVyqqASYDcg&utm_source=copy-link&context=spotify%3Aplaylist%3A37i9dQZF1EIVyKTqCYfcZF&dl_branch=1

**Comment by Shabinder** [comment]
Yes I can reproduce your issue, will get back to you about the cause. 
Thanks for reporting this issue 👍

**Comment by Jamesk21504** [comment]
> Yes I can reproduce your issue, will get back to you about the cause.
> Thanks for reporting this issue 👍

Thanks to you all other songs work.. you're the reason I looked into developing in kotlin... I'll be learning after my boards in some months.. Keep up the work man.. Thanks for everything you're doing

**Comment by Shabinder** [comment]
Similar Issue: https://open.spotify.com/track/2nz41ZdIRChn4FggQtwOIg Nokia 6.2

**Comment by Shabinder** [comment]
Try again in v3.3.1, Its Fixed

**Comment by Shabinder** [comment]
> > Try again in v3.3.1, Its Fixed
> 
> The issue still persists in v3.6.1 disappointed_relieved

link used ?

**Comment by computechnopro** [comment]
> > > Try again in v3.3.1, Its Fixed
> > 
> > 
> > The issue still persists in v3.6.1 disappointed_relieved
> 
> link used ?

https://open.spotify.com/playlist/5jUzqzoqB7T6t8ZwYBF1Ad?si=a659fc9b1aa7446a

**Comment by StaticGamerYT-India** [comment]
this issue still persists @Shabinder @computechnopro
