### ISSUE TITLE
[BUG] : à file I downloaded its just 55 kb but it plays fine on saavn 

### ISSUE THREAD

**Issue by vehosah** [Shabinder/SpotiFlyer#529]
**Describe the bug**
The newest version of the app downloaded a file that it's just only 55 kb

**Media Links Used:** 
  https://open.spotify.com/track/2nz41ZdIRChn4FggQtwOIg

**Expected behavior**
That it should download a full file 

**Screenshots**
If applicable, add screenshots / screenrecording to help explain your problem.

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:  Nokia 6.2
 - OS:   Android 10
 - Version:   3.3.0

**Additional context**

**Comment by Shabinder** [comment]
Thanks for the issue , its same as #528  so progress on Both will be tracked there
