### ISSUE TITLE
[Feature-Request]: Music Cataloging
Put music in folder according to their artist, album, playlist etc. Like Freezer. 

### ISSUE THREAD

**Issue by BlazeJatin** [Shabinder/SpotiFlyer#532]

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
