### ISSUE TITLE
[BUG] : <Longer Tracks Cut Off During Playing>

### ISSUE THREAD

**Issue by Darius499** [Shabinder/SpotiFlyer#533]
**Describe the bug**
I download song that is longer than 10min,but when i play that song in music player, it cant play whole song and it skips to next song after 5min into the song

**Media Links Used:** 
 https://open.spotify.com/track/39zWYYZStDgWi32sOU9AX4?si=GZ5-lX13SR2UCO1QDv2wsw&utm_source=copy-link&dl_branch=1

**Expected behavior**
Being able to play whole duration of the song

**Screenshots**

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   [Xiaomi Mi4]
 - OS:   [Lineage OS, Android]
 - Version:   [Lineage OS 18.1, Android 11]

**Additional context**
There is already same problem #438, and i also already opened issue #237, but it was closed after you updated the app. Using Spotiflyer 3.3.0. 
Thanks for your help.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
