### ISSUE TITLE
[BUG] : 320kbps not working. songs are automatically Downloading in 128kbps

### ISSUE THREAD

**Issue by Shaashank009** [Shabinder/SpotiFlyer#534]
Songs are not Downloading in 320kbps. After changing the quality it remains same 128 kbps pls fix this

**Comment by Y2kz** [comment]
Are you downloding from Youtube, there was issue with that. (Don't know about other sources)
If audio converter fails to download 320kbps it will automatically switch to lower quality.
I am assuming that it is the issue.

**Comment by Shabinder** [comment]
Its not dependent of Audio Converter Success or Failure instead,

The app searches for the Highest quality available and if you are getting 128kbps then that means the app couldn't find a 320kbps source for the same.

**Comment by wadaki** [comment]
For me is the same, I can download what I want in Sporify, everything is 128kbps

**Comment by Shabinder** [comment]
So that means it could only find said song in YT and not other available sources
