### ISSUE TITLE
Songs from spotify are not downloading entirely

### ISSUE THREAD

**Issue by tsdharshan4** [Shabinder/SpotiFlyer#539]
> The actual song is around 3.5 mb but the downloaded song memory is around 146kb, and it is not in playable also![Screenshot_20210907-084728.jpg](https://user-images.githubusercontent.com/54705997/132279061-7cc21766-eccf-49f4-8c5d-32561cccfd12.jpg)![Screenshot_20210907-084713.jpg](https://user-images.githubusercontent.com/54705997/132279249-eb8c4675-1fab-4332-9275-e0b5c5001d8a.jpg)

**Comment by TrueGorOn** [comment]
I faced this too @Shabinder 
![Uploading PicsArt_09-08-10.58.39.jpg…]()

**Comment by TrueGorOn** [comment]
I faced this too @Shabinder  ![PicsArt_09-08-10 58 39](https://user-images.githubusercontent.com/90282748/132552664-db7d2d85-ea18-400e-ba1f-d2850aa996a9.jpg)

**Comment by Pritto88** [comment]
Same here

**Comment by IAmMaulik** [comment]
Same issue with me also

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
