### ISSUE TITLE
no internet error

### ISSUE THREAD

**Issue by senolfndk** [Shabinder/SpotiFlyer#54]
gives no internet error
![Screenshot_20210227-191846_SpotiFlyer](https://user-images.githubusercontent.com/52818836/109393508-325a3e00-7933-11eb-98be-2bb4d33f16fc.jpg)

**Comment by Shabinder** [comment]
It seems this issue is occuring when being used with VPN , right? 
I will check and release a new apk asap.

**Comment by senolfndk** [comment]
no i don't use vpn

Windows 10 için Posta<https://go.microsoft.com/fwlink/?LinkId=550986> ile gönderildi

Kimden: Shabinder Singh<mailto:notifications@github.com>
Gönderilme: 27 Şubat 2021 Cumartesi 23:39
Kime: Shabinder/SpotiFlyer<mailto:SpotiFlyer@noreply.github.com>
Bilgi: şenol fındık<mailto:parantezz_34@hotmail.com>; Author<mailto:author@noreply.github.com>
Konu: Re: [Shabinder/SpotiFlyer] no internet error (#54)


It seems this issue is occuring when being used with VPN , right?
I will check and release a new apk asap.

**Comment by Shabinder** [comment]
You sure? I can see the VPN active Icon in status bar (the key icon in ur screenshot)

**Comment by senolfndk** [comment]
Yes, you're right, I use adguard. Could it be because of it

Windows 10 için Posta<https://go.microsoft.com/fwlink/?LinkId=550986> ile gönderildi

Kimden: Shabinder Singh<mailto:notifications@github.com>
Gönderilme: 28 Şubat 2021 Pazar 03:28
Kime: Shabinder/SpotiFlyer<mailto:SpotiFlyer@noreply.github.com>
Bilgi: şenol fındık<mailto:parantezz_34@hotmail.com>; Author<mailto:author@noreply.github.com>
Konu: Re: [Shabinder/SpotiFlyer] no internet error (#54)


You sure? I can see the VPN active Icon in status bar (the key icon in ur screenshot)

**Comment by Shabinder** [comment]
Yeah try disabling adguard as workaround for this, however will try to fix this issue in coming update.

**Comment by senolfndk** [comment]
ok

Windows 10 için Posta<https://go.microsoft.com/fwlink/?LinkId=550986> ile gönderildi

Kimden: Shabinder ***@***.***>
Gönderilme: 5 Nisan 2021 Pazartesi 18:03
Kime: ***@***.***>
Bilgi: şenol ***@***.***>; ***@***.***>
Konu: Re: [Shabinder/SpotiFlyer] no internet error (#54)


Yeah try disabling adguard as workaround for this, however will try to fix this issue in coming update.

**Comment by Shabinder** [comment]
Fixed in v2.2.5 Release , Try it out

**Comment by senolfndk** [comment]
> V2.2.5 Sürümünde düzeltildi, Deneyin

tamam

**Comment by senolfndk** [comment]
ok

**Comment by senolfndk** [comment]
will you release the windows version

**Comment by Shabinder** [comment]
> will you release the windows version

I will in the coming future.

**Comment by senolfndk** [comment]
ok

Windows 10 için Posta<https://go.microsoft.com/fwlink/?LinkId=550986> ile gönderildi

Kimden: Shabinder ***@***.***>
Gönderilme: 20 Nisan 2021 Salı 06:44
Kime: ***@***.***>
Bilgi: şenol ***@***.***>; ***@***.***>
Konu: Re: [Shabinder/SpotiFlyer] no internet error (#54)


will you release the windows version

I will in the coming future.
