### ISSUE TITLE
[BUG] : After download two files are created with same names 

### ISSUE THREAD

**Issue by TrueGorOn** [Shabinder/SpotiFlyer#541]
Every song I download from Spotify, I find two file of that song in my music player. One is playable other is not. This is a bit annoying. And the unplayable file can't be deleted. But if you delete the playable file then both file gets deleted. 

**Media Links Used:** 
  - Every single song from Spotify

**Expected behavior**
Obviously I expected only one music file after the download. Not two

OS: Android 11
Version: 3.3.0

**Comment by Shabinder** [comment]
Can you refresh your music library as App itself cleans all unnecessary files upon exit

**Comment by TrueGorOn** [comment]
> Can you refresh your music library as App itself cleans all unnecessary files upon exit

Some gets cleaned. But some still exists

**Comment by Shabinder** [comment]
> 
> 
> > Can you refresh your music library as App itself cleans all unnecessary files upon exit
> 
> Some gets cleaned. But some still exists

If that's the case can you share some screenshots showing both files ..?

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
