### ISSUE TITLE
[Feature-Request]: Add an option to delete a file from inside the app

### ISSUE THREAD

**Issue by TrueGorOn** [Shabinder/SpotiFlyer#542]
A song can't be downloaded two times from Spotify. If i mistakenly delete the song from my file manager then when i go to download that again from Spotify, the app thinks the song is already downloaded. So it doesn't allow another download of the same file. 

So it would be great if you add an option to delete a song from within the app.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
