### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [Shabinder/SpotiFlyer#546]
ffmpeg .so are in the repo. Should I just remove them and they will be built or I need to run some scripts? Thanks!

**Comment by Shabinder** [comment]
Hey @linsui 👋 ,
I am aware of the shared libs , I am testing out new build script for fdroid, If all works out I will open a new MR for same, else will create an issue asking for help.

Script (WIP) here:
https://gitlab.com/Shabinder/fdroiddata/-/blob/master/metadata/com.shabinder.spotiflyer.yml

**Comment by Shabinder** [comment]
Hey @linsui I was expecting **build:** steps to execute before gradle builds ???

**Build Job:** 
https://gitlab.com/Shabinder/fdroiddata/-/jobs/1572028462#L2305

**Comment by Shabinder** [comment]
Issue in FdroidData for this : https://gitlab.com/fdroid/fdroiddata/-/issues/2479

**Comment by linsui** [comment]
`build` is executed before gradle assembleRelease. gradle clean is called before that.

**Comment by Shabinder** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9735

**Comment by Shabinder** [comment]
MR is now merged and build will be available in a few days hence closing this.
