### ISSUE TITLE
Fix Album Art

### ISSUE THREAD

**Issue by rajeshrvds** [Shabinder/SpotiFlyer#55]
Album art images looks ugly. Pls use original album art and size. Current album art has ugly border all sides to album art.

**Comment by Shabinder** [comment]
I decreased internationally , to not increase mp3 file size ...

Seems some people want HD album art , I will consider giving an option , so user could choose himself/herself which quality he/she wants.

But if you are talking about youtube downloads , then those are the ones we get with borders etc .

Only option will be there for spotify, gaana ,etc

**Comment by Shabinder** [comment]
Fixed and Set to Max Available Quality in **v2.2.5** Release
