### ISSUE TITLE
[BUG] : <Issue_Title>Downloads fake files

### ISSUE THREAD

**Issue by virenhooda27** [Shabinder/SpotiFlyer#552]
In Android:
If two songs have the same title it doesn't download any of them
Eg Taylor swift afterglow and ed Sheeran afterglow

For about 30% of downloaded songs it downloads fake mp3 files of about 100kb which don't play.

In windows:
Just doesn't open. Tried many ways.

**Comment by Shabinder** [comment]
Always fill Bug Template

in windows try opening the jar from cmd using `java -jar pathtojarfile.jar`

for android share **link** where such issue is occuring

**Comment by virenhooda27** [comment]
Link : https://open.spotify.com/playlist/5nj61JacWfVLUnpkpGLmF2?si=i7Xr5q97RTiCkkYog3zzIA&utm_source=copy-link&dl_branch=1
Using that command on windows a loop is there

[DEBUG] Countly [Storage] read user_0
[DEBUG] Countly [Storage] No data for file user_0
[DEBUG] Countly [SDKLifecycle] Application created
[INFO]  Countly [ModuleDeviceIdCore] [onContextAcquired] Starting device ID acqu
isition
[INFO]  Countly [ModuleDeviceIdCore] Acquiring device id
[DEBUG] Countly [ModuleDeviceIdCore] d4
[DEBUG] Countly [ModuleDeviceIdCore] acquireIdSync DID null (0, 0) / true
[INFO]  Countly [ModuleDeviceIdCore] Generating 0 / 0
[DEBUG] Countly [ModuleDeviceIdCore] Got device id: DID 85690600-999e-4b12-a2a9-
84dc0e620d9d (0, 0)
[DEBUG] Countly [SDKCore] non-limited onDeviceId DID 85690600-999e-4b12-a2a9-84d
c0e620d9d (0, 0), old null
[DEBUG] Countly [Storage] read timedEvent_0
[DEBUG] Countly [Storage] No data for file timedEvent_0
[DEBUG] Countly [Storage] Pushing config_0
[DEBUG] Countly [Storage] Pushing async config_0
[DEBUG] Countly [SessionImpl] begin
[DEBUG] Countly [Storage] Pushing async session_1631256938363
[DEBUG] Countly [Countly] onConsent: features = [Lly.count.sdk.java.Config$Featu
re;@7e7be63f
[DEBUG] Countly [SessionImpl] end
[DEBUG] Countly [Storage] Pushing async session_1631256938363
[INFO]  Countly [SessionImpl] No data in session end request
[DEBUG] Countly [SessionImpl] begin
[DEBUG] Countly [Storage] Pushing async session_1631256938378
[DEBUG] Countly [ModuleRequests] New request 1631256938379: [1631256938379] begi
n_session=1&session_id=1631256938378&metrics=%7B%22_os%22%3A%22Windows+7%22%2C%2
2_os_version%22%3A%226.1%22%2C%22_locale%22%3A%22en_IN%22%7D&device_id=85690600-
999e-4b12-a2a9-84dc0e620d9d
[DEBUG] Countly [Storage] Pushing async request_1631256938379
[DEBUG] Countly [ModuleDeviceIdCore] onDeviceId [DID 85690600-999e-4b12-a2a9-84d
c0e620d9d (0, 0)]
[INFO]  Countly [ModuleDeviceIdCore] Adding device_id to previous requests
[DEBUG] Countly [Storage] readAll request
[DEBUG] Countly [Networking] [check] state: shutdown [false], tasks running [fal
se], net running [false], device id [DID 85690600-999e-4b12-a2a9-84dc0e620d9d (0
, 0)]
[INFO]  Countly [ModuleDeviceIdCore] First transform: success
[DEBUG] Countly [Storage] readAll request
[DEBUG] Countly [Cly] event: key = app_launch
[INFO]  Countly [ModuleDeviceIdCore] Second transform: success
[DEBUG] Countly [Storage] readOne request
[DEBUG] Countly [ModuleDeviceIdCore] Sending device id signal: [DID 85690600-999
e-4b12-a2a9-84dc0e620d9d (0, 0)], was [null]
[DEBUG] Countly [Networking] [check] state: shutdown [false], tasks running [tru
e], net running [true], device id [DID 85690600-999e-4b12-a2a9-84dc0e620d9d (0,
0)]
[DEBUG] Countly [EventImpl] setSegmentation: segmentation = {}
[DEBUG] Countly [Storage] Pushing async session_1631256938378
[DEBUG] Countly [EventImpl] record: {"hour":12,"count":1,"segmentation":{},"dow"
:5,"key":"app_launch","timestamp":1631256938410}
[DEBUG] Countly [Networking] Preparing request: [1631256938379] begin_session=1&
session_id=1631256938378&metrics=%7B%22_os%22%3A%22Windows+7%22%2C%22_os_version
%22%3A%226.1%22%2C%22_locale%22%3A%22en_IN%22%7D&device_id=85690600-999e-4b12-a2
a9-84dc0e620d9d&timestamp=1631256938378&tz=330&hour=12&dow=5
[INFO]  Countly [network] [send] Sending request: [1631256938379] begin_session=
1&session_id=1631256938378&metrics=%7B%22_os%22%3A%22Windows+7%22%2C%22_os_versi
on%22%3A%226.1%22%2C%22_locale%22%3A%22en_IN%22%7D&device_id=85690600-999e-4b12-
a2a9-84dc0e620d9d&timestamp=1631256938378&tz=330&hour=12&dow=5
Debug: (Kermit) System Time:1631256938 , Token Expiry:null[MVIKotlin]: Main thre
ad id is undefined, main thread assert is disabled

Debug: (Kermit) Requesting New Token
Debug: (Kermit) Spotify Provider Created with TokenData(access_token=BQAQ0-TqrPS
XpkHLwiEobQdCM5GJTfZHBJD81HtxiIEeVq4acRZK-76qhDNK7TEoMpXaLROAEOei_AnaumU, token_
type=Bearer, expiry=3600)
[INFO]  Countly [network] [processResponse] Code [200] response [{"result":"Succ
ess"}
] for request[1631256938379]
[DEBUG] Countly [network] Success
[DEBUG] Countly [Networking] Request 1631256938379 sent?: OK
[DEBUG] Countly [Storage] removing request_1631256938379
[DEBUG] Countly [Networking] [check] state: shutdown [false], tasks running [fal
se], net running [false], device id [DID 85690600-999e-4b12-a2a9-84dc0e620d9d (0
, 0)]
[DEBUG] Countly [Storage] readOne request
[INFO]  Countly [ModuleSessions] updating session
[DEBUG] Countly [SessionImpl] update
[DEBUG] Countly [Storage] Pushing async session_1631256938378
[DEBUG] Countly [ModuleRequests] New request 1631256968377: [1631256968377] sess
ion_duration=30&session_id=1631256938378&events=%5B%7B%22hour%22%3A12%2C%22count
%22%3A1%2C%22segmentation%22%3A%7B%7D%2C%22dow%22%3A5%2C%22key%22%3A%22app_launc
h%22%2C%22timestamp%22%3A1631256938410%7D%5D&device_id=85690600-999e-4b12-a2a9-8
4dc0e620d9d
[DEBUG] Countly [Storage] Pushing async request_1631256968377
[DEBUG] Countly [Networking] [check] state: shutdown [false], tasks running [fal
se], net running [false], device id [DID 85690600-999e-4b12-a2a9-84dc0e620d9d (0
, 0)]
[DEBUG] Countly [Storage] readOne request
[DEBUG] Countly [Networking] Preparing request: [1631256968377] session_duration
=30&session_id=1631256938378&events=%5B%7B%22hour%22%3A12%2C%22count%22%3A1%2C%2
2segmentation%22%3A%7B%7D%2C%22dow%22%3A5%2C%22key%22%3A%22app_launch%22%2C%22ti
mestamp%22%3A1631256938410%7D%5D&device_id=85690600-999e-4b12-a2a9-84dc0e620d9d&
timestamp=1631256968393&tz=330&hour=12&dow=5
[INFO]  Countly [network] [send] Sending request: [1631256968377] session_durati
on=30&session_id=1631256938378&events=%5B%7B%22hour%22%3A12%2C%22count%22%3A1%2C
%22segmentation%22%3A%7B%7D%2C%22dow%22%3A5%2C%22key%22%3A%22app_launch%22%2C%22
timestamp%22%3A1631256938410%7D%5D&device_id=85690600-999e-4b12-a2a9-84dc0e620d9
d&timestamp=1631256968393&tz=330&hour=12&dow=5
[INFO]  Countly [network] [processResponse] Code [200] response [{"result":"Succ
ess"}
] for request[1631256968377]
[DEBUG] Countly [network] Success
[DEBUG] Countly [Networking] Request 1631256968377 sent?: OK
[DEBUG] Countly [Storage] removing request_1631256968377
[DEBUG] Countly [Networking] [check] state: shutdown [false], tasks running [fal
se], net running [false], device id [DID 85690600-999e-4b12-a2a9-84dc0e620d9d (0
, 0)]
[DEBUG] Countly [Storage] readOne request
[INFO]  Countly [ModuleSessions] updating session
[DEBUG] Countly [SessionImpl] update
[DEBUG] Countly [Storage] Pushing async session_1631256938378
[DEBUG] Countly [ModuleRequests] New request 1631256999031: [1631256999031] sess
ion_duration=31&session_id=1631256938378&device_id=85690600-999e-4b12-a2a9-84dc0
e620d9d
[DEBUG] Countly [Storage] Pushing async request_1631256999031
[DEBUG] Countly [Networking] [check] state: shutdown [false], tasks running [fal
se], net running [false], device id [DID 85690600-999e-4b12-a2a9-84dc0e620d9d (0
, 0)]
[DEBUG] Countly [Storage] readOne request
[DEBUG] Countly [Networking] Preparing request: [1631256999031] session_duration
=31&session_id=1631256938378&device_id=85690600-999e-4b12-a2a9-84dc0e620d9d&time
stamp=1631256999031&tz=330&hour=12&dow=5
[INFO]  Countly [network] [send] Sending request: [1631256999031] session_durati
on=31&session_id=1631256938378&device_id=85690600-999e-4b12-a2a9-84dc0e620d9d&ti
mestamp=1631256999031&tz=330&hour=12&dow=5
[INFO]  Countly [network] [processResponse] Code [200] response [{"result":"Succ
ess"}
] for request[1631256999031]
[DEBUG] Countly [network] Success
[DEBUG] Countly [Networking] Request 1631256999031 sent?: OK
[DEBUG] Countly [Storage] removing request_1631256999031
[DEBUG] Countly [Networking] [check] state: shutdown [false], tasks running [fal
se], net running [false], device id [DID 85690600-999e-4b12-a2a9-84dc0e620d9d (0
, 0)]
[DEBUG] Countly [Storage] readOne request
[INFO]  Countly [ModuleSessions] updating session
[DEBUG] Countly [SessionImpl] update
[DEBUG] Countly [Storage] Pushing async session_1631256938378
[DEBUG] Countly [ModuleRequests] New request 1631257029046: [1631257029046] sess
ion_duration=30&session_id=1631256938378&device_id=85690600-999e-4b12-a2a9-84dc0
e620d9d
[DEBUG] Countly [Storage] Pushing async request_1631257029046
[DEBUG] Countly [Networking] [check] state: shutdown [false], tasks running [fal
se], net running [false], device id [DID 85690600-999e-4b12-a2a9-84dc0e620d9d (0
, 0)]
[DEBUG] Countly [Storage] readOne request
[DEBUG] Countly [Networking] Preparing request: [1631257029046] session_duration
=30&session_id=1631256938378&device_id=85690600-999e-4b12-a2a9-84dc0e620d9d&time
stamp=1631257029046&tz=330&hour=12&dow=5
[INFO]  Countly [network] [send] Sending request: [1631257029046] session_durati
on=30&session_id=1631256938378&device_id=85690600-999e-4b12-a2a9-84dc0e620d9d&ti
mestamp=1631257029046&tz=330&hour=12&dow=5
[INFO]  Countly [network] [processResponse] Code [200] response [{"result":"Succ
ess"}
] for request[1631257029046]
[DEBUG] Countly [network] Success
[DEBUG] Countly [Networking] Request 1631257029046 sent?: OK
[DEBUG] Countly [Storage] removing request_1631257029046
[DEBUG] Countly [Networking] [check] state: shutdown [false], tasks running [fal
se], net running [false], device id [DID 85690600-999e-4b12-a2a9-84dc0e620d9d (0
, 0)]
[DEBUG] Countly [Storage] readOne request
[INFO]  Countly [ModuleSessions] updating session
[DEBUG] Countly [SessionImpl] update
[DEBUG] Countly [Storage] Pushing async session_1631256938378
[DEBUG] Countly [ModuleRequests] New request 1631257059067: [1631257059067] sess
ion_duration=30&session_id=1631256938378&device_id=85690600-999e-4b12-a2a9-84dc0
e620d9d
[DEBUG] Countly [Storage] Pushing async request_1631257059067
[DEBUG] Countly [Networking] [check] state: shutdown [false], tasks running [fal
se], net running [false], device id [DID 85690600-999e-4b12-a2a9-84dc0e620d9d (0
, 0)]
[DEBUG] Countly [Storage] readOne request
[DEBUG] Countly [Networking] Preparing request: [1631257059067] session_duration
=30&session_id=1631256938378&device_id=85690600-999e-4b12-a2a9-84dc0e620d9d&time
stamp=1631257059067&tz=330&hour=12&dow=5
[INFO]  Countly [network] [send] Sending request: [1631257059067] session_durati
on=30&session_id=1631256938378&device_id=85690600-999e-4b12-a2a9-84dc0e620d9d&ti
mestamp=1631257059067&tz=330&hour=12&dow=5
[INFO]  Countly [network] [processResponse] Code [200] response [{"result":"Succ
ess"}
] for request[1631257059067]
[DEBUG] Countly [network] Success
[DEBUG] Countly [Networking] Request 1631257059067 sent?: OK
[DEBUG] Countly [Storage] removing request_1631257059067
[DEBUG] Countly [Networking] [check] state: shutdown [false], tasks running [fal
se], net running [false], device id [DID 85690600-999e-4b12-a2a9-84dc0e620d9d (0
, 0)]
[DEBUG] Countly [Storage] readOne request
[INFO]  Countly [ModuleSessions] updating session
[DEBUG] Countly [SessionImpl] update
[DEBUG] Countly [Storage] Pushing async session_1631256938378
[DEBUG] Countly [ModuleRequests] New request 1631257089097: [1631257089097] sess
ion_duration=30&session_id=1631256938378&device_id=85690600-999e-4b12-a2a9-84dc0
e620d9d
[DEBUG] Countly [Storage] Pushing async request_1631257089097
[DEBUG] Countly [Networking] [check] state: shutdown [false], tasks running [fal
se], net running [false], device id [DID 85690600-999e-4b12-a2a9-84dc0e620d9d (0
, 0)]
[DEBUG] Countly [Storage] readOne request
[DEBUG] Countly [Networking] Preparing request: [1631257089097] session_duration
=30&session_id=1631256938378&device_id=85690600-999e-4b12-a2a9-84dc0e620d9d&time
stamp=1631257089097&tz=330&hour=12&dow=5
[INFO]  Countly [network] [send] Sending request: [1631257089097] session_durati
on=30&session_id=1631256938378&device_id=85690600-999e-4b12-a2a9-84dc0e620d9d&ti
mestamp=1631257089097&tz=330&hour=12&dow=5
[INFO]  Countly [network] [processResponse] Code [200] response [{"result":"Succ
ess"}
] for request[1631257089097]
[DEBUG] Countly [network] Success
[DEBUG] Countly [Networking] Request 1631257089097 sent?: OK
[DEBUG] Countly [Storage] removing request_1631257089097
[DEBUG] Countly [Networking] [check] state: shutdown [false], tasks running [fal
se], net running [false], device id [DID 85690600-999e-4b12-a2a9-84dc0e620d9d (0
, 0)]
[DEBUG] Countly [Storage] readOne request
[INFO]  Countly [ModuleSessions] updating session
[DEBUG] Countly [SessionImpl] update
[DEBUG] Countly [Storage] Pushing async session_1631256938378
[DEBUG] Countly [ModuleRequests] New request 1631257119111: [1631257119111] sess
ion_duration=30&session_id=1631256938378&device_id=85690600-999e-4b12-a2a9-84dc0
e620d9d
[DEBUG] Countly [Storage] Pushing async request_1631257119111
[DEBUG] Countly [Networking] [check] state: shutdown [false], tasks running [fal
se], net running [false], device id [DID 85690600-999e-4b12-a2a9-84dc0e620d9d (0
, 0)]
[DEBUG] Countly [Storage] readOne request
[DEBUG] Countly [Networking] Preparing request: [1631257119111] session_duration
=30&session_id=1631256938378&device_id=85690600-999e-4b12-a2a9-84dc0e620d9d&time
stamp=1631257119111&tz=330&hour=12&dow=5
[INFO]  Countly [network] [send] Sending request: [1631257119111] session_durati
on=30&session_id=1631256938378&device_id=85690600-999e-4b12-a2a9-84dc0e620d9d&ti
mestamp=1631257119111&tz=330&hour=12&dow=5
[INFO]  Countly [network] [processResponse] Code [200] response [{"result":"Succ
ess"}
] for request[1631257119111]
[DEBUG] Countly [network] Success
[DEBUG] Countly [Networking] Request 1631257119111 sent?: OK
[DEBUG] Countly [Storage] removing request_1631257119111
[DEBUG] Countly [Networking] [check] state: shutdown [false], tasks running [fal
se], net running [false], device id [DID 85690600-999e-4b12-a2a9-84dc0e620d9d (0
, 0)]
[DEBUG] Countly [Storage] readOne request
[INFO]  Countly [ModuleSessions] updating session
[DEBUG] Countly [SessionImpl] update
[DEBUG] Countly [Storage] Pushing async session_1631256938378
[DEBUG] Countly [ModuleRequests] New request 1631257149141: [1631257149141] sess
ion_duration=30&session_id=1631256938378&device_id=85690600-999e-4b12-a2a9-84dc0
e620d9d
[DEBUG] Countly [Storage] Pushing async request_1631257149141
[DEBUG] Countly [Networking] [check] state: shutdown [false], tasks running [fal
se], net running [false], device id [DID 85690600-999e-4b12-a2a9-84dc0e620d9d (0
, 0)]
[DEBUG] Countly [Storage] readOne request
[DEBUG] Countly [Networking] Preparing request: [1631257149141] session_duration
=30&session_id=1631256938378&device_id=85690600-999e-4b12-a2a9-84dc0e620d9d&time
stamp=1631257149141&tz=330&hour=12&dow=5
[INFO]  Countly [network] [send] Sending request: [1631257149141] session_durati
on=30&session_id=1631256938378&device_id=85690600-999e-4b12-a2a9-84dc0e620d9d&ti
mestamp=1631257149141&tz=330&hour=12&dow=5
[INFO]  Countly [network] [processResponse] Code [200] response [{"result":"Succ
ess"}
] for request[1631257149141]
[DEBUG] Countly [network] Success
[DEBUG] Countly [Networking] Request 1631257149141 sent?: OK
[DEBUG] Countly [Storage] removing request_1631257149141
[DEBUG] Countly [Networking] [check] state: shutdown [false], tasks running [fal
se], net running [false], device id [DID 85690600-999e-4b12-a2a9-84dc0e620d9d (0
, 0)]
[DEBUG] Countly [Storage] readOne request
[INFO]  Countly [ModuleSessions] updating session
[DEBUG] Countly [SessionImpl] update
[DEBUG] Countly [Storage] Pushing async session_1631256938378
[DEBUG] Countly [ModuleRequests] New request 1631257179171: [1631257179171] sess
ion_duration=30&session_id=1631256938378&device_id=85690600-999e-4b12-a2a9-84dc0
e620d9d
[DEBUG] Countly [Storage] Pushing async request_1631257179171
[DEBUG] Countly [Networking] [check] state: shutdown [false], tasks running [fal
se], net running [false], device id [DID 85690600-999e-4b12-a2a9-84dc0e620d9d (0
, 0)]
[DEBUG] Countly [Storage] readOne request
[DEBUG] Countly [Networking] Preparing request: [1631257179171] session_duration
=30&session_id=1631256938378&device_id=85690600-999e-4b12-a2a9-84dc0e620d9d&time
stamp=1631257179171&tz=330&hour=12&dow=5
[INFO]  Countly [network] [send] Sending request: [1631257179171] session_durati
on=30&session_id=1631256938378&device_id=85690600-999e-4b12-a2a9-84dc0e620d9d&ti
mestamp=1631257179171&tz=330&hour=12&dow=5
[INFO]  Countly [network] [processResponse] Code [200] response [{"result":"Succ
ess"}
] for request[1631257179171]
[DEBUG] Countly [network] Success
[DEBUG] Countly [Networking] Request 1631257179171 sent?: OK
[DEBUG] Countly [Storage] removing request_1631257179171
[DEBUG] Countly [Networking] [check] state: shutdown [false], tasks running [fal
se], net running [false], device id [DID 85690600-999e-4b12-a2a9-84dc0e620d9d (0
, 0)]
[DEBUG] Countly [Storage] readOne request

**Comment by Shabinder** [comment]
It seems the above stack trace isnt full

maybe a screenrecord will be more helpful ?

**Comment by virenhooda27** [comment]
![1.PNG](https://user-images.githubusercontent.com/90437375/132815745-adde66b5-3222-4c7e-b6d4-31adb7e791ba.PNG)![2.PNG](https://user-images.githubusercontent.com/90437375/132815764-41e46593-cd24-4621-a84f-1b7f70487daf.PNG)![3.PNG](https://user-images.githubusercontent.com/90437375/132815773-f18ad29f-6513-42ff-b07a-4d534ff263a0.PNG)

**Comment by virenhooda27** [comment]
It just keeps on repeating and never stops

**Comment by virenhooda27** [comment]
[DEBUG] Countly [Storage] readOne request

**Comment by virenhooda27** [comment]
The msi also after installing doesn't open.
I click it then nothing

**Comment by Shabinder** [comment]
@virenhooda27 I just tested and jar works fine sir, see #551
