### ISSUE TITLE
[BUG] : <MP3 conversation failed>

### ISSUE THREAD

**Issue by JahidFariz** [Shabinder/SpotiFlyer#553]
Always mp3 conversation link busy. I tried several times, days and weeks. 

MP3ConversionFailed(extraInfo=Client request(https://hostnew.onlineconverter.com/file/error) invalid: 404 Not Found. Text: "Not Found", message=MP3 Converter unreachable, probably BUSY ! 
CAUSE:Client request(https://hostnew.onlineconverter.com/file/error) invalid: 404 Not Found. Text: "Not Found")

**Comment by Shabinder** [comment]
Use latest 3.3.0 from releases or w8 for a day or two for Fdroid Update
