### ISSUE TITLE
[Feature-Request]: size of the current downloading file

### ISSUE THREAD

**Issue by ghost** [Shabinder/SpotiFlyer#558]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Hlo friend
Am albin one of the user of the app.i have seen many music downloading app but this one is better.so keep upgrading the application and make it better.i have an suggestion ......
To show the size of the current downloading file and show the size of the file before downloading it....
So please consider my simple request for an user

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
