### ISSUE TITLE
[BUG] : <Issue_Title> Using JAR version shows FFMPEG not found? 

### ISSUE THREAD

**Issue by True-King** [Shabinder/SpotiFlyer#559]
![image](https://user-images.githubusercontent.com/53064449/132963100-19d40b1f-7a39-4bc2-a644-d774302dad47.png)
So when i open the jar file it shows this error and is not letting me download?

**Comment by Shabinder** [comment]
You need to install ffmpeg , search 
`install FFmpeg in <your OS>`

**Comment by True-King** [comment]
Thanks worked like a charm

**Comment by schirinowski** [comment]
3.3.2 still complains here on Windows 10...
FFMpeg, stored in `D:\Tools\ffmpeg\bin\`, actually IS on the path:
`D:\Tools\Spotiflyer>ffmpeg -version`
`ffmpeg version N-71157-g7c6b043 Copyright (c) 2000-2015 the FFmpeg developers`
`built with gcc 4.9.2 (GCC)`

Any thoughts?

**Comment by schirinowski** [comment]
OK, got it, needed a newer/other version.
`ffmpeg version 2021-09-22-git-447cf53774-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers`
`built with gcc 10.3.0 (Rev5, Built by MSYS2 project)`
