### ISSUE TITLE
Downloads the song but it is under 100kb

### ISSUE THREAD

**Issue by adnanfml** [Shabinder/SpotiFlyer#560]
**Describe the bug**
It downloads the song but it is under 100kb and I can't play it.

**Media Links Used:** 
https://open.spotify.com/track/6UjfByV1lDLW0SOVQA4NAi?si=DkeWywQ9QLuaul6C-tRUIQ&utm_source=copy-link&dl_branch=1

**Expected behavior**
It is supposed to download the full song.

**Screenshots**
![Screenshot_20210912_211615_io stellio music](https://user-images.githubusercontent.com/72918773/132994162-085c010d-1187-4d2c-b9fb-acf4a837406d.jpg)

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:  Honor 20i
 - OS:  Android
 - Version:   Latest

**Comment by IAmMaulik** [comment]
I am also having a similar issue

**Comment by Shabinder** [comment]
Try again in v3.3.1, its fixed
