### ISSUE TITLE
[BUG] : Download is enabled but only 128 kbps

### ISSUE THREAD

**Issue by Aussada69** [Shabinder/SpotiFlyer#562]
**Describe the bug**
Download quality on Spotify

**Media Links Used:** 
  https://open.spotify.com/playlist/37i9dQZF1E8UpXRGAX3zZr?si=itns_HTTRoyZJGexzTfGAA&utm_source=copy-link&dl_branch=1

**Expected behavior**

**Screenshots**
If applicable, add screenshots / screenrecording to help explain your problem.

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   [e.g. iPhone6i9t pro, Samsung J2, PocoF1]
 - OS:   [Android 11 Miuimix ]
 - Version:   [lastest]

Download file is only at 128,192 kbps
[](https://open.spotify.com/playlist/37i9dQZF1E8UpXRGAX3zZr?si=itns_HTTRoyZJGexzTfGAA&utm_source=copy-link&dl_branch=1)

**Comment by Shabinder** [comment]
Hey @Aussada69  👋 ,

this isnt a bug,

Actually, a user only can declare the preferred quality, like 192kbps / 320kbps or any available.

but that is all, it is only PREFERRED,

The app will provide the best it can find, and for all songs, there isn't 320kbps available.
so why this option even exists, say you have selected 128kbps then even if 320 is available you won't get that, you will automatically fallback to 128kbps if that is your preferred

**Comment by Jamesk21504** [comment]
So even if preferred is 320.. it's just not available for some songs... Okayy gotcha.. thanks
