### ISSUE TITLE
[BUG] : Songs not downloading fully. Only 100kb size

### ISSUE THREAD

**Issue by TrueGorOn** [Shabinder/SpotiFlyer#565]
**Describe the bug**
Songs are downloaded from the app. But when i check them their size is only 100-150kb. And they are unplayable. 

**Media Links Used:** 
  - https://open.spotify.com/track/7EYv3adMrIC5mqurz7fHhD?si=xMex47UUSM674E2FbieuGQ&utm_source=copy-link&dl_branch=1

**Expected behavior**
I expect full download of the song which is playable in my music player. 

**Screenshots**
![Screenshot_20210915-021802](https://user-images.githubusercontent.com/90282748/133327839-43afd0ac-e6cd-4af4-89de-ceebf10c5c2d.png)

**StackTrace:**
```

```

**Device Info (please complete the following information):**
 - Device:   Tecno Spark 7
 - OS:   Android 11
 - Version:   3.3.0

**Additional context**

**Comment by Shabinder** [comment]
Duplicate , Issue being tracked here #528
