### ISSUE TITLE
[BUG] : JioSaavn Album not downloading

### ISSUE THREAD

**Issue by UgaBugaBoo** [Shabinder/SpotiFlyer#567]
**Describe the bug**
I tried to download the official JioSavan Album  also tried importing the songs to my own play list and downloading that play list. Neither worked. It shows Entered link not valid

**Media Links Used:** 
  Original Album https://www.jiosaavn.com/featured/hindi_00s/tsJahdem34A_
  My playlist https://www.jiosaavn.com/s/playlist/dc743890bf724e7509bb96a668902396/Hindi_00ss/i4S6We6dWd1ieSJqt9HmOQ__

**Expected behavior**
It should have started downloading songs

**Screenshots**
https://i.imgur.com/D0xEENI.png

**Device Info (please complete the following information):**
 - Device:   Windows 10, and also Android 11 
 - OS:  Windows 10 Pro, cRdroid Android 11

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
