### ISSUE TITLE
Audio Quality!!!

### ISSUE THREAD

**Issue by BlazeJatin** [Shabinder/SpotiFlyer#568]
It can download songs in FLAC like Fildo or any telegram bot like musichunterbot ,flacstorebot , music download robot etc. Lik 320 is so bad , please update download quality man it's 2021 and give the app a more minimal or blurred approach

**Comment by BlazeJatin** [comment]
And it can only download in mono audio , we want sterio

**Comment by Shabinder** [comment]
> 
> 
> And it can only download in mono audio , we want sterio

I believe we download sterio only, maybe some specific song you got was mono.
See below screenshot:
![image](https://user-images.githubusercontent.com/44765050/133551989-3351a028-62e9-40ac-bee7-ef4eb981db83.png)


Flac Support is a TODO , it is being already tracked here : #192
