### ISSUE TITLE
[Feature-Request]: Option to add position number to downloaded songs from a playlist. 

### ISSUE THREAD

**Issue by pota2dev** [Shabinder/SpotiFlyer#569]
Add an option to add numeric position number of the song if it's part of a playlist. 

e.g.-
https://imgur.com/a/ZAeusIj

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
