### ISSUE TITLE
About the Analytics

### ISSUE THREAD

**Issue by saurabhinabys** [Shabinder/SpotiFlyer#579]
Would be great if under the analytics option you could disclose what information will be collected. It would feel much better to help in your development if i could see what I'm sharing with you.

**Comment by saurabhinabys** [comment]
Anyway thank you.

**Comment by Shabinder** [comment]
Sure, you are sharing the following info without any personally identifiable information

![image](https://user-images.githubusercontent.com/44765050/133907046-6f21f98f-3585-4cd1-a5b4-ef1540b601df.png)

**Comment by saurabhinabys** [comment]
Great!!
