### ISSUE TITLE
Songs dont download in full length.

### ISSUE THREAD

**Issue by ITWLumberjack** [Shabinder/SpotiFlyer#583]
**Describe the bug**

A couple of songs won't download in full length. The real duration of the song will appear when attempted to play it but after 6 minutes or less the song will just skip automatically. Usually the songs are 15+minutes in full length

**Media Links Used:** 
  - Paste Song/Album/Playlist Link where you encountered this issue
  
These are the links of some of the songs
https://youtu.be/XOPRhHLAiyo
https://youtu.be/REA07gvxOzg

**Expected behavior**

I expected the song to be downloaded in full length

**Screenshots**
If applicable, add screenshots / screenrecording to help explain your problem.

For some reason I cant send a screen recording. Anyway

**StackTrace:**
```
Paste Stacktrace here if available
``` 

**Device Info (please complete the following information):**
 - Device: Huawei Y7 2019
 - OS:   Android
 - Version: 8.1.0

**Additional context**

**Comment by Darius499** [comment]
Hello, 
I fixed problem with some songs by deinstalling Spotiflyer and then reinstalling again but via F-Droid app store.
Songs that are around 13-14 min are fixed and play entirely, but i downloaded a song that is 24 min long and it cuts of so i don't know which length of song will work and which won't.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
