### ISSUE TITLE
Add track number to mp3 tag

### ISSUE THREAD

**Issue by shompoe** [Shabinder/SpotiFlyer#588]
When downloading an album and playing it offline it would be nice to have all the tracks play in the same order as when streaming the album online.

**Comment by IAmMaulik** [comment]
It already does that doesn't it, on Android atleast

**Comment by shompoe** [comment]
Not for me it doesn't.   Downloading on Android from YouTube Music.

--- 
Mark Desrousseaux



30 Sept 2021, 07:10 by ***@***.***:

**Comment by IAmMaulik** [comment]
Works on spotify

**Comment by shompoe** [comment]
Oh,

For me Spotify don't work at all. Can't download anything.

--- 
Mark Desrousseaux



30 Sept 2021, 11:15 by ***@***.***:

**Comment by IAmMaulik** [comment]
Weird, did you upgrade to the latest version (3.3.2)?

Can you send the link of which album/playlist you are trying to download, so that I can see whether I am also not able to download it

**Comment by shompoe** [comment]
Hi,

Yes, 3.3.2

Try this album...

https://open.spotify.com/album/0qPFKEUHIQ6HI82ePR6Mz2?si=wilQyIamQkKY5_1AYilmLA&utm_source=copy-link&dl_branch=1


--- 
Mark Desrousseaux



30 Sept 2021, 12:00 by ***@***.***:

**Comment by IAmMaulik** [comment]
That's really weird. Those songs on Spotify don't download for me either. Maybe it's because they are in another language because English songs download just fine

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
