### ISSUE TITLE
no option to download in 320kbps download only in 128kbps

### ISSUE THREAD

**Issue by rohitprasadopenxcell** [Shabinder/SpotiFlyer#59]

**Comment by Shabinder** [comment]
Duplicate of #47 ,
I am sorry to inform but 320kbps is not available from youtube.

**Comment by Peouyb** [comment]
Download spotify

**Comment by Peouyb** [comment]
[NUEVOS ARLS 17 DE ABRIL.txt](https://github.com/Shabinder/SpotiFlyer/files/6698456/NUEVOS.ARLS.17.DE.ABRIL.txt)

**Comment by Towhidul1** [comment]
Only loading
Download not working
