### ISSUE TITLE
Underscores in file names

### ISSUE THREAD

**Issue by LuigiSigillo** [Shabinder/SpotiFlyer#592]
In Linux when downloading songs from playlists, the songs are saved with underscores when there are whitespaces. Is this the correct behaviour?
Example:
"Never Going Home" becames "Never_Going_Home"

**Comment by Shabinder** [comment]
Yup this is Intended, It helps when referencing Files at various places like FFmpeg / metadata editor etc

**Comment by LuigiSigillo** [comment]
I understand but in my opinion this can be changed, to respect the original song name.

**Comment by Shabinder** [comment]
> I understand but in my opinion this can be changed, to respect the original song name.

Its hardcoded right now and doing so might bring some breaking changes, will consider this after implementing Important changes already in process, as I think this can w8.

**Comment by LuigiSigillo** [comment]
I leave this two lines, if someone needs to do this automatically for large playlists.
```python
import os
for e in os.listdir("./"):
    os.rename(e,e.replace("_"," "))
```
