### ISSUE TITLE
[Feature-Request]: add metadata editor

### ISSUE THREAD

**Issue by async-devil** [Shabinder/SpotiFlyer#593]
When downloading from YouTube, there are songs where author's name ends with “- Topic”, and renaming it in other apps is really making me mad.

Adding a simple input boxes before downloading or after would make life so easier. Also, it makes possible to fix title after republishers.

There is no need to add too much metadata edit possibilities. Title, artist and optionally album options would be ideal. And these options could be added without much design changes.

Song area is made to be clicked, opening metadata editor menu with three inputs and exit or save button. Also, that menu could be a space for future features.

I would do that myself, if I wasn't a JS developer. Sorry)

Added photo to demonstrate “topic” problem and the song area
![photo_2021-09-24_13-03-06](https://user-images.githubusercontent.com/69465334/134657162-2413b4da-9e53-475f-a1ec-db3bacdb5aae.jpg)

**Comment by Shabinder** [comment]
you want to manually edit metadata where song shows up, 

or there some specific rules which you generally do and I can create an option and everybody can use it
 for ex - 
 - remove artist name from song name

**Comment by async-devil** [comment]
Automatic edit might be a good idea, but there are too many styles of music video naming, so manual edit is have to be. If making automatic, I could make regexp for the most popular naming for you to implement.

**Comment by Shabinder** [comment]
> Automatic edit might be a good idea, but there are too many styles of music video naming, so manual edit has to be. If making automatic.

Ohk, I will be glad to implement this in future as a feature release, but for now some important bug fixes are in works and are priority.

> I could make regexp for the most popular naming for you to implement.

That would be great, do share them and I can prep the codebase to implement the codebase as soon as I can.

**Comment by async-devil** [comment]
Ok then, I will find as many namings as I can and make regexp from them. I'm going to create a repository to contain and test them, so I drop a link here and contact you when I finished.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
