### ISSUE TITLE
Cover art changes when dowoading from YT music

### ISSUE THREAD

**Issue by Simx303** [Shabinder/SpotiFlyer#599]
AN ASTHETIC IMPROVEMENT

When downloading a song from Spotify the cover art is fine and works. But when I download from YT music the same song the cover art changes aspect ratio. If your app works by downloading the music from YT music. Why does the cover art change between different platforms?
![Screenshot_20210924_220745_com aimp player-01](https://user-images.githubusercontent.com/75362577/134728062-240bb346-764c-4de4-96d9-2229c99690d3.jpeg)
![Screenshot_20210924_220851_com.aimp.player-01.jpeg](https://www.dropbox.com/s/f02ph8m8duhxjp7/screenshot_20210924_220745_com.aimp.player.png?dl=0)

**Comment by Shabinder** [comment]
the cover art you see is provided by YT.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
