### ISSUE TITLE
App layout, clipboard and download issues.

### ISSUE THREAD

**Issue by azusaairi** [Shabinder/SpotiFlyer#60]
Adjust app layout if the phone have soft key

![20210317_160651](https://user-images.githubusercontent.com/69487772/111442333-d537f800-873a-11eb-87f8-8a68e74e01d9.jpg)

**Comment by azusaairi** [comment]
And also when i click clipboard from my keyboard, it doesn't show.

Samsung A205F/DS - Android 10

**Comment by Shabinder** [comment]
> And also when i click clipboard from my keyboard, it doesn't show.
> > `Samsung A205F/DS - Android 10`
> 
> Oh and another problem... i can't download some song from this playlist: https://open.spotify.com/playlist/1K5n6x7SSQG9ZWOi9b0sls
> Of 39 song, Only 6 of them failed to download and some downloaded song sound so broken.

What doesn't show when you click clipboard?
As the app is still in early stages and using many preview components like jetpack compose and so , there may be somethings which are broken but I try to fix them as soon as I can and always expect more optimisations with every update.

And the thing about song getting failed is that this app uses youtube for downloading music and some Spotify song aren't available on youtube hence those will fail and youtube offers a limited audio quality.

However I can incorporate another source , where we can get songs in mp3 (preferably) , if you know of any, do share them.

**Comment by azusaairi** [comment]
Thanks for reaching back to me, what i mean by clipboard:

![clipboard](https://user-images.githubusercontent.com/69487772/111542501-67281b00-87a4-11eb-8302-a2a2f889c7fd.gif)

As for the download... well I'm probably just download the song from youtube or use another source.

**Comment by Shabinder** [comment]
> Thanks for reaching back to me, this what i mean by clipboard:

I will need to test and figure the clipboard issue , but for now it seems like a Jetpack Compose Issue , however simple copy/paste do work for now.

Right Now I am getting the project to Kotlin Multiplatform(as a learning experience for me).
Cool Things on way...
I will get back to this issue asap, and hence leaving it open for now.
Once again thanks for reporting this issue.

**Comment by azusaairi** [comment]
Your welcome! Good luck with your app!

**Comment by mani445** [comment]
Add pop up download when sharing

**Comment by Shabinder** [comment]
StatusBar And Navigation Bar Padding Fixes and Many other fixes in **v2.2.5** Released
