### ISSUE TITLE
[BUG] : <Issue_Song Downloaded But Onl y 188 kb sized>

### ISSUE THREAD

**Issue by ss-git-subhash** [Shabinder/SpotiFlyer#601]
**Describe the bug**

**Media Links Used:** 
  - Paste Song/Album/Playlist Link where you encountered this issue

**Expected behavior**

**Screenshots**
If applicable, add screenshots / screenrecording to help explain your problem.

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   [e.g. iPhone6, Samsung J2, PocoF1]
 - OS:   [e.g. iOS, Android, WinOS, MacOS]
 - Version:   [e.g. 3.2.1]

**Additional context**

**Comment by Shabinder** [comment]
Its Fixed In V3.3.1, Try that out.
