### ISSUE TITLE
[BUG] : Downloaded songs will be 128 kbps

### ISSUE THREAD

**Issue by obonbonbon** [Shabinder/SpotiFlyer#603]
Hello.

I found that the downloaded musics is stored at 128kbps in Spotify.
As far as I can confirm, all songs are at 128kbps.
Preferred Audio Quality is set to 320 kbps.

**Device Info (please complete the following information):**
 - Device:  MacBook Pro
 - OS:   MacOS
 - Version:   3.3.1

**Comment by obonbonbon** [comment]
Spotify music files will be sourced from YouTube, so the quality would be 128kbps, right?

**Comment by Shabinder** [comment]
yes

**Comment by Shabinder** [comment]
However we have other sources like JioSaavn which can provide some songs at 320 or 160, but will be only enabled if u select preferred quality to 320kbps
