### ISSUE TITLE
[BUG] : <Crash when trying to set download directory>

### ISSUE THREAD

**Issue by sakuraimikoto33** [Shabinder/SpotiFlyer#604]
Crash when trying to set download directory

**Device Info (please complete the following information):**
 - Device:   WindowsPC
 - OS:  Windows10
 - Version:   3.3.1

**Comment by Shabinder** [comment]
Fixed in https://github.com/Shabinder/SpotiFlyer/commit/545daf5d5b477143f7555b112535377460e86217
will be available in 3.3.2 soon
