### ISSUE TITLE
[Feature-Request]: home assistant compatibility

### ISSUE THREAD

**Issue by test2a** [Shabinder/SpotiFlyer#605]
**Is your feature request related to a problem? Please describe.**

add  the service to home assistant

**Describe the solution you'd like**
https://demo.home-assistant.io/#/lovelace/0
visit this demo page of home assistant. let say there is now a spotiflyer widget. the user pastes the URL and selects the output, be it the phone app or some speaker and home assistant uses spotiflyer to download the url, save the file somewhere and take it from there. the rest of the part is solved issue, we would just have to pipe into it. see projects like https://tutorials-raspberrypi.com/setup-remote-raspberry-pi-spotify-player-in-smart-home/ which use spoitfy api to directly play music across homeassistant. 
the benefit of using spotifyler is obvious and after the first download, playback is already offline. 
There are more possibilities like after download, using voice to text to recognize downloaded media or playlists and playing from there. this can be big
**Describe alternatives you've considered**

**Additional context**

**Comment by Shabinder** [comment]
Interesting 👀 , thanks for the Idea will see what I can do.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
