### ISSUE TITLE
Problems while downloading songs from spotify with Spotiflyer v3.3.2 on Windows & Android

### ISSUE THREAD

**Issue by CHSC-1053** [Shabinder/SpotiFlyer#606]
Encountered 2 Problems while downloading songs from spotify with Spotiflyer v3.3.2 on Windows & Android.

BUG 1: Problem Downloading Songs with same names.
BUG 2: Problem downloading some particular tracks (Tried many times). (Files are corrupted after downloading)

BUG 1:
There is a problem downloading songs with same names from spotify.
The songs either get overwritten or recognised as already downloaded although the composer and album names are different.

Example 1: Alone (by AlanWalker) & Alone (by Marshmellow)
https://open.spotify.com/track/3LlmKSHR3Rs0Y3KHQLAYDk
https://open.spotify.com/track/3MEYFivt6bilQ9q9mFWZ4g

Example 2: Animals (by Martin Garrix) & Animals (by Maroon 5)
https://open.spotify.com/track/1TWfkGrhF7ob0nwB2M6knb
https://open.spotify.com/track/3h4T9Bg8OVSUYa6danHeH5

BUG 2:
There is a problem with some particular tracks which doesnt seem to download correctly, Tried many times.

Example 1: Bad Guy (by Billie Eilish)
https://open.spotify.com/track/2Fxmhks0bxGSBdJ92vM42m

Example 2: Hollywood Perfect (by Unknown Brain)
https://open.spotify.com/track/0qVZveaUjd4PqdAlLmfEg4

Example 3: Hollywood's Bleeding (by Post Malone)
https://open.spotify.com/track/7sWRlDoTDX8geTR8zzr2vt

Example 4: Old Town Road (by Lil Nas X)
https://open.spotify.com/track/2YpeDb67231RjR0MgVLzsG

Example 5: Runaway (by Aurora)
https://open.spotify.com/track/1v1oIWf2Xgh54kIWuKsDf6

Example 6: Sorry (by Justin Bieber)
https://open.spotify.com/track/09CtPGIpYB4BrO8qb1RGsF

The problem with these tracks is that they doesnt seem to work after downloading.
Microsoft Groove says that these files are corrupt and throws an Error Code 0xc00d36c4.
I also tried to play these files on other media players such as VLC and it doesnt seem to work.
I dont understand the perfect problem but it seems to be something while downloading.

- Version:   3.3.2
- Country: India

**Comment by Shabinder** [comment]
@CHSC-1053 Thanks for such a detailed bug report, I will try to fix them asap.

**Comment by CHSC-1053** [comment]
* Update after using Spotiflyer 3.5.0
BUG 1: Doesn't seem to be fixed but when i move one song with same name out of the directory and download another, it seems to work. [Spotiflyer recognizes songs with same name as same songs and shows "already downloaded" for both.]

BUG 2: Some of the examples [Example: 2 & 4] listed in the bug report above are working but not all.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
