### ISSUE TITLE
[Feature-Request]: Please Add Apple Music Support and give the app a more minimalist/Material design. Accent colour changing.

### ISSUE THREAD

**Issue by BlazeJatin** [Shabinder/SpotiFlyer#607]
I put both the features in the title xD

**Comment by Shabinder** [comment]
I will see what I can do about Apple Music,

and About UI, can you share an Inspiration about how it should look like

**Comment by BlazeJatin** [comment]
Just look up on Google's material design templates or material gallery app in playstore, choose which one looks better maybe make it look  Just simple with desaturated colours .And yeah every time we put a link and hit search clear the search query, so we don't have to clear the previous link and paste the new one.
