### ISSUE TITLE
IaaC setup

### ISSUE THREAD

**Issue by mpetuska** [Shabinder/SpotiFlyer#61]
If you'd like I can help set your infrastructure on azure cloud in a completely free way. Also happy to help with full ci cd setup via terraform.

**Comment by Shabinder** [comment]
Yeah I would love it ,
 one more main thing that needs to be done is setup a proxy server , here is the repo:
https://github.com/Shabinder/cors-anywhere

I did tried setting this server on azure ,but on education plan ,this server sleeps after time and when a new request is made the client has to wait for almost 10-13 secs.

**Comment by mpetuska** [comment]
Yeah, had exact same issues with kamp (my open source website). Only that cold startys were going into minutes, not seconds :D Quick hack to keep it alive is to setup [uptimerobot](https://uptimerobot.com/) that pings it every 5 mins ;) That way it's "hot" 100% of the time, while still working on the free azure app service plan.

Anyways, I can't seem to find your backend. Invite me to that project if it's private and I can raise a PR for your terraform infra setup on azure free tier.

**Comment by Shabinder** [comment]
> Yeah, had exact same issues with kamp (my open source website). Only that cold starts were going into minutes, not seconds :D Quick hack to keep it alive is to setup [uptimerobot](https://uptimerobot.com/) that pings it every 5 mins ;) That way it's "hot" 100% of the time, while still working on the free azure app service plan.
> 
> Anyways, I can't seem to find your backend. Invite me to that project if it's private and I can raise a PR for your terraform infra setup on azure free tier.

Ohh yeah I forgot to invite you to the repo, you will recieve the invite in a few seconds....

**Comment by mpetuska** [comment]
I'm a bit confused then. Do you not have dedicated backend for your web client?

Actually, it'd help a ton if you could just list out what infrastructure you need and I then could take care of setting it up for you.

**Comment by Shabinder** [comment]
> I'm a bit confused then. Do you not have dedicated backend for your web client?
> 
> Actually, it'd help a ton if you could just list out what infrastructure you need and I then could take care of setting it up for you.

Due to lack of hardware at disposal, I built everything with a focus to keep most of the work on client , so there is absolute no backend for desktop and android ,but in web I couldnt make cross origin request , so i needed to deploy a proxy server for web app ,  to making requests.

I am currently hosting that on my raspberry pi ,and for website I am using Github Pages and Github Workflow Actions for automatic Deploys.

So the only thing as close to a backend is that proxy server which keeps web app usable.

**Comment by mpetuska** [comment]
Ah, gotcha. Will setup that cors anywhere on azure for you tomorrow then.

**Comment by Shabinder** [comment]
@mpetuska  hey, I am also planning to host FFmpeg, is azure a good fit for it? Will it be able to handle all the load?

**Comment by mpetuska** [comment]
Not sure what that is, but if you can dockerize it then it should be fine.

**Comment by Shabinder** [comment]
> Not sure what that is, but if you can dockerize it then it should be fine.

ohhkay , However I am looking at client side options, but it is platform specific , so a lot of work is required from my side....
will see how it goes.

**Comment by mpetuska** [comment]
Terraform infra for the az backend setup.
