### ISSUE TITLE
History not working

### ISSUE THREAD

**Issue by adnanfml** [Shabinder/SpotiFlyer#611]
**Describe the bug:**
The songs are already downloaded and saved on my phone but it still doesn't show in my history

**Media Links Used:** 

**Expected behavior**
It is supposed to show as downloaded in history. I downloaded this song in the previous version of spotiflyer

**Screenshots:**
![Screenshot_20210927_091145_com shabinder spotiflyer](https://user-images.githubusercontent.com/72918773/134842493-a2d3854e-30e2-47b9-b885-a521460adfbc.jpg)

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:  Honor 20i
 - OS:   Android 10
 - Version:   3.3.2
 - Country: India

**Additional context:**
It worked in the previous version but since I updated it has this problem. Please fix it as soon as possible.

**Comment by Shabinder** [comment]
This Release brought some breaking changes in Naming Conventions, that's why app isn't able to detect if that song is downloaded

**Comment by adnanfml** [comment]
> This Release brought some breaking changes in Naming Conventions, that's why app isn't able to detect if that song is downloaded

okay sir got it🤝🏼 will wait for the next release

**Comment by Shabinder** [comment]
but however App will recognise all download you do from now on

**Comment by adnanfml** [comment]
> but however App will recognise all download you do from now on

ah got it thank you
