### ISSUE TITLE
[Feature-Request]: favourites

### ISSUE THREAD

**Issue by test2a** [Shabinder/SpotiFlyer#612]
**Is your feature request related to a problem? Please describe.**
say there is a bug playlist that i do not want to download at once or it is growing one so i need to get back to it often. the history tab shows everything which can bury this particular link. 
**Describe the solution you'd like**
favourites tab or starred links would solve this issue as we can filter the existing history tab to what we want to go back to
**Describe alternatives you've considered**

**Additional context**

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
