### ISSUE TITLE
[BUG] : album art

### ISSUE THREAD

**Issue by Yoshadin** [Shabinder/SpotiFlyer#613]
**Describe the bug:**
album art is low quality.

**Expected behaviour**
High quality album art.

**Device Info (please complete the following information):**
 - Device:  huawei y9s
 - OS: Android 10
 - Version:  3.2.2
 - Country: India

**Additional context:**
-The album art quality is very low

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
