### ISSUE TITLE
[BUG] : Language

### ISSUE THREAD

**Issue by Yoshadin** [Shabinder/SpotiFlyer#623]
**Describe the bug:**
name of songs in some languages are not supported. The is "__" instead of the song title.

**Device Info (please complete the following information):**
 - Device: HUAWEI y9s 
 - OS:  Android 10
 - Version:   [e.g. 3.2.1]
 - Country: india

**Comment by Shabinder** [comment]
App removes any special character except numericals,alphabets as when having those in file name FFmpeg seems to have issues in various cases

**Comment by bestzxcmos03** [comment]
@Shabinder Can it possible to stored the name of song in any variables then use the ffmpeg after that set the name of song back before it stored in drive? Because i've downloading from url my playlist and the length of "_" is replace each other. From Thai language.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
