### ISSUE TITLE
[Feature-Request]: support for RadioJavan

### ISSUE THREAD

**Issue by iJahangard** [Shabinder/SpotiFlyer#636]
Radio Javan is a great website that you can find all kind of Persian music in there

Some of those songs are not in any other sources

https://www.radiojavan.com/

That would be awesome if you add support for this website
Thank in advance

**Comment by Shabinder** [comment]
![image](https://user-images.githubusercontent.com/44765050/135589317-e5bf48dc-acc9-4c55-818e-bfc710c1c255.png)
Is this site online ?

**Comment by iJahangard** [comment]
Umm ,hi
I guess any county other than Iran can access the website
I usually use vpn to access to it , Frankfort , Amsterdam , any places in USA , UK .... I guess

Which country do you in?

**Comment by Shabinder** [comment]
India

**Comment by iJahangard** [comment]
Use a VPN then!

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
