### ISSUE TITLE
Downloading remixes

### ISSUE THREAD

**Issue by Llama037** [Shabinder/SpotiFlyer#655]
So there are like three songs that i want to download, but SpotiFlyer downloads remixes. 
For "INDUSTRY BABY" by lil nas x it downloads some remix, same for "white lies" by vize, and for some reason, it downloads russian versoin of The living tombstone - So long.

[INDUSTRY BABY file](https://dl.uploadgram.me/615f4e58d3a33g) 
[It's been so long](https://dl.uploadgram.me/615f4e825e98dg) 
[White lies](https://dl.uploadgram.me/615f4e9e81fcfg) 

Theese links are the files that spotiflyer downloads

**Comment by Kyle2142** [comment]
I have the same problem, here is an example:
https://open.spotify.com/track/2BZYVqGyL1L1adBbq2ClVv
The downloaded one is some remix - but the metadata says it is the original

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
