### ISSUE TITLE
Simplify Installation and Ship FFmpeg even for Desktop

### ISSUE THREAD

**Issue by woshibbb** [Shabinder/SpotiFlyer#663]

**Comment by Shabinder** [comment]
What ? I cant understand the issue?

Fill Bug Report

**Comment by woshibbb** [comment]
To install this software, I won't give up     That's it   FFmpeg     

The on the mobile phone can't be used normally and will crash

My VPN is American

**Comment by Shabinder** [comment]
Actually, I decided to leave the FFmpeg installation burden on user as that way I won't need to build the binaries for all platforms and include them based on the platform, as that will be quite tricky. 

However, I will consider including everything dep in and then shipping the release in the future so a user can just download and use it.

**Comment by Shabinder** [comment]
However if there is any other error, you will need to share stacktrace for me to fix that

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
