### ISSUE TITLE
[BUG] : AUDIO QUALITY PEGGED AT 128 KBPS

### ISSUE THREAD

**Issue by sparsechunk** [Shabinder/SpotiFlyer#671]
**Describe the bug:**

- After successfully downloading a track, I noticed that the downloaded track Audio Quality was 128kbps. Finally, just to confirm the discovery, I decided to download for each set Audio Quality and the result was the same.

**Media Links Used:** 

- https://open.spotify.com/playlist/37i9dQZF1DZ06evO15bKCY?si=00cZ3Q2iSmisscL2yQmiKg&utm_source=copy-link 
- https://open.spotify.com/playlist/37i9dQZF1DX5mILnBJLA26?si=YYXcB8AoQeqSBSfWaxA7pQ&utm_source=copy-link 

**Expected behavior**

- Downloaded Track Bitrate should be consistent with the one selected on the App 

**Device Info (please complete the following information):**
 - Device:   Redmi Note 9 Pro
 - OS:   Android
 - Version:   11
 - Country: Nigeria

**Additional context:**

My music App is **Poweramp.**

Finally, I'd like to commend you for the beautiful App.

Thanks & Regards

**Comment by sparsechunk** [comment]
Oh! Understood.

However, downloading the same tracks using Sidify software tends to produce a different result i.e 320 KBPS tracks download when set in-app.

I am not in any way trying to discredit your work. Just sharing what I noticed.

**Comment by Shabinder** [comment]
I cant comment on sidify working as its closed source and moreover,

I can also download it as 320kbps but that will just mean only expanding the mp3 audio file without any actual benefit as YT encodes all audio to 128kbps, so  converting that to 320 makes no sense and will just occupy more storage in ur device without any benefit
