### ISSUE TITLE
[BUG] : <Song Title bug>

### ISSUE THREAD

**Issue by amanchabukswar** [Shabinder/SpotiFlyer#679]
![Screenshot_20211017-195217](https://user-images.githubusercontent.com/36570503/137631760-9dad311d-5483-4079-b68d-d9fe245ef590.png)
Tried to download russian songs and getting these kinds of name in file manager. 
LG G7 thinq on Android 10

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
