### ISSUE TITLE
[BUG] : <song pitch different than original>

### ISSUE THREAD

**Issue by amanchabukswar** [Shabinder/SpotiFlyer#680]
I've downloaded the song where that song have different pitch of sound than original. 
Song link: https://open.spotify.com/track/3kxqYEJ96YrLS8rs0BMBn0?si=va3tSmplRPW4B3coU0eytA&utm_source=copy-link

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
