### ISSUE TITLE
SD Card Writing

### ISSUE THREAD

**Issue by hyperpoppy** [Shabinder/SpotiFlyer#681]
If you can't possibly make it so you can write to the SD card, then remove external storage options from the app entirely. When choosing a location to download to, the ad card shouldn't be visible if you can't write to it. At least make a popup that tells you that you can't use ad cards! And who cares if it won't be fast if you make it possible? Makes no damn sense.

**Comment by FauconFR** [comment]
this is actually a bug because in newer versions of android you need to make it so that the app opens the default file manager, naviguate to the sd card, and press "USE THIS FOLDER"

**Comment by Shabinder** [comment]
refer https://github.com/Shabinder/SpotiFlyer/issues/116 
I am not implementing this because it will just increase headaches in implementing the app itself and also many hacks are required to make it work when I did implemented it.

**Comment by Shabinder** [comment]
will remove SD card option from storage selector in future releases.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
