### ISSUE TITLE
[BUG] : Crashes after clicking 'Download All'

### ISSUE THREAD

**Issue by deybedanta** [Shabinder/SpotiFlyer#682]
**Describe the bug:**
After inputting a spotify playlist link and clicking download all, it freezes and eventually crashes.

**Media Links Used:** 
https://open.spotify.com/playlist/08cBI3ONjQeZTYRYxl6WZF?si=1091978e3c4a42ea

**Expected behavior**
Downloads all

**Device Info (please complete the following information):**
 - Device:   HP 14-CK0025TU
 - OS:   Linux Mint
 - Version:   20.2
 - Country: India

**Comment by luphoria** [comment]
Further context: this is because the loading animation is rendered however many songs are on the playlist. This happened to me because my playlist was 2000+ songs. I manually clicked ~1000 and then did Download All, it worked

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
