### ISSUE TITLE
[BUG] : <Issue_Title> SpotiFlyer won't exit on clicking the exit button

### ISSUE THREAD

**Issue by PS-Professional** [Shabinder/SpotiFlyer#688]
**Bug describe:**
Hi
I'm using the SpotiFlyer on Ubuntu and Android. On my Android device, when I click on the Exit button on the notification panel, it will quit but soon it will start its process again, meaning that it won't quit.
Can you fix this problem?

**Expected behavior :**
Quit on clicking the exit button and end the process in the background

**Device Info :**
 - Device:   Huawei P Smart
 - OS:   Android 9.0 [EMUI 9.1.0.219]
 - Version:   3.5.0
 - Country: Iran

**Comment by fukwho** [comment]
Same problem, but on Windows JAR version.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
