### ISSUE TITLE
Conversion to mp3 unnescessary

### ISSUE THREAD

**Issue by auroraanna** [Shabinder/SpotiFlyer#691]
Afaik SpotiFlyer downloads audio from YouTube Music [which uses 128 kbps AAC](https://support.google.com/youtubemusic/thread/168815/what-audio-quality-does-youtube-music-stream?hl=en&msgid=168875). AAC and mp3 are both lossy formats meaning they strip out data which is hard to hear anyway for the purpose of saving storage space. It is unnecessary and even hurtful to the quality of the audio to convert between 2 lossy formats. However that is what this app is doing. Tracks should just get downloaded and not get converted not to mention that mp3 is an outdated format.

**Comment by BuyMyMojo** [comment]
Also having an option to download from youtube as an Opus audio file coppied into a .ogg file would be amazing too

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
