### ISSUE TITLE
Link is not valid message when searching

### ISSUE THREAD

**Issue by Bwangster12** [Shabinder/SpotiFlyer#7]
I get a link is not valid message when searching on latest version.
![Screenshot_20201110-080254](https://user-images.githubusercontent.com/26938129/98677667-4f8ae280-232b-11eb-85f9-717ed79c0c86.png)

**Comment by Shabinder** [comment]
I believe You found the cause , but still for those who face the same , This may help them out:

To download
You have to share its **url** like :
- https://open.spotify.com/playlist/37i9dQZEVXbMDoHDwVN2tF?si=UolM_jSLQ5iuCEzuHEv7Mw
- https://gaana.com/playlist/gaana-dj-hindi-top-50-1
- https://youtu.be/3ierD2MJEjY

**Comment by Bwangster12** [comment]
Yes, I tried going in and searching for an artist. Thanks.
