### ISSUE TITLE
Request: 360kbps songs 

### ISSUE THREAD

**Issue by mizzunet** [Shabinder/SpotiFlyer#70]
The songs downloading are of 128kbps, aren't they? Any chance adding 360kpbs download-ability?

**Comment by Shabinder** [comment]
currently, we are using only youtube music, so that is limited to 128kbps for now, However, I am working on adding more sources like JioSaavn so that we can download 320 kbps songs if available ...

Stay Tuned.

**Comment by mizzunet** [comment]
> currently, we are using only youtube music, so that is limited to 128kbps for now, However, I am working on adding more sources like JioSaavn so that we can download 320 kbps songs if available ...
> 
> Stay Tuned.
That's cool, looking forward to it, thanks. Btw, here is a project
https://github.com/monuyadav016/Saavn-Downloader

**Comment by Shabinder** [comment]
> > currently, we are using only youtube music, so that is limited to 128kbps for now, However, I am working on adding more sources like JioSaavn so that we can download 320 kbps songs if available ...
> > Stay Tuned.
> 
> What finally happened to Spotify? If it stopped working, it should be emphasized after YouTube. Jio something outside India no one knows that.

Adding Source wont affect any existing functionality ,
Like when I add JioSaavn as a source , then when you download any song , it will try to get link from Youtube(128kbps), and JioSaavn(320Kbps/160Kbps) and will download the song with the **highest quality** available.

**Comment by mizzunet** [comment]
> > > currently, we are using only youtube music, so that is limited to 128kbps for now, However, I am working on adding more sources like JioSaavn so that we can download 320 kbps songs if available ...
> > > Stay Tuned.
> > 
> > 
> > What finally happened to Spotify? If it stopped working, it should be emphasized after YouTube. Jio something outside India no one knows that.
> 
> Adding Source wont affect any existing functionality ,
> Like when I add JioSaavn as a source , then when you download any song , it will try to get link from Youtube(128kbps), and JioSaavn(320Kbps/160Kbps) and will download the song with the **highest quality** available.

Great!

**Comment by Shabinder** [comment]
> > > > currently, we are using only youtube music, so that is limited to 128kbps for now, However, I am working on adding more sources like JioSaavn so that we can download 320 kbps songs if available ...
> > > > Stay Tuned.
> > > 
> > > 
> > > What finally happened to Spotify? If it stopped working, it should be emphasized after YouTube. Jio something outside India no one knows that.
> > 
> > 
> > Adding Source wont affect any existing functionality ,
> > Like when I add JioSaavn as a source , then when you download any song , it will try to get link from Youtube(128kbps), and JioSaavn(320Kbps/160Kbps) and will download the song with the **highest quality** available.
> 
> Great! BTW, the code for JioSaavn has been added?
> https://github.com/JioSaavn/Jio-Saavn-Downloader this is a web based app for downloading JioSaavn, you may know it.

yeah I know about it.

**Comment by Panchajanya1999** [comment]
Is it possible to download FLACs from Spotify??

**Comment by Shabinder** [comment]
Hey @Panchajanya1999 I will have to look into it , But no promises .

And **Today I finalized 360KBPS Support**, Will Release a new apk in a day or two.

**Comment by mizzunet** [comment]
> Hey @Panchajanya1999 I will have to look into it , But no promises .
> 
> And **Today I finalized 360KBPS Support**, Will Release a new apk in a day or two.

Cool, thanks.

Deezer can be used for both 360kbs and FLAC, I used to use Freezer for that. However I had to try VPN as Deezer isn't nkut available in my country

**Comment by Shabinder** [comment]
Hey Everybody 👋  ,

v3.1.0 is release and it is capable of downloading 320 kbps songs and also supports Jio-Saavn.

Closing this issue now, If you face any issues with new update report them by opening new issue
