### ISSUE TITLE
[Feature-Request]: <Please Add Episodes download support>

### ISSUE THREAD

**Issue by imhkr** [Shabinder/SpotiFlyer#706]

**Comment by b3pio** [comment]
+1. Support for video podcast episodes even better!

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
