### ISSUE TITLE
[BUG] : App is crashing in Android version below ( nougat )

### ISSUE THREAD

**Issue by iamvpbhaskar** [Shabinder/SpotiFlyer#710]
**Describe the bug:**
App is crashing in Android version( nougat ) I'm using this moto 2nd gen which is running on nougat android version.

**Media Links Used:** 
 I have not any media this time 

**Expected behavior**

**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   Moto G (2nd gen)
 - OS:   Nougat
 - Version:   nougat 7.1.2_r39
 - Country: [eg: India, will help in detecting if service is accessible to u]

**Additional context:**
After installing it started crashing then I reinstall it in my phone ..
This is working in my 2nd phone and my other family members phone it's - very nice and useful application ..

- **[ ] Thanks to developers** !!

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
