### ISSUE TITLE
[BUG] : Album deleted after I changed the folder name from '_' to '='

### ISSUE THREAD

**Issue by BlazeJatin** [Shabinder/SpotiFlyer#713]
I know it's a character limitation but maybe you can work this out.
I downloaded the latest album from Ed Sheeran '='.
The folder was named '_' so I renamed it to '=' and after that when I launched spotiflyer it deleted all the songs inside that album.

**Comment by Shabinder** [comment]
It didnt deleted , it just not detects it anymore as you renamed the folder

We handle file management on per name basis so don't rename if you want spotiflyer to detect those

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
