### ISSUE TITLE
[Feature-Request]: any way you can do time coordinated lyrics?

### ISSUE THREAD

**Issue by BlazeJatin** [Shabinder/SpotiFlyer#714]
Time synced lyrics like other apps.
I can't see any lyrics in the MP3 file too( mapbe it's my player's fault).
And ability to download playlist/album art in the folder where we downloaded it's songs.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
