### ISSUE TITLE
[BUG] : The app on PC  Shows only A White Screen

### ISSUE THREAD

**Issue by MrSalehSalem** [Shabinder/SpotiFlyer#715]
I tried both versions the msi and the jar. still the same. 

![Captu3re](https://user-images.githubusercontent.com/79551639/139685903-ee3653dc-76d2-41e7-b96e-be85555d19e0.JPG)

**Comment by Vikng412** [comment]
**I am facing the same problem** 
![image](https://user-images.githubusercontent.com/78209058/150627138-8e7b2078-4dba-465b-af83-2f3ea5815b79.png)

**Comment by Marco94** [comment]
Still no solution for this bug?

I am in Windows 11 and I have the same problem with version msi. With version jar it can not open and I do not know the cause (I have tested with lasted java 32 and 64bits, too with reinstall and it still not opened).

But in other PC with Windows 10 the version msi is look ok.

**Comment by Shabinder** [comment]
Same as https://github.com/Shabinder/SpotiFlyer/issues/941

**Comment by Shabinder** [comment]
@Marco94 here is the fix : https://github.com/JetBrains/compose-jb/issues/1771#issuecomment-1058005510

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
