### ISSUE TITLE
[Feature-Request]: Apple Music Support

### ISSUE THREAD

**Issue by BlazeJatin** [Shabinder/SpotiFlyer#717]
Apple Music Support needed. Asap.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
