### ISSUE TITLE
All apps crash after installation

### ISSUE THREAD

**Issue by ByofBe** [Shabinder/SpotiFlyer#72]
I installed SpotiFlyer and tried it successful.
I opened the Es file manager to see the downloaded application crashed.I cleared the cache  the same.
Restarted Phone try again crashed.
Try Yahoo mail crashed 
a lot of apps crash in the same
I try deleted and installed apps again crashed.

Pls help me

My Phone Samsung Galaxy A50 
![Screenshot_20210323-040928_Settings](https://user-images.githubusercontent.com/81199975/112079004-7c2ff000-8b90-11eb-9348-a86786d0be2c.jpg)

**Comment by ByofBe** [comment]
Uploading Screen_Recording_20210323-043225_One UI Home.mp4…

**Comment by ByofBe** [comment]
# @

**Comment by ByofBe** [comment]
https://user-images.githubusercontent.com/81199975/112079549-6cfd7200-8b91-11eb-878b-c9be14ca3a79.mp4

**Comment by Shabinder** [comment]
> Screen_Recording_20210323-043225_One.UI.Home.mp4

Here Yahoo mail is crashing , it has no link with spotiflyer.....

**Comment by ByofBe** [comment]
After installing SpotiFlyer Not only yahoo mail but also some other apps started to crash

**Comment by ByofBe** [comment]
https://user-images.githubusercontent.com/81199975/112096477-5fef7b80-8baf-11eb-8425-ede64991c426.mp4

**Comment by Shabinder** [comment]
> After installing SpotiFlyer Not only yahoo mail but also some other apps started to crash

I don't know what is the cause , no one has ever reported such behaviour and even spotiflyer app has nothing to do with other apps, could that be an issue with your device's OS..?

**Comment by ByofBe** [comment]
Android System WebView application was causing the crashes

Thanks for everything

**Comment by Shabinder** [comment]
Yeah , I also just read the article.
https://www.businessinsider.in/tech/apps/news/how-to-fix-android-apps-crashing-issue-on-your-mobile/amp_articleshow/81646271.cms
