### ISSUE TITLE
Sound clarity

### ISSUE THREAD

**Issue by AbhiRV2002** [Shabinder/SpotiFlyer#728]
Hello Spotiflyer team,
I downloaded Spotiflyer and it's a great app to download music from spotify. But theres an issue on sound quality. The downloaded song sounds different from that on spotify. The downloaded song has some harshness in it. I was using snaptube from long time and it does a good job on downloading songs from youtube with clear sound but it does not give album art and artist info on songs. I like spotiflyer because of its ability to download song with album art as well as artist info. So again thanks for making such a great app. And please check if there's a bug in sound quality of spotiflyer.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
