### ISSUE TITLE
Why not Heroku?

### ISSUE THREAD

**Issue by mizzunet** [Shabinder/SpotiFlyer#73]
> I am hosting a server for WEB APP on my own personal device , so expect some downtimes, If you have a server available and would like to share , open an issue or ping me wherever you can get a hold of me.

Why not using Heroku?

**Comment by Shabinder** [comment]
> > I am hosting a server for WEB APP on my own personal device , so expect some downtimes, If you have a server available and would like to share , open an issue or ping me wherever you can get a hold of me.
> 
> Why not using Heroku?

Heroku free plan is of limited hours and  app also sleeps after sometime of inactivity . However good new , **mpetuska**  has done azure setup for same. So,all good as of now.
Will update readme.
