### ISSUE TITLE
[BUG] : Error when downloading from SoundCloud

### ISSUE THREAD

**Issue by SoumyBhow** [Shabinder/SpotiFlyer#731]
**Describe the bug:**
Everytime I try to download a song from SoundCloud it gives a 401 Unauthorized text error as seen in the screenshot.

**Media Links Used:** 
(https://m.soundcloud.com/blankemusicau/breathe)

**Expected behavior**
Spotiflyer is expected to download the song without error.

**Screenshots:**
![Screenshot_20211113-184723789](https://user-images.githubusercontent.com/42043870/141662359-f57827e5-30d1-4dc4-9251-b22ebfaac471.jpg)

**Device Info (please complete the following information):**
 - Device:  OnePlus 7 Pro
 - OS:   Android 11 AEX Custom ROM
 - Version:   3.5.0
 - Country: Canada

**Comment by Quinten0508** [comment]
Exact same issue here. 
Device: OnePlus 8 Pro
OS: Android 11 - OOS 11 stable
Version: 3.5.0
Country: Netherlands

**Comment by SoumyBhow** [comment]
Okay after some time a couple of things have changed. I'm using a different android 12 custom ROM now and Spotiflyer version 3.6.1. However, I still cannot download from SoundCloud. I've attached a screenshot. I'm certain it's the same issue but it's hard to tell since the message is cut off.
![Screenshot_20220130-052532_SpotiFlyer](https://user-images.githubusercontent.com/42043870/151695930-26557901-f268-40d4-8376-842e9186b46c.png)

**Comment by Shabinder** [comment]
Can you give it a try be using a VPN and see if it makes it work ?

**Comment by SoumyBhow** [comment]
I tried a VPN to USA and it still gives the same error.

**Comment by DanixUwU** [comment]
I know what’s going on, spotiflyer can’t download a single song on Soundcloud, but she can download the song you want if that song is on a Souncloud playlist.

**Comment by jshdvdvdbsb** [comment]
For anyone having the same problem, as the comment above this says, playlist and album links worked for me.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
