### ISSUE TITLE
I download the app in Android to the last uptade but dont open

### ISSUE THREAD

**Issue by freestyleyt** [Shabinder/SpotiFlyer#732]

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
