### ISSUE TITLE
[BUG] : Issues with different files

### ISSUE THREAD

**Issue by deanbruhn** [Shabinder/SpotiFlyer#733]
**Describe the bug:**
I am getting errors when I try and download a playlist off of Spotify, and then specifically the songs listed below when I try and download them. 

**Media Links Used:** 
Playlist with the problematic songs: https://open.spotify.com/playlist/6X0Ltuor2P13baMng8eKuq?si=7550e9180ce84dd6)
Song 1: https://open.spotify.com/track/3ztFkcnXLZKyeViezxIhs7?si=bc1f2ae976194f66
Song 2: https://open.spotify.com/track/26zZBOpwa7kn8UQMiIUoGu?si=4623f6858d554496
Song 3: https://open.spotify.com/track/23K40FEezYsqRm29n32fHc?si=5c4cf6b740e54446
Song 4: https://open.spotify.com/track/3wBNknFLDo0Cd8bt2NEV1Q?si=0b20eac0b84241a9
Song 5: https://open.spotify.com/track/7oefLWAwZW9PVhQdhgErSW?si=ad2cac5214004640

Error: "DownloadLinkFetchFailed(errorTrace=Find Link for 24/7 

Fetching From Saavn Failed:DownloadLinkFetchFailed(errorTrace=No SAAVN Match Found for 24/7)
	at com"

**Expected behavior**
I have tried to download these multiple times both in the playlist and on their own. I am getting the issue across all of them. 

**Device Info (please complete the following information):**
 - Device:   Desktop Computer 
 - OS:   Debian 11
 - Version:   Linux-Deb 3.5.0 Package
 - Country: Unites States

**Additional context:**
All of the songs contain special characters "-" and "/" which might be the issue.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
