### ISSUE TITLE
Cannot write to SD card storage.  "no write access..." perms have been given to the app

### ISSUE THREAD

**Issue by troutcannon** [Shabinder/SpotiFlyer#734]
I have given access to the app, but it will not write to SD card.  I have tried to make new directories, etc

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
