### ISSUE TITLE
Update source code 

### ISSUE THREAD

**Issue by Tahaelhosseny** [Shabinder/SpotiFlyer#735]
Hello Mr. Shabinder ,

first very thanks for this awesome app, second am asking If I can get the source code for the android app to add it to my project if it is possible.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
