### ISSUE TITLE
[BUG] : Inconsistent Bit Rates

### ISSUE THREAD

**Issue by deanbruhn** [Shabinder/SpotiFlyer#740]
**Describe the bug:**
When I download various records like Baptists - Bushcraft I am not getting consistent bitrates.

Track List:
Betterment - 192kbps
Think Tank Breed - 192kbps
Bullets - 192kbps
In Droves - 128 kbps
Still Melt - 128 kbps
Mortarhead - 128 kbps
Crutching Trails - 128 kbps
Bushcraft - 192 kbps
Soiled Roots - 128 kbps
Russian Spirits  - 128 kbps
Abandon  - 128 kbps

**Media Links Used:** 
https://open.spotify.com/album/0GBxMikYve63RCjtRxLKcR?si=LYEFSHfPTc29QWLrpf5Oog

**Expected behavior**
For all of the downloads to have consistent bitrates

**Device Info (please complete the following information):**
 - Device:   Desktop Computer
 - OS:   Debian 11
 - Version:   Deb 3.5.0
 - Country: United States

**Additional context:**
My Preferred Audio Quality is set to 320 kbps

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
