### ISSUE TITLE
Spotiflyer quality

### ISSUE THREAD

**Issue by Bassquakes** [Shabinder/SpotiFlyer#741]
I can' t download 320kbps only can 128kbps...can someone help me?

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
