### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by Avdhacker** [Shabinder/SpotiFlyer#753]
android 6.0.1 doesn't show the icon and stops working before starting ?😢

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
