### ISSUE TITLE
[BUG] :  WINDOWS 10 SPOTIFLYER CLIENT ISSUE

### ISSUE THREAD

**Issue by immanuelgracious** [Shabinder/SpotiFlyer#763]
**Describe the bug:**
Windows 10 Spotiflyer client is unusable, it keeps glitching and crushing there after

**Media Links Used:** 
Spotify

**Expected behavior**
Expected it to just work like the linux client but it has issues on windows 

**Screenshots:**

**Device Info (please complete the following information):**
 - Device:   DELL PC. 4gb RAM, intel core i3
 - OS:   Windows 10
 - Version:   3.5.0
 - Country: Uganda

**Additional context:**

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
