### ISSUE TITLE
[Feature-Request]: Download Queue to retain incomplete downloads *even after restart*

### ISSUE THREAD

**Issue by turn-a-round** [Shabinder/SpotiFlyer#768]
**Is your feature request related to a problem? Please describe.**
A Download Queue feature: In desktop (we're using Linux v3.5.0), whenever we're downloading multiple items & we hit the back button, we loose all the incomplete downloads. It'll be better to implement a ***"Download Queue"*** which will retain the download status of incomplete downloads and can resume after restart.

**Describe the solution you'd like**
Implement a ***"Download Queue"*** which will retain the download status of incomplete downloads and can resume after restart.

**Describe alternatives you've considered**

**Additional context**

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
