### ISSUE TITLE
[BUG] : Desktop (Linux) app crashes after closing popup

### ISSUE THREAD

**Issue by turn-a-round** [Shabinder/SpotiFlyer#769]
**Describe the bug:**
Using Linux desktop app v3.5.0: When we click the Download all button, it opens a popup for donation/payment. The downloads also starts in the background. But when the popup is closed, the whole app crashed & closed.

**Media Links Used:** 

**Expected behavior**

**Screenshots:**
![Screenshot from 2021-12-05 13-46-01](https://user-images.githubusercontent.com/8726805/144739194-d261326f-ed0f-4720-8053-fe64f48bb33d.png)

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   [e.g. iPhone6, Samsung J2, PocoF1]
 - OS:   [e.g. iOS, Android 10, WinOS, MacOS]
 - Version:   [e.g. 3.2.1]
 - Country: [eg: India, will help in detecting if service is accessible to u]

**Additional context:**

**Comment by Xabaras666** [comment]
i have the same problem

**Comment by phillipprado** [comment]
Same here

**Comment by vncastanheira** [comment]
The same is happening on Windows, the popup doesn't close no matter what you click on.

![image](https://user-images.githubusercontent.com/1210284/189221292-c12f331f-f14b-4098-8ee3-5a12e3bb2e37.png)

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
