### ISSUE TITLE
Problem with current Logo

### ISSUE THREAD

**Issue by martin-desktops** [Shabinder/SpotiFlyer#777]
Hi, great software, but... Doesn't this logo violate Spotify guidelines? 

https://beta.developer.spotify.com/assets/branding-guidelines/spotify-logo-color-guidelines.pdf

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
