### ISSUE TITLE
[BUG] : <Unable to Open JVM>

### ISSUE THREAD

**Issue by BadBoyHaylou** [Shabinder/SpotiFlyer#784]
**Describe the bug:**
Says that JVM failed to open when I try to open app

**Media Links Used:** 
N.A.

**Expected behavior**
App starts

**Screenshots:**
<img width="960" alt="2021-12-13" src="https://user-images.githubusercontent.com/80583938/145799547-ebc5240f-fa18-4b09-bfd3-29f3369b37dd.png">

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:  Acer Swift 5
 - OS:   WinOS
 - Version:  3.5.0
 - Country: Singapore

**Additional context:**
The app worked 1 day ago

**Comment by KaungSithuLinn** [comment]
Same here too

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
