### ISSUE TITLE
[ADD SUPPORT]: <Kindly Add Resso App Support>

### ISSUE THREAD

**Issue by Devil3478** [Shabinder/SpotiFlyer#798]
Please add Resso App Support, there are lots of amazing song that I want to download.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
