### ISSUE TITLE
App crashes after downloading specifc ammount of songs

### ISSUE THREAD

**Issue by Xellerate005** [Shabinder/SpotiFlyer#80]
I was using the app and i realised that the app starts crashing, or just end up being slow after i try to download 10 or more songs

**Comment by Shabinder** [comment]
@Xellerate005 Thanks for reporting this issue , but I just checked at my end , I am not encountering any such crash.
Can you please share more details like on which playlist,etc

Also try Clearing Apps Data and downloading Again.

**Comment by Shabinder** [comment]
No Response for over a week.
Issue Stale, hence closing.
