### ISSUE TITLE
App downloaded instrumental only

### ISSUE THREAD

**Issue by Earbud98** [Shabinder/SpotiFlyer#810]
Basicaly, title says it all. Some downloaded songs from spotify play instrumental version of that song with weird instruments... Any fix ?

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
