### ISSUE TITLE
[BUG] : ffmpeg path Could not be found

### ISSUE THREAD

**Issue by msebastian100** [Shabinder/SpotiFlyer#812]
**Describe the bug:**
i have installed the software.
Now the software says ffmpeg path Could not be found. 

**Screenshots:**

![2021-12-24_10h55_31](https://user-images.githubusercontent.com/4114151/147342935-d7c69c7f-48fb-4134-b981-7261a2b562de.png)

**Device Info (please complete the following information):**
 - OS:   Win11
 - Version:  /

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
