### ISSUE TITLE
[BUG] : Soundcloud Playlist not downloading

### ISSUE THREAD

**Issue by GL513** [Shabinder/SpotiFlyer#818]
**Describe the bug:**

Just sits and " loads" the whole time

**Media Links Used:** 

https://soundcloud.com/user-386475998/sets/the-most-noise?ref=clipboard&p=a&c=0&si=b0f762561ea5494cbe55e0afe31cd84c&utm_campaign=social_sharing&utm_medium=text&utm_source=clipboard
**Expected behavior**

Playlist should download
**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device: Samsung Galaxy A51 5G
 - OS:   Android
 - Version:   11
 - Country: USA
**Additional context:**

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
