### ISSUE TITLE
Auto update app

### ISSUE THREAD

**Issue by sushantbhagat02** [Shabinder/SpotiFlyer#82]
When ever we open the app it should check for updates automatically and download the updated app 😃 
App is pretty good 🙂👍
Hope it brings high quality audio download from other platforms soon 
Thanks for u r hard work and wish u all the best

**Comment by Shabinder** [comment]
Auto Update is a nice feature to have, will consider adding it, and thanks for your appreciation.

**Comment by senolfndk** [comment]
Can you add song playback player feature and download button?
![Screenshot_20210610-165955](https://user-images.githubusercontent.com/52818836/121538658-a06fd000-ca0d-11eb-8dbd-ed93db1fb148.jpg)
![Screenshot_20210610-170013](https://user-images.githubusercontent.com/52818836/121538663-a1a0fd00-ca0d-11eb-8560-fb17335865b6.jpg)

**Comment by Shabinder** [comment]
> Can you add song playback player feature and download button?


Adding Playback feature will be a big task as I have to implement the same for multiplatform and I don't have that much time as my Exams or ongoing ...
However will work on this when I get somewhat free

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
