### ISSUE TITLE
[Feature-Request]: <Feature_Title>

### ISSUE THREAD

**Issue by drrajeevkumar01** [Shabinder/SpotiFlyer#826]
Hello guys Can u fetch resso music data to this app..?

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
