### ISSUE TITLE
Not Downloading in 320 kbps from Spotify

### ISSUE THREAD

**Issue by jquilli** [Shabinder/SpotiFlyer#829]
### Discussed in https://github.com/Shabinder/SpotiFlyer/discussions/786

<div type='discussions-op-text'>

<sup>Originally posted by **Ar7hurus** December 14, 2021</sup>
Hello
Why the app can't download the songs in 320 kbps from Spotify?
I have the highest quality set in the Spotify app as well as 320 kbps in SpotiFlyer and it downloads songs only in 128 kbps.
I'm doing something wrong here? </div>

**Comment by erikku530** [comment]
I am also encountering the same issue. Appreciate some solution on this. Thank you.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
