### ISSUE TITLE
[BUG] : Sound quality

### ISSUE THREAD

**Issue by KianmehrKM** [Shabinder/SpotiFlyer#832]
So basically I went on the app and put it on the highest quality download (320Kbps), after that I went to download some songs, I tried Minecraft: Volume Alpha album by C418, after the download was finished, I inspected the audio that it was not 320kbps, rather 128kbps! I redownloaded and reset the settings but still was the same thing...
I saw many people have the issue but I don't know why it is like that...
My device is Nokia 6.1, 64GB ROM, 4GB RAM, Android 10, Iran.
![Screenshot_20220101-153024.png](https://user-images.githubusercontent.com/85435062/147850095-4b62987e-d07f-4008-bba7-8a2c4b46425b.png)![Screenshot_20220101-153012.png](https://user-images.githubusercontent.com/85435062/147850097-fcb2347e-d3d8-4642-98e5-4f767f7099fc.png)

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
