### ISSUE TITLE
[BUG] : <YouTube Music Premium downloading at 128kbps

### ISSUE THREAD

**Issue by jTtRx** [Shabinder/SpotiFlyer#833]
*** Description of bug ***

First of, the app is much appreciated. So thank you for this!

I should also explain that I've looked through your bug history, and although I appreciate YouTube music (standard) uses compression at 128kbps, Premium members like myself stream at 256kbps AAC (which is pretty much equivalent to 320kbps MP3).

However, all tracks downloaded through Spotiflyer, when played back through, are 128kbps despite selecting preferred 320kbps. 

Is it the case that Spotiflyer is just applying 128kbps as standard because it's YouTube Music, or is it that YouTube are using the AAC type instead causing the issue here? If so, do you intend on future support for this?

I appreciate the help on this. Thank you!

*** Example of url used ***
https://music.youtube.com/watch?v=wS8Ri68haHc

*** Expected behaviour *** 
A close to original quality clone of the streamed version.

**Describe the bug:**

**Media Links Used:** 

**Expected behavior**

**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   [e.g. iPhone6, Samsung J2, PocoF1]
 - OS:   [e.g. iOS, Android 10, WinOS, MacOS]
 - Version:   [e.g. 3.2.1]
 - Country: [eg: India, will help in detecting if service is accessible to u]

**Additional context:**

**Comment by Cederick** [comment]
I'd also appreciate YouTube login capabilites in order to download content that is locked behind YouTube Premium at YouTube and YouTube Music.

**Comment by Shabinder** [comment]
will definitely look into possibilities with this.
but probably in re-write or at a later time when I do get more free time at my hand.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
