### ISSUE TITLE
Song not downloading just this one (trying to download like a month)

### ISSUE THREAD

**Issue by cristianoashok** [Shabinder/SpotiFlyer#834]
Song not downloading just this one (trying to download like a month)

Song Link: Polozhenie - Zedline Remix
https://open.spotify.com/track/0B85QRzKh91WOWYDpc1ABP?si=_c5EMWjrTgmIOdxNNk3UZA&utm_source=copy-link

**Device Info
 - Device:  Asus Rog 2
 - OS:  Android 11
 - Country: India

**Additional context:**
Only this song is not downloading.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
