### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by shockergit** [Shabinder/SpotiFlyer#838]
Does this directly download from spotify or from youtubeif i give url of spotify.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
