### ISSUE TITLE
(Question) Does this download straight from spotify?

### ISSUE THREAD

**Issue by SystaxError** [Shabinder/SpotiFlyer#839]
Im wondering if this downloads straight from spotify (like zSpotify) or if it searches on youtube for the music? im looking for a one that downloads from spotify since zspotify got taken down recently and youtube music quality is shit

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
