### ISSUE TITLE
[bug] Mix playlist not working

### ISSUE THREAD

**Issue by FrostyNick** [Shabinder/SpotiFlyer#840]
Link: [https://youtube.com/playlist?list=RDzeF6yeo-hS0](https://youtube.com/playlist?list=RDzeF6yeo-hS0)

- I've tested this on two smartphones and it shows an error "invalid json".
- By doing above, I can tell it's a public playlist.
- Other playlists work on both devices.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
