### ISSUE TITLE
[BUG] It downloads the remix of the song instead of the original

### ISSUE THREAD

**Issue by SRZGit** [Shabinder/SpotiFlyer#847]
**Describe the bug:**
Songs like Vossi Bop by Stormzy and Go Crazy by Chris Brown have remixes. However,whenever i copy the ORIGINAL song link and download using Spotiflyer,it downloads the remixed version instead.

**Media Links Used:** 
VOSSI BOP ORIGINAL : https://open.spotify.com/track/5DXKtoZLm31msT7tNGNHLG?si=bd35f74401bb42e8
VOSSI BOP REMIX (The One It Downloaded) : https://open.spotify.com/track/3dl98e4LgX6bEHn5BNAOC0?si=6581ebe567074e44

Go Crazy ORIGINAL : https://open.spotify.com/track/1IIKrJVP1C9N7iPtG6eOsK?si=937ce800ae004d72
Go Crazy REMIX (The One It Downloaded) : https://open.spotify.com/track/1Jz1yhcPm1Yt6aoed3zact?si=2142249e169749e8

**Expected behavior**
I expected it to download the original songs. Not the remixes.

**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:  PC/Android
 - OS:  Windows 10, Android 11
 - Version: 3.2.0
 - Country: Malaysia

**Additional context:**

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
