### ISSUE TITLE
[ERROR] : <Spotify download error>

### ISSUE THREAD

**Issue by NamasteIndia** [Shabinder/SpotiFlyer#855]
**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   [poco X3 pro]
 - OS:   Android 11
 - Version:   [e.g. 3.2.1]
 - Country: [india]

**Additional context:**

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
