### ISSUE TITLE
[BUG] : Song available on JioSaavn, but not downloading

### ISSUE THREAD

**Issue by Moon422** [Shabinder/SpotiFlyer#869]
**Describe the bug:**
I am trying to download Bad Guy, but does not seem to download the actual song. The song is available on JioSaavn. I have to tried to paste the link to JioSaavn still does not work. The Spotiflyer downloader can pull the metadata and clicking on the download button does show progress, but the actual file in the download directory is a file of around 50kb.

**Media Links Used:** 
https://open.spotify.com/track/2Fxmhks0bxGSBdJ92vM42m?si=8fed395d55784d3d

**Screenshots:**
https://imgur.com/a/7rNZ10C [Screenshot]

**Device Info:**
 - Device:  Windows 10 Desktop
 - OS:  Windows 10
 - Version: Windows 10 20h2
 - Country: Bangladesh [JioSaavn available]

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
