### ISSUE TITLE
App won't launch

### ISSUE THREAD

**Issue by ChinoKaffu** [Shabinder/SpotiFlyer#87]
I have given the app all the requirements and permissions it demanded for it to work, but after all that, the app would not launch. Using the app for the first time, it works well. For the 2nd and succeeding times, the app will not even launch.

**Comment by Shabinder** [comment]
Device info? And as I understand , App do lainches and works for 1st time , but not after 1 st time , right?

**Comment by ChinoKaffu** [comment]
Redmi Note 8. Yes, the app only launches for the first time, and not anymore after the first time. To use the app again, I have to restart my phone and that's a hassle.

**Comment by Shabinder** [comment]
Hey, please check if this issue is still there in the **v2.2.5** release.
Initially Uninstall installed APK and then install new Release.

**Comment by ChinoKaffu** [comment]
Pretty much fixed, thank you very much! Keep up the good work, much love (. ❛ ᴗ ❛.)
