### ISSUE TITLE
No data in file(Tracks)!

### ISSUE THREAD

**Issue by Endstarky** [Shabinder/SpotiFlyer#871]
Device: PC(Windows)
Some tracks are downloaded, but while trying to play in music players(Groove, Strawberry music player) the file has no data in it.
![strawberry_qbUHn1LQGS](https://user-images.githubusercontent.com/67501470/149535551-903587b0-3f2c-47c0-b5c7-ce46fe981abf.png)
.
Like the above example as u can see that the file has no sample rate or any other properties in the original file explorer too.
![Uploading image.png…]()
And if I try redownloading it, it sometime download the data file successfully but most of the time it doesn't.

**Comment by Endstarky** [comment]
![explorer_5eazhn3fXG](https://user-images.githubusercontent.com/67501470/149536875-9169cbcf-805d-4760-8014-f70d3861b533.png)

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
