### ISSUE TITLE
[BUG] : Failed to launch JVM

### ISSUE THREAD

**Issue by NakleplayKokos** [Shabinder/SpotiFlyer#876]
**Describe the bug:**
Cant load the app, I tried reinstalling Spotiflyer (with the same version and previous version) and even Java

**Expected behavior**
App would open
![Failed to launch JVM](https://user-images.githubusercontent.com/97829042/149655400-a4a4b076-7dea-4ef6-af00-10d41936cf15.png)

**Screenshots:**
Added

**Device Info (please complete the following information):**
 - Device:   HP Pavilion Gaming 15 laptop
 - OS:   WIN 11 ver. 22000.466 (21H2)
 - Version of Spotiflyer:   3.5.0, 3.3.1
 - Country: Czechia

**Additional context:**
The app worked before kinda well, had the "FFmpeg not loaded" bug, but the app worked even with this bug.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
