### ISSUE TITLE
downloading songs that are not in the playlist.

### ISSUE THREAD

**Issue by venya-san** [Shabinder/SpotiFlyer#89]
![Screenshot_20210421-004259_Samsung Music](https://user-images.githubusercontent.com/60911510/115441427-0a080500-a23b-11eb-9f7a-41c720cbe2c9.jpg)

This three song (marked with ✔) was not in the playlist, this happen in 2.2.5 version. i use the old version for now...

Playlist: https://open.spotify.com/playlist/37i9dQZF1DWWMOmoXKqHTD?si=29SKkg2WSfGuXuiXQQB_Lw&utm_source=copy-link

**Comment by Shabinder** [comment]
![Screenshot_20210421-012119_SpotiFlyer](https://user-images.githubusercontent.com/44765050/115455952-3b370400-a240-11eb-996a-250bbb1ecff7.png)
All the three songs are being sent by Spotify in their response to API call.

I checked with earlier version of the app too, they also show these songs.

**Spotify is sending stale responses ,** there is nothing that can be done on App Side I beleive.

**Comment by venya-san** [comment]
Well that's unfortunate... but if my memory serves me right, this doesn't happen and all the songs in this spotify playlist match with your app. Maybe something was changed on spotify.
