### ISSUE TITLE
[BUG] : <Issue_Title> same songs i tried before is not downloading .

### ISSUE THREAD

**Issue by Ezioauditorre58** [Shabinder/SpotiFlyer#928]
-->

**Describe the bug:**

**Expected behavior**

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   samsung note 10 lite
 - OS:   android 
 - Version:   [e.g. 3.2.1
 - Country: south africa

**Additional context:**

It downloaded some songs but the app stopped downloading songs, it isn't allowing me.
It is a few songs:
 beauty and the beast - something there,
Monark - you lie
The chainsmokers - the reaper and more 
But i also wanna say thank toy for this app i have been looking for an app like this.

**Comment by yavnaz** [comment]
Getting it on every playlist, album & song attempt (too many to list)

**Comment by yavnaz** [comment]
Getting it on every playlist, album & song attempt (too many to list); using both youtube music & spotify.

**Comment by Ezioauditorre58** [comment]
Hello
So what's the way forward ?
Is there some kind of patch coming to fix this problem or what ?
I like this app and I don't want to stop using it .

**Comment by Shabinder** [comment]
Fixed in **v3.6.0** : https://github.com/Shabinder/SpotiFlyer/releases/tag/v3.6.0

**Comment by Ezioauditorre58** [comment]
Hello shabinder/SpotiFlyer
Hope you are well,
Thank you so much for fixing the issue, the app is working fine now except
a few songs not downloading, but I have downloaded more songs, so thank
you very much.


Regards Ezio
