### ISSUE TITLE
App isn't downloading at all any help 

### ISSUE THREAD

**Issue by alfaoalfa** [Shabinder/SpotiFlyer#93]

**Comment by Shabinder** [comment]
describe your issue in detail please with more info about your device, and did app worked fine earlier?

**Comment by Shabinder** [comment]
> Sometimes I also feel like it's not downloading because the images and animations of dowloading and downloaded don't update if the application is running in background. But in my cases, unless there is some network related issue, the download is successful although the icon says it's still downloading

Does Notification status reflect completion?

**Comment by sarkarharsh** [comment]
> > Sometimes I also feel like it's not downloading because the images and animations of dowloading and downloaded don't update if the application is running in background. But in my cases, unless there is some network related issue, the download is successful although the icon says it's still downloading
> 
> Does Notification status reflect completion?

yes it does reflect that download is complete
