### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Demha123456** [Shabinder/SpotiFlyer#931]
Please guys don't send like 50 issues of the same bug check if someone already posted it
If it's already posted don't post it again if it's the same

**Comment by kneecaps5974** [comment]
Yesss

**Comment by IScoffedTheLaw** [comment]
Right? Good luck finding a fix if the developer responded to any of the 30 reports in the last weeks. This is quite ridiculous.

**Comment by Shabinder** [comment]
I am glad that some people do see and understand how difficult it gets to keep track when people open multiple issues related to same Bug .

I just did a **v3.6.0** release : https://github.com/Shabinder/SpotiFlyer/releases/tag/v3.6.0, with some crucial fixes

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
