### ISSUE TITLE
White screen on spotiflyer windows 10

### ISSUE THREAD

**Issue by Vikng412** [Shabinder/SpotiFlyer#941]
### Discussed in https://github.com/Shabinder/SpotiFlyer/discussions/940

<div type='discussions-op-text'>

<sup>Originally posted by **Vikng412** January 22, 2022</sup>
After installing as I opened spotiflyer on windows only white screen was showing
![image](https://user-images.githubusercontent.com/78209058/150629881-883a280f-b60b-43d2-8d53-3a4f0399ff8c.png)
I don't know what to do cause its not even showing an error.</div>

**Comment by Shabinder** [comment]
Try in **v3.6.0** : https://github.com/Shabinder/SpotiFlyer/releases/tag/v3.6.0 with Java 15 or greater

**Comment by Vikng412** [comment]
the white screen problem still isn't solved for me. also i observed that in a region the cursor changes to "I-cursor".
![image](https://user-images.githubusercontent.com/78209058/151688980-a41f6a3d-0dd7-403f-a086-40e7899612e1.png)

**Comment by Vikng412** [comment]
also i don't know for whatever reason the jar file doesn't run(on opening) even after having latest version of JAVA installed.

**Comment by Shabinder** [comment]
try running the jar from cmd , and see if it prints something there

**Comment by Vikng412** [comment]
I tried it but nothing runs, but when I went to delete the jar file it says that "it is open in java" but I don't know how to and where to look for the running program as it's not showing in background apps (up arrow menu in taskbar) or any where

**Comment by Shabinder** [comment]
Try rerunning from cmd after pc restart

**Comment by Vikng412** [comment]
![image](https://user-images.githubusercontent.com/78209058/151740065-ae1ac2b5-f27b-4049-9596-d60c34d2ff4c.png)
:(

**Comment by Shabinder** [comment]
Seems like App is working fine , just rendering isnt working , maybe want to report this here : [compose-jb](https://github.com/JetBrains/compose-jb)

**Comment by Shabinder** [comment]
> I reported it, thanks for bearing with me for these few days you must already have been busy and here I was adding to your pile even though nothing really was wrong with it(from your side).
> 
> P.S.-I will be posting an issue again, if its very necessary.

No Worries, here to help, and if you make any discovery ping me with the info here or a new issue maybe.

Also can you share the Issue you created here too.

**Comment by Vikng412** [comment]
Sure, here's the issue I created [https://github.com/JetBrains/compose-jb/issues/1771](url)

**Comment by Vikng412** [comment]
Sure, here's the issue I created (https://github.com/JetBrains/compose-jb/issues/1771)
