### ISSUE TITLE
[BUG] : <Issue_Title>Not downloading Help

### ISSUE THREAD

**Issue by THEGREATEST78** [Shabinder/SpotiFlyer#946]
**Describe the bug:**
 Download All not working (shows Exclamatin marks) 

**Media Links Used:** 
https://music.youtube.com/playlist?list=OLAK5uy_kOcvxWb--7vi4_rwP2-bO1PHMukVqlJUg&feature=share

**Expected behavior**
 after pressing download all the app should have started  downloading 

**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   [e.g. iPhone6, Samsung J2, PocoF1] Huawei Mate 20 pro 
 - OS:   [e.g. iOS, Android 10, WinOS, MacOS] Android
 - Version:   [e.g. 3.2.1] 12
 - Country: [eg: India, will help in detecting if service is accessible to u] South Africa 

**Additional context:**

**Comment by Shabinder** [comment]
Fixed in **v3.6.0** : https://github.com/Shabinder/SpotiFlyer/releases/tag/v3.6.0
