### ISSUE TITLE
Songs not downloading

### ISSUE THREAD

**Issue by Annan4664** [Shabinder/SpotiFlyer#97]
Songs not downloaded, notification says completed and files created are around 19kb

**Comment by Scheeppii** [comment]
I have the same issue

**Comment by JustAFan634** [comment]
Same here

**Comment by Shabinder** [comment]
Use **V2.1 for Now,** A service we were using to download converted music is down.

**Comment by Shabinder** [comment]
Check out **v2.3.0**, downloading issue is fixed
