### ISSUE TITLE
No lyrics in ID3 tags, no Synchronized lyrics<!--

### ISSUE THREAD

**Issue by drandrew1983** [Shabinder/SpotiFlyer#973]
there is no embedded ID3 lyrics in the downloaded songs. also no options to download synched lyrics .lrc
it would be nice if at last embedded lyrics are there.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
